- src/Apps/Collect/Components/ArtworkGrid/CollectArtworkFilterRefetch.tsx
Fixes a bug that causes the collect page to refetch data on page load
> [PATCH collect] prevent page from reloading data on load

- src/Apps/Order/Routes/Status/index.tsx
- src/__generated__/StatusQuery.graphql.ts
- src/__generated__/Status_order.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-540
Use `format` when getting `estimatedDelivery` from MP.
> Fix issue with date format on status page

- src/Apps/Order/Routes/__tests__/Status.test.tsx
- src/DevTools/__test__/renderUntil.test.tsx
- src/Utils/Responsive/__test__/Responsive.test.tsx
- src/setup_jest.ts
Addresses https://github.com/artsy/reaction/pull/1345#discussion_r222047185
Will comment inline.
> [Responsive] Don’t try to actually use media queries in tests.

- .yarnrc
See https://github.com/artsy/palette/pull/111.
> Add yarnrc to avoid update churn

- src/Apps/Collect/Components/ArtworkGrid/index.tsx
- src/Apps/Collect/Components/Filters/PriceRange.tsx
- src/Apps/Collect/FilterState.tsx
finishes https://artsyproduct.atlassian.net/browse/GROW-927
This is functional but without tests. I'll look to see if I could add some more test coverage, but feel free to merge if this PR is good enough.
> [FEATURE Collect] Disable price filter + 'bid' filter combination

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Styleguide/Components/EntityHeader.tsx
Adress https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-353
> [Fix EntityHeader] Follow button should sit inline with text

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/__stories__/ArtistInfo.story.tsx
- src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
- src/Apps/__test__/Fixtures/Artwork/ArtistInfo.ts
- src/Artsy/Relay/createEnvironment.ts
- src/DevTools/MockRelayRenderer.tsx
- src/Styleguide/Components/EntityHeader.tsx
- src/Styleguide/Components/MarketInsights.tsx
- src/Styleguide/Components/ReadMore.tsx
- src/Styleguide/Components/SelectedExhibitions.tsx
- src/__generated__/ArtistInfo_Test_Query.graphql.ts
- src/__generated__/ArtistInfo_artist.graphql.ts
Fixes issue where content was missing and additionally adds some tests using the new test scaffold setup:
> @mzikherman => [FIX artistInfo]: Fix missing section, add tests

- src/Apps/Collect/Components/Header/index.tsx
Addresses: https://artsyproduct.atlassian.net/browse/GROW-924
This extracts the Collection Header Component from https://github.com/artsy/reaction/pull/1382 into its own PR. How the data hooks up to the `CollectionApp` can be addressed in a separate PR. I think the shape of the data may change slightly once we have everything hooked up but I think this gets us pretty close to how things might look.
> [FEATURE collection] adds collections header

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
- src/Apps/WorksForYou/MarketingHeader.tsx
- src/Apps/WorksForYou/index.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/ArtworkFilterArtworkGrid_filtered_artworks.graphql.ts
- src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Fixes: 
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-364
Also bumps `artist/:id/overview` artwork grid count to 24
> [PATCH artist] Update Artwork grid to 24; fix theme

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
Fixes: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-387
Adds a zero state if a certain filter combo returns no results:
> [FEATURE artistPage] Add zero state for filter combo

- .vscode/extensions.json
- .vscode/settings.json
- src/Components/Publishing/RelatedArticles/Canvas/RelatedArticlesCanvas.tsx
- src/Styleguide/Components/Tabs.tsx
- src/Utils/Responsive/index.tsx
Stories are the worst culprit for the "typoes" this removes that as well.
> Improves spell checking to be less intrusive, and to also reduce the number of highlights

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Artist/routes.tsx
- src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
- src/__generated__/ArtworkFilter_artist.graphql.ts
- src/__generated__/Overview_artist.graphql.ts
Updates to be merchandisability.
> @damassi => [FEATURE ArtistPage] Update default sort on artist page

- src/Apps/Artwork/Components/ArtworkDetails/index.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkDetails.test.tsx
- src/Apps/__test__/Fixtures/Artwork/ArtworkDetails.ts
- src/__generated__/ArtworkDetails_Test_Query.graphql.ts
This adds a super simple test for the following not present for auction works.
Not sure how I feel about testing the actual html for strings but not clear how to test for an actual component render here. I think that'll do for now.
> beginning of test for artwork Details

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsChecklist.tsx
Temporarily commenting out checkmarks here per last comment for this issue: https://artsyproduct.atlassian.net/browse/DISCO-402
Text change will be done in MP and reflected when https://github.com/artsy/metaphysics/pull/1335 is deployed.
The look:
@damassi - let me know if you want me to pr a force update.
>  [FIX ArtworkDetailsChecklist] Temporarily remove checkmarks from checklist

- src/Apps/Order/Components/Helper.tsx
- src/Apps/Order/Components/__tests__/Helper.test.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
#minor the FAQ shouldn't open in a modal anymore.
> [FIX bnmo] FAQ opens in new tab

- README.md
Super minor, to trigger release
> [FIX Trivial] update readme to trigger  release

- src/Apps/WorksForYou/MarketingHeader.tsx
- src/Components/Artwork/Details.tsx
https://artsyproduct.atlassian.net/browse/DISCO-360
Related: https://github.com/artsy/emission/pull/1200
> [PATCH wfy] Update url

- data/schema.graphql
- data/schema.json
- src/Apps/Collect/CollectionApp.tsx
- src/Apps/Collect/FilterState.tsx
- src/Apps/Collect/__tests__/CollectionApp.test.tsx
- src/__generated__/CollectionAppTestQuery.graphql.ts
Related: https://artsyproduct.atlassian.net/browse/GROW-949
> [Collection] add test to CollectionApp

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/index.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
@oxaudo Not sure why you needed to add these, maybe there’s something wrong with your local env?
> [typings] Remove unneccesary any casts.

- src/Components/Publishing/ToolTip/__tests__/ToolTip.test.tsx
- src/Components/Publishing/Video/Player/__tests__/FullscreenHelpers.test.tsx
- src/Components/Publishing/Video/Player/__tests__/VideoPlayer.test.tsx
- src/Styleguide/Components/ArtistBio.tsx
- src/Styleguide/Components/__tests__/ArtistBio.test.tsx
- src/__generated__/ArtistBioTestQuery.graphql.ts
In this exciting second edition, we:
- Replaced ArtistBio tests that used the presentational component with ArtistBio tests that use the fragment container.
- Sprinkled some `any` dust around a few other files
🕺
> [type checking test files] ArtistBio, etc

- .storybook/webpack.config.js
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
- src/Apps/Collect/Components/Filters/__tests__/FilterContainer.test.tsx
- src/Apps/WorksForYou/index.tsx
- src/Components/Artwork/Details.tsx
- src/Components/Artwork/GridItem.tsx
- src/Components/Artwork/Metadata.tsx
- src/Components/Artwork/__tests__/Details.test.tsx
- src/Components/__tests__/__snapshots__/Artwork.test.tsx.snap
- typings/sharify.d.ts
Now that we've launched and there are no plans to un-launch, this PR removes references to the feature flag/conditional logic. 🎉
Tracked in: https://artsyproduct.atlassian.net/browse/PURCHASE-592
I've run this locally and it looks okay, but would love some good 👀 on the logic!
> [FIX bnmo] Removes reference to buy now feature flag

- .gitignore
- src/Apps/Collect/Components/Filters/MediumFilter.tsx
- src/Apps/Collect/Components/Filters/__tests__/MediumFilter.test.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-947
- Use hardcoded list of mediums for filter if none are returned from query
- Adds `.cache-loader` to `.gitignore`
> @l2succes => [Collections] use hardcoded medium list

- src/Apps/Artist/Components/__test__/ArtistHeader.test.tsx
- src/Apps/__test__/Fixtures/Artist/ArtistHeader.tsx
- src/__generated__/ArtistHeader_Test_Query.graphql.ts
Getting comfortable with some of the test utils (and looking forward to going all out on artist page!)
> @damassi => [Testing] Add a test for the artist page header

- src/Apps/Artist/Components/__test__/ArtistHeader.test.tsx
- src/Components/Publishing/Video/Player/__tests__/FullscreenHelpers.test.tsx
- src/Typings/global.d.ts
- src/setup_jest.ts
Fixes some issues that slipped through earlier today due to GH webhook CI outage.
> [Tests] Fix failing tests that slipped through due to CI outage

- src/Apps/Artist/Components/__test__/NavigationTabs.test.tsx
- src/Apps/__test__/Fixtures/Artist/NavigationTabs.tsx
- src/Styleguide/Components/__mocks__/RouteTabs.tsx
- src/__generated__/NavigationTabs_Test_Query.graphql.ts
Uses jest mocks for the underlying `Link` components.
> @damassi => [Testing] Add test for NavigationTabs for an artist

- package.json
- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Elements/GlobalStyles.tsx
- yarn.lock
Fixes 
- https://artsyproduct.atlassian.net/browse/DISCO-439
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&view=planning&selectedIssue=DISCO-437
Also removes a css reset that seemed to be clobbering Force's reset in prod (but not locally) 
Will follow up with a second pr right after with tests. (Want to get this into Force staging.)
> [FIX artist] Fix follow artist button

- src/Apps/WorksForYou/MarketingHeader.tsx
Fixes 
- https://artsyproduct.atlassian.net/browse/DISCO-297?filter=10075
- https://artsyproduct.atlassian.net/browse/DISCO-298
> [FIX wfyBanner] Fix issue with unbound tracking props

- src/Apps/Artist/Routes/CV/ShowEntry.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/index.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkDetails.story.tsx
- src/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
- src/__generated__/ArtworkDetailsQuery.graphql.ts
- src/__generated__/ArtworkDetails_Test_Query.graphql.ts
- src/__generated__/ArtworkDetails_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
- yarn.lock
Addresses: 
- https://artsyproduct.atlassian.net/browse/DISCO-405 (new tab)
- https://artsyproduct.atlassian.net/browse/DISCO-262 (weird comma space in cv)
> [FEATURE ArtworkDetails] Add provanence tab

- src/Components/ArtworkGrid/index.tsx
Oops, also export named exports
> [FIX folderStructure] Fix artwork grid

- src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/CollectionAppTestQuery.graphql.ts
- src/__generated__/CollectionFilterContainer_collection.graphql.ts
- src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Makes sure we only show available mediums
> [Collection] fix medium aggregations

- src/Apps/Artist/Routes/Shows/ArtistShows.tsx
- src/Apps/Artist/Routes/Shows/__test__/Shows.test.tsx
- src/__generated__/Shows_Test_Query.graphql.ts
Reusing the CV fixture, since this is just a textual version of that info.
> @mzikherman => [Testing] Add Shows tab test

- src/Apps/Collect/CollectionApp.tsx
Addresses: https://artsyproduct.atlassian.net/browse/GROW-962
> [PATCH collection] throw Not Found error when collection do not exist

- src/Apps/Order/Routes/__tests__/Payment.test.tsx
Noticed master was failing `tsc`
> [Test] Remove unused var

- src/Apps/Artwork/Components/__stories__/ArtworkDetails.story.tsx
- src/Apps/__test__/Fixtures/Artworks.ts
Will self merge this one. Just a little data cleanup
> Minor test data cleanup

- .storybook/webpack.config.js
Extracted from https://github.com/artsy/reaction/pull/1228
> Add types to the webpack config

- .storybook/webpack.config.js
This should solve our netlify CI issue
> Fix webpack issue that caused storybooks to fail

- package.json
- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkImages.tsx
- src/Apps/Artwork/Components/ImageCarousel.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkImages.story.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/ArtworkApp_artwork.graphql.ts
- src/__generated__/ArtworkImagesQuery.graphql.ts
- src/__generated__/ArtworkImages_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
- yarn.lock
- Comment out WIP stuff to clear the way
- Swaps query renderers with fragment containers
- Add ArtworkImages component to wrap Carousel
- Add in footer, recently viewed, etc.
> [Artwork Page] First pass cleanup

- data/schema.graphql
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPageviews.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarPageviews.story.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarPageviews.test.tsx
- src/Styleguide/Elements/icons/Pageviews.tsx
- src/__generated__/ArtworkSidebarPageviewsQuery.graphql.ts
- src/__generated__/ArtworkSidebarPageviews_Test_Query.graphql.ts
- src/__generated__/ArtworkSidebarPageviews_artwork.graphql.ts
Still going to add a spec here.
Looks like:
> @damassi => Add component for pageviews trust signal for an artwork

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artwork/ArtworkApp.tsx
@damassi - I think the latest reshuffle brought this issue: https://artsyproduct.atlassian.net/browse/DISCO-489
Seems like the simple fix here and it makes sense. Cause once the data is loaded the content is re rendered.
> small visual fix for works for you render

- package.json
- src/Utils/Responsive/DeprecatedResponsive.tsx
- yarn.lock
No need to relog after every render.
> [PATCH responsive] Only log warning on mount

- package.json
- yarn.lock
See https://github.com/artsy/react-responsive-media/pull/15
> [PATCH package] Bump @artsy/react-responsive-media@1.0.9

- package.json
- yarn.lock
> [PATCH package] Bump @artsy/react-responsive-media@1.0.10

- .circleci/config.yml
_Let's get these builds running faster, faster_.
Let's see how much time we can trim... ⏳
> 🔥blazing fast builds 🔥

- .circleci/config.yml
Just runs yarn on deploy (just to be safe).
> Run yarn just to ensure deploy passes

- package.json
- src/Apps/Order/Components/TransactionSummary.tsx
- src/Styleguide/Utils/BreakpointVisualizer.tsx
- src/Utils/Responsive/DeprecatedResponsive.tsx
- yarn.lock
https://github.com/artsy/react-responsive-media/pull/18
> [PATCH Responsive] Fix issue with SSR rendered content not showing after rehydration.

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPageviews.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarPageviews.test.tsx
Easy peasy, this adds **..this week**
> @mzikherman => Update pageviews CTA language

- src/Apps/Order/Routes/Status/index.tsx
- src/Apps/Order/Routes/__tests__/Status.test.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/Apps/__tests__/Fixtures/Order.ts
- src/__generated__/StatusQuery.graphql.ts
- src/__generated__/Status_order.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
This PR addresses [PURCHASE-366](https://artsyproduct.atlassian.net/browse/PURCHASE-366), paired on with @pepopowitz. It includes an update to styled-system which might be removed from another PR from @pepopowitz. 
This actually fixes an issue with margins in the `<Message>` component, which were previously only ever 20px on desktop. You can see what that looks like here: https://artsy-reaction.netlify.com/?selectedKind=Apps%2FOrder%20Page%2FBuy%20Now%2FStatus&selectedStory=fulfilled%20%28ship%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=PeterPanen%2Fstorybook-addon-scissors%2Fpanel Just flagging this as something that was fixed /cc @briansw 
We also tried replacing `<br />` tags with the more semantic meaning like  `<p>` tags (however, `<p>` tags can't contain `<div>`s like …
> Offer status page

- src/Styleguide/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
- src/Styleguide/Components/FollowArtistPopover/index.tsx
- src/__generated__/FollowArtistPopoverQuery.graphql.ts
- src/__generated__/FollowArtistPopoverRowMutation.graphql.ts
- src/__generated__/FollowArtistPopoverRow_artist.graphql.ts
Looks like ^ , starting to come together!
> @damassi => Better styling for contents of follow artist popover

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkDetails/index.tsx
- yarn.lock
Ugh. Thought this was happening at a lower level but needs to be attached to each individual stitched in component.
> [FIX tracking] Add dispatcher

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarExtraLinks.test.tsx
This is minor follow up on artsy/reaction#1566. Will self merge that on green
> Convert all links on ExtraLinks to onClick events to make tracking easier.

- src/Apps/Artwork/ArtworkApp.tsx
- src/Styleguide/Components/Lightbox/Lightbox.tsx
Supersedes https://github.com/artsy/reaction/pull/1567
> [FIX artworkPage] Only load lightbox clientside

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
Address: https://artsyproduct.atlassian.net/browse/GROW-1009
This is the second part of adding optional canvas cover overlays and is dependent on https://github.com/artsy/positron/pull/1793
> [FEATURE Publishing] Conditionally apply cover overlay

- package.json
- src/Apps/Artist/Routes/Shows/ArtistShowBlockItem.tsx
- src/Styleguide/Utils/HorizontalPadding.tsx
- yarn.lock
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30742
Waiting for those changes to be released as a package.
> [types] Update styled-system types usage.

- package.json
- src/Apps/Artist/Routes/CV/CVItem.tsx
- src/Apps/Artist/Routes/CV/__tests__/CV.test.tsx
- yarn.lock
> Updates the Jest types for tooling

- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarPartnerInfo.test.tsx
- src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
Exercises the partner info component within the responsive artwork page sidebar.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-513 :lock:
> Add spec for Responsive Artwork Page (RAP) PartnerInfo component

- package.json
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
- src/Apps/Artwork/Components/ImageCarousel.tsx
- src/Apps/Order/Components/Helper.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- yarn.lock
Now the only thing that is left here to figure out why mediator events are not triggered in Force.
The rest is working:)
> use the Link from palette for extra links

- data/schema.graphql
- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
- src/__generated__/OfferMutation.graphql.ts
Follow up on https://github.com/artsy/metaphysics/pull/1392 so we can remove `initialOffer` mutation.
https://artsyproduct.atlassian.net/browse/PURCHASE-683
> Switch to use addInitialOfferToOrder

- apollo.config.js
- package.json
- yarn.lock
The required fix for the extension has been merged, so just waiting for a new release now. https://github.com/apollographql/apollo-tooling/pull/769
> [vscode] Configuration for the vscode-apollo extension

- .vscode/extensions.json
Sibling PR to https://github.com/artsy/emission/pull/1239
> Recommend against including the Prisma GraphQL extension

- src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
- src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
- src/__generated__/WorksForYouArtistFeed_viewer.graphql.ts
- src/__generated__/WorksForYouQuery.graphql.ts
Fixes graphql validation warning:
> [Graphql] Fix query warning

- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Styleguide/Components/__tests__/CountdownTimer.test.tsx
- src/Styleguide/Components/__tests__/Timer.test.tsx
- src/Utils/__mocks__/getCurrentTimeAsIsoString.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-679
Also fixed a couple of things
- Make sure to use the `lastOffer` field for the transaction summary
- Added the response choice parameters to the window.alert for the continue button so we can test that the data is being set properly already.
> Test the respond page

- package.json
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Styleguide/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
- src/Styleguide/Components/FollowArtistPopover/index.tsx
- yarn.lock
For now I'm removing the react-popover addition and just putting this pop up statically below the follow element.
We can figure out later - what artsy popover elements should look like.
For now also using the existing size for Avatar. May need to introduce a smaller `xxs` size to palette if @design decides that it is crutial.
For now the popover looks like that:
> adding style to FollowArtistPopover

- src/Components/FollowButton/FollowArtistButton.tsx
> [PATCH followArtistPopover] - style

- src/Apps/Artwork/Components/ImageCarousel.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
Quick follow-up to https://github.com/artsy/reaction/pull/1663 which fixes left left arrow clicks as well as wide images.
> [FIX artwork] Properly transition to different images

- src/Apps/Artwork/Components/ImageCarousel.tsx
> [FIX artwork] Fix back arrow

- package.json
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextAuction.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
- src/__generated__/ArtistArtworkGrid_artwork.graphql.ts
- src/__generated__/ArtworkContextArtistQuery.graphql.ts
- src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
- src/__generated__/ArtworkContextAuctionQuery.graphql.ts
- src/__generated__/ArtworkContextFairQuery.graphql.ts
- src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
- src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
- src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
- src/__generated__/AuctionArtworkGrid_artwork.graphql.ts
- src/__generated__/FairArtworkGrid_artwork.graphql.ts
- src/__generated__/PartnerArtworkGrid_artwork.graphql.ts
- src/__generated__/PartnerShowArtworkGrid_artwork.graphql.ts
- src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
- src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
- src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
- src/__generated__/RelatedWorksArtworkGrid_artwork.graphql.ts
Attempting to fix semantic release as its in a stuck state :/
> [PATCH artwork] Update artwork count

- package.json
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- yarn.lock
> [patch palette] upgrade palette

- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Artsy/Router/Components/Boot.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-719
> First pass in fixing createToken stripe not showing errors

- src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
- src/__generated__/ArtworkSidebarQuery.graphql.ts
- src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
- src/__generated__/ArtworkSidebar_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
> @oxaudo => Add AuctionTimer to artwork page sidebar for not-closed auctions

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
Just getting a new version out.
> [PATCH Sidebar] Bump version

- data/schema.graphql
- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/submitPendingOffer.ts
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
- src/__generated__/CounterSubmitMutation.graphql.ts
- src/__generated__/Counter_order.graphql.ts
- src/__generated__/routes_CounterQuery.graphql.ts
Update schema to latest MP and added mutation for submit pending offer in counter flow.
> Submit Pending Counter Offer

- src/Apps/Order/Routes/Status/index.tsx
- src/Apps/Order/Routes/__tests__/Status.test.tsx
fixes https://artsyproduct.atlassian.net/browse/PURCHASE-739
> [PATCH bnmo] fix extra # and submitted offer copy

- src/Apps/Artist/Routes/Shows/ArtistShows.tsx
- src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
- src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
- src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
- src/Styleguide/Components/ArtistCard.tsx
Was getting some js errors for getting `.cropped` of null so searched for all .cropped and replaced those with `get` functions (just to be safe :). Thanks @damassi for adding this function in a first place!
> make getting url from images defensive

- src/Components/Publishing/Nav/NewsNav.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
single character change so adds don't overlap the header
> [PATCH publishing] fix z-index on news sub-menu

- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Culture.tsx
- src/Components/Publishing/Layouts/FeatureLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Nav/Nav.tsx
- src/Components/Publishing/Nav/__tests__/Nav.test.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
- src/Components/Publishing/Sections/ImageSetPreview/ImageSetLabel.tsx
- Stops fullscreen images from limiting height on smaller screens
- Hide slideshow titles, and fixup display in both features
- Cleanup `Nav` sticky styling
> EOY Culture QA

- src/Apps/Order/Routes/Respond/index.tsx
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-746
It actually tries to show spinner but we immediately remove it in case of accept and reject. Fix here was to remove the removing :)
> Remove invisible spinner

- src/Components/Publishing/EditorialFeature/Components/Eoy2018Culture.tsx
Adds sticky headers to EOY Culture feature
Addresses https://artsyproduct.atlassian.net/browse/GROW-1034
> [PATCH publishing] EOY Culture sticky headers

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
> [PATCH ArtworkBanner] update spacing

- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/ArticleHeader.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Culture.tsx
- src/Components/Publishing/EditorialFeature/EditorialFeature.tsx
- src/Components/Publishing/EditorialFeature/Fixtures/Eoy2018Artists.ts
- src/Components/Publishing/EditorialFeature/Fixtures/Eoy2018Culture.ts
- src/Components/Publishing/EditorialFeature/__tests__/EditorialFeature.test.tsx
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Sections/Text.tsx
- src/Components/Publishing/__stories__/EditorialFeature.story.tsx
- yarn.lock
Changes apply to both EOY articles:
- Uses article `Text` component and enables tooltips
- Adds fixtures
- Adds storybooks
- Adds snapshot tests
> EOY Tooltips, cleanup

- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
- src/__generated__/ArtworkContextArtistQuery.graphql.ts
- src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
- src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
- src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
- src/__generated__/PartnerArtworkGrid_artwork.graphql.ts
To match the current implementation on Force.
> @damassi => [ArtworkPage] Use correct sort and for sale params for partner artworks

- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/AuctionCard.tsx
This should bring the responsive view to the close match of definitions from here: https://artsyproduct.atlassian.net/browse/DISCO-583
> [PATCH OtherAuctions] - responsive view for other auctions.

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/AuctionCard.tsx
Update to follow https://artsyproduct.atlassian.net/browse/DISCO-611
> [PATCH Sidebar] - make commercial buttons bigger.

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
- src/__generated__/ArtworkActions_artwork.graphql.ts
- src/__generated__/ArtworkImageBrowserQuery.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
Fix regression introduced here https://github.com/artsy/reaction/pull/1752 and addresses follow-up comments about checking if a work is an auction before evaluating.
> [PATCH artwork] Fix bell icon

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Styleguide/Components/Footer.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-559 and slightly increases padding between share and image on mobile.
> [Artwork] Add conditions of sale link

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Styleguide/Components/Carousel.tsx
- src/Styleguide/Components/RecentlyViewed.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-608
Addresses bad mobile experience of the Recently Viewed bottom bar by accounting for responsive. 
(Merging to get to staging to test since XCode is still downloading)
> [PATCH recentlyViewed] Fix mobile scrolling

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Styleguide/Components/Carousel.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-601
> [PATCH artwork] Fix issue where rapid selects selects image background

- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-594
> [PATCH artwork] Pass mediator to related grids to trigger modal when saving 

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Fixes lightbox clicking on mobile. (It worked fine, but it doesn't work well when simulating a mobile device.)
> [PATCH artwork] Fix mobile lightbox

- src/Components/FollowButton/FollowArtistButton.tsx
- src/Styleguide/Components/ArtistCard.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-625
This was also a bug in /artist/id for unauthed users.
> [PATCH artwork] Fix auth in ArtistCardFollow

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarBidAction.ts
Keep slight difference in the language there but otherwise it's the same button for live auction regardless of one is registered or not.
Address https://artsyproduct.atlassian.net/browse/DISCO-617
> [PATCH BidActions] - User should be able to watch live bidding when registration is closed and live bidding is in progress

- src/Apps/Order/Components/ArtworkSummaryItem.tsx
- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/Reject/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/__generated__/Counter_order.graphql.ts
- src/__generated__/Reject_order.graphql.ts
- src/__generated__/routes_CounterQuery.graphql.ts
- src/__generated__/routes_RejectQuery.graphql.ts
- src/__stories__/config.js
fixes https://artsyproduct.atlassian.net/browse/PURCHASE-741
And a few other things:
- restructures the stories to be easier to browse
- fix a bunch of other spacing issues
- fix the helper placements
- add our responsive media framework's global css to the storybook setup
> Misc UI fixes for counteroffer pages

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-606
Fixes issue related to mail popup being (semi) blocked. https://developer.apple.com/safari/technology-preview/release-notes/#r15
> [PATCH artwork] Fix safari mail issue

- package.json
- yarn.lock
Replaces https://github.com/artsy/force/pull/3261
> [FIX package] Update network stack to surface GraphQL errors.

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/Status/index.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Apps/Order/Routes/__tests__/Status.test.tsx
- src/Components/Publishing/Video/Player/Scrubber.tsx
- src/Components/__stories__/PopoverExamples/DisplayPopoverOnBlurExample.tsx
This is just a copy update PR for this ticket:
https://artsyproduct.atlassian.net/browse/PURCHASE-768
See over there for a bunch of pretty pictures. ❤️
> PURCHASE-768: Copy updates

- package.json
- yarn.lock
So we get https://github.com/intuit/auto-release/pull/128
> Update auto, should fix our custom tags

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/__tests__/Offer.test.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
> fix offer speed bump thresholds

- src/Apps/WorksForYou/MarketingHeader.tsx
Removes BNMO banner on Works for You page.
Addresses [PURCHASE-735](https://artsyproduct.atlassian.net/browse/PURCHASE-735).
> Remove BNMO marketing banner on Works for You page

- src/Apps/Artwork/ArtworkApp.tsx
Fixes issue where a tall sidebar would push down the center content area:
> [Artwork] Make center content properly flow regardless of sidebar size

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
Jeffrey came across this issue: https://artsyproduct.atlassian.net/browse/DISCO-652
Here is the fix:)
> fix display for single editioned works with hidden availability

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/Artsy/Analytics/Schema/Values.ts
> @damassi => Analytics for clicking to enter a live auction

- src/Artsy/Analytics/Schema/Values.ts
- src/Styleguide/Components/Lightbox/Lightbox.tsx
> @damassi => Add analytics for clicking lightbox zoom

- package.json
- yarn.lock
```
$ yarn omg src/Apps/Artwork/Components/SomethingSomething
yarn run v1.12.3
$ /Users/eloy/Code/Artsy/reaction/node_modules/.bin/om g src/Apps/Artwork/Components/SomethingSomething
create src/Apps/Artwork/Components/SomethingSomething.tsx
create src/Apps/Artwork/Components/__tests__/SomethingSomething.test.tsx
✨  Done in 0.58s.
$ cat src/Apps/Artwork/Components/SomethingSomething.tsx
import React from "react"
export interface SomethingSomethingProps {
}
export const SomethingSomething: React.SFC<SomethingSomethingProps> = props => {
return null
}
$ cat src/Apps/Artwork/Components/__tests__/SomethingSomething.test.tsx
import { mount } from "enzyme"
import React from "react"
import { SomethingSomething } from "../SomethingSomething"
describe("SomethingSomething", () => {
it("renders", () …
```
> [package] Add @omakase/cli which has the component/container generator.

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ArtworkApp_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
cc @cavvia these are those two sets of custom analytics you had added (enhanced properties for the pageview track, and the `Viewed Product` one).
> @damassi => Custom artwork analytics for BNMO + pageview

- .autorc
- package.json
- yarn.lock
Updates to v2!! Should fix some release issues we've been having. Hopefully the changelog thing too..
> Update auto-update to v2

- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
https://artsyproduct.atlassian.net/browse/SELL-1273
🙈 The copy in the Jira ticket was wrong, and I updated that too.
> Fix artsy.com typo

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Missed this in the code review!
> @oxaudo => Correct reference to props in BNMO analytics

- src/Apps/Artist/Routes/Overview/index.tsx
- src/Styleguide/Components/ArtistInsight.tsx
- src/Styleguide/Components/ArtistInsightsModal.tsx
Update design implementation with a few requested changes.
tickets: https://artsyproduct.atlassian.net/browse/DISCO-662, https://artsyproduct.atlassian.net/browse/DISCO-661 :lock: 
**Before**
**After**
> Tidy up Artist Insights design implementation

- src/Apps/Artist/Routes/Overview/index.tsx
Mixed up the different variations switching from two experiment variations to one. For the A/B test we want to show Artist Insights after the bio.
> Move Artist Insights component after bio

- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/ArticleHeader.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/__tests__/index.test.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
- src/Components/Publishing/EditorialFeature/Fixtures/Eoy2018Artists.ts
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
Adds a few unit tests for EOY artists page.
> EOY artists unit tests

- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/v2/Carousel.tsx
Fixes slightly clipped arrows due to chevron icon replacement
> Fix Carousel arrows

- .circleci/config.yml
- package.json
- src/Artsy/Router/Components/Boot.tsx
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- yarn.lock
Follow-up PR to https://github.com/artsy/palette/pull/181
> Remove GridThemeProvider and move to palette

- src/Apps/Order/Dialogs.tsx
- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Reject/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Accept.test.tsx
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Apps/Order/Routes/__tests__/Reject.test.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-792 
Finishing up the ErrorModal -> ModalDialog refactor.
Can't wait to clean up those tests 💆‍♂️
> Refactor error modals

- src/Apps/__tests__/Fixtures/SelectedCareerAchievements.ts
- src/Components/v2/__tests__/ArtistInsight.test.tsx
- src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
- src/__generated__/SelectedCareerAchievementsTestQuery.graphql.ts
Add specs for the overall and individual artist insight components.
> Add specs to exercise components for Artist Insights V2

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
- src/Apps/Order/Routes/__tests__/Offer.test.tsx
User sees helpful error message in a modal if they submit an offer to exchange with an invalid amount
> added error message modal for invalid amount

- src/DevTools/README.md
see https://github.com/artsy/reaction/pull/1854#issuecomment-454100304 for context
> Add docs for relay data mocking

- src/Apps/Collections/CollectionsApp.tsx
- src/Apps/Collections/Components/CollectionsGrid.tsx
- src/Apps/Collections/Components/__tests__/CollectionsGrid.test.tsx
- src/Apps/Collections/__tests__/CollectionsApp.test.tsx
finishes https://artsyproduct.atlassian.net/browse/GROW-1013
I was lazy and didn't bother updating kaws... but I think this PR is simple enough. Let me know what you think!
> Sort Collections alphabetically by title in Index page

- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/ArticleHeader.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
Adds min and max font-size calculations to prevent linebreaks in EOY artists feature header.
> Use fluid fontsize for EOY artists feature

- src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
- src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreviewClassic.tsx
- src/Components/Publishing/Typings.ts
Removes `null` state from ImageSetPreview, adds better typings for Image data
> Imageset props

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
This is needed for https://github.com/artsy/force/pull/3392.
> Expose image width and height for view in room

- package.json
- src/Components/v2/Lightbox/Lightbox.tsx
- yarn.lock
Possible fix for https://sentry.io/artsynet/force-production/issues/841992571/
Ensure that the element passed to the deep zoom window is an HTML element before mounting.
Also update lint staged
> [Bugfix] Guard against missing elements

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ArtworkActions_artwork.graphql.ts
- src/__generated__/ArtworkImageBrowserQuery.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
This should address https://artsyproduct.atlassian.net/browse/DISCO-685
I added the event trying to follow the other buttons, but @cavvia should definitely confirm it before we are happy with it.
> add tracking to view in room click

- package.json
- src/Apps/Collect/Components/Filters/ColorFilter.tsx
- src/__generated__/ArtworkActions_artwork.graphql.ts
- src/__generated__/ArtworkImageBrowserQuery.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
- yarn.lock
minor, plus some generated files from a previous PR
> @mzikherman => [Collect] Allow clicking on check icon to deselect color filter

- src/Apps/Artist/Routes/Shows/ArtistShowBlockItem.tsx
- src/Components/Artwork/GridItem.tsx
- src/__generated__/ArtworkActions_artwork.graphql.ts
- src/__generated__/ArtworkImageBrowserQuery.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
Fixes https://artsyproduct.atlassian.net/browse/GROW-1094
> [Bugfix] Only track artwork scroll on /collect

- src/Components/v2/AuctionCard.tsx
- Fixes moment deprecation warning on artwork page
> Fixes moment warning

- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
Related: https://artsyproduct.atlassian.net/browse/BUGS-717
> Autofocus on first field in authentication forms

- src/Apps/Collect/Components/Filters/ColorFilter.tsx
There's...probably a better way to position these :() Fixes https://artsyproduct.atlassian.net/browse/DISCO-684
> @mzikherman => [ColorFilter] Update positions for checkmark overlay

- src/Components/Publishing/Fixtures/Components.ts
Adds a fixture of ImageCollection data for easy testing.
> Fixture for ImageCollection data

- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Series/SeriesAbout.tsx
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
Addresses: https://artsyproduct.atlassian.net/browse/GROW-600
> Add social sharing buttons on series pages

- .autorc
- package.json
- yarn.lock
> Use shared auto config

- renovate.json
Enable auto-merging of minors and patches.
> [Renovate] Auto-merge minor and patch updates

- src/Components/Publishing/Icon/IconDrag.tsx
Was giving errors over null state.
Self merging since trivial.
> Fixup IconDrag interfaces

- src/Components/Publishing/Typings.ts
Update typings for use in Positron.
Self merging since trivial.
> Add to be deprecated slideshow and image to SectionType type

- src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
Fix broken snapshot tests from #1969
> Fix broken snapshot tests from #1969

- README.md
> Update state of reaction

- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Series/SeriesAbout.tsx
- src/Components/Publishing/Series/SeriesTitle.tsx
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
- src/Components/Publishing/Typings.ts
- src/Components/Publishing/Video/Player/VideoPlayer.tsx
- src/Components/Publishing/Video/VideoAbout.tsx
- src/Components/Publishing/Video/VideoCover.tsx
- src/Components/Publishing/Video/VideoInfoBlock.tsx
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
Some series and video components were declared with `<Props, null>`, which prevented us from converting some files in Positron to `.tsx`
Null states have been removed from video/series components, also added a few additional typings and minor cleanup while in there.
> Update series/video null states

- src/Artsy/Relay/middleware/metaphysicsExtensionsLoggerMiddleware.ts
Noticed these, was actually causing Storybooks to crash locally.
> @orta => [Metaphysics Logger] Fix some edge cases

- package.json
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- yarn.lock
Fix snapshots since we now have better displayNames on palette components
> Bump styled components / snapshots

- src/Components/v2/AuctionTimer.tsx
> @mzikherman => [AuctionTimer] Fix bug when :00 would render as :0

- src/Apps/Order/Routes/NewPayment/index.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/__generated__/NewPaymentRouteCreateCreditCardMutation.graphql.ts
- src/__generated__/NewPaymentRouteSetOrderPaymentMutation.graphql.ts
- src/__generated__/NewPayment_order.graphql.ts
- src/__generated__/routes_NewPaymentQuery.graphql.ts
Build 'Payment' page for resubmitting payment method
> New payment route

- src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-910
> Exclude vertical from related articles canvas if article layout is news

- package.json
- src/Artsy/Router/__tests__/buildServerApp.test.tsx
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
- yarn.lock
This fixes 
https://artsyproduct.atlassian.net/browse/PLATFORM-1184. See that ticket for a complete write-up of the details.
This PR also removes the apparently thus far unused `loadable-components` dep.
> Always render in context of isolated stylesheet.

- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
Proper `href` and linking of items.
> @mzikherman => [Autosuggest] Link on click/enter to suggestion items

- src/Components/Search/__tests__/SearchBar.test.tsx
I _think_ this is the one you were referring to? 
https://github.com/artsy/reaction/pull/2035#discussion_r258053726
> [SearchBar] Fix disabled test.

- src/Components/Publishing/Article.tsx
Related slack convo: https://artsy.slack.com/archives/C2TQ4PT8R/p1550601288097000
> [Publishing] remove GridThemeProvider

- data/schema.graphql
- Updates schema after https://github.com/artsy/metaphysics/pull/1514#pullrequestreview-205411728
> Updates relay schema

- src/Components/Publishing/EditorialFeature/__tests__/EditorialFeature.test.tsx
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- Adds `jest-styled-components` to EditorialFeature test and updates snapshot
> Adds jest-styled-components to EditorialFeature

- data/schema.graphql
Noticing some schema failures. This pulls in the latest
> Pull in latest schema

- src/Components/CollectionsRail/CollectionEntity.tsx
- src/Components/CollectionsRail/CollectionsRail.tsx
- src/Components/CollectionsRail/__tests__/CollectionEntity.test.tsx
- src/Components/CollectionsRail/__tests__/CollectionsRail.test.tsx
Updates analytics tracking calls to use revised fields here: https://docs.google.com/spreadsheets/d/1_VDAmRJz2K87FXDq7oh_tQSgwBv4syuZjaaR3sfetcI/edit#gid=0
cc @abhitip
> Update CollectionsRail analytics with revised fields

- src/Components/Search/SearchBar.tsx
Fixes the issue observed in staging.
> @mzikherman => [Autosuggest] Make sure to wrap SearchBar with context provider

- package.json
- src/Components/Publishing/Nav/Nav.tsx
- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/Sections/Author.tsx
- src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
- src/Components/Publishing/Sections/VerticalOrSeriesTitle.tsx
- src/Components/v2/Carousel.tsx
- yarn.lock
Not sure how these got into master. Quick fix.
> Fix type errors

- package.json
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
- yarn.lock
Fix snapshots due to alphabetization
> Bump palette

- src/Components/NavBar/index.tsx
- src/Components/__stories__/NavBar.story.tsx
**Zeplin:** https://zpl.io/aNPZPPZ
Begins the process of laying out the new top nav. Just static this round with everything in the same file. Follow up PRs will clean up code, structure and start adding types. 
New react hooks are a real beauty 👌.  
Rebased from https://github.com/artsy/reaction/pull/2090
> First pass static <NavBar /> UI

- src/Apps/Collect/CollectMediumMetadata.ts
- src/Apps/Collect/CollectionApp.tsx
- src/Apps/Collect/__tests__/CollectApp.test.tsx
- src/Apps/Collect/__tests__/CollectMediumMetadata.test.ts
- src/Apps/Collect/__tests__/CollectionApp.test.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-1129
> Update title meta for collections

- src/Artsy/Relay/renderWithLoadProgress.tsx
> Return correct error

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
removed isAdmin check for VIR button
> View-in-room - Remove admin flag on view-in-room feature

- src/Components/NavBar/MobileNavMenu/MobileToggleIcon.tsx
- src/Components/NavBar/MobileNavMenu/index.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
Just a quick styling of the mobile menu: 
Next up: 
- Add notification number badge
> [NavBar] Style mobile nav

- package.json
- yarn.lock
> Pin palette dep

- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Header/Layouts/Components/FeatureFullscreenHeader.tsx
- src/Components/Publishing/Sections/Image.tsx
Addresses: [GROW-1135](https://artsyproduct.atlassian.net/browse/GROW-1135)
This increases the resize width to be 2000 instead of 1200 to prevent blurred images.
> GROW-1135: resize full-width images to 2000

- .circleci/config.yml
- package.json
- yarn.lock
Resolves [PLATFORM-1289](https://artsyproduct.atlassian.net/browse/PLATFORM-1289)
It's important for us to have more insights to our tests in CI. Both which tests commonly fail and which tests take a long time to run. CircleCI provides a somewhat [simple hook](https://circleci.com/docs/2.0/collect-test-data/#jest) for this behavior. After this PR is merged, we'll be able to see this information in [this view](https://circleci.com/build-insights/gh/artsy/reaction/master).
> Wire up test to report results to ci

- src/Apps/Artist/Routes/Overview/index.tsx
Turns out we want to make this change with an AB test, so I'm hiding these genes again.
> DISCO-852: Hide genes once again

- src/Apps/Artist/Routes/Overview/index.tsx
Address: [GROW-1139](https://artsyproduct.atlassian.net/browse/GROW-1139)
This uses `showCollectionsRail` to determine when to show the rails on the artist page.
> set up artist collections rail test

- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
- src/Apps/Search/routes.tsx
- src/__generated__/SearchResultsArtistsQuery.graphql.ts
- src/__generated__/SearchResultsArtists_viewer.graphql.ts
Noticed this tab got missed in the pagination sweep, so this adds it.
> @dblandin => [SearchResults] Add pagination to artists tab

- src/Apps/Order/Utils/commitMutation.tsx
> run prettier

- src/Apps/Order/Utils/__tests__/commitMutation.test.tsx
- src/Apps/Order/Utils/commitMutation.tsx
> move jest.unmock call

- data/schema.graphql
- src/Apps/Order/Utils/commitMutation.tsx
- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/Routes/More/SearchResultsMore.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/SearchResultsMoreQuery.graphql.ts
- src/__generated__/SearchResultsMore_viewer.graphql.ts
- src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
Pretty easy! This just adds `INSTITUTION` to the entities for the 'More' tab, as well as tweaks to the tab counts.
> @dblandin => [SearchResults] Add institution to More tab

- src/Apps/__stories__/OrderApp.story.tsx
- src/Apps/__tests__/Fixtures/Order.ts
Trivial fix to make the OrderApp stories work again. I tested all of them.
> Fix OrderApp stories

- src/Apps/Search/Components/__tests__/SendFeedback.test.tsx
cc @dblandin 
Added some specs.
> @mzikherman => [SearchResults] Add tests for sending feedback

- src/Components/Publishing/Icon/IconLayoutBasic.tsx
- src/Components/Publishing/Icon/IconLayoutFullscreen.tsx
- src/Components/Publishing/Icon/IconLayoutSplit.tsx
- src/Components/Publishing/Icon/IconLayoutText.tsx
Updates a few publishing icons to not declare null states
> [TRIVIAL] Remove null states from publishing Icons

- data/schema.graphql
We made a couple of breaking changes to vortex's schema. Just propagating the change to here.
> Sync metaphysics schema

- src/Components/Publishing/Header/Layouts/Components/FeatureTextHeader.tsx
Renames and exports `FeatureTextAsset` for use in Positron
> [TRIVIAL] export FeatureTextAsset

- src/Apps/Search/Components/NavigationTabs.tsx
lil' fix, was noticing these weren't working and the method needed to be bound properly.
> @mzikherman => [SearchResults] Fix analytics for nav tabs

- data/schema.graphql
- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/routes.tsx
- src/__generated__/SearchResultsArtistsQuery.graphql.ts
- src/__generated__/SearchResultsArtists_viewer.graphql.ts
- src/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
Depends on https://github.com/artsy/metaphysics/pull/1634
Pretty simple!
> @damassi => [Search] Allow pagination to be set from URL, and modify URL on artists tab

- package.json
- src/Apps/Collect/Components/Filters/MediumFilter.tsx
- src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
- src/Apps/Collect/Components/Filters/__tests__/MediumFilter.test.tsx
- src/Apps/Collect/Components/Filters/__tests__/TimePeriodFilter.test.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/MediumFilter.test.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/TimePeriodFilter.test.tsx
- yarn.lock
Blocked by https://github.com/artsy/palette/pull/350.
Follow up which adds a `deselectable` prop to `/collect` and `/search` apps to fix a migration over to `<RadioGroup>` in https://github.com/artsy/reaction/pull/2218. Once #350 up above is merged the double-fire issue will also be resolved.
> [RadioGroup] Add deselectable option

- src/Apps/Artwork/Components/PricingContext.tsx
- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
- src/Apps/Artwork/routes.tsx
- src/Artsy/Relay/createRelaySSREnvironment.ts
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/__generated__/PricingContextTestQuery.graphql.ts
- src/__generated__/PricingContext_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
This was a neat little solution 👌 Thanks again for the suggestion, @mzikherman
> Gate pricing context

- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
Closes https://artsyproduct.atlassian.net/browse/DISCO-880
pretty simple!
> @cavvia => [Search] Make sure to expand medium and price filters

- src/Apps/Search/Components/SendFeedback.tsx
- src/Apps/Search/Components/__tests__/SendFeedback.test.tsx
For logged out users, they have to provide a name and email in addition to the message. We were showing the correct errors for all these cases (`Invalid email`), but we weren't actually preventing the submission. D'oh!
Bit of a refactor (+ more tests), but we now actually prevent submissions if there are any errors.
Closes https://artsyproduct.atlassian.net/browse/DISCO-889
> @dblandin => [Search] Make sure to prevent feedback submission for invalid emails

- src/Apps/Search/Components/SendFeedback.tsx
Closes https://artsyproduct.atlassian.net/browse/DISCO-888
> @mzikherman => [Search] Tweak styling of feedback component

- src/Apps/Search/Components/GenericSearchResultItem.tsx
Closes https://artsyproduct.atlassian.net/browse/DISCO-885
To make this more like the existing page, we decided to make the whole row a link.
> @dblandin => [Search] Make entire row clickable for non artwork tab results

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
- src/Apps/__stories__/Apps.story.tsx
W/o any tabs or totals when there are no results:
We also are hiding tabs if there are no results of that type.
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-881
> @dblandin => Adjusted zero state

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/Components/SearchMeta.tsx
- src/Apps/Search/Components/__tests__/SearchMeta.test.tsx
- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- src/Apps/Search/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
I'll have an accompanying Force PR once this is merged to hook that part up.
Pretty simple!
> @dblandin => [SearchResults] Respond to /search instead of /search2

- src/Apps/Search/Components/GenericSearchResultItem.tsx
- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Components/v2/RouteTabs.tsx
- Adjusting color of tabs (inactive state more visible)
- Background color on hover (no underlines) for results
> @dblandin => [SearchResults] Some tweaks to calling out when hovering over an item

- src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistRecommendations.test.tsx
- src/Apps/Artist/Routes/Overview/__tests__/Index.fixture.tsx
- src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/__stories__/ArtistApp.story.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ArtistRecommendationsQuery.graphql.ts
- src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
- src/__generated__/ArtistRecommendations_artist.graphql.ts
- src/__generated__/Overview_artist.graphql.ts
- src/__generated__/RecommendedArtist_artist.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Addresses https://artsyproduct.atlassian.net/browse/DISCO-869.
This PR builds out the carousel for a recommended artist.
Here's what it looks like:
> Artist recommendation carousel

- src/Apps/Search/SearchApp.tsx
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-903
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-900
Pretty minor visual schtuff.
> @mzikherman => Bring back ze footah

- src/Apps/Search/FilterState.tsx
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-910
> @mzikherman => [Search] Preserve keyword when resetting filter on mobile

- .storybook/webpack.config.js
Quick fix from https://github.com/artsy/reaction/pull/2270 -- looks like we need to merge in existing plugins with our custom ones.
> Fix Storybooks plugins webpack config

- src/DevTools/README.md
Fixes from @alloy's post-merge review of `DevTools/README.md` in #2253
> createTestEnv docs follow-up

- src/Apps/Artwork/Components/PricingContext.tsx
- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
> Show 0 instead of null for lowest bucket

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artist/Components/__tests__/NavigationTabs.test.tsx
If the lab feature is present, hide the tab.
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-873
> @pepopowitz => [Artist Recommendations] Hide Related Artists tab

- src/Components/Publishing/Icon/IconEditEmbed.tsx
- src/Components/Publishing/Icon/IconEditImages.tsx
- src/Components/Publishing/Icon/IconEditSection.tsx
- src/Components/Publishing/Icon/IconEditText.tsx
- src/Components/Publishing/Icon/IconEditVideo.tsx
- src/Components/Publishing/Icon/IconHeroImage.tsx
- src/Components/Publishing/Icon/IconHeroVideo.tsx
These raise type errors if used in `.tsx` files
> [TRIVIAL] Remove null states from Icons

- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Components/v2/Carousel.tsx
- https://artsyproduct.atlassian.net/browse/DISCO-947
- Refactored original PR with help from @damassi to this PR
- This only adds this behavior to the `RecommendedArtist` component and carousel
> DISCO-947 - RecommendedArtist carousel arrows only render if more content

- src/Apps/Artwork/Components/PricingContext.tsx
- src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
- src/__generated__/PricingContextStoryQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1008
Also added a story for the `PricingContext` component :tada:
> When price is outside range include it in the bottom or top bucket

- src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
Minor updates to the positioning of the skeleton.
> Update style for search results page skeleton

- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MoreNavMenu.tsx
- src/Components/NavBar/Menus/NotificationsMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
- src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
- src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/Utils/__tests__/auth.test.ts
- src/Components/NavBar/__tests__/NavBar.test.tsx
- src/Components/NavBar/__tests__/NavItem.test.tsx
- src/Components/NavBar/__tests__/NotificationsBadge.test.tsx
Adds test coverage to new `<NavBar>` work.
> [NavBar] Add test coverage

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- https://artsyproduct.atlassian.net/browse/DISCO-974
> DISCO-974 - Expand price by default on collect and artist page

- src/Apps/Artwork/Components/PricingContext.tsx
- src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
- src/Apps/Artwork/routes.tsx
- src/__generated__/PricingContextStoryQuery.graphql.ts
- src/__generated__/PricingContextTestQuery.graphql.ts
- src/__generated__/PricingContext_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-979
Leaving this as "do not merge" until we get the green light!
> Removes lab feature requirement for pricing context

- src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
- Removes erroneously pushed `console.log`
> Removes accidental console.log

- package.json
- src/Artsy/Analytics/Schema/Values.ts
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MoreNavMenu.tsx
- src/Components/NavBar/Menus/UserMenu.tsx
- src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/NotificationsBadge.tsx
- src/Components/NavBar/Utils/useTracking.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
- src/Components/NavBar/__tests__/NavItem.test.tsx
- src/Components/NavBar/__tests__/NotificationsBadge.test.tsx
- yarn.lock
Implements tracking for the new `<NavBar />` component. 
Todo: 
Tracking matrix: https://docs.google.com/spreadsheets/d/17oqFli15x1SmNBu_-fPZhFifMw2BNSPJe9VdOgs1aKs/edit#gid=797068217
> [NavBar] Implement tracking

- renovate.json
Continuing the slow rollout of the master issue approval workflow
> Update renovate to use new lib workflow

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/PriceRangeFilter.tsx
- src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/PriceRangeFilter.tsx
- Adds disabled text to priceRange filters on Artwork, Search and Collect pages
> Adds disabled text to priceRange filters

- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
#trivial 
Some misc QA stuff that feel out while testing between reaction / force. Mostly just a backdrop for when nav is open:
> [NavBar] Misc QA

- src/Components/NavBar/Menus/NotificationsMenu.tsx
> [NavBar] Fix typo

- data/schema.graphql
Syncs the MP schema; noticed sync failures elsewhere. 
cc @mdole
> [Schema] Sync schema

- data/schema.graphql
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/__stories__/NavBar.story.tsx
Adds a hover state to mobile items.
> Add hover to mobile nav items

- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/GridItem.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/WaysToBuyFilter.tsx
- Updates skeleton styling to more closely match the page layout
- Fixes some minor margin issues with filter layout
> Updates search results skeleton styling

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
- src/Components/Publishing/Layouts/__tests__/SeriesLayoutAdsEnabled.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Typings.ts
This PR enables the new ads on both Sponsored and non Sponsored Series landing pages
[Links to GROW 1207](https://artsyproduct.atlassian.net/browse/GROW-1207)
[Links to GROW 1257](https://artsyproduct.atlassian.net/browse/GROW-1275)
> Enable New ads on series landing pages

- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/VideoLayoutAdsEnabled.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
Addresses: [GROW-1208](https://artsyproduct.atlassian.net/browse/GROW-1208)
This adds the new ad for sponsored video pages.
**Desktop:**
**Mobile:**
> [Ad Server] add new ads for video layout pages

- data/schema.graphql
Syncs updates from https://github.com/artsy/metaphysics/pull/1731. 
Not much here? Anyway, at least it'll be up to date.
> Sync schema

- package.json
- yarn.lock
Matches `@types/react` with Palette and bumps a few type-related things, to fix issues around linking.
> [Lib] Fix type-checking between Reaction / Palette

- apollo.config.js
Follow-up to match Emission config: https://github.com/artsy/emission/pull/1626
👌 
#trivial
> [Tooling] Update apollo.config to match Emission

- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
- https://artsyproduct.atlassian.net/browse/DISCO-1021
> DISCO-1021 - Bring user to top of page when advancing pagination

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Typings.ts
JIRA: https://artsyproduct.atlassian.net/browse/GROW-1204
Sample feature article: http://localhost:5000/article/artsy-editorial-artists-famous-friends-originality-work
> [Article] add GPT ads to featured article

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/MobileActionSheet.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- src/Apps/Collect/Components/Filters/SortFilter.tsx
- src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
- src/Apps/Collect/Components/MobileActionSheet.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/WaysToBuyFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsMobileActionSheet.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/Search/SearchBar.tsx
Fixes a few issues caught during NavBar QA, as well as some other issues unrelated but noticed when doing a quick audit of the app. Will comment inline. 
Going to merge this since we have a NavBar QA meeting first thing in the morning and need fixes in staging. Will follow up on any requested changes / feedback.
> [QA] Miscellaneous app QA

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Typings.ts
Found a bug with ads rendering on featured article without feature flag enabled
Reverts artsy/reaction#2478
> Revert "[Article] add GPT ads to featured article"

- src/Apps/Search/Components/ZeroState.tsx
- src/Apps/Search/FilterState.tsx
- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
- src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/FilterState.test.ts
- https://artsyproduct.atlassian.net/browse/DISCO-1022
- Adds `hasFilter` boolean to Search `FilterState`
- Moves `Provider` to pass `FilterState` to ZeroState component
- Updates copy to search results using a filter
- Refactored https://github.com/artsy/reaction/pull/2467
> DISCO-1022 - Updates zero state copy

- src/Components/Input.tsx
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/NotificationsBadge.tsx
- src/Components/Search/SearchBar.tsx
- src/Components/__tests__/__snapshots__/Input.test.tsx.snap
More updates from todays NavBar QA session. Comments / images inline.
> [NavBar] Address QA items

- package.json
- src/Components/NavBar/Menus/MoreNavMenu.tsx
- src/Components/NavBar/NavBar.tsx
- yarn.lock
This is an experiment so that design can determine how best to position the nav dropdowns. 
Clicking more will toggle state:
> [NavBar] Add toggle test for menu position

- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- Fixes ArtistCollectionRail carousel
> Removes width from slide box element

- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
- Align slides in  `ArtistCollectionRail` carousel `left`
> ArtistCollectionRail slides align left

- src/Components/Truncator.tsx
- src/Components/v2/ArtistCard.tsx
This PR addresses some feedback on #2526, to give better hints with comments on the `Truncator` component.
> [ArtistCard] Update comments to give hints about proper truncation methods

- package.json
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- yarn.lock
Adds some light animation to the dropdowns per design request. Note the below isn't quite capturing it  due to frame-rate -- it's a slide down with a very very light bounce:
> [NavBar] Add animation to dropdown

- package.json
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- yarn.lock
Reverts artsy/reaction#2530
This is a temporary measure to try to get staging back up. 
cc @damassi, @joeyAghion, @eessex
> Revert "[NavBar] Add animation to dropdown"

- package.json
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- yarn.lock
Waiting on https://github.com/artsy/palette/pull/511 to merge this back in. 
Reverts artsy/reaction#2532
> Restore NavBar dropdown animations

- src/Components/Publishing/News/__tests__/NewsDateHeader.test.tsx
> Test CI date fix

- .babelrc
- package.json
- yarn.lock
I've tested this in Storybooks as well as linking to force and everything works great ¯\_(ツ)_/¯
> [Lib] Remove babel-plugin-rename-import

- src/Components/NavBar/NavItem.tsx
Updates ease settings. 
#trivial
> [NavBar] Adjust animation settings

- src/Components/Publishing/Byline/DateSource.tsx
- https://artsyproduct.atlassian.net/browse/GROW-1310
- Followup to https://github.com/artsy/reaction/pull/2554
> GROW-1310 - Updates date to isostring for luxon consumption

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Fixes price tracking on buy now clicks.
> fix event tracking for price. #minor

- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Renames test fixture for non-sponsored feature articles.
> Rename Feature Article Fixture

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/Components/__tests__/NavigationTabs.test.tsx
- src/Apps/Search/routes.tsx
- https://artsyproduct.atlassian.net/browse/PURCHASE-1198
- Adds `Fairs` and `Institutions` to search result tabs
- Depends on https://github.com/artsy/reaction/pull/2589
> PURCHASE-1198 - Adds fair and museums to Search results tabs

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
> Prevent Empty Div From Rendering If No Ad Served or Ad Blocker Enabled

- src/Apps/Collect/Components/Collection/Header/index.tsx
address : [grow_1367](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1367)
- any changed on width     **->**     the numbers of artist module would be changed automatically
**less  than 768**
**between 768 - 899**
**between 900 - 1024**
**greater than 1024**
> grow_1367 Featured artist module on Small viewport should be 3 per row

- src/Components/Publishing/Display/DisplayAd.tsx
Removes viewable threshold prop from ad component
> Removes viewable threshold prop from ad component

- src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCard.tsx
Renames so we can target styles in Positron.
> [Trivial] Rename and export article card image container

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Typings.ts
Addresses bug fixes in ads:
1) Removes prop from when ads were only served behind a feature flag
2) Fixes padding on mobile ads on standard articles
3) Updates failing tests in super articles
4) Fixes the ad dimension on ads in mobile standard article views
> Ad bug fixes

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Layouts/FeatureLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/Sections/Sections.tsx
Fixes a previously failing test where ads were being rendered on super articles.
> Remove ads from super articles

- src/Apps/Collect/Components/Collection/Header/__tests__/Header.test.tsx
- src/Apps/Collect/Components/Collection/Header/index.tsx
This PR addresses https://artsyproduct.atlassian.net/browse/GROW-1282.
It adds test coverage for the collection header, a few types, and some refactoring to remove concepts that are no longer needed.
> Test & refactor collection header

- src/Apps/Artwork/Components/PricingContextModal.tsx
- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
- src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
- https://artsyproduct.atlassian.net/browse/PURCHASE-1347
- Depends on https://github.com/artsy/palette/pull/547#issuecomment-515188093
> PURCHASE-1347 - Uses modal for price in context

- data/schema.graphql
Noticed MP was out of sync in Force
> Sync MP schema #trivial 

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/TOC.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/TableOfContents.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
- src/Components/Publishing/EditorialFeature/EditorialFeature.tsx
Sets up basic structure/wireframe for Artsy Vanguard 2019 feature.
> Scaffold Vanguard series page

- package.json
- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
- src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
- yarn.lock
- Updates palette to `4.14.41`
> Updates palette to 4.14.41

- src/Apps/__tests__/Fixtures/Collections.ts
- src/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
- src/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
Addresses: [GROW-1449](https://artsyproduct.atlassian.net/browse/GROW-1449)
This is follow up work to https://github.com/artsy/reaction/pull/2628. It adds the following to the component:
- The carousel
- Makes the collections items linkable
- Add specs
> Featured collections hub

- src/Artsy/Analytics/Schema/Values.ts
- src/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
- src/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Addresses: [GROW-1370](https://artsyproduct.atlassian.net/browse/GROW-1370)
> GROW-1370: add analytics tracking to FeaturedCollections module

- src/Apps/__tests__/Fixtures/Collections.ts
- src/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
- src/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
- src/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
- src/Components/CollectionsHubRails/index.tsx
- src/__generated__/ArtistSeriesEntity_member.graphql.ts
- src/__generated__/ArtistSeriesRail_collectionGroup.graphql.ts
- src/__generated__/CollectionsHubRails_marketingCollection.graphql.ts
- src/__generated__/CollectionsRailsQuery.graphql.ts
address: [Grow1354](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1354)
- arrow buttons is not showing in the screenshot because there are only 4 items. So, In the test, I set up a showing the arrow buttons test, and it is passed when there are more than 4 items.
> Grow 1354 Artist Series Module

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
Adds credit lines for creative contributors.
> [Vanguard] Add creative credits

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
> Refactor svg blobs on artist headers

- src/Components/Publishing/Fixtures/Articles.ts
Found an incorrect fixture while pairing with @mbilokonsky
> [TRIVIAL] Update fixture to use correct naming for related_article_ids

- src/Components/v2/Carousel.tsx
- src/Components/v2/__stories__/Carousel.story.tsx
Updates the carousel to pass back props / index so that if needed, we can pass that data along to tracking (or whatever).
> [Carousel] Pass index / props down to render items

- package.json
- src/Apps/Collect2/Routes/Collect/CollectionApp.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Collect2/collectRoutes.tsx
- src/Apps/Search/routes.tsx
- src/Artsy/Relay/renderWithLoadProgress.tsx
- src/Artsy/Router/Utils/RenderStatus.tsx
- src/Artsy/Router/Utils/Route.tsx
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/Components/ArtworkFilter/Dropdown.tsx
- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Modal/Modal.tsx
- src/Components/Modal/ModalWrapper.tsx
- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Video/Player/VideoPlayer.tsx
- src/Components/QuickInput.tsx
- src/Components/StepMarker/index.tsx
Adds a new interstitial loading state for full-page routes:
> [Router] Add in  interstitial loading state

- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/Collect2/Routes/Collections/index.tsx
Fixes some alignment issues on /collect and /collections:
> [Collect] Fix text alignment

- package.json
- src/Apps/Order/Routes/__tests__/Accept.test.tsx
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
- src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
- src/Apps/Order/Routes/__tests__/Reject.test.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Components/v2/__tests__/CountdownTimer.test.tsx
- yarn.lock
- Updates palette
- Mocks `global.setInterval` for tests using `TimeRemaining` which is using the `useInterval` palette util hook which uses a setInterval to update state.
> Updates palette and mocks setInterval in tests using TimeRemaining

- src/Apps/Collect2/Routes/Collections/index.tsx
> Remove debug text #trivial

- src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Reverts artsy/reaction#2728
Couple of reverts to revert https://github.com/artsy/reaction/pull/2714
> Revert "[ArtworkFilter] Ensure page is reset to 1 on filter change #trivial"

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
- Based on the QA feedback, make some change on the Artist Series on the collection hub. ref to [QA for 1334](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1354).
- For the smaller viewpoint, when there are only 4 items in the carousel, it will show the arrow button. See below GIF.
> New PR for improving CSS

- src/Artsy/Router/Utils/Route.tsx
> @mzikherman => [Error Handling] Correct default if no status codes provided

- src/Apps/Collect2/Components/Collection/Header/DefaultHeader.tsx
- src/Apps/Collect2/Components/Collection/Header/__tests__/DefaultHeader.test.tsx
- src/Apps/Collect2/Components/Collection/Header/__tests__/Header.test.tsx
- src/Apps/Collect2/Components/Collection/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
- src/Apps/Collect2/Components/Collection/Header/index.tsx
- src/Artsy/Analytics/Schema/Values.ts
address : [Grow 1450](https://artsyproduct.atlassian.net/browse/GROW-1450)
Going to collect those data.
> Analytics tracking default header Grow-1450

- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/Routes/__tests__/RegisterRouteAnalytics.test.tsx
- 3c32e8f Fix bug where rendering the submission failed modal cleared props
- 7a69c7d Add page title to Auction Registration form
> Some fixes to auction registration form

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/FrameText.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
- Prevent flashing of inverted body text
- Fix text inversion on desktop safari
- Remove roman numerals from video section headers
- Remove black background from inverted text over video
> Vanguard QA

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__tests__/Fixtures/Order.ts
- src/__generated__/OrderApp_order.graphql.ts
- src/__generated__/routes_OrderQuery.graphql.ts
Following artsy/force#4515 we're now invoking the setup logic for Intercom.
Didn't have a chance to test this on eigen because of the MP issues that prevented our QA session today, so give it a go before merging if you have the time. (note you'll need to grab the `INTERCOM_*` env vars from force staging then run force locally with this reaction branch linked. And then you need to configure eigen to use local force (think this can be done from the dev menu, but I do it by editing `ARDefaults.m`)
> Add intercom to order app

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/FrameText.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
- src/Components/Publishing/Nav/Nav.tsx
- src/Components/Publishing/Sections/FullscreenViewer/FullScreenProvider.tsx
[Links to GROW-1508](https://artsyproduct.atlassian.net/browse/GROW-1508)
Fixes this layout issue preventing the close button and nav arrows from being visible:
> Handle Nav Bar and Side Frame Text When Slideshow is Open

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
[Links to GROW-1515] (https://artsyproduct.atlassian.net/browse/GROW-1515)
> Remove padding from article content on mobile

- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Sections/Caption.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Caption.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Image.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Video.test.tsx.snap
[Links to GROW 1517](https://artsyproduct.atlassian.net/browse/GROW-1517)
Before change:
After change:
> align captions on artist image and artist artworks

- README.md
We never did really spread this out... gonna PR a few repos w/ it
> Add Artsy Engineering footer

- src/Apps/Order/Components/BankTransferExperiment.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Artsy/Analytics/Schema/Values.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1456
> PURCHASE-1456 Add BankTransferExperiment

- 2
- src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
Fixes issue with partner phone
> Collect null QA

- src/Artsy/Router/Utils/RenderStatus.tsx
Adding a more generic log to see if we can diagnose google cache error.
> Add error log

- src/Artsy/Router/Utils/RenderStatus.tsx
Reverts artsy/reaction#2835
@joeyAghion reverting this as we can reproduce locally.
> Revert "Add error log"

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Footer.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-1538
Related conversation: https://artsy.slack.com/archives/C8Z0AULEA/p1569250401062600
> [Vanguard] Corrections footer

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/__tests__/ArtistWrapper.test.tsx
Fixes https://sentry.io/organizations/artsynet/issues/1246156313/?project=28316&query=is%3Aunresolved&statsPeriod=14d
Fixes https://sentry.io/organizations/artsynet/issues/1171290563/?project=28316&query=is%3Aunresolved&statsPeriod=14d
The commits tell the story.
> @damassi => Few more Sentry bugs

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- Adds `<LazyLoadComponent>` to the artist page for recently viewed
- Defer artist recs
> @damassi => Couple of more defers on the artist page

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
Fixes https://sentry.io/organizations/artsynet/issues/908095670/?query=is%3Aunresolved
Fixes https://sentry.io/organizations/artsynet/issues/1246354568/?query=is%3Aunresolved
> @eessex => [Artwork] Be defensive about missing partner in additional info section

- src/Artsy/Router/buildClientApp.tsx
Fixes an object path to make safer. #trivial
> [Router] Make user path a bit safer

- src/Utils/time.ts
Updates per https://github.com/artsy/reaction/pull/2885#discussion_r332771334
> Update `time` util to not cache at relay layer

- package.json
- src/Components/Publishing/Sections/Text.tsx
- yarn.lock
Relies on https://github.com/artsy/react-html-parser/pull/1
> [Publising/Text] Update react-html-parser to use DOMParser

- src/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
- src/Apps/Artwork/Components/TrustSignals/__stories__/TrustSignals.story.tsx
Follow up on https://github.com/artsy/reaction/pull/2896 to fix Verified Seller logic.
Also adds stories for the other trust signal components
> Trust signal followup

- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
- src/Apps/__tests__/Fixtures/Artwork/ArtworkImageBrowser.fixture.ts
- src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
- src/__generated__/ArtworkActions_Test_Query.graphql.ts
- src/__generated__/ArtworkImageBrowser_Test_Query.graphql.ts
There's only one spec left that uses the stub provider, that's in progress.
> @damassi => Move more specs to `renderRelayTree`

- src/Artsy/Relay/createRelaySSREnvironment.ts
This fixes https://github.com/artsy/force/pull/4698 so it can be applied again.
> [createRelaySSREnvironment] Lazy load deps so they can be stripped.

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Components/v2/Carousel.tsx
> [Carousel] Type `new Flickity(…)` and document SSR import issue.

- src/Apps/Auction/__fixtures__/routes_BidQuery.ts
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/getRedirect.ts
- src/Apps/Auction/routes.tsx
https://artsyproduct.atlassian.net/browse/AUCT-685
paired with @erikdstock
> Require login for bid confirm route

- src/Artsy/Router/buildServerApp.tsx
This removes the double render in our server-side render pass.
> [Router] Remove double render

- src/Apps/Collect2/Routes/Collection/index.tsx
We'll hold on merging this until we're ready to officially launch the collections hubs rails.
Addresses https://artsyproduct.atlassian.net/browse/GROW-1599
> Enable collection hubs rails for everyone!

- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/routes.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
- src/__generated__/ConfirmBidValidTestQuery.graphql.ts
- src/__generated__/routes_ConfirmBidQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/AUCT-667
> Add analytics calls to ConfirmBid route

- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
Address: [Grow 1563](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1563)
This PR is going to add tracking "Hover" action to our code. It already tracked the "Click" action. So, I set up a condition when `haver && doHoverTracking` is true, then they will do the hover tracking.
> Grow 1563 Add analytics tracking to Nav Bar

- src/Apps/Auction/Components/AuctionFAQ.tsx
#minor Noticed this while QAing the artwork view.
> Conditions of sale --> Conditions of Sale in Auction FAQ

- src/Components/Publishing/ArticleMeta.tsx
- src/Components/Publishing/__tests__/ArticleMeta.test.tsx
- typings/sharify.d.ts
Ports [existing jade template](https://github.com/artsy/force/blob/master/src/desktop/apps/article/templates/meta.jade) to react, part of https://artsyproduct.atlassian.net/browse/PLATFORM-1876
Force side is here: https://github.com/artsy/force/pull/4757
> Article meta component

- package.json
- src/Apps/Artist/Routes/Overview/Components/Genes.tsx
- src/Apps/Artist/Routes/Overview/Components/__tests__/Genes.test.tsx
- src/Components/NavBar/NavItem.tsx
- src/__generated__/GenesTestQuery.graphql.ts
- yarn.lock
Fixes [PURCHASE-1578](https://artsyproduct.atlassian.net/browse/PURCHASE-1578)
[Design](https://app.zeplin.io/project/5ab94282c124db8d58365b47/screen/5d93c61cbd37a5180747902b)
Requires follow up:
Noticed the slide down requires an animation. need to follow up on that in Palette but it would not affect reaction code.
> [PURCHASE-1578]  Adds `<Tags>` component for genes

- README.md
Also will be testing to ensure that the PR process against this
alternative Reaction mainline looks good.
> [aucts price transparency] Warn about this branch in the README.

- src/Apps/Artist/Components/MarketDataSummary/MarketDataSummary.tsx
- src/Apps/Artist/Components/MarketInsights/MarketInsights.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artwork/Components/ArtworkMeta.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Artwork/Components/OtherWorks/index.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/routes.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Order/Components/ItemReview.tsx
- src/Components/ArtworkFilter/Dropdown.tsx
- src/Components/Gene/GeneArtworks.tsx
- src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
- src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
- src/Components/Tag/TagArtworks.tsx
- src/Components/v2/ArtistMarketInsights.tsx
- src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
- src/Components/v2/SelectedCareerAchievements.tsx
Fixes those placeholder fields with a correct `slug` or `internalID`.
> @alloy => [v2] Resolve sludORInternalID ambiguities

- src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
- src/Apps/WorksForYou/WorksForYouFeed.tsx
- src/Components/Artwork/Save.tsx
Closes https://artsyproduct.atlassian.net/browse/PLATFORM-1961
> [MP v2] Migrate WorksForYou app

- src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/__stories__/Collect.story.tsx
- src/Apps/__tests__/Fixtures/Collections.ts
- src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
- src/Components/v2/RecentlyViewed.tsx
- src/__generated__/CollectionRefetch2Query.graphql.ts
- src/__generated__/Collection_viewer.graphql.ts
- src/__generated__/DefaultHeader_headerArtworks.graphql.ts
- src/__generated__/SeoProductsForArtworks_artworks.graphql.ts
Update /collection app to use v2 fields
> [v2] migrate /collection/:id

- src/Apps/Auction/Components/LotInfo.tsx
- src/Apps/Auction/Components/__stories__/LotInfo.story.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidder.ts
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createCreditCardAndUpdatePhone.ts
- src/Apps/Auction/Routes/__stories__/Register.story.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/Routes/__tests__/Register.test.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/__fixtures__/routes_RegisterQuery.ts
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/getRedirect.ts
- src/Apps/Auction/routes.tsx
- src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
- src/__generated__/ConfirmBidValidTestQuery.graphql.ts
- src/__generated__/LotInfo_artwork.graphql.ts
- src/__generated__/LotInfo_saleArtwork.graphql.ts
- src/__generated__/RegisterCreateCreditCardAndUpdatePhoneMutation.graphql.ts
- src/__generated__/RegisterValidTestQuery.graphql.ts
- src/__generated__/routes_ConfirmBidQuery.graphql.ts
- src/__generated__/routes_RegisterQuery.graphql.ts
Migrate Auction app to use Metaphysics V2.
> Migrate Auction app to Metaphysics V2

- src/Apps/Artist/Routes/Articles/__tests__/Articles.test.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/Apps/Artist/Routes/CV/__tests__/CV.test.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artist/Routes/Shows/__tests__/Shows.test.tsx
- src/Apps/Artist/routes.tsx
- src/Apps/__tests__/Fixtures/Artist/Routes/ArticlesFixture.ts
- src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
- src/Apps/__tests__/Fixtures/Artist/Routes/CV.tsx
- src/Apps/__tests__/Fixtures/Artist/Routes/ShowsFixture.ts
- src/DevTools/createMockNetworkLayer/index.ts
Gets the route tests for all the tabs (except Overview) working.
There are still a bunch of Artist components (and Overview components) tests still working on.
> @alloy => Artist app tests for v2

- data/schema.graphql
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
Jira: https://artsyproduct.atlassian.net/browse/AUCT-716
> Allow users to register+bid

- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- src/Apps/Search/Routes/Entity/__tests__/SearchResultsEntity.test.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
Closes https://artsyproduct.atlassian.net/browse/PLATFORM-1960
> [MP v2] Finish Search migration

- src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
- src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Components/MarketInsights/MarketInsights.tsx
- src/Apps/Artist/Components/MarketInsights/__tests__/Fixtures/Artists.fixture.ts
- src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistRecommendations.test.tsx
- src/Apps/Artist/Routes/Overview/Components/__tests__/Genes.test.tsx
- src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/__tests__/Fixtures/Artist/Components/ArtistHeader.tsx
- src/Apps/__tests__/Fixtures/Artist/Components/NavigationTabs.tsx
- src/Apps/__tests__/Fixtures/Artist/Routes/Overview/Genes.tsx
- src/Apps/__tests__/Fixtures/Collections.ts
All tests and type check should be good to go.
> @alloy => [v2] Finish artist app

- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Components/v2/ArtworkFilter/index.tsx
- src/__generated__/CollectionRefetch2Query.graphql.ts
- src/__generated__/Collection_collection.graphql.ts
- src/__generated__/Header_artworks.graphql.ts
- src/__generated__/Header_collection.graphql.ts
Fixes https://www.notion.so/artsy/Featured-artists-links-all-point-to-artist-undefined-fe16be0e02514609b2fe6c61e0b8e80c
> [MP v2] Fix Collection featured artist header

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/BidderPositionQuery.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-713
* `OUTBID`
* `RESERVE_NOT_MET`
* `SALE_CLOSED`
* Javascript error (e.g. disable WiFi and try bidding)
> User should be notified of an outbid or (any non-winning status) when attempting to confirm a bid

- data/schema.graphql
> [schema] Sync with latest removal

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
This PR is an update to changes requested by @abhitip after reviewing the work from #2964.
> Refactors Display Ad Component to Handle Analytics Firing

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.test.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarExtraLinks.ts
Bug fix, follow-up to https://artsyproduct.atlassian.net/browse/AUCT-736 🔒
> Fix for SaleArtwork/Sale without a partner

- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
https://artsyproduct.atlassian.net/browse/GROW-1626
~Note: This is a very simple change, but gonna keep this PR open to try out the review app techniques discussed over in https://artsy.slack.com/archives/CP9P4KR35/p1575576740223500~ done!
> Restore Artworks link to mobile nav

- src/Components/NavBarTest/Menus/MobileNavMenu.tsx
- src/Components/NavBarTest/Menus/MoreNavMenu.tsx
- src/Components/NavBarTest/Menus/NotificationsMenu.tsx
- src/Components/NavBarTest/Menus/UserMenu.tsx
- src/Components/NavBarTest/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBarTest/Menus/__tests__/MoreNavMenu.test.tsx
- src/Components/NavBarTest/Menus/__tests__/NotificationsMenu.test.tsx
- src/Components/NavBarTest/Menus/__tests__/UserMenu.test.tsx
- src/Components/NavBarTest/Menus/index.tsx
- src/Components/NavBarTest/NavBar.tsx
- src/Components/NavBarTest/NavItem.tsx
- src/Components/NavBarTest/NotificationsBadge.tsx
- src/Components/NavBarTest/Utils/__tests__/authentication.test.ts
- src/Components/NavBarTest/Utils/authentication.ts
- src/Components/NavBarTest/__tests__/NavBar.test.tsx
- src/Components/NavBarTest/__tests__/NavBarTracking.test.tsx
- src/Components/NavBarTest/__tests__/NavItem.test.tsx
- src/Components/NavBarTest/__tests__/NotificationsBadge.test.tsx
- src/Components/NavBarTest/index.tsx
- src/__generated__/NotificationsMenuTestQuery.graphql.ts
Addresses: [GROW-1683](https://artsyproduct.atlassian.net/browse/GROW-1683)
This PR clones the original NavBar component and refactors it to meet the design of the experiment version of the navigation a/b test.
@anandaroop and I paired on the last bit of this 🙂
> [GROW-1683] clone the NavBar component for navigation a/b test

- README.md
> Remove @alloy from point people

- src/Apps/Artist/Components/ArtistHeader.tsx
I left out a margin in my last PR
> Margin fix for Artist Header

- src/Components/v2/CCPARequest.tsx
Little one, should have linked in Force first to get this right!
> @mzikherman => [CCPARequest] Proper cta styling for Force integration

- src/Apps/Purchase/PurchaseApp.tsx
- src/Apps/Purchase/routes.tsx
Adding admin check in front of `PurchaseApp`.
> Put admin check in front of purchases page

- src/Components/FollowButton/Button.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/v2/ArtistCard.tsx
Fixes [PURCHASE-1723](https://artsyproduct.atlassian.net/browse/PURCHASE-1723)
Before
After
> Fix spacing issue in follow button on related artists component

- README.md
[Discussed in Slack](https://artsy.slack.com/archives/C2TQ4PT8R/p1579289448007700).
> Removes FOSSA badge. #trivial

- src/Apps/Order/Routes/Respond/index.tsx
Add `data-test` tags to offer response radio btns
> Add `data-test` tags to offer response radio btns

- src/Components/Artwork/GridItem.tsx
- src/Components/ArtworkGrid/ArtworkGrid.tsx
Follow up to https://github.com/artsy/force/pull/4922, to confirm presence of `ArtworkGrid` components
> Add cypress test attrs for artwork grid

- data/schema.graphql
> [Schema] Update schema to latest

- src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
> @eessex => Fix SSR on article pages

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ArtworkApp_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
- Adds tracking for viewing artworks that are part of auctions
https://artsyproduct.atlassian.net/browse/AUCT-870
> [AUCT-870] - Add lot viewed analytics

- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
Doing a thing for reasons. Ask me about it, it's a laugh.
> Collapse auction results filter for reasons

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/__generated__/ArtistAuctionResultsQuery.graphql.ts
- src/__generated__/ArtistAuctionResults_artist.graphql.ts
Fixes [PURCHASE-1749](https://artsyproduct.atlassian.net/browse/PURCHASE-1749)
Desktop:
Mobile:
> [PURCHASE-1749] Add auction result size filter

- src/Components/NavBar/MinimalNavBar.tsx
We're using a new `<MinimalNavBar>` component and it needs an identifier for our acceptance tests.
> Add integrity classname

- src/Components/NavBar/MinimalNavBar.tsx
> Use data-link instead of classname for integration test

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/Artsy/Analytics/Schema/Values.ts
Fixes [PURCHASE-1790](https://artsyproduct.atlassian.net/browse/PURCHASE-1790)
Sample tracking events:
When size filter changes:
```JSON
{
"context_page": "Artist Auction Results",
"context_page_owner_id": "4d8b928b4eb68a1b2c0001f2",
"context_page_owner_slug": "pablo-picasso",
"context_page_owner_type": "Artist",
"action_type": "Auction results filter params changed",
"current": {
"organizations": [],
"sizes": [
"MEDIUM"
],
"openedItemIndex": null,
"page": 1,
"sort": "ESTIMATE_AND_DATE_DESC"
},
"changed": {
"sizes": [
"MEDIUM"
]
}
}
```
When sort changes:
```JSON
{
"context_page": "Artist Auction Results",
"context_page_owner_id": "4d8b928b4eb68a1b2c0001f2",
"context_page_owner_slug": "pablo-picasso",
"context_page_owner_type": "Artist",
"action_type": "Auction results filter params …
```
> [PURCHASE-1790] Add auction result filter instrumentation

- src/Artsy/Analytics/trackingMiddleware.ts
- src/Components/Search/SearchBar.tsx
- typings/sharify.d.ts
This is actually safe to merge! The only Reaction-side change is to update the experiment name.
<details>
<summary>📦 Published PR as canary version: <code>25.14.1-canary.3184.52166.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.14.1-canary.3184.52166.0
yarn add @artsy/reaction@25.14.1-canary.3184.52166.0
```
</details>
> @damassi => [ClientSide Routing] Launch v3 of the AB test

- src/Apps/Conversation/Components/ConversationSnippet.tsx
- src/Apps/Conversation/Routes/Conversation/index.tsx
Follow up on #3173 to fix the link that was missing `/user`
going to self-merge it
> Fix conversation detail link

- src/Apps/Artist/routes.tsx
- src/Apps/Artwork/routes.tsx
- src/Apps/Auction/routes.tsx
- src/Apps/Collect2/collectRoutes.tsx
- src/Apps/Conversation/routes.tsx
- src/Apps/Order/routes.tsx
- src/Apps/Search/routes.tsx
Reverting https://github.com/artsy/reaction/pull/3188
> [BundleSplitting] Reenable

- src/Apps/Search/routes.tsx
Seeing a chunk issue, so going to avoid splitting for the time being.
> [Search] Dont split bundles

- data/schema.graphql
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/MediumFilter.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/__generated__/ArtistAuctionResultsQuery.graphql.ts
- src/__generated__/ArtistAuctionResults_artist.graphql.ts
Fixes [PURCHASE-1765](https://artsyproduct.atlassian.net/browse/PURCHASE-1765)
Screenshot:
> [PURCHASE-1765] Add medium (categories) filter to auction results

- .circleci/config.yml
- package.json
- yarn.lock
This restores #3220 but fixes an issue that we had where it was failing in master.  
See https://github.com/artsy/lint-changed/pull/3 for more details on the actual  fix.
> Only lint changed files

- src/Apps/IdentityVerification/IdentityVerificationApp.tsx
- src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
- src/__generated__/IdentityVerificationAppStartFlowMutation.graphql.ts
Completes [[AUCT-894](https://artsyproduct.atlassian.net/browse/AUCT-894)]
TODO:
> Begin ID Verification flow from collector verification app

- src/Apps/Artist/__tests__/routes.test.tsx
- src/Apps/Artist/routes.tsx
- src/Apps/Artwork/Components/ArtworkBanner/index.tsx
Noticed that the redirect was formatted incorrectly
> [Artist] Fix redirect

- src/Apps/getAppRoutes.tsx
Removing auction stuff from routes
> Remove auction routes

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/routes.tsx
Remove all router code from the bid flow. 
Merging to get this hotfix out.
> Remove BidFlow from router

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Noticed [this error come through sentry](https://sentry.io/organizations/artsynet/issues/1497344547/?project=28316&query=is%3Aunresolved+Node+was+not+found&statsPeriod=24h) and wanted to see if it fixes the problem (this already exists on desktop).
> Debug ErrorBoundry error on mobile

- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Components/__stories__/AddressForm.story.tsx
Realized we need to select the country where Artwork is from for the form to work properly.
> the default should be country of origin if the country select is locked to EU only

- src/Artsy/Router/NetworkOfflineMonitor.tsx
Switches from `debounce` to `throttle` and fixes invocation.  
#trivial
> [Clientside Nav] Fix throttle invocation

- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/Desktop/ModalManager.tsx
- src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
- src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
Updates form titles / submit text - related to https://github.com/artsy/force/pull/5243
https://artsyproduct.atlassian.net/browse/GALL-92
> Forgot form titles

- src/Apps/Artist/Routes/Consign/index.tsx
- src/Utils/user.ts
Noticed that there was some weirdness around isAdmin on staging, so moving the check into the useEffect hook so only evaluated on client.
> Fix admin check on staging

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
Wire up MarketData numbers. 
#trivial
> [Consignments] Ensure dynamic data is passed

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
- src/Apps/Artist/Routes/Consign/index.tsx
Updates artist name with dynamic data. 
#trivial
> [Consignments] Update artist name

- src/Components/NavBar/Menus/MobileLink.tsx
- src/Components/NavBar/Menus/NavigatorContextProvider.tsx
- src/Components/NavBar/Menus/NewMobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/NewMobileNavMenu.test.tsx
- src/Components/NavBar/Menus/index.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
- src/Components/NavBar/menuData.ts
Addresses: [FX-1702](https://artsyproduct.atlassian.net/browse/FX-1702)
This adds the new mobile nav menu that introduces nested sub menus.
> [FX-1702] new mobile nav menu

- src/Apps/IdentityVerification/IdentityVerificationApp.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-930
> User can navigate to IDV FAQ from the IDV landing page

- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/ReadMore/__tests__/ReadMore.test.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Typings.ts
Adds a third ad placement in Standard Articles.
https://artsyproduct.atlassian.net/browse/FX-1839
https://artsyproduct.atlassian.net/browse/FX-1837
> Adds a 3rd Display Ad to Standard Articles

- data/schema.graphql
This PR gets reaction back in sync with MP's schema.
> Update MP schema

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
- src/Apps/Artist/Routes/Consign/Components/Subheader.tsx
- src/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.test.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Apps/Artist/Routes/Consign/index.tsx
- src/Apps/Artist/routes.tsx
- src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
- src/DevTools/MockBoot.tsx
- src/Utils/getENV.tsx
- src/__generated__/ConsignRoute_Test_Query.graphql.ts
- src/__generated__/Consign_artist.graphql.ts
- src/__generated__/Consign_artworksByInternalID.graphql.ts
- src/__generated__/routes_ArtistConsignQuery.graphql.ts
- typings/sharify.d.ts
Does a couple things: 
- Adds some meta tags to the new `artist/consign` page
- Updates titles and subtitles to `h1` / `h2` for SEO
> [Consignments] Add Artist/Consign SEO/meta tags

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Followup to my [auctions results tweaks PR](https://github.com/artsy/reaction/pull/3284). This commit didn't get pushed by accident, its a fix that Justin suggested in the comments for the other PR.
> Missing Image Fix

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
- src/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Apps/Artist/Routes/Consign/index.tsx
- src/Apps/Artist/routes.tsx
- src/Components/Artwork/FillwidthItem.tsx
Addresses feedback in https://artsyproduct.atlassian.net/browse/CSGN-93
A couple post-launch follow-up items as noted in JIRA comments:
- Ensure all Recently Sold artworks are public in CMS
- Move Recently Sold items into a proper carousel
> [Consignments] Artist/Consign QA

- src/Apps/IdentityVerification/IdentityVerificationApp/CompleteFailed.tsx
<details>
<summary>📦 Published PR as canary version: <code>25.36.1-canary.3310.55325.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.36.1-canary.3310.55325.0
yarn add @artsy/reaction@25.36.1-canary.3310.55325.0
```
</details>
> Copy: Remove stray whitespace in verification failed view

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Apps/Artist/routes.tsx
- src/__generated__/routes_ArtistConsignQuery.graphql.ts
Addresses remaining items here: https://artsyproduct.atlassian.net/browse/CSGN-93
> [Consignments] QA round 2

- src/Components/NavBar/Menus/NewMobileNavMenu.tsx
- src/Components/NavBar/menuData.ts
Addresses: [FX-1857](https://artsyproduct.atlassian.net/browse/FX-1857) & [FX-1858](https://artsyproduct.atlassian.net/browse/FX-1858)
This PR addresses the remaining UI QA items and fixes the copy, links, and ordering issues.
> Mobile nav menu ui qa

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Apps/Artist/Routes/Consign/index.tsx
- src/Artsy/Analytics/Schema/Values.ts
Addresses https://artsyproduct.atlassian.net/browse/CSGN-78
Adds tracking to events on new Artist/Consign page.
> [Consignments] Add tracking to Artist/Consign

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Apps/Artist/routes.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/routes_ArtistConsignQuery.graphql.ts
Unguards admin access, and updates the FAQ for launch. 
Will follow up with second deploy after https://github.com/artsy/reaction/pull/3322 is merged.
> [Consignments] Launch Consign Page / Update FAQ

- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/Routes/__tests__/Register.test.tsx
- src/Apps/Auction/__fixtures__/routes_RegisterQuery.ts
- src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
- src/__generated__/RegisterValidTestQuery.graphql.ts
- src/__generated__/Register_me.graphql.ts
- src/__generated__/Register_sale.graphql.ts
- src/__generated__/routes_RegisterQuery.graphql.ts
completes https://artsyproduct.atlassian.net/browse/AUCT-949
<details>
<summary>📦 Published PR as canary version: <code>25.41.2-canary.3334.56177.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.41.2-canary.3334.56177.0
yarn add @artsy/reaction@25.41.2-canary.3334.56177.0
```
</details>
> Display information about identity verification on credit card form

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artist/__tests__/routes.test.tsx
- src/Apps/Artist/routes.tsx
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Temporarily reverts artsy/reaction#3307 until we can fix a redirect loop that's causing the artist page to fail to load on staging.
> Revert "Redirect logged in users to the works for sale tab"

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artist/__tests__/routes.test.tsx
- src/Apps/Artist/routes.tsx
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
This fixes the redirect loop we encountered on the artist page. 
Most of the changes here are the actual revert of the former revert. The fix can be found here: https://github.com/artsy/reaction/commit/478389537863c91aa77d500469207ab97be57a6a#diff-53ea779b20e5bd37af12c435a46415edR135
<details>
<summary>📦 Published PR as canary version: <code>25.42.3-canary.3338.56288.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.42.3-canary.3338.56288.0
yarn add @artsy/reaction@25.42.3-canary.3338.56288.0
```
</details>
> Fix redirect loop when user logged in on artist page

- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
For integrity tests, add `stat-test` attr to SignUpForm
> #trivial data-test attrs for SignUpForm

- src/Apps/FeatureAKG/Components/Feature.tsx
- src/Apps/FeatureAKG/Components/FeaturedArticles.tsx
- src/Apps/FeatureAKG/Components/FeaturedArtists.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
- src/Apps/FeatureAKG/FeatureApp.tsx
- src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
- src/Apps/FeatureAKG/routes.tsx
- src/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
- src/__generated__/FeatureApp_viewer.graphql.ts
- src/__generated__/Feature_viewer.graphql.ts
- src/__generated__/FeaturedArticles_articles.graphql.ts
- src/__generated__/FeaturedRails_viewer.graphql.ts
- src/__generated__/routes_FeatureQuery.graphql.ts
This PR updates the art keeps going layout based on some visual QA by Nicole and Megan.
I've left some comments/questions inline!
> Visual fixes based on QA

- src/Apps/FeatureAKG/Components/Feature.tsx
- src/Apps/FeatureAKG/Components/FeaturedArticles.tsx
- src/Apps/FeatureAKG/Components/FeaturedArtists.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedCollections.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedFairs.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
- src/Apps/FeatureAKG/Components/FeaturedThisWeek.tsx
- src/Apps/FeatureAKG/Components/SelectedWorks.tsx
- src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
- src/__generated__/FeaturedArticles_articles.graphql.ts
- src/__generated__/routes_FeatureQuery.graphql.ts
Bunch of little changes! I also removed `lazyLoad` from the `ResponsiveImage` components as it doesn't appear to work as-expected yet.
> Adds tracking for Art Keeps Going + some other visual improvements

- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Components/Search/SearchBar.tsx
This was meant to be completed as part of [PURCHASE-1787]
[PURCHASE-1787]: https://artsyproduct.atlassian.net/browse/PURCHASE-1787
> Search bar artist results link to works-for-sale page

- src/Components/FollowButton/Button.tsx
- src/Components/FollowButton/ButtonDeprecated.tsx
- src/Components/FollowButton/__tests__/__snapshots__/Button.test.tsx.snap
- src/Components/Publishing/ToolTip/ArtistToolTip.tsx
- src/Components/Publishing/ToolTip/GeneToolTip.tsx
- src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
- src/Components/Publishing/ToolTip/ToolTip.tsx
> #trivial - add data-test attrs

- src/Apps/Collect/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
Updated snapshots from a linked Reaction.
> Fix snapshots

- src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
- src/Components/Artwork/GridItem.tsx
- src/Components/Artwork/Save.tsx
- src/Components/ArtworkGrid/ArtworkGrid.tsx
Minor updates for new auth tests on /collect & /collection/:id routes
> #trivial Add integrity data attrs

- src/Components/UserSettingsTwoFactorAuthentication/__stories__/UserSettingsTwoFactorAuthentication.story.tsx
- src/Components/UserSettingsTwoFactorAuthentication/index.tsx
- src/__generated__/UserSettingsTwoFactorAuthenticationQuery.graphql.ts
- src/__generated__/UserSettingsTwoFactorAuthenticationStoryQuery.graphql.ts
- src/__generated__/UserSettingsTwoFactorAuthentication_me.graphql.ts
Add initial version of User -> Settings -> Two-Factor Authentication component.
> Add 2FA user settings component

- src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
Add `data-test` attr `featuredArtistsRail` for integrity.
> #trivial Add test attr for integrity

- src/Artsy/Router/RenderStatus.tsx
Its a bit too fast and frantic right now, slowing it down a bit...
> [Clientside Nav] Slow down top bar a bit

- src/Apps/Auction/Routes/Register/index.tsx
- src/Components/Auction/AuctionRegistrationModal.tsx
- src/Components/Auction/PostRegistrationModal.tsx
- src/Components/Auction/__stories__/AuctionRegistrationModal.story.tsx
- src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
- src/Components/Auction/__tests__/PostRegistrationModal.test.tsx
- src/Utils/identityVerificationRequirements.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-952
This PR is coupled to https://github.com/artsy/force/pull/5392. Please see the other PR for more details.
> [AUCT-952] Bidder sees copy in "about to register" and "registration pending" modals with information about identity verification

- src/Components/Publishing/Nav/NewsNav.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
Related to: https://github.com/artsy/force/pull/5432
> Reverts Hotfix; Brings back dynamic nav bar on /news pages

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
More test attributes for targeting auth entrypoints on artist page.
> #trivial - Artist page data-test attrs

- src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
Re: [FX-1850](https://artsyproduct.atlassian.net/browse/FX-1850)
Simple thing, just ticking a box off my onboarding list here.
> Fixes collapsing container

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
This updates our UI code to remove client-side tracking completely, since we're now tracking things via a server-side event in force.
> [Consignments] Remove client-side tracking

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
> Revert "[Consignments] Remove client-side tracking"

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
- src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/index.tsx
- src/Components/ArtistCard.tsx
- src/Components/Artwork/Save.tsx
- src/Components/FollowIcon.tsx
Updates artwork page with data attrs for integrity.
> #trivial - Add test attrs for artwork page auth entrypoints

- src/Apps/Collect/Routes/Collection/Components/Header/DefaultHeader.tsx
- src/Apps/Collect/Routes/Collection/Components/Header/DefaultHeaderArtwork.tsx
- src/Apps/Collect/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
- src/Apps/Collect/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
- src/Apps/__stories__/Collect.story.tsx
Fixes bug wherein images may be null.
> Fixes for nullable artwork images

- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
To properly update boolean field values, you need to set the initial value to a boolean.
Follow-up to https://github.com/artsy/reaction/pull/3480
> Fix Formik boolean handling

- src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
- src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
Fixes build. (I should have rebased before merging!)
> Fixes paths to flushPromiseQueue

- .circleci/config.yml
- package.json
Would also be nice to get back PR-specific deploys — are we doing that anywhere else?
> Deploys Storybook to S3

- src/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/Apps/ViewingRoom/routes.tsx
- src/Apps/__stories__/AppShell.story.tsx
- src/Apps/__stories__/ViewingRoom.story.tsx
- src/Apps/getAppRoutes.tsx
- src/__generated__/routes_ViewingRoomQuery.graphql.ts
Force PR: https://github.com/artsy/force/pull/5524
This builds out the static desktop layout for viewing rooms and stubs stuff for the next few phases.
Next:
- Make responsive
- Break components out into actual structure / cleanup
- Wire up to Relay
- Write tests
> [ViewingRoom] Stub out viewing room

- src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
- src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomIntro.tsx
- src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomStatements.tsx
- src/Apps/ViewingRoom/Routes/Statement/index.tsx
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
- src/Apps/ViewingRoom/Routes/Works/index.tsx
This PR adds responsivity to the new Viewing Rooom app:
> [ViewingRoom] Make responsive

- .circleci/config.yml
@damassi pointed out that tests were failing on forks. This bump should resolve that issue.
> Bump yarn orb to ensure forks still aren't failing

- src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomPullQuote.tsx
- src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
- src/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
- src/__generated__/ViewingRoomPullQuote_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomStatementRoute_viewingRoom.graphql.ts
- src/__generated__/routes_ViewingRoomStatementRouteQuery.graphql.ts
So I think this blob of text is a pullQuote on the VR level. Reshuffled things here and created a component for that.
As for the images - none of the works from this artist have more than one image. But I'll try to think of something on staging...
> adding pullQuote to VR

- src/Apps/Feature/Components/FeatureFeaturedLink.tsx
- src/Apps/Feature/Components/FeatureHeader.tsx
- src/Apps/Feature/Components/FeatureSet.tsx
- src/Apps/Feature/Components/__stories__/FeatureFeaturedLink.story.tsx
- src/Apps/Feature/Components/__stories__/FeatureHeader.story.tsx
- src/Apps/Feature/Components/__tests__/fixtures.ts
- src/Apps/Feature/FeatureApp.tsx
- src/Apps/__stories__/FeatureApp.story.tsx
- src/__generated__/FeatureApp_feature.graphql.ts
- src/__generated__/FeatureHeader_feature.graphql.ts
- src/__generated__/routes_FeatureQuery.graphql.ts
Nothing too wild here. Let me know if I'm missing some useful Palette components or patterns.
I need to just move on to the real data because most of what has to happen now is: improve image handling (which I want real images to build with) and build out how the different union type options display in the sets.
[desktop screen recording](http://static.damonzucconi.com/_capture/zXNgyW9ETyum.gif)
[mobile screen recording](http://static.damonzucconi.com/_capture/H01gHd0O8VKz.gif)
> Roughs in Feature app UI

- src/Apps/Feature/FeatureApp.tsx
Didn't realize this would actually cause the production build to fail but pass in the pull request.
*The more you know*
> Removes placeholders to fix build

- src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/Apps/ViewingRoom/Components/ViewingRoomMeta.tsx
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
- src/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/Components/Carousel.tsx
- src/__generated__/ViewingRoomApp_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
- src/__generated__/routes_ViewingRoomQuery.graphql.ts
Just some light QA cleanup on the viewing room!
> [Viewing Room] QA

- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
- src/Components/Carousel.tsx
Again try to fix the carousel initialization issue
> Fix carousel init

- .eslintrc.js
- src/Apps/ViewingRoom/Components/__tests__/ViewingRoomHeader.test.tsx
- src/Apps/ViewingRoom/Components/__tests__/ViewingRoomTabBar.test.tsx
- src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
- src/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.test.tsx
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
- src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.test.tsx
- src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomAppFixture.ts
- src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomStatementRouteFixture.ts
- src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
- src/Apps/ViewingRoom/__tests__/ViewingRoomApp.test.tsx
- src/Artsy/Router/RouterLink.tsx
- src/__generated__/ViewingRoomApp_Test_Query.graphql.ts
- src/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
- src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
This adds some tests to the Viewing Room app. 
(Assigning again to you @dzucconi just so you can see some of our testing patterns.)
> [Viewing Room] Add tests

- src/index.ts
Accidentally deleted in https://github.com/artsy/reaction/commit/7cdc1678c72e5f715a0bed3c5edbb8e446ab0461 .
> Restore accidentally deleted index.ts entrypoint file

- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
- src/__generated__/AppSecondFactorStorySuccessQuery.graphql.ts
- src/__generated__/AppSecondFactor_me.graphql.ts
- src/__generated__/SmsSecondFactorStoryErrorQuery.graphql.ts
- src/__generated__/SmsSecondFactorStorySuccessQuery.graphql.ts
- src/__generated__/SmsSecondFactorStoryUndeliverableQuery.graphql.ts
- src/__generated__/SmsSecondFactorStoryUpdateErrorQuery.graphql.ts
- src/__generated__/SmsSecondFactor_me.graphql.ts
- src/__generated__/TwoFactorAuthenticationQuery.graphql.ts
- src/__generated__/TwoFactorAuthenticationRefetchQuery.graphql.ts
- src/__generated__/TwoFactorAuthenticationTestQuery.graphql.ts
If a user is enrolling in 2FA for the first time, the access token used will become invalid once enabled. In that case we'll prepare the user to log back in.
<details>
<summary>📦 Published PR as canary version: <code>26.36.15-canary.3529.60747.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.36.15-canary.3529.60747.0
yarn add @artsy/reaction@26.36.15-canary.3529.60747.0
```
</details>
> Show complete modal conditionally showing reauth prompt

- src/Apps/Conversation/Components/Conversation.tsx
- src/__generated__/Conversation_conversation.graphql.ts
- src/__generated__/routes_DetailQuery.graphql.ts
[PURCHASE-1906]
https://www.notion.so/artsy/Artwork-appears-stretched-in-conversation-thread-a4e4a658230b4a38ba26a37a419b1a6e
__Before:__
__After:__
[PURCHASE-1906]: https://artsyproduct.atlassian.net/browse/PURCHASE-1906
> Artwork appears stretched in conversation thread

- src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/Apps/ViewingRoom/Components/ViewingRoomMeta.tsx
- src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomAppFixture.ts
- src/Apps/ViewingRoom/__tests__/ViewingRoomApp.test.tsx
- src/__generated__/ViewingRoomApp_Test_Query.graphql.ts
- src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
- src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
- src/__generated__/routes_ViewingRoomQuery.graphql.ts
Let's see if I messed up any of the specs.
> replace endAt with formatted value for endAt

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
- src/Apps/Artwork/Components/ArtworkDetails/index.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
- src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
For testing artwork page authentication flows via Integrity
> #trivial - data-test attrs for Artwork auth

- src/Apps/Feature/Components/FeatureSet.tsx
- src/Apps/Feature/__tests__/FeatureApp.test.tsx
- src/Apps/Feature/__tests__/fixtures.ts
- src/Artsy/Analytics/trackingMiddleware.ts
- src/Artsy/Router/buildClientApp.tsx
- src/Components/Masonry.tsx
- src/Components/__stories__/Masonry.story.tsx
- src/__generated__/FeatureApp_Test_Query.graphql.ts
- src/__generated__/FeatureSet_set.graphql.ts
Re: [COM-17](https://artsyproduct.atlassian.net/browse/COM-17)
> [COM-17] Supports artworks on feature pages

- package.json
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
- src/Apps/__stories__/ViewingRoom.story.tsx
- src/Components/Carousel.tsx
- yarn.lock
Addresses weird carousel bug we see occasionally around images lacking static widths: https://github.com/metafizzy/flickity/issues/691. Added as devDep here since we use it as a dep in force.
> Fix carousel

- data/schema.graphql
- src/Apps/Feature/Components/FeatureFeaturedLink.tsx
- src/Apps/Feature/Components/FeatureHeader.tsx
- src/Apps/Feature/Components/FeatureSet.tsx
- src/Apps/Feature/Components/__stories__/FeatureFeaturedLink.story.tsx
- src/Apps/Feature/Components/__tests__/fixtures.ts
- src/Apps/Feature/FeatureApp.tsx
- src/Apps/Feature/__tests__/fixtures.ts
- src/__generated__/FeatureApp_Test_Query.graphql.ts
- src/__generated__/FeatureApp_feature.graphql.ts
- src/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts
- src/__generated__/FeatureHeader_feature.graphql.ts
- src/__generated__/routes_FeatureQuery.graphql.ts
* Targets correct area for anchor tag
* Adds hover state for featured links
* Supports different image art directions for featured links
> Minor Feature page Q/A

- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
- src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
- src/Apps/__stories__/ViewingRoom.story.tsx
- src/__generated__/ViewingRoomCarousel_artwork.graphql.ts
- src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
- src/__generated__/routes_ViewingRoomWorksRouteQuery.graphql.ts
Ensuring that there are static image widths for the carousel. #trivial
> [Viewing Room] Ensure fixed widths present

- data/schema.graphql
- src/Apps/Feature/Components/FeatureFeaturedLink.tsx
- src/Apps/Feature/Components/FeatureHeader.tsx
- src/Apps/Feature/Components/FeatureSet.tsx
- src/Apps/Feature/Components/__tests__/fixtures.ts
- src/Apps/Feature/__tests__/fixtures.ts
- src/__generated__/FeatureApp_Test_Query.graphql.ts
- src/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts
- src/__generated__/FeatureHeader_feature.graphql.ts
- src/__generated__/FeatureSet_set.graphql.ts
- src/__generated__/routes_FeatureQuery.graphql.ts
Ok, last little items —
* Renders remaining Markdown fields
* Feature cover image optimizations
> Remaining Feature page Q/A items

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx
Damon extracted our Masonry component into its own file; this just updates the ref.  #trivial
> [Consignments] Swap masonry component

- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
- src/Components/Tag/TagArtworks.tsx
Qa related to https://github.com/artsy/force/pull/5549
<details>
<summary>📦 Published PR as canary version: <code>26.40.12-canary.3553.61300.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.40.12-canary.3553.61300.0
yarn add @artsy/reaction@26.40.12-canary.3553.61300.0
```
</details>
> Fix contextModule on /Tag page, Forgot link includes existing query params

- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/index.tsx
Collapse UI for XS viewports.
jira :lock: : https://artsyproduct.atlassian.net/browse/TRUST-183
> Add responsive styles to 2FA Enrollment UI

- src/Apps/Conversation/Components/ConversationSnippet.tsx
[PURCHASE-1903]
https://www.notion.so/artsy/Message-previews-format-broken-48f340a6056147b5965ad61484b4e161
[PURCHASE-1903]: https://artsyproduct.atlassian.net/browse/PURCHASE-1903
> [Thread Preview] style tweaks

- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/__tests__/Desktop/ForgotPasswordForm.test.tsx
Fixes bug where signup link on forgot password form does not link to signup form.
> Forgot password form can switch to signup form

- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/BackupSecondFactorModalContent.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
Follow-up to https://github.com/artsy/palette/pull/688
Import from the top-level package now that `BorderBoxProps` is exposed there.
> Update BorderBoxProps import

- src/Apps/Feature/Components/FeatureSet.tsx
- src/Apps/__stories__/FeatureApp.story.tsx
Just fixes the very minor spacing issues on the older pages that might show up in search results or what have you.
> Minor fixes for legacy feature pages

- src/Apps/Feature/Components/FeatureFeaturedLink.tsx
- src/Apps/Feature/Components/FeatureHeader.tsx
- src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
Per Nicole all those places should have tight titles.
> add unstable_trackIn to titles in VR, feature and featured Link

- package.json
- src/Apps/Conversation/Components/Reply.tsx
- src/Apps/Conversation/Mutation/SendConversationMessage.ts
[PURCHASE-1904]
https://www.notion.so/artsy/Conversation-not-updated-correctly-when-new-messages-is-entered-by-collector-61d0224fe67e4d44bf8c13fe52565a4b
This PR is the result of our mob pairing session on Tuesday. In addition to the message order bug, we fixed an issue where the text area input wasn't clearing properly.
[PURCHASE-1904]: https://artsyproduct.atlassian.net/browse/PURCHASE-1904
> Conversation not updated correctly when new messages is entered by collector

- src/Components/FlashBanner.tsx
Finishes [[AUCT-1037]](https://artsyproduct.atlassian.net/browse/AUCT-1037)
#minor
[AUCT-1037]: https://artsyproduct.atlassian.net/browse/AUCT-1037
> Email confirmation message copy updates

- README.md
So people know we still need this as a dependency!
> Clarify deprecation notice

- .circleci/config.yml
Moves to a real version, dev orbs expire after 90 days: https://circleci.com/gh/artsy/reaction/62659
> Bump yarn orb

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
- src/Components/Publishing/Sections/Artwork.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
> Avoids passing width/height to captions

- src/Components/Publishing/Banner/Banner.tsx
Very minor PR to update some copy to match newer brand guidelines.
https://artsyproduct.atlassian.net/browse/GRO-2
> GRO-2: Update copy

- src/Components/Publishing/RelatedArticles/Panel/RelatedArticlesPanelLink.tsx
- src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
Just a little PR to add alt text for the related stories images.
https://artsyproduct.atlassian.net/browse/GRO-16
/cc @artsy/grow-devs
> Add missing alt text

- package.json
- src/Components/__tests__/__snapshots__/Input.test.tsx.snap
- yarn.lock
Fixes snapshot errors due to palette color changes.
> Update palette to v13.24.2

- src/Components/Publishing/Sections/Video.tsx
This PR applies changes required for adopting inclusive language, more info here: https://github.com/artsy/README/issues/427
> chore: Adopt inclusive language

- .vscode/tasks.json
- renovate.json
Realized some of my Dependabot PRs were the ones sitting here with failing tests, so wanted to try and resolve this. I believe this should resolve it.
@damassi  - Any issues if I put up a PR to remove the lint-check as part of ci? I don't think enforcing prettier on this repo is providing a lot of value and just making it harder to keep up-to-date, but let me know if you disagree.
> fix: formating

- .circleci/config.yml
- renovate.json
https://artsyproduct.atlassian.net/browse/PLATFORM-4066
Updates renovate assignee to @ovasdi
> chore: update renovate assignee

- yarn.lock
Follow up to #3724, which missed some transitive dependencies.
> chore: bump minimist
