artsy/reaction

- .gitignore
- .storybook/config.js
- .storybook/iframe.html
- .storybook/index.html
- fuse.js
- package.json
- src/__stories__/config.js
- yarn.lock
This replaces the [webpack bundler](http://webpack.github.io) that [Storybook normally uses](https://github.com/storybooks/react-storybook/tree/master/src/server) by [FuseBox](http://fuse-box.org).
For our “TypeScript -> Babel with Relay transforms” pipeline It is _insanely_ much faster. Changes are reflected in the running UI near instantaneously.
I simply vendored some of the files that the regular webpack setup would generate (HTML), omitted things that seemed irrelevant to us (CSS modules, `<head>` customization). There may be issues left in this first pass, but it works well enough in my limited testing and is _so_ much faster to develop with, that I think we should start using it sooner rather than later.
> [fuse-box] A simple port of storybook’s webpack support.

- src/components/login_header.tsx
The storybook for the `LoginHeader` component is broken due to a path issue.
> Fix the storybook for the LoginHeader component

- src/components/artwork/details.tsx
This removes the warning below:
> TextLink in ArtworkDetails should have a key

- src/components/artwork/details.tsx
Following up on @alloy's comment: https://github.com/artsy/reaction-force/pull/36#discussion_r103796738
> explicitly declare __id to makre sure it is always available

- data/schema.graphql
- data/schema.json
- src/apps/loyalty/containers/inquiries/browser.tsx
- src/apps/loyalty/containers/inquiries/index.tsx
- src/apps/loyalty/containers/inquiries/update_collector_profile.ts
- src/apps/loyalty/server/index.tsx
- src/relay/config.ts
Thanks for the pairing @alloy and @l2succes 
This hooks up the mutation that lets you mark yourself as a loyalty applicant, as well as saving the textbox of self-reported purchases.
> @alloy => Working collector profile mutation!

- .env.oss
- src/apps/loyalty/containers/inquiries/index.tsx
- src/apps/loyalty/server/gravity.ts
- src/apps/loyalty/server/index.tsx
- Use `API_URL` instead of `ARTSY_URL`
- Don't render artwork inquiries that weren't conversations. A test for this can be added once https://github.com/artsy/reaction-force/pull/92 is merged.
> @l2succes => Some minor adjustments

- src/apps/loyalty/__mocks__/isomorphic-relay.ts
- src/apps/loyalty/__tests__/server.tsx
- src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
- src/apps/loyalty/containers/inquiries/__tests__/index.tsx
- src/apps/loyalty/server/index.tsx
- src/apps/loyalty/server/route_handlers.tsx
Building on yesterday's snapshot tests, this moves the last route handler for inquiries out of the server index file, adds a snapshot test, and a couple more small tests (+ one about not rendering inquiries that lack an impulse conversation).
> @l2succes => Move inquiries route handling to separate file + a few more tests

- src/apps/loyalty/containers/3w_thank_you/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/acb_thank_you/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
- src/apps/loyalty/containers/login/index.tsx
- src/components/buttons/default.tsx
- src/components/buttons/facebook.tsx
- src/components/buttons/twitter.tsx
closes: https://github.com/artsy/reaction-force/issues/103
By default, the `flex-direction` property is set to `row` which aligns the flex-items along the main (x) axis. It looks like that is what's causing the "LOG IN" text to sit to the left. I think we want to style it to have`flex-direction: column` in this case.
> [Loyalty QA] center log in button text in safari

- src/apps/loyalty/containers/3w_thank_you/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/acb_thank_you/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
- src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
- src/components/__tests__/__snapshots__/artwork.test.tsx.snap
- src/components/text_link.tsx
This addresses the font size for the email link on the thank you page: https://github.com/artsy/collector-experience/issues/228
This change doesn't affect any links in the Artwork grid.
> TextLink shouldn't have any specific font sizes

- src/apps/loyalty/__tests__/server.tsx
- src/apps/loyalty/containers/inquiries/index.tsx
- src/apps/loyalty/containers/repeat_visitor/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/repeat_visitor/__tests__/index.ts
- src/apps/loyalty/containers/repeat_visitor/index.tsx
- src/apps/loyalty/server/helpers.tsx
- src/apps/loyalty/server/route_handlers.tsx
Adds the repeat visitor page.
Since I think we'd just want this at `/thank-you`, but we do full server-side reloads/redirects, there's no way of knowing if someone visits `/thank-you` b/c they just submitted their application, or it's a repeat visit.
So we just use a query param to indicate they just submitted the form. Since `/thank-you` will redirect you back to `/inquiries` if you aren't actually a registered applicant, I think it's fine to rely on the query param. What do you think?
> @l2succes => Repeat Visitor page

- index.js
- package.json
- src/apps/loyalty/containers/inquiries/index.tsx
- src/apps/loyalty/server/route_handlers.tsx
- src/apps/loyalty/server/template.tsx
- typings.d.ts
- yarn.lock
~~Just a little thing to start...this basically loads the segment JS and passes in our key thru sharify.~~
~~This does work in the browser JS console...now to try to actually use it in the react code.~~
This adds the segment JS into the inquiries template, and also directly tracks the successful loyalty submission with the required props.
I did a tiny refactor to the state to just store an array of the selected conversations.
> @l2succes => Loyalty Applicant submission tracking

- circle.yml
- package.json
The `npm prepublishOnly` hook is not being run on circle CI because the version of npm is outdated so it has to be triggered manually
https://github.com/travis-ci/travis-ci/issues/6953
> Fixes CircleCI auto publish

- src/relay/config.ts
Re-adds the metaphysics ref from sharify vs hard-coded value.
> @l2succes => Use metaphysics url from ENV rather than hard-coded value

- package.json
- src/apps/loyalty/__tests__/server.tsx
- src/apps/loyalty/containers/inquiries/browser.tsx
- src/apps/loyalty/containers/login/browser.tsx
- src/apps/loyalty/server/gravity.ts
- src/apps/loyalty/server/helpers.tsx
- src/apps/loyalty/server/middlewares/relay.ts
- src/apps/loyalty/server/middlewares/user.ts
- src/apps/loyalty/server/route_handlers.tsx
- src/apps/loyalty/types.ts
- src/components/__stories__/artwork_filter.tsx
- src/components/__stories__/artwork_grid.tsx
- src/components/__stories__/save.tsx
- src/components/__tests__/artsy.test.tsx
- src/components/artsy.tsx
- src/relay/config.ts
- src/typings/global.d.ts
- src/typings/gravity.d.ts
- src/typings/sharify.d.ts
- yarn.lock
As discussed on the Slackers, we’re going to only be accessing the user on the server-side in 1 way. I chose the `CURRENT_USER` in the sharify data, because we need to access that on the client-side anyways.
I also did some shuffling around of Gravity model typings.
> Standardise user access

- src/apps/loyalty/containers/inquiries/index.tsx
This makes it easier to debug if there's an issue. We had a couple today: staging data out of sync (inquiry to conversation), plus missing ENV vars in production.
They were tough to diagnose without having to repro locally, put a `debugger` or breakpoint or something in the error handler (which just pops up a generic warning), and seeing what the specific issue was.
I think this is fine even in production?
> @alloy => Console warn if a mutation fails

- package.json
- src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
- src/components/__tests__/__snapshots__/artwork.test.tsx.snap
- src/components/artwork/details.tsx
- src/components/artwork_grid.tsx
- src/components/text_link.tsx
Closes #160 
Pro tip: `min-width: 0` is the magic property on a flex container to have `text-overflow` work properly....the more you know.
> @alloy - Truncate artwork title with ellipsis 

- circle.yml
It seems like a `.env` file (used to inject `METAPHYSICS_ENDPOINT` in `.storybook/webpack.config.js`) is missing in CircleCI and we need to copy `.env.oss` to `.env`.
> Copy .env file for webpack config for storybook

- src/components/__stories__/fair_booth.tsx
- src/components/artwork_grid.tsx
- src/components/fair/booth.tsx
- src/components/fair/feed.tsx
- src/relay/queries/fair.ts
Getting some code up here, running into two errors: 1. The dreaded `Maximum call stack size exceeded` again, randomly. 2. `RelayQueryPath.getQuery(): Cannot generate accurate query for path with connection` when trying to load more artworks in an individual booth component.
> Add show feed component for fair filter

- danger/pr.js
- tsconfig.json
This is going to be working off our [staging peril](https://dashboard.heroku.com/apps/artsy-peril) instance, instead of running on CI. So it might take a bit of setup.
You can see the peril settings here: https://github.com/artsy/artsy-danger/blob/master/peril.settings.json
If you want to understand how all this works, see:  https://github.com/danger/peril/blob/master/docs/setup_for_org.md
> [Dev] Adds Danger

- package.json
- src/apps/loyalty/server/index.tsx
- yarn.lock
This is the result of https://github.com/artsy/artsy-passport/pull/112 https://github.com/artsy/artsy-passport/pull/113 and https://github.com/artsy/artsy-passport/pull/114
It removes the only CoffeeScript dependency in reaction-force, and thus kills the need for the language inside the app.
Interestingly in doing so, TypeScript raised a compiler error because the typings could then be inferred . However, as `options` is added [dynamically](https://github.com/artsy/artsy-passport/blob/master/lib/index.coffee#L18) then it isn't seen. So I any'd it. If people care enough I can add types to the lib _ooooorrrrr_ someone else can, and I'll pair with them.
> Update to Artsy passport 2.x - Removes CoffeeScript

- src/components/artwork_filter/dropdown.tsx
This fixes a style issue in Force.
> Fix the position of arrow in DropDown

- docs/getting_started.md
https://github.com/artsy/reaction/pull/200#discussion_r127812738
The actual value of `this.state` at runtime is `null`, so that’s more accurate.
> [doc] Use `null` for state instead of `void`.

- src/components/publishing/__stories__/publishing.tsx
- src/components/publishing/__test__/__snapshots__/artwork.test.tsx.snap
- src/components/publishing/__test__/__snapshots__/image.test.tsx.snap
- src/components/publishing/__test__/__snapshots__/image_collection.test.tsx.snap
- src/components/publishing/__test__/fixtures.tsx
- src/components/publishing/artwork.tsx
- src/components/publishing/artwork_caption.tsx
- src/components/publishing/image.tsx
- src/components/publishing/image_caption.tsx
- src/components/publishing/view_fullscreen.tsx
- src/utils/index.ts
Refactors the Artwork and Image components to be more Typescript-friendly and adds in support for the "classic" views.
> @eessex => [Publishing] Refactor Artwork and Image components and support "classic"

- src/components/publishing/__stories__/publishing.tsx
- src/components/publishing/__test__/__snapshots__/imageset_preview.test.tsx.snap
- src/components/publishing/__test__/fixtures.tsx
- src/components/publishing/imageset_preview.tsx
- Uses mini layout by default, and does not require layout prop to be passed in
- Does not require title prop, use alternate layout when title not included
> @kanaabe => Imageset updates

- .storybook/webpack.config.js
- package.json
The deploy is still failing because we're copying the env.oss file to .env which contains `NODE_ENV=development`.
There are a few ways to solve this, but I just switched to using `process.env.NODE_ENV` and passed in the configuration on the `yarn deploy-storybook` command.
> @orta => Fix deploy-storybook command related to NODE_ENV in Circle

- src/components/publishing/__test__/__snapshots__/caption.test.tsx.snap
- src/components/publishing/__test__/__snapshots__/image_collection.test.tsx.snap
- src/components/publishing/__test__/__snapshots__/sections.test.tsx.snap
- src/components/publishing/__test__/__snapshots__/video.test.tsx.snap
- src/components/publishing/__test__/caption.test.tsx
- src/components/publishing/sections/caption.tsx
Minor updates: 
- Adds our text-editor's generic placeholder class to caption component (not ideal to include a vendor class, but it saves a lot of css on the other side).
- Flips weighting in Caption for displaying children vs section html (will display a child if it has one)
> @alloy => Caption editable updates

- src/components/publishing/__stories__/article.story.tsx
- src/components/publishing/__stories__/header.story.tsx
- src/components/publishing/__stories__/typography.story.tsx
- src/components/publishing/__test__/article.test.tsx
- src/components/publishing/article.tsx
- src/components/publishing/fixtures/articles.ts
- src/components/publishing/header/__test__/header.test.tsx
- src/components/publishing/icon/expand.tsx
- src/components/publishing/sections/__test__/__snapshots__/artwork.test.tsx.snap
- src/components/publishing/sections/__test__/__snapshots__/caption.test.tsx.snap
- src/components/publishing/sections/__test__/__snapshots__/image.test.tsx.snap
- src/components/publishing/sections/__test__/__snapshots__/image_collection.test.tsx.snap
- src/components/publishing/sections/__test__/__snapshots__/sections.test.tsx.snap
- src/components/publishing/sections/__test__/sections.test.tsx
- src/components/publishing/sections/artwork.tsx
- src/components/publishing/sections/artwork_caption.tsx
- src/components/publishing/sections/caption.tsx
- src/components/publishing/sections/fullscreen_viewer/__test__/__snapshots__/fullscreen_viewer.test.tsx.snap
- src/components/publishing/sections/fullscreen_viewer/caption.tsx
- src/components/publishing/sections/fullscreen_viewer/fullscreen_viewer.tsx
- src/components/publishing/sections/image.tsx
- src/components/publishing/sections/image_wrapper.tsx
- src/components/publishing/sections/section_container.tsx
- src/components/publishing/sections/sections.tsx
- src/components/publishing/sections/styled_text.tsx
- src/components/publishing/sections/text.tsx
- src/components/publishing/sections/video.tsx
- src/components/publishing/sections/view_fullscreen.tsx
- src/components/publishing/typings.ts
- New ImageWrapper component handles artwork/image + expand icon overlay to enter the fullscreen viewer
- Focus slider on component update to ensure that key commands work without clicking/focusing on component.
> @alloy => FullscreenViewer QA

- src/components/publishing/header/__test__/__snapshots__/header.test.tsx.snap
- src/components/publishing/header/feature_header.tsx
- src/components/publishing/header/header.tsx
Updates to header to accommodate children in Writer
- Adds support for a third child to feature header (for image asset UI)
- Changes css `width: 100vw` to `100%` for accommodating Writer's sidebar
- Adds deck class to child as deck
> @kanaabe => Header children

- src/components/publishing/__stories__/header.story.tsx
- src/components/publishing/__stories__/typography.story.tsx
- src/components/publishing/fixtures/articles.ts
- src/components/publishing/header/__test__/__snapshots__/header.test.tsx.snap
- src/components/publishing/header/classic_header.tsx
- src/components/publishing/header/feature_header.tsx
- src/components/publishing/header/header.tsx
- src/components/publishing/header/standard_header.tsx
- src/components/publishing/icon/layout_fullscreen.tsx
- src/components/publishing/icon/layout_split.tsx
- src/components/publishing/icon/layout_text.tsx
- src/components/publishing/index.tsx
A few more changes to the headers for use in writer:
- Adds lead paragraph to classic header and fixtures
- Adds icons for feature header layouts
- Doesn't resize images if url is empty
- Doesn't render image if url is empty
- Vertical name is not required
> @kanaabe => Header updates for Writer

- src/apps/loyalty/containers/3w_thank_you/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/acb_thank_you/__tests__/__snapshots__/index.ts.snap
- src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
- src/apps/loyalty/containers/repeat_visitor/__tests__/__snapshots__/index.ts.snap
- src/components/__stories__/typography.story.tsx
- src/components/title.tsx
In order to implement https://github.com/artsy/collector-experience/issues/505 we need to be able to change the color of a title.
> Add ability to set a custom color for the Title tag

- src/apps/loyalty/containers/forgot_password/__tests__/__snapshots__/index.tsx.snap
- src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
- src/components/__stories__/input.story.tsx
- src/components/input.tsx
Similar to the `rightView` option for `Input`, but this adds the ability to assign a view to the left of the input. I need this in order to implement: https://app.zeplin.io/project/59b2e6a22224266545e2aea2/screen/59b2e7a8968341983ee82a9b
I also added two examples of an `Input` with `leftView`/`rightView` options.
> Add ability to set leftView to input

- src/__stories__/config.js
- src/components/publishing/__test__/article_tracking.test.tsx
- src/components/publishing/article.tsx
- src/components/publishing/byline/share.tsx
- src/components/publishing/related_articles/__test__/__snapshots__/related_articles_canvas.test.tsx.snap
- src/components/publishing/related_articles/related_article_figure.tsx
- src/components/publishing/sections/view_fullscreen.tsx
- src/typings/react-tracking.d.ts
This attempts to fill out the tracking calls for publishing components for https://github.com/artsy/publishing/issues/50
There were a handful of tracking calls that I couldn't find homes for in the Reaction components.
Specified in the [analytics spreadsheet](https://docs.google.com/spreadsheets/d/17oqFli15x1SmNBu_-fPZhFifMw2BNSPJe9VdOgs1aKs/edit#gid=1499052602):
1. `Sign up for editorial email` 
2. `Clicked partner logo` (Venice 360)
3. `Video play` (Venice 360)
4. `Video duration` (Venice 360)
Seems the last three are irrelevant right now, but #1 I'm curious if we need to re-implement that component?
These events I saw in our current analytics code but didn't find homes for them, nor did I see them in the analytics doc
- `Clicked primary partner logo` (Super article)
- `Clicked …
> @kanaabe: Added tracking for publishing components

- src/components/onboarding/__stories__/selectable_link.story.tsx
- src/components/onboarding/selectable_link.tsx
This cleans up the icon in the Selectable Link component. This should allow use to move the collector intent view to do.
_side note:_ @alloy you mentioned using dynamic styling based on props in the Budget component PR. I gave it a stab but couldn't quite get it to work. Could you help me to refactor this to use that?
> [Onboarding] use circle checkbox for icon

- src/components/onboarding/__stories__/budget.story.tsx
- src/components/onboarding/__stories__/selectable_link.story.tsx
- src/components/onboarding/selectable_toggle.tsx
- src/components/onboarding/steps/budget.tsx
Made with the 🎉 @xtina-starr 
Issue [here](https://github.com/artsy/collector-experience/issues/507). 
Currently looks like:
Still needs:
We've just added a few reviewers just for some extra eyes 😄
> [Onboarding] Budget screen views

- src/assets/animations.tsx
- src/components/onboarding/__stories__/artists.story.tsx
- src/components/onboarding/selectable_item_container.tsx
- src/components/onboarding/steps/artists.tsx
- src/relay/queries/popular_artist.ts
This (partially) implements https://github.com/artsy/collector-experience/issues/505
Right now typing in the search bar doesn't update the list. Also, a click event for each individual artist is not hooked up. But as we discussed we should get this merged before we hook up the data layer with all the components.
> Popular artist container

- src/Components/Onboarding/SelectableLink.tsx
This is a continuation of https://github.com/artsy/reaction/pull/270 which refactors the selectable link component's styling to incorporate dynamic styling based on props.
> [Onboarding] refactor selectable link to use dynamic styling based on props

- package.json
Follow up from https://github.com/artsy/force/pull/1818. CircleCI doesn't support yarn@1.x yet so we can't install Reaction in Force atm. Following @damassi's suggestion, we probably don't need to specify this anyway. We might be missing something tho, so please lmk!
> @orta => Unlock yarn version

- .storybook/webpack.config.js
When I first implemented the email component (https://github.com/artsy/reaction/pull/246), I needed to add this bit of Webpack config to get the `request` package working in storybooks. Issue detailed here: https://github.com/request/request/issues/1529. Now that we're using `superagent`, this is no longer necessary.
> @alloy => Remove unnecessary storybook webpack config

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Sections/ViewFullscreen.tsx
The issue with the slideshow was simply using `childContextTypes` in the child component vs. `contextTypes` but I also decided to loop in the refactors from the last PR.
I can't find a way to use the simulator to test the mobile tap issue you encountered because of the un-pollyfilled advanced browser features Reaction uses. Maybe @alloy or @orta has an idea of how to do this? Barring a way to locally test this should allow us to test on GH pages atleast.
> @kanaabe: Refactored article component to fix fullscreen slideshow

- src/Components/Publishing/Header/FeatureHeader.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
Related to https://github.com/artsy/publishing/issues/83
If there is no hero.url, pass a string rather than undefined. Allows a new feature article with empty heroSection to render in Writer.
> @kanaabe => [Minor] Don't require hero.url to render FeatureHeader

- package.json
Removes required `8.4.x` in favor of `8.x.x` in `package.json`.
> Unlock Node 8 minor versions

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
Fixes https://github.com/artsy/publishing/issues/96
This PR checks to see what target is underneath the click target and if a `CanvasVideo` prevent default behavior. 
**TODO:** 
Expand the click target to cover video if the video has already been played and playback is complete.
> @kanaabe => [Bugfix]: Ad Unit video playback

- .storybook/webpack.config.js
Fixes issue where after file change the process locks up with thousands of console errors leading to slow iteration time: 
Hot reloading is already in the environment via `webpack/development.js`. 
Note that this warning now appears: 
But its only a few and doesn't impact performance. (Don't have time right now to debug further.)
> Remove duplicate HMR loader

- src/Components/History.tsx
This arose while trying to debug some publishing work. This adds a guard so that we only load history on the client.
> @alloy => Only load History on client

- src/Apps/Loyalty/Containers/3wThankYou/__tests__/__snapshots__/index.ts.snap
- src/Apps/Loyalty/Containers/AcbThankYou/__tests__/__snapshots__/index.ts.snap
- src/Apps/Loyalty/Containers/ForgotPassword/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/Inquiries/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/Login/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/RepeatVisitor/__tests__/__snapshots__/index.ts.snap
- src/Components/Text.tsx
- src/Components/__stories__/Typography.story.tsx
We have [a requirement](https://github.com/artsy/collector-experience/issues/609#issuecomment-338811236) where we need to show texts in the size of 26px.
> Add 'xlarge: 26px' for to the Text component

- src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Text.test.tsx.snap
- src/Components/Publishing/Typings.ts
- Updates spacing on h2 > a
- Adds 'blockquote' and image_set layouts to typings for section layouts
Gets close to closing https://github.com/artsy/publishing/issues/128
(Still need to backfill image_sets with 'overflow_fillwidth' layouts)
> @kanaabe => Component spacing

- src/Apps/Loyalty/Containers/3wThankYou/__tests__/__snapshots__/index.ts.snap
- src/Apps/Loyalty/Containers/AcbThankYou/__tests__/__snapshots__/index.ts.snap
- src/Apps/Loyalty/Containers/ForgotPassword/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/Inquiries/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/Login/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/RepeatVisitor/__tests__/__snapshots__/index.ts.snap
- src/Components/Text.tsx
Right now the `Text` component only passes the `className` prop down to the `p` tag. This makes it difficult to apply a style workaround and requires us to update the upstream `@artsy/reaction-force`(this repo), which has more steps than just changing it in e.g. Force. This PR changes the component to pass down any props to the `p` tag so we'll be able to have more control without having to change upstream.
> Text component should accept all props

- .gitignore
- src/Assets/Theme.ts
- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
- src/Components/Publishing/Header/StandardHeader.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/ClassicHeader.test.tsx.snap
- src/Components/Publishing/Header/__test__/__snapshots__/StandardHeader.test.tsx.snap
- src/Components/Publishing/Layouts/Sidebar.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/__stories__/Article.story.tsx
Alright, this feels so much better. See screenshots below. Once @owendodd approves of the layout, I'll reassign it for code review.
Couple things to point out:
1. Breakpoint is changed to 1080 for `lg`
- This number makes more sense with the layouts and a 40px margin. 680px (sections) + 120 (3*40px margins) + 280 (minimum sidebar width) = 1080
- I saw this only affected the Display Canvas so I'll make sure that looks good too **(WIP)** 
2. No grid..yet. I think the layout could benefit from a Grid layout but it also worked nicely by adding a parent with a strict margin and letting the child div do auto margins. 
3. Right after 1080 I hide the sidebar because it will no longer fit - I'm thinking we either come up with a condensed sidebar, or just opt for centering everything. Centering …
> @eessex => Cleaner responsive StandardLayout

- src/Utils/Events.ts
This adds the `Events` API to the `window` object which is kinda ugly in TS, but luckily not something we commonly need to do. The reason for it here is that we want a truly global singleton object that is shared across asset packages and between Reaction & Force—otherwise, the Reaction components instantiate one object and Force instantiates a different one and they don't communicate. This is a pattern we use in other truly global event emitters like our [analytics hooks](https://github.com/artsy/force/blob/master/desktop/lib/analytics_hooks.coffee#L10).
> Make Events API truly global

- src/Components/Publishing/Sections/Video.tsx
When attaching an image to a player, ensure that it has a cover image before showing play button.
> @damassi => Hide play button if missing thumbnail

- src/Components/Publishing/Byline/Byline.tsx
- src/Components/Publishing/Byline/__test__/__snapshots__/Byline.test.tsx.snap
- src/Components/Publishing/Constants.ts
- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Header/BasicHeader.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/ClassicHeader.test.tsx.snap
- src/Components/Publishing/Header/__test__/__snapshots__/StandardHeader.test.tsx.snap
- src/Components/Publishing/RelatedArticles/RelatedArticleFigure.tsx
- src/Components/Publishing/Sections/Author.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/Authors.test.tsx.snap
- src/Components/Publishing/__stories__/Byline.story.tsx
- Gives us a better empty state for twitter handles and author bios.
- Converts all the things to `authors` now that the backfill is complete
> @damassi => Use authors field and set better empty state

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
- src/Components/Publishing/Display/Canvas/index.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.tsx.snap
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Sections/Video.tsx
- src/Components/Publishing/Sections/VideoControls.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/Video.test.tsx.snap
- src/Components/Publishing/__stories__/Display.story.tsx
- Use `cover_image_url` instead of `assets` for video cover images
- Adds mobile styles for Panel video (cover image has play button, plays on click)
- Moves video caret/controls into reusable component
- Allows for unit.link to be empty
I added a tracking event for the video play with `action: "Click"` -- is there a way to make this accommodate both click and mouseenter, or should we make separate events?
> @craigspaeth => Mobile Panel video, allow empty links

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/__test__/Article.test.tsx
- src/Utils/Responsive.tsx
- src/__stories__/config.js
Addresses https://github.com/artsy/publishing/issues/160
Also, added additional functionality to our `<Responsive>` util (cc @eessex) that can be used like so:
```jsx
<Responsive>
{({ xs, sm, md, lg, xl }) => 
<div>
{xs && 
<ExtraSmallDiv /> }
{md && 
<MediumDiv /> }
</div>
}}
</Responsive>
```
> @kanaabe => Display panel should insert itself into the body of the article on mobile

- src/Components/Publishing/Header/BasicHeader.tsx
- src/Components/Publishing/Sections/Video.tsx
Addresses https://github.com/artsy/publishing/issues/189
This locks our Basic Video header to fixed heights so that the css doesn't jump during SSR.
> @kanaabe => Make video widths fixed

- src/Assets/Theme.ts
- src/Components/Publishing/Header/BasicHeader.tsx
- src/Components/Publishing/Header/FeatureHeader.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/ClassicHeader.test.tsx.snap
- src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
- src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap
- Ups breakpoint to 1280 -- macbook screens are ~ 1260, meaning they loaded pages with no margins.
- Adds relative positioning to feature header and cleans up some overlap/margin problems
- Adds top margin to basic headers without embeds
> @craigspaeth => QA / Headers margins

- src/Components/Publishing/Header/FeatureHeader.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
Looks like there was some code related to basic header that doesn't need to be here (we are already checking for layout to be text, it can't be basic too). This was preventing the image upload from displaying in the text layout in writer.
> @damassi => Text feature children display

- package.json
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/DisplayPanel.test.js
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/__stories__/Article.story.tsx
- src/Components/Publishing/__stories__/Display.story.tsx
This PR refactors our display unit to further account for mobile behaviors. Some states were missing such as image toggles on mobile (as it only accounted for css `:hover` events on desktop). Additionally tightened up the behavior pipeline so that things funnel through the component more systematically.
> @kanaabe => Complete Display Ad interactions on mobile

- src/Components/Publishing/Header/BasicHeader.tsx
Since share needs the full url to scrape metadata --
> @kanaabe => Use fullHref for Basic Header share #minor

- package.json
- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/__test__/DisplayPanel.test.js
- src/Components/Publishing/Header/BasicHeader.tsx
- src/Components/Publishing/Sections/ImageWrapper.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__test__/Sections.test.js
- src/Components/Publishing/__stories__/Article.story.tsx
- tsconfig.json
- yarn.lock
One of the more frustrating bug sequences I've encountered:
1. When testing the new Publishing layout in staging, I would notice that the view would occasionally break
1. Digging in, I noticed that it would only break when the Display ad was image-based, not video 
1. That led me to conclude that the immediate right sidebar link was the culprit -- and more specifically the new mobile-based injection code
1. I pulled that all apart, compiled and restarted innumerable times
1. This led me to uncover an issue related to infinite scroll Display injection, so i guess that 1/2 day's worth of time was worth it 😓 
1. Realized however that the issue has nothing to do with the sidebar Display, although the state of the sidebar Display is indicative of the problem -- if image, it breaks, if video, …
> @damassi => Fix SSR slideshow bug

- src/Components/__stories__/Icons.story.tsx
added some examples we implemented on Wednesday:
> Add examples for circle icons with different scale

- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
- src/Components/Publishing/__stories__/Article.story.tsx
Fixes issue noticed during SH with @kanaabe - the hover state was filling in across the full width:
> @damassi => Fix width in display ads

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
This follows the tracking events we did for [Venice 360](https://github.com/artsy/force/blob/master/desktop/apps/editorial_features/components/venice_2017/client/video.coffee#L117-L145) for tracking 3 & 10 second intervals as well as percent complete. It also fixes a small bug where clicking the video play button would count as a clickthrough tracking event.
> Add video playback tracking to display video component

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
- src/Components/Publishing/Fixtures/Components.ts
- tslint.json
Adds cover image support to canvas video. 
**NOTE!** There is no field in positron for uploading cover images in this way, so pulls from display ad.
> @kanaabe => Add cover image support to Canvas video

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/DisplayPanel.test.js
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
- src/Components/Publishing/Sections/Sections.tsx
This fixes an issue that was noticed where tracking wasn't firing on mobile due to `ReactDOM.render` not passing along context (during ad injection). Also added some more tests.
cc @craigspaeth - I ditched the method decorators so that this would be easier to test!
> Update tracking / tests

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Sections/Video.tsx
- src/Components/Publishing/__stories__/Video.story.tsx
Pairing w @kanaabe 
- Adds entity_type and enitity_id to Article root tracking event
- Adds event for video play to Video component, accepts custom trackingData as a prop or defaults to Article's track event data.
> @craigspaeth => Video accepts custom tracking params

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/index.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
- src/Components/Publishing/Display/track-impression.ts
Yikes, what a rabbit hole. This implements a `trackImpression` decorator that stores a cache of the previous impressions to prevent multiples being fired. This avoids the React lifecycle pitfalls and the decorator hides some ugliness and feels a bit more in the style of React Tracking. [Context from Slack](https://artsy.slack.com/archives/C3YTM6BTK/p1510171534000387)
PS. I thought I disliked decorators before—now after writing one... 😵 ...so complicated
> Stop multiple impression tracking calls

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
Addresses https://waffle.io/artsy/publishing/cards/5a031d4133995d00a880c149
This fixes the issue of cutting off text, but the margins still aren't perfect. There's a moment between 1280px and 1320px where the margin isn't consistent. After faffing with this one for a while, I think it's best we rewrite the way these slides work with `react-slick`. Half of this battle was understanding the CSS. 
For now, this solves the problem but I look forward to refactoring this component.
> @damassi => Fixes CanvasSlideshow cutting text off

- src/Components/Publishing/Byline/Share.tsx
- src/Components/Publishing/__test__/ArticleTracking.test.tsx
Per [input from @wrgoldstein](https://github.com/artsy/positron/issues/1416), updates labels on 'share' tracking data
> @kanaabe => Update share labels

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
- src/Utils/__test__/resizer.test.ts
- src/Utils/resizer.ts
Thanks for helping + setting up the Cloudfront side! This PR makes use of the new url by adding an `isDisplay` option to the resizer methods.
> @mzikherman => Use a different on-the-fly Cloudfront url for Display Ads

- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/Text.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.js.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Text.test.tsx.snap
Rather than using html classes for drop-caps, the parent container (in this case sections, in Positron, sectionContainer) determines whether the section is the first text in a feature article.
Related to https://github.com/artsy/positron/pull/1451
> @damassi => Use props to set drop-caps

- src/Components/Publishing/ReadMore/ReadMoreWrapper.tsx
- src/Components/Publishing/ReadMore/__test__/ReadMore.test.tsx
Addresses https://waffle.io/artsy/publishing/cards/59fa24a2d0de2e016e8386a3
Fixes a bug where the contents of the article shifted up a tiny bit on clicking Read More.
> @craigspaeth => Fixes jump on clicking "Read More"

- src/Components/Publishing/Byline/Byline.tsx
- src/Components/Publishing/Header/BasicHeader.tsx
- src/Components/Publishing/Header/ClassicHeader.tsx
- src/Components/Publishing/Header/FeatureHeader.tsx
- src/Components/Publishing/Header/Header.tsx
- src/Components/Publishing/Header/StandardHeader.tsx
- src/Components/Publishing/Header/__test__/FeatureHeader.test.tsx
- src/Components/Publishing/Header/__test__/Header.test.tsx
- src/Components/Publishing/Header/__test__/StandardHeader.test.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
Related to the 'invalid date' bug in Writer -- allow a header to accept a date as props (currently we only can render published_at).
> @kanaabe => Header can accept date as props

- circle.yml
This should fix the `tslint` failure occurring in CircleCI.
> Use yarn 1.3.2 to install dependencies in CircleCI

- src/Components/Onboarding/Steps/Artists/ItemLink.tsx
This removes unused state I added a few months ago. We are working on the Follow Artist component with a different approach (https://github.com/artsy/reaction/pull/402), and this has been just mysterious code that prevented us from refactoring. Let's just delete it and come back once we finish the Follow Artist and Follow Gene components.
> Remove unused state in the Artist component

- src/Components/Publishing/Icon/IconDrag.tsx
- src/Components/Publishing/Sections/StyledText.tsx
Two minor fixes -- 
- In StyledText, check if feature before showing drop-caps styles
- In IconDrag, add fill color two two shapes that were missed
> @alloy => Don't show dropcaps unless feature, icon colors

- src/Apps/Loyalty/Containers/3wThankYou/__tests__/__snapshots__/index.ts.snap
- src/Apps/Loyalty/Containers/AcbThankYou/__tests__/__snapshots__/index.ts.snap
- src/Apps/Loyalty/Containers/Inquiries/__tests__/__snapshots__/index.tsx.snap
- src/Apps/Loyalty/Containers/RepeatVisitor/__tests__/__snapshots__/index.ts.snap
- src/Components/Helpers.tsx
- src/Components/Publishing/Series/Series.tsx
- src/Components/Publishing/Series/SeriesAbout.tsx
- src/Components/Publishing/Series/SeriesAbout2.tsx
- src/Components/Publishing/Series/__test__/__snapshots__/Series.test.tsx.snap
- src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
One thing I noticed while building out the video landing pages was that Series components don't use `react-styled-flexboxgrid` so it causes a little inconsistency when importing them into the video pages. I think if we're committed to using grid systems, we should start with these pages since they're new. This converts the SeriesAbout component to use `react-styled-flexboxgrid`. We'll have to get to regular article pages another time!
Note that this uses the breakpoints and sizes of the regular grid layout, not our publishing ones.
Some screenshots:
> @eessex => Use grid in SeriesAbout

- src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/Components/Onboarding/Steps/Artists/ItemLink.tsx
- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
- src/Components/Onboarding/Steps/Artists/SelectableItemContainer.tsx
Now the user can click an artist and see a related artist. 
* moved the `#onArtistFollowed` function up to the `ArtistSearchResultsContent` and `PopularArtistsContent` to be able to update different stores for different relay queries. Not sure about the interface yet but I think we should be able to figure out and make it more mature as we add more logic to it (e.g. Follow Gene)
* Animation is not implemented yet, but could be addressed as a separate task
* The `SelectableItemContainer` component could be inlined since all it does is just to iterate over each item on `this.props.artists` (proof of concept: https://github.com/yuki24/reaction/commit/bd2bdd312c39340ed8014fe299de8b2c7e4a9b58)
> User can see a related artist after searching and following an artist

- gulpfile.js
- package.json
- tsconfig.json
- yarn.lock
re-adding all the gulp stuff, but with the critical `pipe(babel())` line.
> @alloy => Copy and transpile __generated__ files

- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
- src/Components/Publishing/Series/ArticleCard.tsx
- src/Components/Publishing/Series/__test__/__snapshots__/ArticleCard.test.tsx.snap
Uses the title for ArticleCard instead of thumbnail_title. Addresses a point in https://github.com/artsy/publishing/issues/277
> @kanaabe => Use title instead of thumbnail_title for ArticleCard #minor

- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Nav/Nav.tsx
- src/Components/Publishing/Nav/__test__/Nav.test.js
- src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
- src/Components/Publishing/Series/SeriesAbout.tsx
- src/Components/Publishing/Series/SeriesTitle.tsx
This should do it for partner logos!
Nav now using `partner_condensed_logo` properly:
Titles and about sections all use `partner_light_logo` properly:
> @eessex => Update partner logos to use new fields

- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
- src/Components/Publishing/Series/ArticleCard.tsx
- src/Components/Publishing/Series/__test__/__snapshots__/ArticleCard.test.tsx.snap
Was able to replicate this bug in browserstack, but not xCode's simulators -- maybe we should get an account... the free trial is only 30min.
- Changes articleCard's image container height to 'inherit'
> @kanaabe => iOS overlapping text bug

- src/Components/Artsy.tsx
- src/Components/__tests__/Artsy.test.tsx
* You can still disable this by passing `null` as `currentUser`
* This makes storybook deploys use details from the `.env` file.
> [Artsy] Always use user details from env if available.

- src/Components/Publishing/Sections/Artwork.tsx
- src/Components/Publishing/Sections/Image.tsx
- src/Components/Publishing/Sections/ImageWrapper.tsx
- src/Components/Publishing/Sections/__test__/Artwork.test.tsx
- src/Components/Publishing/Sections/__test__/Image.test.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/Image.test.tsx.snap
Some changes to images and artworks to allow better control in Positron--
- Use `editCaption` prop rather than children to render caption fields
- Allow children in both artwork and image (for remove buttons and potentially other things, renders without styles or container)
- Allow image captions to be empty
- Use linked prop in images to determine if `ViewFullscreen` button is displayed
- Adds unit tests for images and artworks
This will affect https://github.com/artsy/reaction/pull/455/files, but I can update that PR once this is merged.
> @kanaabe => Image editing tweaks

- src/Components/Artist/MarketInsights/MarketInsights.tsx
- src/Components/Artist/MarketInsights/index.tsx
- src/Components/__stories__/MarketInsights.story.tsx
- src/Components/__tests__/MarketInsights.test.tsx
- src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap
I'm still faffing with actually getting this to work in Force, but I _think_ this might work, since we can now use a component that will fetch the data and render.
It cleans up the storybook too, which is akin to how we'll use it in Force.
> @alloy => Export component with a QueryRenderer for MarketInsights

- data/schema.graphql
- data/schema.json
- src/Components/Artist/MarketInsights/MarketInsights.tsx
- src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap
Addresses last couple of bullet points for https://github.com/artsy/collector-experience/issues/872.
Depends on https://github.com/artsy/metaphysics/pull/898
There'll be one last PR in Force, to bring in the latest Reaction module, as well as a `z-index` fix for the tooltip bug, and then Force `master` will be ready to go with these final QA pieces!
One last pass at QA to verify final fixes, and then we can merge https://github.com/artsy/force/pull/2070 , which replaces the admin-only guard with the actual AB test (next Tuesday).
> @joeyAghion => Last market insights QA

- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
- src/Components/Publishing/Sections/Caption.tsx
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/Caption.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Image.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/ImageCollection.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.js.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Text.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Video.test.tsx.snap
- src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap
One half of https://github.com/artsy/positron/issues/1531
Adds Draft's default block (equivalent to paragraph) to StyledText classes.
> @kanaabe => Draft default class

- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.js.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Text.test.tsx.snap
- src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap
Got the selectors slightly wrong for first-child/last-child in draft, this fixes them so spacing is correct in Positron.
> @kanaabe => Draft blocks

- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.js.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Text.test.tsx.snap
- src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap
One more small change to the classes for Draft -- prefix selector with `div[data-block=true]` so it does not apply to div's inside an `h2` or other kind of block.
> @kanaabe => Prefix draft selector

- .vscode/settings.json
- package.json
This updates Prettier column settings to the default (80) per the [RFC outcome](https://github.com/artsy/potential/issues/127#issuecomment-358997987). In favor of an incremental approach (while acknowledging existing PRs in the wild), it does _not_ reformat the codebase. Existing code will remain the same until touched at which point our git precommit hook (or VSCode editor settings) will rewrite.
> [Prettier] Update column setting to default

- src/Components/Onboarding/Steps/Artists/ArtistList.tsx
- src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
- src/Components/Onboarding/Steps/Artists/index.tsx
- src/Components/Onboarding/Steps/CollectorIntent.tsx
- src/Components/Onboarding/Steps/Genes/GeneList.tsx
- src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
- src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
- src/Components/Onboarding/Steps/Genes/index.tsx
- src/Components/Onboarding/Types.ts
- src/Components/Onboarding/Wizard.tsx
- src/Components/Onboarding/__stories__/Artists.story.tsx
- src/Components/Onboarding/__stories__/Wizard.story.tsx
This is a WIP for https://github.com/artsy/collector-experience/issues/737. A few things remain to be implemented:
> Fix wizard

- src/Components/Onboarding/SelectableLink.tsx
- src/Components/Onboarding/Steps/Artists/index.tsx
- src/Components/Onboarding/Steps/Genes/index.tsx
Addresses https://github.com/artsy/collector-experience/issues/847 by decoupling text input from query + throttles the query state change.
Noticed there weren't any tests in this project yet so I was going to add one but got a little stuck on an error with `ContextProvider` and mocking the Relay side. I'll follow up with tests but didn't want to hold back on the PR.
This uses 500 millisecond throttle which was a little nicer than 1 second which felt pretty slow.
> @yuki24 => [Onboarding] Throttled search

- package.json
- src/Components/Animation/ReplaceTransition.tsx
- src/Components/Icon.tsx
- src/Components/Onboarding/ItemLink.tsx
- src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
- src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
- src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
- src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
- src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
- src/Components/Publishing/Partner/__test__/__snapshots__/PartnerInline.test.tsx.snap
- src/Components/Publishing/Sections/FullscreenViewer/__test__/__snapshots__/FullscreenViewer.test.tsx.snap
- src/Components/Publishing/Sections/__test__/__snapshots__/Authors.test.tsx.snap
- src/Components/__stories__/Animation.story.tsx
- yarn.lock
This PR adds a `<ReplaceTrnsition>` component. finishes https://github.com/artsy/collector-experience/issues/843
**Jan 22 2018: updated the screenshot**
* Right now, people are moving forward to the `react-transition-group` version 2, which seems to cover many issues. Ideally, we should be using this version.
* In the master branch, there's already a [`<ReplaceTransition>` component](https://github.com/reactjs/react-transition-group/blob/7a64114/src/ReplaceTransition.js) in `react-transition-group`. However, it requires [exactly two elements](https://github.com/reactjs/react-transition-group/blob/7a641148849fc3aa0aa0acb673da9bc3cc35a7a0/src/ReplaceTransition.js#L10) shown and mounted simultaneously. Unfortunately, this is not the case in our list components such as `<PopularArtists>`. I …
> [WIP] Add animation transition on follow

- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/Sections/__test__/ArtworkCaption.test.js
- src/Components/Publishing/Sections/__test__/__snapshots__/ArtworkCaption.test.js.snap
Fixes the zero-state on artwork captions, ie captions with no title, date, partner, etc. There's a lot of noise with Prettier changes/fixture updates but [here](https://github.com/artsy/reaction/compare/master...kanaabe:zero-state-artwork?expand=1#diff-109086d38202a7acf7b1dc711fd98a4eR25) is the main bit.
Artwork fixtures are also named now, so we can reference them by what the data looks like instead of arbitrarily with `Artworks[1]`.
> @damassi => Zero state artwork captions

- src/Components/Onboarding/ItemLink.tsx
- src/Components/Onboarding/Steps/Budget.tsx
- src/Components/Onboarding/Steps/CollectorIntent.tsx
- src/Components/Onboarding/Steps/Layout.tsx
- src/Components/Onboarding/Types.ts
- src/Components/Onboarding/Wizard.tsx
- src/Components/Onboarding/__stories__/Wizard.story.tsx
This fixes the minor CSS items we saw related to the `line-height` in the titles as well the resizing that was happening to the images. In addition, it also supports a `redirectTo` prop to be passed Wizard component and down to the Budget component so that we can support redirecting the user to their entry point before account creation/onboarding after onboarding steps are completed.
> @kanaabe => Minor ui tweaks

- src/Components/Publishing/Email/EmailPanel.tsx
- src/Components/Publishing/Email/__test__/EmailPanel.test.tsx
- src/Components/Publishing/Email/__test__/__snapshots__/EmailPanel.test.tsx.snap
We were missing a track call on the fixed email signup in articles. Talking about this guy on the side bar:
This adds a track call to the success callback. Hope this is helpful to read through for implementing analytics for Onboarding!
> @xtina-starr => Signup tracking on article pages

- src/Components/Onboarding/Steps/Budget.tsx
- src/Components/Onboarding/Steps/Layout.tsx
fixes [AR-70](https://artsyproduct.atlassian.net/browse/AR-70), [AR-71](https://artsyproduct.atlassian.net/browse/AR-71), and [AR-72](https://artsyproduct.atlassian.net/browse/AR-72). This is the first step to address [AR-69](https://artsyproduct.atlassian.net/browse/AR-69) and we'll be working on [AR-73](https://artsyproduct.atlassian.net/browse/AR-73) and [AR-75](https://artsyproduct.atlassian.net/browse/AR-75) next.
tested on Firefox, Safari, Chrome, IE Edge, IE11 and mobile safari.
> [Onboarding] UI QA: fixes the title size, correct margan b/t title and serach, and sticky footer

- src/Components/Onboarding/Steps/Genes/index.tsx
This fixes the placeholder for the category search input thanks to @bhoggard for pointing this out!
> [Onboarding] Fix placeholder for category search

- src/Components/Onboarding/Steps/Artists/index.tsx
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-74
It looks like the Gene step already has autofocus on, so it's only the artist step.
> @xtina-starr => [Onboarding][AR-74] Autofocus on the artist step 

- src/Components/Onboarding/Steps/Artists/index.tsx
- src/Components/Onboarding/Steps/Budget.tsx
- src/Components/Onboarding/Steps/CollectorIntent.tsx
- src/Components/Onboarding/Types.ts
- src/Components/Onboarding/Wizard.tsx
- src/Components/Onboarding/__stories__/Wizard.story.tsx
Forgot that we need this piece of logic to get the Force side working! This allows you to pass a prop called `forceStep` which sets `state.currentStep` to be the one we ask for based on the slug. It can handle slugs that doesn't exist as a step (defaults to the first step) and updates the url.
Adds a story to represent forceStep:
> @yuki24 => [Onboarding] Be able to force a step to start on

- src/Components/Onboarding/Steps/Budget.tsx
- src/Components/Onboarding/Steps/CollectorIntent.tsx
We need to pass the slug onto the HOC that wraps BudgetComponent. The preferred way is to do `Budget.slug = BudgetComponent.slug` but that returns a TS error on `ContextConsumer` for not having defined slug. However, we probably don't want to litter the `ContextConsumer` types to do this so this works around the error by using string literals to set the variable.
I don't know if this is controversial to people, but it works 😄 
Ref: https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over
> @yuki24 => Fixes static variables on HOC

- src/Components/Onboarding/ProgressIndicator.tsx
- src/Components/Onboarding/Wizard.tsx
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-91
Wasn't too sure about the stripes in the background of the indicator bc the comps were a little fuzzy but this is what I came up with:
Also the animation here uses ease-in but we can configure that to whatever.
> @yuki24 => [Onboarding] Wizard progress indicator

- src/Components/Buttons/Facebook.tsx
- src/Components/__stories__/Buttons.story.tsx
We are working on [the landing page for the Armory Week 2018](https://app.zeplin.io/project/5a7a2abbc504dc1d5465383a/screen/5a7a2af99341bdce56ecdb2b). This page has a button that lets the user sign in through Facebook, but with a different button text from `"Log in with Facebook"`. This PR updates the `<FacebookButton>` component to accept an arbitrary text (or any `props.children`) so it's ll be more flexible and useable in the landing page.
> Update <FacebookButton> to display props.children

- package.json
- src/Components/Onboarding/Wizard.tsx
- src/Components/Onboarding/__stories__/Wizard.story.tsx
- yarn.lock
_When I tried to test this staging was missing popular artists data, which caused the `<PopularArtists>` component to fail to load._
This brings the `<RoutesWithProgressBar>` component (currently in Force) onto Reaction. We wanted to use the `@track` decorator in Force, but it turns out that not everything is set up properly and it seems a bit too early to adopt it. For now, it may make more sense to maintain TS classes and components in Reaction.
> Move the <RoutesWithProgressBar> component from Force to Reaction

- circle.yml
- Adds `commands` prefix to deployment for semantic-release
- Use command from package json rather than run
> @damassi => Semantic release qa

- README.md
- circle.yml
Circle was not running the storybooks command because the circle.yml `deployment` command only accepts one argument per branch -- this consolidates the release and demo blocks.
> [FIX semantic-release] consolidate deploy commands

- src/Components/Onboarding/Wizard.tsx
_This is unrelated to the build failures we observed last week and just a fix for the bug introduced by https://github.com/artsy/reaction/pull/527_
The `<CollectorIntentComponent>` and `<BudgetComponent>` components were imported and rendered in the `<Wizard>` component, but they weren't wrapped by the `ContextConsumer` function and don't know about `currentUser` or `relayEnvironment`. AS a result of this, clicking the NEXT button, which makes a call to MP, started failing due to `401 Unauthorized`.
This PR updates the `<Wizard>` component to import the right step components so it'll be able to make a request with an appropriate token.
> [Onboarding] Fix the Wizard component not pulling in realy environment

- circle.yml
Ignores gh-pages branch for slack alerts to #front-end channel.
Removes messages like this:
> @damassi => Don't alert slack for gh-pages

- gulpfile.js
- package.json
- yarn.lock
This is a quick-fix for `src/__generated__` paths in output in order to unblock. (@alloy will follow up with a formal release in Relay)
> [FIX toolchain] User gulp-replace to fix relay paths

- src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
- src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
- src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
This fixes a bug and also adds a type as a guard against potential type mismatch. Regarding the bug, we were passing an `artistId` to `onArtistFollowed` when it was expecting an artist object. This passes that artist and adds the artist type check so we can catch something like this in the future.
> [FIX onboarding] fixed a bug where <PopularArtists> didn't update the <ItemLink> with the suggested artist

- src/Utils/__test__/metaphysics.test.ts
- src/Utils/metaphysics.ts
This at least handles the reaction side of https://github.com/artsy/force/issues/2191
Happy to change what the text actually is, but at least it's there.
> Adds a user agent to the metaphysics fetch

- src/Components/Publishing/Layouts/ArticleLayout.tsx
It looks like the compiler is a bit more strict. If defining a context it (with `@tracking()`) we need to be sure to add it in to the list. The fullScreenModal context was breaking things.
> [FIX tracking-context] Add context to contextTypes

- package.json
- yarn.lock
Fixes an odd race-condition I've found when running SSR across apps:
```
ypeError: styleSheet.getNameForHash is not a function
at ComponentStyle.generateAndInjectStyles (/Users/damassi/Sites/artsy/reaction/node_modules/styled-components/dist/styled-components.cjs.js:1805:37)
at StyledComponent.generateAndInjectStyles (/Users/damassi/Sites/artsy/reaction/node_modules/styled-components/dist/styled-components.cjs.js:1482:40)
at StyledComponent.componentWillMount (/Users/damassi/Sites/artsy/reaction/node_modules/styled-components/dist/styled-components.cjs.js:1520:40)
at resolve (/Users/damassi/Sites/artsy/force/node_modules/react-dom/cjs/react-dom-server.node.development.js:2119:12)
at ReactDOMServerRenderer.render (/Users/damassi/Sites/artsy/force/node_modules/react-dom/cjs/react-dom-server. …
```
> [FIX lib] Downgrade styled-components in devDeps

- package.json
- yarn.lock
Try this one more time. Looks like 2.5 ships with flat bundles, which breaks jest-styled-components.
> [FIX lib] Downgrade styled-components 2.4.0

- README.md
Adds docs around 
```
yarn link
cd ../force && yarn link @artsy/reaction && yarn start
```
(I'm still thinking about how I'd like to wrap all of these commands up)
> [DOC readme] Update with yarn watch instructions

- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Fixtures/Helpers.tsx
- src/Components/Publishing/Sections/SectionContainer.tsx
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__tests__/Text.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Text.test.tsx.snap
- src/Components/Publishing/Typings.ts
- src/Components/Publishing/__stories__/Text.story.tsx
- Adds styles for News articles to `StyledText` component
- Adds 'news' layout to article typings
- Adds helper function `TextFromArticle` to get all html from text sections
- Reworks text fixtures to conform to section modeling, adds fixture articles with only text sections
- Uses cloneDeep in fixtures when duplicating articles
*** blockquote width is determined in sectionContainer, so will not show up in this screenshot
> @sarahscott => News text / Fixtures updates

- src/Components/Publishing/Display/track-once.ts
This was introduced to account for impression tracking that didn't provide an article id (right now that's Instant Articles). But using the internal `_reactInternalInstance` as the `||` is probably not a good idea since it's meant to be used internally by React. And now this line is broken with React 16 because they've switched to using a different node internally called `_reactInternalFiber `. 
If an article id isn't provided, it can be assumed that this is a one-off ad (Instant Article) which doesn't need to keep a cache of display units.
Sorry a lot of words here, so I'm happy to explain in person if that's easier.
> @xtina-starr => Remove use of internal _debugID in Impression tracking

- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.js
- src/Components/Publishing/Typings.ts
`uniqueId()` is problematic for SSR where sometimes the `id` generated on the server doesn't match the client and therefore can't mount the ad unit. Instead, lets use the article id which still works with infinite scroll to account for uniqueness.
> @eessex => Use article id as injection marker for mobile display

- package.json
- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/News/NewsSections.tsx
- src/Components/Publishing/Sections/SocialEmbed.tsx
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__tests__/SocialEmbed.test.tsx
- src/Components/Publishing/__stories__/Sections.story.tsx
- yarn.lock
This adds `jsonp` and `react-oembed-container` packages. In an earlier implementation I started writing the jsonp fetcher and script injection from scratch but in the end these libs were way less flaky and covered more edge cases. If anyone is weary about adding more dependency load let's talk --
these are both pretty small libs tho. 
See notes here: https://artsyproduct.atlassian.net/browse/GROWTH-268
> @eessex => Social embed

- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/News/NewsHeadline.tsx
- src/Components/Publishing/News/NewsSections.tsx
- src/Components/Publishing/News/__tests__/__snapshots__/NewsHeadline.test.tsx.snap
- src/Components/Publishing/__stories__/Article.story.tsx
Uses the familiar `isTruncated` prop to determine if an article is truncated. Once you click it stays expanded
On hover outline and click to expand:
> @sarahscott => Adds News Truncation

- src/Components/Publishing/Fonts.tsx
- src/Components/Publishing/Nav/NewsNav.tsx
- src/Components/Publishing/Nav/__tests__/NewsNav.test.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
- src/Components/Publishing/__stories__/Nav.story.tsx
Fairly simple nav for News. Haven't added it to the Article because I think this should exist one level up, when we have an InfiniteScroll. Addresses https://artsyproduct.atlassian.net/browse/GROWTH-278
Desktop:
Mobile:
> @sarahscott => News Nav

- src/Components/Publishing/Sections/SocialEmbed.tsx
- src/Components/Publishing/Sections/__tests__/SocialEmbed.test.tsx
Handles the error we were seeing earlier -- we should not fetch anything if the url is null.
> @sarahscott => Handle non-valid links in SocialEmbed

- src/Components/Publishing/Sections/Artwork.tsx
- src/Components/Publishing/Sections/Image.tsx
- src/Components/Publishing/Sections/ImageWrapper.tsx
- src/Components/Publishing/Sections/__tests__/Artwork.test.tsx
- src/Components/Publishing/Sections/__tests__/Image.test.tsx
Adds an optional boolean prop `editing` to images and artworks, which disables the fade in on loading. 
Once we switched to Redux in Positron, changes to the article can trigger re-rendering in the tree, which causes erratic fade-ins that can confuse users.
> @damassi => Skip images-loaded fade if editing

- src/Components/Onboarding/Steps/Layout.tsx
I believe [the original issue](https://artsyproduct.atlassian.net/browse/GROWTH-361) I was looking into was fixed by https://github.com/artsy/force/pull/2291, but even with that fix there are many other issues in MS Edge or IE 11, and this PR fixes one of them.
The issue this PR addresses is that on the onboarding screen the NEXT button does not show up. This PR removes the `position: sticky;` property that seems to fix the issue. I was worried about mobile safari not respecting `position: fixed`. I tested it on iOS 9 and 11, and apparently that is no longer an issue. See the screenshots below:
> [FIX onboarding] Fixed a bug where the NEXT button doesn't show up on Edge

- src/Components/Onboarding/Steps/Layout.tsx
Reverts artsy/reaction#588
For some reason, the NEXT button is completely gone on the iOS (see screenshot below). I'll have to look into it more deeply.
> Revert "[FIX onboarding] Fixed a bug where the NEXT button doesn't show up on Edge"

- src/Components/Publishing/Byline/DateSource.tsx
This makes sure `editSource` can still render if `news_source` is null.
> @kanaabe => Fix in editSource of NewsByline

- src/Components/Publishing/Constants.ts
- src/Components/Publishing/Nav/NewsNav.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
- src/Components/Publishing/News/NewsDateDivider.tsx
- src/Components/Publishing/News/NewsDateHeader.tsx
- src/Components/Publishing/News/__tests__/NewsDateDivider.test.tsx
- src/Components/Publishing/News/__tests__/NewsDateHeader.test.jsx
- src/Components/Publishing/News/__tests__/__snapshots__/NewsDateDivider.test.tsx.snap
- src/Components/Publishing/Typings.ts
- Adds NewsDateHeader component to render styled article date or 'today'
- Replaces NavNews date with NewsDateHeader component
- Adds NewsDateDivider, for displaying date between articles in list
- Minor updates to NavNews styling
> @kanaabe => News Date headers

- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
- Adds `marginTop` optional prop to NewsLayout, used on first article in a list to avoid menu overlap
- Adds `onExpand` optional prop to NewsLayout, called on click, used to change `window.location` in Force
> @sarahscott => Add marginTop, onExpand to NewsLayout

- src/Components/Publishing/Byline/AuthorDate.tsx
- src/Components/Publishing/Byline/NewsByline.tsx
- src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
Addresses [GROW-400](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-400)
Replaces 'Posted by' with bullet in news byline.
> [FIX publishing] Replace news posted by with bullet

- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
As of writing https://www.artsy.net/personalize/artists is broken:
This was caused by a `null` value in a response from MP:
And here is the whole query:
```graphql
query {
popular_artists(exclude_followed_artists: true) {
artists {
id
_id
__id
name	
image {
cropped(width: 100, height: 100) {
url
}
}
}
}
}
```
We are also working on fixing the roo cause on the server-side, but to get the onboarding back quickly let's just make it defensive about `null` values.
> [FIX onboarding] Make <PopularArtist> defensive about null values

- src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
This is a fix that should've been part of https://github.com/artsy/reaction/pull/605.
> Fixed a bug where users cannot follow artists during onboarding

- src/Components/Publishing/Byline/DateSource.tsx
- src/Components/Publishing/Byline/__tests__/DateSource.tsx
Makes sure 'via' in byline isn't rendered unless there's a source.
> @eessex =>  do not render "via" if no source exists

- src/Assets/Colors.tsx
- src/Components/ArtworkFilter/ForSaleCheckbox.tsx
- src/Components/Authorization/commonElements.tsx
- src/Components/Checkbox.tsx
- src/Components/__stories__/Input.story.tsx
This updates the existing `<Checkbox>` component:
And here is how to use it:
```tsx
<Checkbox onChange={event => console.log("I'll remember you!", event)}>
Remember me
</Checkbox>
<Checkbox checked>
Remember me
</Checkbox>
<Checkbox disabled>
Remember me
</Checkbox>
<Checkbox checked disabled>
Remember me
</Checkbox>
```
This is an existing component, so the interface for `props` are unchagend, but now it can take a `children` prop to show the label for a checkbox input.
This also updates the styling, so for example, the  `<FilterBar>` in the `<GeneArtworks>` component would look slightly different:
> Add a <Checkbox> component

- src/Components/Publishing/Sections/Text.tsx
A bug in 'content-end' spans came up today for an article that has not had text added yet-- content-end placement has been updated to check if a paragraph exists in the text section before attempting to add a 'content-end' span to it.
Fixes [GROW-451](https://artsyproduct.atlassian.net/browse/GROW-451)
> @kanaabe => Content end bug

- package.json
- src/Components/StepMarker/__test__/StepMarker.test.js
- src/Components/StepMarker/index.tsx
- src/Components/StepMarker/types.ts
- src/Components/__stories__/StepMarker.story.tsx
- tslint.json
Adds a new `<StepMarker />` component in support of a new order form as seen here: 
Additionally provides a render-props API like:
```javascript
const steps = [
{
label: "Shipping",
isActive: false,
isComplete: false,
},
{
label: "Payment",
isActive: false,
isComplete: false,
},
{
label: "Review",
isActive: false,
isComplete: false,
},
]
return (
<Container>
<StepMarker steps={steps}>
{({ nextStep, previousStep, gotoStep, stepState }) => {
...
}}
</StepMarker>
<Container>
)
```
**Spec:**
- https://app.zeplin.io/project/5ab94282c124db8d58365b47/screen/5abd3f9478dd7103788ecc99
> @yuki24 => [Component] Add <StepMarker /> 

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Layouts/NewsLayout.tsx
Makes `isHovered` available on `<Article>` to allow activating News articles on mobile. #minor
> @kanaabe => [PATCH news] Make isHovered available on Article

- src/Components/Publishing/Layouts/ArticleLayout.tsx
- src/Components/Publishing/Layouts/Components/Sidebar.tsx
- src/Components/Publishing/Layouts/FeatureLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/Sidebar.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/__stories__/Article.story.tsx
- src/Components/Publishing/__tests__/Article.test.tsx
While looking into adding series/sponsor components to Features, I realized that a lot of non-overlapping logic was housed in the `ArticleLayout` component, making it pretty difficult to follow. This PR separates some of these concerns into separate components, so that we can more easily add to feature and standard articles independently.  No significant changes were made in logic, mostly just moving things around.
- Moves the body of features into the already existing `FeatureLayout`
- Moves the body of standard articles into the already existing `StandardLayout`
- Moves sidebar content into the `Sidebar` component
- Adds more unit tests for each layout and sidebar
The `ArticleLayout` file might better be described as `ArticleWithFullscreenViewer` -- however renaming it meant the changes …
> @kanaabe => Refactor ArticleLayout

- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Series/SeriesAbout.tsx
- src/Components/Publishing/Series/__tests__/SeriesAbout.test.js
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.js.snap
- src/Components/Publishing/Typings.ts
- src/Components/Publishing/__stories__/Series.story.tsx
Follows up on this API change - https://github.com/artsy/positron/pull/1683
- Adds support for `series` object to `SeriesAbout` component
- Adds support for editSubTitle prop in `SeriesAbout` component
- Adds `series` object to `ArticleData` typing
- Adds `series` object to series fixtures
TODO: once the Positron PR is merged and data is backfilled, the old `series_description` field should be removed from Reaction.
> @xtina-starr => SeriesAbout supports custom sub_title and editing sub_title

- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/ArtworkCaption.test.js
- src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.js.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap
Wraps comma delimiter in JSX span when joining artist names. The `react-lines-ellipsis` library was breaking when plain strings were passed to it, all items sent to the library need a DOM wrapper.
Addresses [GROW-515](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-515)
> @kanaabe => Slideshow bug

- src/Components/ErrorBoundary.tsx
- src/Components/Publishing/Sections/Truncator.tsx
The caption component seems to bug out differently based on the caption it gets -- I'm going to make a separate ticket for looking at this more closely. 
For expediencies sake on the Emerging Artists feature/slideshow bug, this PR adds an ErrorBoundary component, and wraps the Truncator component in it to prevent irregular captions from breaking their parent components. 
This is the same bug that is causing articles not to render [referenced in this ticket](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-529)
> @kanaabe => Add ErrorBoundary component

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/index.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Layouts/__tests__/VideoLayout.test.js
Unfortunately prettier makes changes a little hard to see here...
One more PR related to articles showing no data -- https://sentry.io/artsynet/force-staging/issues/532264963/
- Wraps DisplayPanel component in ErrorBoundary
- Wraps DisplayCanvas component in ErrorBoundary
- Adds check if canvas has assets before searching for textmatch in url
> @l2sucess => ErrorBoundaries in Display components

- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.js
Oops! I removed this before thinking we don't need it since we don't want to make a track call, but instead we should keep this and omit it here so we still get a pageview: https://github.com/artsy/force/blob/e69298df7f9f9a321ee75142e7fc7bce3d62b733/src/desktop/assets/analytics.coffee#L17
> @eessex => Adds back read more tracking

- src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.js
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.js.snap
This limits the tracking call to only ever fire once. It was firing twice because there is an onClick handler for both the container and the expand button. We also now pass in the pathname to account for a race condition where the url wasn't changing in time for tracking to pick up the right path.
Addresses: https://artsyproduct.atlassian.net/browse/GROW-552
> @eessex => Track "Expand" button once

- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.js.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap
Adds an error boundary up one level -- captions will still fail, but the truncated section that triggers and error will display as white rather than crashing the page.
> @l2succes => Caption bug

- src/Components/Tooltip.tsx
- src/Components/__stories__/Tooltip.story.tsx
- src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap
I'm planning to reuse this component for the other `?` roll overs in force as requested here: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=39&projectKey=EV&modal=detail&selectedIssue=EV-96 and made possible by @damassi here: https://github.com/artsy/stitch/pull/8
I need to be able to specify if the roll over should be shown left or right of the question mark. So adding those as props here. The current version will work because those props are optional and defaulted to current values.
Considering that is my first PR - all critique is welcome:)
> adding more options to Tooltip component

- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/ToolTip/Artist.tsx
- src/Components/Publishing/ToolTip/Components/ArtistMarketData.tsx
- src/Components/Publishing/ToolTip/__tests__/Artist.test.tsx
- src/Components/Publishing/ToolTip/__tests__/ArtistMarketData.test.js
Adds list of artist genes as fallback if no market data is present.  Displays nothing if no genes or market data are present.
> @l2succes => Artist tooltip can show genes

- src/Components/Tooltip.tsx
- src/Components/__stories__/Tooltip.story.tsx
- src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap
@briansw also approved some font/spacing change here. This should be the roll over for the `?` that we use in force across the board.
> giving tooltip an option to be aligned vertically and horizontally

- package.json
Had to change this today to get our NPM and github versions back in sync, this goes back to the "0.0.0-development" version for semantic-release
> @l2success => Go back to development for npm version number

- src/Components/FollowButton/Button.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/__tests__/Button.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/ToolTip/ArtistToolTip.tsx
- src/Components/Publishing/ToolTip/Components/FollowButton.tsx
- src/Components/Publishing/ToolTip/GeneToolTip.tsx
- src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
- src/Components/Publishing/ToolTip/__tests__/__snapshots__/ToolTip.test.tsx.snap
- src/__generated__/FollowArtistButtonMutation.graphql.ts
- src/__generated__/FollowArtistButton_artist.graphql.ts
Moved our tooltip `FollowButton` into the general /Components directory, and added a wrapper component `FollowArtistButton` that can attach Relay props and handle the follow mutation.
Will add another variation in a separate PR for `FollowGeneButton` once https://github.com/artsy/metaphysics/pull/1035 is merged.
> @kanaabe => Relay Follow button

- src/Assets/Checkmark.tsx
- src/Assets/Colors.tsx
- src/Assets/Fonts.tsx
- src/Components/ArtworkFilter/ForSaleCheckbox.tsx
- src/Components/Checkbox.tsx
- src/Components/__stories__/Input.story.tsx
There are some visual changes in the checkbox design system https://zpl.io/bAvnwlB, and this PR updates the `<Checkbox>` component in reaction to match the style.
The new one is compatible with the existing one but also adds a new `error: boolean` prop:
```html
<Checkbox error>
Agree to Conditions of Sale.
</Checkbox>
<Checkbox error checked>
Agree to Conditions of Sale.
</Checkbox>
```
> Update styling for the checkbox component

- package.json
- src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
The url parsing was causing 500 errors because URL is part of the window object.
> @l2succes => import URL

- src/Components/Artwork/Save.tsx
- src/__generated__/ArtistToolTip_artist.graphql.ts
- src/__generated__/SaveArtworkMutation.graphql.ts
Adds the ability to save artworks within contexts that don't directly support Relay. Depends on https://github.com/artsy/force/pull/2512.
How it works:
- Old force section wants to use new artwork bricks / grid
- Arbitrary data is fed into the grid from the outside as props
- Since there's no outer relay context managing data fetching and population, saves don't work since the typical Relay HOC environment is missing. Successful mutations don't re-inject props
- On the Force side of things we use `<ContextConsumer>` and pass in a user
- This boots up a new Relay environment at runtime that we can piggy back on for a `commitMutation` function call (saves), ignoring that the rest of the component display tree isn't using it directly
- During this update cycle we use `setState` to change the …
> @mzikherman => [Artwork/Save] Support saves in non-relay artwork grids 

- src/Components/Artwork/Details.tsx
Adds the array index to the key for an extra level of specificity. Problem can be seen when the same grid content is rendered in more than one place; since the key is currently pointing to the artwork ID in two places the react reconciler warns.
> @eessex => [Warning] Fix react key issue in Details

- src/Components/Publishing/Display/Canvas/index.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__tests__/DisplayCanvas.test.js
- src/Components/Publishing/Display/__tests__/DisplayPanel.test.js
- src/Components/Publishing/Layouts/StandardLayout.tsx
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-596
One thing to note, for sizmek we assume the `pixel_tracking_code` is a URL here, so we'll have to make sure to let the team know to only include the url and not the script tags.
> @essex => [Display Ad] adds support for pixel tracking in ads

- package.json
Don't clobber stdout when starting app with `concurrently`
> [Toolchain] Add --raw to concurrently

- src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
- src/Components/Publishing/ToolTip/__tests__/LinkWithTooltip.test.js
Addresses missing click event for tooltips.  (Hover background covers in-text link while tooltip is open.)
> @kanaabe => [FIX tooltips] track clicks on tooltip hover background

- src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
- src/Components/Publishing/ToolTip/ToolTip.tsx
- src/Components/Publishing/ToolTip/__tests__/LinkWithTooltip.test.js
Addresses [GROW-669](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-669)
> @kanaabe => Tooltip arrows are centered to link text

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
The dupe impression issue happens in Force on window resizes (i guess re-renders are happening on the parent level there) -- instead lets just use a fixed `renderTime` from the server so the timestamp is guaranteed to only be set once. Then for infinite scroll we can store an array of `renderTimes` that will also be unique and unaffected by any re-renders.
> @l2succes => Use renderTime from server

- package.json
- patches/graphql+0.13.2.patch
- yarn.lock
Bump `graphql@0.12.3` -> `graphql@0.13.2`. 
Fixes:
Related: https://github.com/graphql/graphql-js/pull/1174
> [Dep] Bump / patch graphql@0.13.2

- data/schema.graphql
- data/schema.json
- package.json
- src/Components/ArtistFilter/Artworks.tsx
- src/Components/ArtistFilter/Filter.tsx
- src/Components/ArtistFilter/index.tsx
- src/Components/ArtistFilter/state.ts
- src/Components/__stories__/ArtistFilter.story.tsx
- src/__generated__/ArtistFilterArtworksQuery.graphql.ts
- src/__generated__/ArtworksQuery.graphql.ts
- src/__generated__/Artworks_filtered_artworks.graphql.ts
- src/__generated__/Filter_artist.graphql.ts
- yarn.lock
This has a quick pass at a somewhat functional filter component for the artist page. It uses `unstated` for state management (so no `setState` appears in our components).
There's a fragment container for the filter sidebar and artworks, and the artworks 'browser' is a pagination container. The prev/next windowed pagination appears to be quite tricky...I haven't found any good libs for that yet, so didn't really make too much of a stab at that yet (besides a hacky 'next' button). I'll make some comments inline.
Depends on some local Metaphysics changes as well, will open a PR there.
> [ArtistFilter] Working unstyled component w/ inf scroll

- src/Components/Publishing/Constants.ts
- src/Components/Publishing/__stories__/Display.story.tsx
A recent moment upgrade split off some methods into its own package (`moment-timezone`). 
That package didn't have typescript type definitions beforehand which is why we're catching this now.
> [FIX publishing] moment upgrade bugfix #trivial

- src/Styleguide/Artwork/Gallery.tsx
- src/Styleguide/Artwork/__stories__/Gallery.story.tsx
- yarn.lock
Takes a first pass at fleshing out the desktop version of the artwork gallery component. Would note that there is some similarities between this and the banner.
> First pass at artwork gallery component

- src/Styleguide/Elements/GlobalStyles.tsx
- src/Styleguide/Elements/__stories__/Typography.story.tsx
- src/Styleguide/Utils/InfoContainer.tsx
- src/__stories__/storiesOf.js
Adds a new GlobalStyles component to `/Elements` while we build this out. this will eventually get hoisted up. Also an `<InfoWindow />` component which should be used when using the `addons-info` component (keeps things properly aligned throughout styleguide generated content)
> @zephraph => Add GlobalStyles pattern + some text

- package.json
- src/Components/Publishing/News/NewsSections.tsx
- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/ToolTip/Components/Description.tsx
- src/Components/Truncator.tsx
- src/Styleguide/Components/ReadMore.tsx
- src/Styleguide/Components/__stories__/ReadMore.story.tsx
- yarn.lock
This adds a new `<ReadMore>` component to our set. Note that "read more" is an old, tricky, edge-case filled problem that hasn't yet (to my knowledge) been solved in an performant way that a) addresses browser dimensions; and b) includes SSR, since we need to measure the viewport. @zephraph - have you had to deal with this before? Any thoughts? For now however I think this will be sufficient, but all in all its pretty whatevs as you can see by dragging the viewport width around... 
I'm using the same component that we use elsewhere in publishing (https://www.artsy.net/news), but I had to make a PR to the underlying lib to support custom "read more" links: https://github.com/xiaody/react-lines-ellipsis/pull/19. We're currently pointing at this PR commit in `package.json`, so I'll make sure …
> @zephraph => <ReadMore /> expandable component

- package.json
- src/Styleguide/Elements/Flex.tsx
- src/Styleguide/GlobalStyles/index.tsx
Runs `tsc emit-types` in the `precommit` hook so that we can see if there are any issues with `--declaration` files.
> [PATCH checkDeclarations] Ensure declaration in precommit

- package.json
- yarn.lock
Bumps palette to the latest and temporarily disables `--declaration` emission due to its increased strictness. Since we're having to move fast right now we can refactor and re-introduce after our sprint.
> [PATCH lib] Bump palette@1.2.0; Disable type declarations temporarily

- .stylelintrc
- package.json
- src/Styleguide/Elements/Responsive.tsx
- src/Styleguide/Pages/Artwork/Banner.tsx
- src/__stories__/storiesOf.js
- yarn.lock
This is an experimental responsive api built off of react's context api and the web's [matchMedia](https://caniuse.com/#search=matchmedia) api. 
It provides a framework for describing application level breakpoints, but doesn't enforce specific values. It uses dom events around `matchMedia` so it's not polling to figure out when to update a component. 
**Responsive Context Api**
`<ResponsiveProvider/>` is called near the root of the app. It can take two props. 
1. `initialBreakpoint` -- What breakpoint (if any) to initialize the app to. i.e. `"xs"`, `"sm"`, `"md"`
2. `breakpoints` -- An object with a key of the breakpoint's name and a value of the breakpoint expression. i.e. `{ xs: "(max-width: 767px)" }`
`<ResponsiveProvider/>` has the following state
1. `breakpoints` -- An object with …
> Experimental responsive handler component

- src/Styleguide/Elements/Flex.tsx
- src/Styleguide/Pages/Artwork/Banner.tsx
- src/Styleguide/Pages/Artwork/Gallery.tsx
- src/Styleguide/Pages/Artwork/__stories__/Banner.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Gallery.story.tsx
- src/Styleguide/Utils/Section.tsx
Both the artwork banner and the artwork gallery are now fully responsive. I went through and corrected minor things like font and avatar sizes between the different breakpoints. 
Also, because I got tired of dragging the browser, I created a Section component to wrap the component in. It's an accordion type thing that makes it easier for one story to show multiple variations on a component.
> Banner, Gallery fully responsive

- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/__stories__/ArtistCard.story.tsx
- src/Styleguide/Elements/Avatar.tsx
- src/Styleguide/Elements/__stories__/Avatar.story.tsx
- src/Styleguide/Pages/Artwork/Banner.tsx
- src/Styleguide/Pages/Artwork/Gallery.tsx
Implements the small artist card view as well as wiring it up w/ the responsive component. 
Does a little clean-up/consistence around the avatar. There are only two sizes in the designs currently (100px, 70px) so I added a size prop to that. @damassi it might be worth having a discussion about hoisting that into palette.
> Make artist card responsive

- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/AuctionCard.tsx
- src/Styleguide/Components/__stories__/AuctionCard.story.tsx
- src/Styleguide/Elements/Card.tsx
Adds an implementation of a responsive auction card. 
Refactored the "card" functionality and hoisted it up into elements. It's likely something that we'll see more of and it has some pretty specific shared behavior. 
I'm not necessarily happy with the image implementation of this component. Getting the xs implementation correct was a bit difficult, and I'm not sure approached it in the best way. Would love some feedback.
> Implement Auction Card

- src/Components/Icon.tsx
- src/Styleguide/Components/__stories__/Toggle.story.tsx
- src/Styleguide/Elements/Checkbox.tsx
- src/Styleguide/Elements/Radio.tsx
- src/Styleguide/Elements/__stories__/Input.story.tsx
- typings/styled-system.d.ts
Adds new `<Radio />` and `<Checkbox />` + Stub out `ArtworkFilter` layout.
**Note**: We'll be able to share most stuff between checkbox / radio; for the time being I just duplicated contents. Will sweep back over and consolidate.
> Add <Radio> and <Checkbox> + Artwork Filter 

- src/Components/ArtworkGrid.tsx
- src/Components/Publishing/ReadMore/ReadMoreWrapper.tsx
- src/Components/Publishing/Sections/ImageWrapper.tsx
- src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
- yarn.lock
Reaction is on React 16.4. This is just a bump to types. I'm going to open a similar PR on force, but that'll be actually updating react too.
> Update React Types

- src/Styleguide/Components/Pagination.tsx
- src/Styleguide/Components/ReadMore.tsx
- src/Styleguide/Components/Tabs.tsx
- src/Styleguide/Elements/Card.tsx
- src/Styleguide/Elements/Checkbox.tsx
- src/Styleguide/Elements/Flex.tsx
- src/Styleguide/Elements/Radio.tsx
- tsconfig.json
Adds declaration so we get VSCode warnings about missing interface imports:
> [PATCH tsconfig] Add declaration to config

- package.json
- src/Styleguide/Utils/Responsive.tsx
- yarn.lock
We temporarily added a polyfill of sorts for React's context api while we were on 16.2.0. Now that we're on 16.4.0 it's no longer needed.
> Remove create-react-context dependency

- src/Components/Authentication/Desktop/Components/DesktopHeader.tsx
- src/Components/Authentication/Desktop/Components/DesktopModal.tsx
- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Desktop/ResetPasswordForm.tsx
- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Components/Authentication/TermsOfServiceCheckbox.tsx
- src/Components/Authentication/commonElements.tsx
- src/Components/Buttons/Default.tsx
- src/Components/Input.tsx
- src/Components/Modal/Modal.tsx
- src/Components/Publishing/Email/__tests__/__snapshots__/EmailPanel.test.tsx.snap
- src/Components/Publishing/Email/__tests__/__snapshots__/InstantArticleEmailSignup.test.tsx.snap
- src/Components/Publishing/Nav/__tests__/__snapshots__/SubNav.test.tsx.snap
- src/Components/__stories__/Authentication.story.tsx
This should cover all the latest changes for Desktop Modals in Zeplin. Here are some screenshots...
I think the only visual difference is the button heights (which would mean changing the line height of the `Default` button -- something I'd like to address more carefully later on).
One more thing that needs to be handled further is the `subtitle` -- it seems like we want to use the "Log in to your account" copy for Login screens always, but I need to check with @owendodd if that is indeed the case. If it is, we can include a default for Login screens to avoid having to overwrite in many places. 
Also went ahead and extracted TOS stuff to it's own component so it can be reused for mobile.. `src/Components/Authentication/TermsOfServiceCheckbox.tsx`
Login:
Signup:
Reset Password:
> @l2succes => Match Desktop Modals to latest design

- package.json
- src/Assets/Animations.tsx
- src/Styleguide/Elements/Image.tsx
- tsconfig.json
Type emission errors weren't getting exposed in `yarn type-check` so errors don't get outputted in PR builds.
merge on green
> [Dev] fix `yarn type-check` #trivial

- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Desktop/ModalManager.tsx
- src/Components/Authentication/Desktop/ResetPasswordForm.tsx
- src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
- src/Components/Authentication/commonElements.tsx
Forgot to display server errors in the Login & reset password forms
> @kanaabe => [PATCH auth] adds global errors to login/reset password view

- src/Styleguide/Pages/Artwork/Sidebar/Artists.tsx
- src/Styleguide/Pages/Artwork/Sidebar/ArtworkMetadata.tsx
- src/Styleguide/Pages/Artwork/Sidebar/Classification.tsx
- src/Styleguide/Pages/Artwork/Sidebar/SizeInfo.tsx
- src/Styleguide/Pages/Artwork/Sidebar/TitleInfo.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/ArtworkMetadata.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/Classification.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/SizeInfo.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/TitleInfo.story.tsx
- src/Styleguide/Pages/Artwork/index.js
Another baby step in the sidebar.
Produced this:
Thanks @zephraph for walking me through `styled-system` conventions.
Also not exactly sure level of stories is good there. Quite a lot of data setup but I think it's good to see all the variations. And also I think once we start testing with real data - would be very helpful to produce the extreme case data scenarios and have those displayed in stories
> adding Artwork metadata component

- src/__stories__/storiesOf.js
- yarn.lock
There's a corresponding PR in palette that'll need to be merged for this to be complete. 
Moves the mediaQueries to the theme file so that they can be easily used in the styled-components css.
> Pull mediaQueries from theme file

- package.json
- src/Styleguide/Components/Pagination.tsx
- src/Styleguide/Components/Tabs.tsx
- src/Styleguide/Components/Toggle.tsx
- src/Styleguide/Components/__stories__/Tabs.story.tsx
- src/Styleguide/Elements/Button.tsx
- src/Styleguide/Pages/Artist/Components/CurrentEvent.tsx
- src/Styleguide/Pages/Artist/__stories__/CurrentEvent.story.tsx
- src/Styleguide/Utils/Section.tsx
- yarn.lock
Update sans medium fonts where necessary and replace `<Icon>` with `<Arrow>`. Finishes up mobile pagination: 
Also adds new API around `<Tabs />`:
```jsx
<Tabs labels=['hello', 'how', 'are', 'you']>
{({ activeTab }) => {
return <div>{activeTab.label}</div>
}}
</Tabs>
```
> @zephraph => Update font weights, Mobile pagination, Render props in <Tabs /> component

- src/Styleguide/Components/AuctionCard.tsx
- src/Styleguide/Elements/Box.tsx
- src/Styleguide/Elements/Image.tsx
- src/Styleguide/Elements/__stories__/Image.story.tsx
- src/Styleguide/Sections/__stories__/OtherAuctions.story.tsx
So we had a need to create an image container that could stay square and scale but retain still show the full image inside of it. This is a first implementation of that pattern. It's implemented in the auction card component and in the image story. 
Note that I still need to work with Brian to figure out the details of the mobile version of the auction card so that looks a little.... weird at the moment. Will also need to work through the details of where else this component will need to be used. 
Here's the component rendering in the _Other Auction_ section.
Notice that even though all the images have different sizes, they all fit in a square container.
> Add responsive image component

- src/Styleguide/Components/MarketInsights.tsx
I accidentally left off the key prop when iterating over some elements.
> Add key to iterated elements

- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/Mobile/ResetPasswordForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- yarn.lock
Addresses [GROW-690](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-690)
This uses the same `context.form.status` as the desktop component, assuming the data will be structured in the same way.
Q - there are no tests at the moment for the existing form components, are we planning to add those separately as a work item?
> @kanaabe => Mobile auth server errors

- src/Components/Authentication/Desktop/FormSwitcher.tsx
- src/Components/Authentication/Desktop/ModalManager.tsx
- src/Components/Authentication/Types.ts
- src/Components/Authentication/helpers.ts
Follows up on https://github.com/artsy/force/pull/2620
- Uses `options` object in props for FormSwitcher
- Renames `redirectUrl` to `redirectTo`
- Adds `destination` to  ModalOptions type
> @xtina-starr => Rename redirectUrl to redirectTo

- .babelrc
- .storybook/webpack.config.js
- package.json
- src/Styleguide/Components/ArtworkGridExample.tsx
- src/Styleguide/Components/__stories__/ArtistBio.story.tsx
- src/Styleguide/Components/__stories__/MarketInsight.story.tsx
- src/Styleguide/Components/__stories__/SelectedExhibitions.story.tsx
- src/Styleguide/Pages/Artist/Overview.js
- src/Styleguide/Pages/Artist/index.js
- src/Styleguide/Pages/Artwork/__stories__/ArtistInfo.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/Artists.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/ArtworkMetadata.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/Classification.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/Commercial.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/SizeInfo.story.tsx
- src/Styleguide/Pages/Artwork/__stories__/Sidebar/TitleInfo.story.tsx
- src/Styleguide/Pages/Fixtures/ArtistBio.ts
- src/Styleguide/Pages/Fixtures/Artwork/Sidebar/Artists.ts
- src/Styleguide/Pages/Fixtures/Artwork/Sidebar/ArtworkMetadata.ts
- src/Styleguide/Pages/Fixtures/Artwork/Sidebar/Classification.ts
- src/Styleguide/Pages/Fixtures/Artwork/Sidebar/Commercial.ts
- src/Styleguide/Pages/Fixtures/Artwork/Sidebar/SizeInfo.ts
- src/Styleguide/Pages/Fixtures/Artwork/Sidebar/TitleInfo.ts
- src/Styleguide/Pages/Fixtures/MarketInsights.ts
- src/Styleguide/Pages/Fixtures/SelectedExhibitions.ts
- src/__generated__/ArtworkGridExampleQuery.graphql.ts
- tsconfig.json
- yarn.lock
Was noticing when trying to bring pages into force that it doesn't like anything to come from `__storybooks__` folders. Moved fixtures out (which were referenced in a few places in our code) so that we can start presenting stuff in force. 
cc @oxaudo, @alloy, @zephraph, @mzikherman
> [Styleguide] Move fixtures to /Fixtures directory 

- src/Components/Authentication/commonElements.tsx
This address one of the [QA items](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=GROW-702). Where the forgot password link isn't working on the login static page.
> @kanabe: ensure forgot password link works

- package.json
- yarn.lock
Noticed that our source files were being copied over to `dist` leading to errors in force, so removed `--copy-files` from `yarn compile`. Not sure why that was there to begin with?
Also bumps palette to latest.
> @zephraph => Remove --copy-files from `yarn compile`

- src/Styleguide/Pages/Artist/Routes/CV/CVContents.tsx
- src/Styleguide/Pages/Artist/Routes/CV/index.tsx
- src/Styleguide/Pages/Artist/index.tsx
- src/__generated__/CVArtistQuery.graphql.ts
- src/__generated__/CVContentsQuery.graphql.ts
- src/__generated__/CVContents_artist.graphql.ts
This is v similar to the Shows tab, except here since it's just a textual list our pagination is actually done using `createPaginationContainer` (and no fancy cursor/pagination stuff). As you click 'Load More' (not styled!), you append the next page of that section.
> @damassi => Make CV tab dynamic

- src/Router/PreloadLink.tsx
- src/Styleguide/Components/RouteTabs.tsx
- src/Styleguide/Pages/Artist/ArtistApp.tsx
- src/Styleguide/Pages/Artist/Components/ArtistHeader.tsx
- src/Styleguide/Pages/Artist/Routes/Articles/index.tsx
- src/Styleguide/Pages/Artist/Routes/AuctionResults/index.tsx
- src/Styleguide/Pages/Artist/Routes/CV/CVQuery.ts
- src/Styleguide/Pages/Artist/Routes/CV/CVQueryRenderer.tsx
- src/Styleguide/Pages/Artist/Routes/CV/index.tsx
- src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsQuery.ts
- src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsQueryRenderer.tsx
- src/Styleguide/Pages/Artist/Routes/RelatedArtists/index.tsx
- src/Styleguide/Pages/Artist/Routes/Shows/ShowsQuery.ts
- src/Styleguide/Pages/Artist/Routes/Shows/ShowsQueryRenderer.tsx
- src/Styleguide/Pages/Artist/Routes/Shows/index.tsx
- src/Styleguide/Pages/Artist/__stories__/ArtistHeader.story.tsx
- src/Styleguide/Pages/Artist/routes.tsx
- src/__generated__/ArtistHeader_artist.graphql.ts
- src/__generated__/CVQuery.graphql.ts
- src/__generated__/routesQuery.graphql.ts
- src/__generated__/routes_ArticlesQueryRendererQuery.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
- src/__generated__/routes_ResultsQueryRendererQuery.graphql.ts
Hosited up queries from QueryRenderers's to the router in order to bring us into a proper route-transition system. Notice no transition flash when moving from overview to various tabs. Things are loaded in the background and once complete we move to a new route. During this phase we can tap into an `isLoading` state and, in the future, actual % downloaded (via middleware): 
When user clicks nav item it loads the relay content and then transitions, all wired into overall router state. 
While this can be dried up a bit, this is a fairly representitive example of an app's `routes` file: https://github.com/damassi/reaction/blob/6def3e175bb0541671625aba5f5cee53c791d9ce/src/Styleguide/Pages/Artist/routes.tsx. There's a top query and fragments are passed in corresponding to the routes' tree …
> @alloy => First pass at moving query to route + PreloadLink

- src/Styleguide/Elements/Flex.tsx
- src/Styleguide/Pages/Artwork/Share.tsx
- src/Styleguide/Pages/Artwork/__stories__/Share.story.tsx
- yarn.lock
#closes https://artsyproduct.atlassian.net/browse/RA-2
This doesn’t actually pull the sheet into the static page yet, because I wasn’t quite sure how to do that right now or if this is going to be using another modal implementation. But this is what it currently looks like:
> Artwork share sheet

- src/Styleguide/Elements/Box.tsx
- src/Styleguide/Elements/Image.tsx
- src/Styleguide/Pages/Artist/Routes/Shows/ShowBlockItem.tsx
- src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
This corrects a few issues. 
1.) It changes the show images from a responsive image to a normal image
2.) Removes the max width of the show item. The only thing with a max width should be the grid itself.
3.) Cleans up some minor issues in the `Image` and `Box` elements to make them a bit more consistent across the board. 
4.) Fixes a rouge missing key error
Remaining work is to apply the max width to the grid container.
> Correct artist show's margin on images

- src/Components/Input.tsx
Reworks the Input component to use absolute position, so autofill background color can fill entire box.  Also dropdowns now appear at the bottom edge rather than at text-bottom.
> @l2succes => Input background-color fills container

- src/Components/Publishing/Sections/Text.tsx
- src/Components/Truncator.tsx
Necessary to bump Reaction in Positron:
- In `Text` component, moves require for Relay `LinkWithTooltip` so it is only imported if needed.
- Updates path for imported `ErrorBoundary` in `Truncator`, which was not resolving correctly.
> @damassi => Small updates for Positron

- src/Styleguide/Components/Slider.tsx
- src/Styleguide/Components/__stories__/Slider.story.tsx
- src/Styleguide/Pages/Artist/Components/ArtistHeader.tsx
Allows us to pass in any kind of component to render, following this API:
```jsx
<Slider
data={carousel.images}
render={slide => {
return (
<Image
px={5}
src={slide.resized.url}
width={slide.resized.width}
height={slide.resized.height}
/>
)
}}
/>
```
> @mzikherman => Make <Slider> more flexible by adding render prop

- src/Components/Authentication/__tests__/Desktop/ForgotPasswordForm.test.tsx
- src/Components/Authentication/__tests__/Desktop/LoginForm.test.tsx
- src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
- src/Components/Authentication/__tests__/FormSwitcher.test.tsx
- src/Components/Publishing/Sections/Text.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-756
Was not using the correct import, and was missing the tracking props. Introduced by [this PR](https://github.com/artsy/reaction/pull/898). 
Also kills a few test warnings from the `/Authentication` directory.
> @xtina-starr => Tooltip tracking fix

- src/Styleguide/Components/Tabs.tsx
- src/Styleguide/Components/__stories__/Tabs.story.tsx
Reaction noob in the house!
This is the first example of consuming a design system component in CMS, and then customizing it  here per our needs in the design spec.
I'm open to the possibility that everything here is done wrong 😛 , but this is where I've gotten so far.
Example usage below…
H/t @orta for the suggestion to start documenting the props interfaces, and seeing that flow through to the Volt side in VS Code.
cc @jonallured
> Allow Tabs to have user-specified data and justification 

- src/Components/Modal/Modal.tsx
We should be allowed to update on any changes to the modal such as type changes in `FormSwitcher`
> @eessex => Remove `shouldComponentUpdate` on Modal

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
- src/Apps/Artist/__static__/RelatedArtistsStaticLayout.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Components/FollowButton/Button.tsx
- src/Components/FollowButton/ButtonDeprecated.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/FollowGeneButton.tsx
- src/Components/FollowButton/__tests__/Button.test.tsx
- src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
- src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Router/buildClientApp.tsx
- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/__stories__/ArtistCard.story.tsx
- src/Utils/Responsive.tsx
Updates `FollowArtistButton` with a new prop `useDeprecatedButtonStyle` which, when set to false (by default is true), will point to new button style in `Styleguide/Elements/Button` and accept `buttonProps` (`variant`, `size`). 
**NOTE:** The manner in which this was achieved has introduced some tech-debt around the fork between the old `FollowArtistButton` and the new `Button` style. `FIXME`'s have been added where appropriate.
> @mzikherman => [Artist] Wire up Button to FollowArtistButton

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Components/LoadingArea.tsx
- src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
- src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
- src/Apps/Artist/Routes/Shows/ArtistShows.tsx
- src/Apps/Artist/__static__/RelatedArtistsStaticLayout.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Components/FollowButton/Button.tsx
- src/Components/FollowButton/ButtonDeprecated.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/FollowGeneButton.tsx
- src/Components/FollowButton/__tests__/Button.test.tsx
- src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
- src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Router/PreloadLink.tsx
- src/Router/buildClientApp.tsx
- src/Router/state.tsx
- src/Router/types.ts
- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/__stories__/ArtistCard.story.tsx
- src/Utils/Responsive.tsx
**Branched from https://github.com/artsy/reaction/pull/938**
Abstracts our `<LoadingArea>` component so that it can be used wherever we need a loader to show during a fetch.
> @mzikherman => Add generic loading screens across all loadable content

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
This gets the artwork filters working again, (the way they were), before we ripped out all the query renderers. So this actually filters.
Main to-dos:
- all of these filters should deselect the other ones (probably will handle this just via state, all of the `setState` triggers should _also_ set the others back to the default)
- no need to refetch the sidebar and re-render it as you filter (this will be tricky, probably will have to refactor sidebar/grid)
- hook up sort
- hook up 'loading area' when selecting a filter
> @zephraph  => Get artwork filter in a semi working state again

- src/Components/Authentication/Desktop/ModalManager.tsx
Address the first item in https://artsyproduct.atlassian.net/browse/GROW-737
In this PR we make sure to pass in the GDPR and analytics properties (i.e. signup intent and signup referer) for social auth.
> [PATCH authentication] pass GDPR and analytic properties for social auth

- src/Components/Authentication/Desktop/Components/DesktopModal.tsx
Turned out to be straightforward -- we just need to use `DesktopModal`'s version of `onClose` which includes the tracking call.
> @eessex => Track on background click

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/Styleguide/Elements/Radio.tsx
This allows the radio buttons to be re-rendered properly with correct props. This also fixes some irregularities in filtering, which generally feels better.
However, it's still not perfect- the aggregations/sidebar are being refetched and rerendered, and I'm noticing that when you select a medium/other filter we get 2 duplicate Metaphysics queries being kicked off simultaneously :((
> @zephraph => Only allow one selected radio button at a time for artwork filter

- src/Router/buildClientApp.tsx
- src/Router/buildServerApp.tsx
Looking to remove the admin only guard in Force, was noticing a crash on the page.
It was this setup for users, when logged out this isn't passed in to the Reaction app, and so you wound up with something like:
```
currentUser = {
accessToken: undefined
id: undefined
}
```
vs. what the Relay `createEnvironment` method can work with, which is to pass in something not truthy for `currentUser`.
This needs a Reaction bump -> Force bump, plus relaxing of the admin-only flag, and then we can QA the logged out page in Force on staging.
> @zephraph => Boot artist page for logged out users

- src/Components/Authentication/Desktop/ModalManager.tsx
- src/Components/Authentication/FormSwitcher.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-737 and https://artsyproduct.atlassian.net/browse/GROW-780 by adding support for tracking social auth analytics properties. We are explicitly passing the service provider the user authenticated with as well fixing the 'create account' and 'successfully logged in' events.
> [PATCH authentication] add missing analytics properties for social auth

- .circleci/config.yml
- package.json
- yarn.lock
Removes the current storybook deployment process. This is the first step in falling back to using netlify to manage our storybook deploys.
> Remove storybook deploys from the deploy ci task

- src/Components/FollowButton/FollowArtistButton.tsx
This feels like it might be ok, but also might not?
Basically, the thinking is the follow artist button either performs a follow (+ state change to represent 'followed', etc.), or the unfollow version. When there is no current user in the context/global app state, the `onAuthModal` callback occurs (which is typically a 'mediator'- a Force event bus which triggers the appropriate modals).
So, the follow button wholly handles its behavior when clicked, and shouldn't ever link. So, this makes sure that if the follow button itself is clicked (`handleFollow` called), you don't inadvertently link or do anything else.
What do you think?
> @zephraph => Prevent following a link when tapping a follow button

- .circleci/config.yml
Unfortunately NPM and the node ecosystem has some serious security flaws. It's not exactly an unknown topic, but given yesterday's [incident](https://status.npmjs.org/incidents/dn7c1fgrr7ng) it's important that we think about how we can be more defensive towards our registry usage. 
Yarn and npm allow the [arbitrarily execution of code](https://www.infoq.com/news/2016/03/npm-infection) on install via lifecycle hooks. That means if one of the ~7286 packages in Reaction were to be compromised, we'd have issues. This topic deserves a wider conversation, but for now I want to narrow it to the focus of CI. 
In our CI builds we expose some sensitive tokens via environment variables. Anything running during that process can read those environment variables. I'd like to start exploring using …
> Limit access to tokens on CI

- src/Components/Publishing/Byline/Author.tsx
- src/Components/Publishing/Byline/Byline.tsx
- src/Components/Publishing/Byline/Date.tsx
- yarn.lock
Updating palette to the latest version. Latest release removes `react-primitives` as a dependency that I didn't realize was still being pulled in...
> Update palette to latest version

- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/FollowGeneButton.tsx
- src/Components/FollowButton/Typings.tsx
- src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
- src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/ToolTip/ArtistToolTip.tsx
- src/Components/Publishing/ToolTip/GeneToolTip.tsx
- src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
- src/Components/Publishing/ToolTip/__tests__/GeneToolTip.test.tsx
Related to [GROW-779](https://artsyproduct.atlassian.net/browse/GROW-779)
Updates Tooltip auth analytics to use new camelCase `contextModule` arg. 
Also addresses a minor bug in CanvasContainer for missing url.
Will follow up with point 2 from the Jira ticket on Force after this is merged.
> @xtina-starr => Analytics contextModule for Tooltips

- src/Router/buildServerApp.tsx
This works by making sure this is being passed in flat (not nested inside `system`), to the `AppContainer`.
Corresponding Force PR in a sec
> @alloy => Correctly pass initialBreakpoint prop around

- src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Styleguide/Elements/Select.tsx
Options in the select dropdown are generally supposed to be sentence case. There were a few instances where it wasn't.
> Make select options sentence case

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artist/routes.tsx
- src/Router/buildServerApp.tsx
- src/__generated__/ArtworkFilter_artist.graphql.ts
- src/__generated__/Overview_artist.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
This is part 1 of accepting an initial filter state (from URL).
This uses found-relay `prepareVariables` to pass that in, so `?medium=photography`, etc. will work.
Because there's a query, and many nested fragments, I added `@argumentDefinitions` and `@arguments` to keep passing those variables down. I thought I noticed in the GraphQL docs it read that fragments should be able to access root query variables, and the generated query _doesnt_ seem to keep passing the variables down, however w/o all of these the Relay compiler complains about missing variables.
So for now, I left them.
Part II is to get this to be actually passed in as initial props to the component, so that the UI can accurately reflect this (ie- 'for sale' should be checked, etc.)
> @alloy => Parse filters from URL and pass into overview query

- src/Router/buildServerApp.tsx
Before the larger refactor, this now works! No client-side Metaphysics requests at all (verified via `yarn link/watch`), only once you select a filter, or do something like that, do we fire one off.
> @alloy => Correct prop name to fix rehydration

- src/Components/Artwork/Save.tsx
cc @briansw 
We always show the 'heart' icon if its saved, adjusted the red color, and also switched to the 'x' icon when you hover over and it is saved (possible can fully be accomplished using CSS, but went with state/JS).
> @zephraph => Tweak artwork brick save/hover state

- src/Apps/Artist/ArtistApp.tsx
- src/Components/Publishing/Byline/__tests__/NewsByline.test.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
- src/Components/Publishing/News/__tests__/NewsDateDivider.test.tsx
- src/Components/Publishing/News/__tests__/__snapshots__/NewsDateDivider.test.tsx.snap
- src/Styleguide/Components/ArtistCard.tsx
cc @zephraph 
I was futzing with `text-overflow: ellipsis`, and possible truncation via `props.name.slice(0, MAX_LENGTH)`, when I realized, why not just use `Truncator`?
Seems to be decent!
> @mzikherman => Wrap artist name on artist cards, and errant separator when no RVA

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/Submission/index.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/Payment_order.graphql.ts
- src/__generated__/Review_order.graphql.ts
- src/__generated__/Shipping_order.graphql.ts
- src/__generated__/Submission_order.graphql.ts
- src/__generated__/routes_PaymentQuery.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
- src/__generated__/routes_SubmissionQuery.graphql.ts
This is super basic, but it adds the beginnings of route-handling in reaction. If this looks okay (it's all behind an admin flag anyways) then we can go ahead and release this version and merge the force side.
[Update] This now includes all routes with a button to navigate between them as described in the notion doc.
Rendered in force (storybooks also work, provided you are visiting the route of an order that you have created and you use your access token in the `.env`):
> adds basic routing for orders/shipping

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Styleguide/Components/Tabs.tsx
- src/Styleguide/Elements/Grid.tsx
- yarn.lock
Fixes [DISCO-104](https://artsyproduct.atlassian.net/browse/DISCO-104).
Makes entire page not scrollable. Does this in a few ways. 
1. Makes the grid have `overflow: hidden`. It'll never be scrollable because of that (for better or worse)
2. Updates the tabs to be scrollable on xs. This is the main thing that was forcing the site to be too wide on xs.
> Scrollable tabs, body doesn't scroll

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Layouts/ClassicLayout.tsx
- src/Components/Publishing/Layouts/__tests__/ClassicLayout.test.tsx
- src/Components/Publishing/__stories__/ArticleClassic.story.tsx
Experimental -- adds 'ClassicLayout' component, and adds ability to render 'classic' layout articles from top level article component. 
This is not yet used in production, but will allow us to view classic articles in storybooks.
This also gives us ability to spike on killing Backbone article pages, or using stitch to render this component rather than backbone views where `/mobile/components/article` is still used.
> @l2succes => Article can render classic layouts

- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Sections/StyledText.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Text.test.tsx.snap
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
Noticed while assembling Article type presentation, list styles are missing from Article text. This was also noted by Alex Forbes.
> @l2succes => [FIX publishing] Put back list styles in article text

- src/Apps/Artist/Routes/CV/ShowEntry.tsx
We have some shows appearing in the cv tab w/o partners.
> Dont crash on a partner-less show for CV show display

- src/Assets/Icons/CheckIcon.tsx
- src/Assets/Icons/ChevronIcon.tsx
- src/Styleguide/Components/Stepper.tsx
- src/Styleguide/Components/Tabs.tsx
- src/Styleguide/Components/__stories__/Tabs.Stepper.story.tsx
- src/Styleguide/Components/__stories__/Tabs.story.tsx
[zeplin link]( zpl.io/VxY0J0g)
Sell ticket: https://artsyproduct.atlassian.net/browse/SELL-744
Paired with @zephraph and we decided to reuse `Tabs` component and extend it to accept a *separator* component and a *transformer* function to modify the tab buttons.
> Adds Stepper Component

- src/Styleguide/Components/RouteTabs.tsx
Quick follow up to https://github.com/artsy/reaction/pull/1049.
Here in [this](https://github.com/artsy/reaction/pull/1049/commits/ec6d102fdbed39945c0e2f66b1d1919e0dcef848) commit I removed the `margin-right` tag to use a `separator` to make space between tabs customizable but `RouterTab` uses the styles but does not extend the `Tab` component so as a fix I added the margin back only for `RouterTab`. 
before:
after:
> Fixes RouterTabs margin

- src/Apps/Order/Routes/Shipping/index.tsx
This just selects the first item in the radio group. 
We'll need to get clarification on what the behavior of this should truly be.
> Temporarily hard code shipping default

- src/Styleguide/Elements/Message.tsx
- src/Styleguide/Elements/__stories__/Message.story.tsx
[jira](https://artsyproduct.atlassian.net/browse/PURCHASE-310)
This was originally called 'Messenger' in the designs, but @zephraph @katarinabatina and I discussed renaming it to sound less like an interactive chat thing. I'm proposing 'Message', but definitely open to other suggestions.
> Add Message component

- src/Styleguide/Elements/Radio.tsx
This was causing an issue when rendering the app in force (I'm not exactly sure why it works here and not there, but since we don't pass a `name` into the radio button from the radio group, we were getting a "`name not defined`" error.
> small fix for the radio group field

- package.json
- src/Apps/__stories__/OrderApp.story.tsx
- src/Relay/createEnvironment.ts
- src/Relay/createMockNetworkLayer.ts
- src/Router/StorybooksRouter.tsx
- src/Router/buildClientApp.tsx
- src/Router/types.ts
- typings/json.d.ts
- yarn.lock
This adds the ability to mock up a Relay response in the `StorybookRouter` (and in other places) to be able to get responses without needed to rely on metaphysics staging.
> Add relay mocking to storybook router

- .env.oss
- .storybook/webpack.config.js
- src/Components/Artwork/GridItem.tsx
- typings/sharify.d.ts
Updates the `GridItem` component to support dynamic image sizing via Gemini. 
**Before** (arbitrary browser size): 
**After**:
> @mzikherman => [ArtworkGrid] Add support for dynamic image resizing

- src/Components/Helpers.tsx
This PR removes the `margin-x` from the `<Input>` component. This will make the component slightly more generic and useable in the new Buy Now flow. The only page that will be affected by this change is the search input in the onboarding flow:
In order to find the pages/components that could possible be affected by this, I've looked up the components that depend on the input component, and I found 10 components that depends on it (excluding storybooks):
```
in reaction/src/Components/__stories__/Input.story.tsx
in reaction/src/Components/__stories__/PopoverExamples/DisplayPopoverOnBlurExample.tsx
in reaction/src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
in reaction/src/Components/Authentication/Desktop/LoginForm.tsx
in …
```
> Remove unneeded margin-left/right from the <Input> component

- src/Styleguide/Elements/Select.tsx
In the new Buy Now flow we have a use case for the existing `<LargeSelect>`component. Currently, the height of this component is `46px`, which makes it slightly larger than other existing components used in the form. This PR updates the component so the component of the height will always be `40px`. This component is used in [the auction results page](https://staging.artsy.net/artist/yayoi-kusama/auction-results). In zeplin, the height of the select box is also `40px`, so this will actually make the height consistent across design mockups and the actual implementation.
Here are some screenshots of what it's going to look like after this PR. As you can see, it makes the height consistent and there will be no significant visual issue in the auction results page.
> Update the height of the <LargeSelect> component to always be 40px

- src/Components/Artwork/GridItem.tsx
Caps column image widths to 400 and 300, depending on breakpoint size. 
```js
switch (match) {
case "xs":
case "sm":
case "md":
return 400
case "lg":
case "xl":
default:
return 300
}
```
> [ArtworkGrid] Limit image size by breakpoint

- src/Styleguide/Elements/Radio.tsx
- src/Styleguide/Elements/RadioGroup.tsx
I noticed that the Radio Group component had an extra hover state in the design system zeplin project, which I hadn't seen when working on this component originally. https://zpl.io/VqE4M6G
I also noticed that the `cursor: pointer` rule was applied for the label component even when the radio group was disabled, so I fixed that too.
> fix radio group disabled and hover states

- src/Apps/Order/Components/Summary.tsx
- src/Apps/Order/Components/__tests__/Summary.test.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/__generated__/Payment_order.graphql.ts
- src/__generated__/Review_order.graphql.ts
- src/__generated__/Shipping_order.graphql.ts
- src/__generated__/Summary_order.graphql.ts
- src/__generated__/routes_PaymentQuery.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
Will follow up with the force PR.
This goes over what we talked about in the knowledge share last week. The main changes are:
- Get the `mediator` from the global app state instead of from being passed in as props
- Add a fetch for the artwork id on the `Summary` component. We can expand this later to include more artwork data.
> [PATCH orderPage] Reference mediator from appstate + send artwork ID with inquiry modal

- src/Components/Publishing/Header/Layouts/Components/FeatureFullscreenHeader.tsx
- yarn.lock
Forgot to include SuperArticles in this check for whether a nav exists. Is a styled components prop so not tested.
> @xtina-starr => SuperArticle header margins

- package.json
- yarn.lock
Removes my fork now that https://github.com/dragma/styled-bootstrap-grid/pull/17 was merged. 
I'd still like to rewrite this lib, perhaps from scratch, though we should keep the same API since its pretty idiomatic across various grid libs. I'm thinking something that we could seamlessly replace that's perhaps built on top of our new Responsive component. 
cc @zephraph
> [PATCH lib] Remove ref to Styled Grid fork

- .storybook/webpack.config.js
- data/schema.graphql
- data/schema.json
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Artist/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Components/Artsy.tsx
- src/Router/buildClientApp.tsx
- src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
- src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
- src/__generated__/ArtworkFilter_artist.graphql.ts
- src/__generated__/Overview_artist.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
- typings/gravity.d.ts
controlled by lab feature
For storybook purposes, you can set `USER_LAB_FEATURES=Lab1,Lab2,Lab3` a comma separate string of lab features to turn on (since we're not fetching current user).
When coming from Force, `req.user` will have a `lab_features` array.
> @damassi => Add new set of commercial filtering options on artist page filter

- src/Components/Animation/SlideTransition.tsx
- src/Components/MinimalCtaBanner.tsx
- src/Components/Publishing/Article.tsx
- src/Components/Publishing/__tests__/Article.test.tsx
- src/Components/__stories__/CtaBanner.story.tsx
This addresses https://artsyproduct.atlassian.net/browse/GROW-705.
- It implements the CTA on the article page.
- Updates the MinimalCtaBanner to include animations per the spec.
- Allows the user to dismiss the CTA Banner .
> @eessex: Mobile signup cta for articles

- src/Assets/Icons/ChevronIcon.tsx
@jonallured found out that unlike [css transform rotation](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate) svg [transform](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#Rotate) doesn't work with `deg`. This PR fixes that.
> Removes 'deg' from chevron transform rotation

- src/Apps/Order/Components/BuyNowStepper.tsx
- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/Submission/index.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/__generated__/Submission_order.graphql.ts
- src/__generated__/routes_SubmissionQuery.graphql.ts
This updates the payoff screen to have the correct layout.
Pretty standard except I did end up moving (after talking to @zephraph) the stepper component into its own `BuyNowStepper` which is rendered only on the pages that have a stepper (meaning, not on the payoff page).
Open to other ideas about naming, etc.!
> @zephraph => Update Payoff page to have layout

- src/Styleguide/Elements/Separator.tsx
We have a case where we need to override the `width` in the new `<BorderedRadioGroup>`. This PR removes the hard-coded `width: 100%` and make it more flexible.
> Add the ability to override the width for <Separator>

- package.json
- src/Apps/Artist/ArtistApp.tsx
- yarn.lock
The recently viewed component currently shows up at the _bottom_ of the artist paged for an authenticated user. Being that it's behind a login, it has _no_ value for SEO. Currently, every image in the component is configured as the large and there's no lazy loading happening. 
This PR is a quick and dirty fix that adds a new js dependency to the bundle but has significant impact on the above-the-fold performance of the artist page for an authenticated user. 
This isn't the only work that needs to happen. The images need to be properly sized and preferably individually lazy loaded. For now, this'll do. 
If one of us gets time, we can write our own lazy loading component and remove the js dependency. Until now, it gives us a capability that we need and I think is worth the cost.
This is a …
> Lazy-load recently viewed

- src/Apps/Artist/Routes/Overview/index.tsx
- src/__generated__/Overview_artist.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
When rationalizing our 3 ES calls for `/related/shows` (once for carousel, once for exhib highlights, and once for current event), there was a fourth...the carousel again!
Realizing that we have it in https://github.com/artsy/reaction/blob/2c856446c4356c910daf958fe1366a2a98deefe2/src/Apps/Artist/ArtistApp.tsx#L93 , so don't need it in the Overview query.
> @damassi => Dont request the header fragment in the overview query

- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
Fixes a link that was going to `/summary` instead of `/submission` and adds back the "continue" button on the shipping page.
> Fixes /submission link and adds back continue button #superminor

- src/Apps/Order/Components/Summary.tsx
- src/Apps/Order/Components/__tests__/__snapshots__/Summary.test.tsx.snap
I noticed that the Helper component was butting up against the bottom of the screen in xs. [The designs](https://zpl.io/bzWDR54) specify a space of 2. I didn't feel it was necessary to add a check for `xs` since space underneath the sidebar on desktop won't affect layout, but let me know.
| Before  | After  |
|---|---|
| <img width="503" alt="screen shot 2018-08-14 at 10 36 49 am" src="https://user-images.githubusercontent.com/498212/44098423-33bc11bc-9fae-11e8-8a70-ed6e445fc320.png">  | <img width="484" alt="screen shot 2018-08-14 at 10 36 52 am" src="https://user-images.githubusercontent.com/498212/44098433-38dd0160-9fae-11e8-9ed1-a7347383c033.png">  |
> Adds bottom space to Helper component #trivial

- src/Styleguide/Components/Collapse.tsx
- src/Styleguide/Components/__stories__/Collapse.story.tsx
- src/Styleguide/Components/__tests__/Collapse.test.tsx
This adds a new `<Collapse>` component we are going to use in the new Buy Now flow:
> [FEATURE components] Add <Collapse> component

- src/Apps/Order/Routes/Shipping/index.tsx
- src/Styleguide/Elements/Radio.tsx
- src/Styleguide/Elements/RadioGroup.tsx
- src/Styleguide/Elements/__stories__/RadioGroup.story.tsx
- src/Styleguide/Elements/__tests__/RadioGroup.test.tsx
This PR basically changes three things:
* Update the existing `<RadioGroup>` component to not render borders
* Break down the monolith `<RadioGroup>` interface into a composable API
* Add a new `<BorderedRadioGroup>` component
At this point, we don't use the `<RadioGroup>` component outside of Reaction, so this should be ok to change the interface. We may be able to use this component on the new Artist page (e.g. https://www.artsy.net/artist/andy-warhol) in the future.
> Add a new <BorderedRadioGroup> component

- src/Components/ErrorPage.tsx
- src/Components/__stories__/ErrorPage.story.tsx
- src/Components/__tests__/ErrorPage.test.tsx
- src/Components/__tests__/__snapshots__/ErrorPage.test.tsx.snap
This PR adds a basic error page to reaction.
Some notes:
- It's just the error page _content_ right now (since it seems that the header is still rendered right now from force? I wasn't totally sure about this. If we need to render a custom header here, hopefully we can do something minimal with just the logo)
- This doesn't hook up the page rendering to anything, it's just the component which accepts `code`, `message`, and `detail`.
- I copied this verbatim from force, but tried to alter the styles within reason to match our design system
> @damassi => Adds basic error page

- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts
This pull request adds the first mutation to the new order components (🎉) and address [PURCHASE-329](https://artsyproduct.atlassian.net/browse/PURCHASE-329). I've left a few TODOs with associated tickets to make sure they don't get dropped; the most immediate is moving the address entry fields into their own component so we can re-use it on the billing address screen. We'll almost certainly want to use Formik, as @damassi suggested, so I've included that in the note as well.
Since Relay will update its store with the new order state, we can tie into using that in our routing logic once this PR is merged. /cc @zephraph.
Here it is in action:
> Shipping form commits mutation

- src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
- src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
Addresses
https://artsyproduct.atlassian.net/browse/GROW-851
https://artsyproduct.atlassian.net/browse/GROW-841
I think this may have originated from our switch to typed analytics -- we now use the `react-tracking` library rather than a deprecated version that was in utils.  The tracking event was expecting an additional arg of state, which caused an error when clicking the video link.
> @l2succes => Display video bugs

- src/Apps/Order/Components/__stories__/ItemReview.story.tsx
- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/Apps/Order/Components/__stories__/TransactionSummary.story.tsx
There was an inconsistency in some of the story names that caused two order sections to show up. This PR cleans that up.
> Make order story names consistent

- data/schema.graphql
- data/schema.json
- src/Styleguide/Components/WorksForYou/WorksForYouContents.tsx
- src/Styleguide/Components/WorksForYou/index.tsx
- src/Styleguide/Components/__stories__/WorksForYou.story.tsx
- src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts
- src/__generated__/WorksForYouContentsPaginationQuery.graphql.ts
- src/__generated__/WorksForYouContents_viewer.graphql.ts
- src/__generated__/WorksForYouQuery.graphql.ts
Looks like:
This definitely needs an update layout-wise (just plain `<div>` and `<hr />`) for now. However, it's all functional w/ inf scroll working properly! There's a small MP PR with this as well.
Question- I wasn't sure if/how we would use the new router/app state for this, so I just kept it as a component with the Artsy context. Since we'll be keeping the Force-side server stuff and sidebar, etc. I was thinking we would just render this as `<ContextProvider><WorksForYou></ContextProvider>` in Force (similar to the storybook setup here). Does that seem reasonable to you? We can always pair or refactor that as well (Artsy context -> more modern approach).
> [WorksForYou] Create WorksForYou component to replace main grid

- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
@erikdstock and I are working on the payment step so we'd like to pull this out of shipping so that we can reuse it for billing address. The types aren't finalized, but we can update that in another PR.
> Abstract out the shipping form fields into an address form component

- data/schema.graphql
- data/schema.json
- src/Apps/Order/Components/ShippingAndPaymentDetails.tsx
- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/Apps/Order/Routes/Submission/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/Apps/__test__/Fixtures/Order.ts
- src/Styleguide/Elements/icons/CreditCardIcon.tsx
- src/__generated__/ShippingAndPaymentDetails_order.graphql.ts
- src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts
- src/__generated__/Submission_order.graphql.ts
- src/__generated__/routes_SubmissionQuery.graphql.ts
I bumped metaphysics to the latest version and synced the schema because I needed the `Order#shippingName` field introduced in https://github.com/artsy/metaphysics/pull/1227
I also added a missing state for the Shipping details component. The 'pick up' state:
We should get Brian to do a copy review on Monday.
> hook up ShippingAndPaymentDetails

- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
This PR moves the user to the payment step after the mutation for setting the payment has returned. I made the button show a spinner while the mutation was happening as well, and left a note about error-handling that we can tackle later on.
I ran into an interesting problem with Enzyme and found this comment really helpful: https://github.com/airbnb/enzyme/issues/1153#issuecomment-394951184 I have a better understanding of how Enzyme works with the React component lifecycle now.
Fixes [PURCHASE-383](
https://artsyproduct.atlassian.net/browse/PURCHASE-383).
> Navigates to payment after shipment step

- src/Apps/Order/Components/ItemReview.tsx
- src/Apps/Order/Components/TermsOfServiceCheckbox.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Components/Forms/OrderForm/Forms/ShippingForm.tsx
- src/__generated__/Review_order.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
This starts to add components to the "review" page.
No major changes except the addition of a `TermsOfServiceCheckbox` which is different enough from the current one that we use in the auth modal that I thought it deserved its own.
I left the `Step Summary Item` placeholders there until https://artsyproduct.atlassian.net/browse/PURCHASE-384 is done!
> adds v1 of review page with dynamic components

- src/Styleguide/Components/WorksForYou/WorksForYouArtist.tsx
- src/Styleguide/Components/WorksForYou/index.tsx
- src/Styleguide/Components/__stories__/WorksForYou.story.tsx
- src/__generated__/WorksForYouArtistPaginationQuery.graphql.ts
- src/__generated__/WorksForYouArtist_viewer.graphql.ts
- src/__generated__/WorksForYouQuery.graphql.ts
Corresponding Force PR coming, but this lets us use this component by passing in a specific artist too. Last thing is to add the for sale passing in, and then this is _basically_ done.
Locally in Force this is functional, though there's still some work to go in and make sure everything is neat and tidy (errant spinners, deselecting an artist, etc)
> @damassi => Add an artist mode to works for you component

- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.tsx.snap
Pair sesh with @l2succes 
Checks if asset url is a video before calling gemini, should return original url for video and resized url for image. 
Fixes:
https://artsyproduct.atlassian.net/browse/GROW-859
> @xtina-starr => [FIX display] do not resize video assets

- src/Apps/Order/Components/TransactionSummary.tsx
- src/Apps/Order/Components/__stories__/TransactionSummary.story.tsx
Fixes [PURCHASE-372](
https://artsyproduct.atlassian.net/browse/PURCHASE-372), which had the following requirements:
- Artist name should be displayed, truncated if longer than one line with …
- Title should be italicized, year should not be, whole title should be truncated if longer than one line with …
- Seller/partner should be displayed, truncated if longer than one line with …
I [clarified with Brian on Slack](https://artsy.slack.com/archives/C9YNS4X32/p1534788907000100) about how truncation works. Here's the what it looks like:
| Mobile  | Desktop |
|---|---|
|  <img width="309" alt="screen shot 2018-08-20 at 3 01 48 pm" src="https://user-images.githubusercontent.com/498212/44361116-e9d08880-a48a-11e8-9bdc-e1563c0b8f79.png"> | <img width="306" alt="screen shot 2018-08-20 at 3 02 03 …
> Summary formatting issues

- tslint.json
- tslint/README.md
- tslint/noImportUnMockedRule.js
We've talked about doing these before, but me and @ansor4 wasted a bunch of time on something we can easily make a linter rule for - so this fixes #1172 and now we have at least one custom lint rule, so the next ones are much easier to write.
Making the rules is simple, and I added docs so it's easy for the next person.
🎉
> Adds a tslint rule for unmocking when doing tests with tracking

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Styleguide/Components/RecentlyViewed.tsx
A couple little fixes for @briansw: 
- Column size on /overview artwork filter (25 / 75 vs 30 / 70%)
- Thumbnail size on Recently Viewed (100 -> 180)
> [PATCH artist] Design layout updates

- src/Apps/Order/Routes/Review/index.tsx
- src/__generated__/Review_order.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
This is minor but finishes up: https://artsyproduct.atlassian.net/browse/PURCHASE-386
I made a follow-up ticket to replace the region code (i.e. "US") with the actual country name ("United States"), but it seems like that should wait until we've finished updating the schema. (That's here: https://artsyproduct.atlassian.net/browse/PURCHASE-421)
> Replace shipping review with actual component

- package.json
Fixes an issue with `yarn type-check` which was causing our force/reaction link setup to fail unexpectedly.
> [Dev] fixes compiler error issues

- docs/getting_started.md
I've gone to Reaction's `docs/` directory enough times looking for these that I'm just going to point to them from there.
> Points to Force instructions on linking with Reaction

- README.md
The installation instructions were missing a step in the ReadME informing devs that they should install the Watchman library before starting the server to prevent an error from being thrown.
> Update reaction read me

- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-408
This PR removes the hard-coded "US" and expciltly sets it to the state. This may be a naive solution, but for now this is a working solution that reduces confusing behaviour. In the future we may want to make this UX slightly better by automatically detecting the country with IP.
> Fixes an issue where shipping country does not default to US

- src/Apps/WorksForYou/WorksForYouArtist.tsx
- src/Apps/WorksForYou/WorksForYouContents.tsx
- src/Apps/WorksForYou/index.tsx
I think this does it:
- protect the marketing banner behind the BNMO lab
- make avatar images clickable to the artist page
- enable tracking, which then 'just works' on the save button
> @cavvia => Make WFY avatar a link, and enable analytics tracking

- src/Apps/Order/routes.tsx
This addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-418. For now, when a user tries to access the blank `/order2/:id` route, we'll redirect them to the `/shipping` subroute.
I wasn't sure how to test the redirect, perhaps https://artsyproduct.atlassian.net/browse/PURCHASE-370 will unblock that?
I've also added another ticket: https://artsyproduct.atlassian.net/browse/PURCHASE-428 so we remember to follow-up on additional behavior that we may want around submitted orders.
> Redirect to /order2/:id/shipping if you access /order2/:id

- src/Apps/Order/Components/ShippingAndPaymentReview.tsx
- src/Apps/Order/Components/ShippingAndPaymentSummary.tsx
- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/Apps/__test__/Fixtures/Order.ts
- src/__generated__/ShippingAndPaymentReview_order.graphql.ts
- src/__generated__/ShippingAndPaymentSummary_order.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
As discussed in [this thread](
https://github.com/artsy/reaction/pull/1193#discussion_r213549330), we've hit kind of a weird edge of Relay/GraphQL schemas/tsc where we can only compare `__typename` to the names of types we spread over, even though the `Pickup` type has no useful information. That leads to two interesting tradeoffs:
- include the spread and transfer extra data from Metaphysics, but get type-checking working as expected, or
- not include it and only compare to `"Ship"` (or `"%other"`, which is a sentinel for non-spread-over value types). 
#1193 chose the first option, but this PR changes it to the second one. If you see weird type errors, let me know.
> Removes extraneous fragment spreading

- src/Apps/Order/Components/ShippingAddress.tsx
- src/Apps/Order/Components/ShippingAndPaymentReview.tsx
- src/Apps/Order/Components/ShippingAndPaymentSummary.tsx
- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/Apps/Order/Components/__tests__/ShippingAddress.test.tsx
- src/Apps/__test__/Fixtures/Order.ts
- src/Styleguide/Components/CountrySelect.tsx
- src/__generated__/ShippingAndPaymentReview_order.graphql.ts
- src/__generated__/ShippingAndPaymentSummary_order.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-421
This PR adds a new constant called `COUNTRY_CODE_TO_COUNTRY_NAME` , which is a country-code-to-full-name map based on the same data used in the `<CountrySelect>` component. The name sounds ok but a bit too long, so open to suggestions.
I also noticed that in the storybook we had `US` in the `region` property, which has been fixed as part of this PR.
> User sees a full country name in shipping details views

- src/Artsy/Analytics/Schema/Interaction.ts
- src/Artsy/Analytics/Schema/Values.ts
- src/Artsy/Analytics/Schema/index.ts
- src/Components/MinimalCtaBanner.tsx
- src/Components/Publishing/Article.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-880.
Adds analytics events:
- Auth impression when the cta banner is displayed
- Click event for when the user dismiss the cta banner
- Passes analytic properties to auth sign up modal
> @l2succes: adds analytics for mobile auth cta

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Banner/Banner.tsx
- src/Components/Publishing/Banner/__tests__/Banner.test.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/__tests__/Article.test.tsx
This fixes an issue with the entire Article component and its children re-rendering entirely on scroll due to calling `setState` inside of a `handleScroll` high up in the render tree.
This also caused our ad impression tracking to fire at every scroll changes
Related: https://artsyproduct.atlassian.net/browse/GROW-872
> Fixes Articles re-rendering on scroll

- src/Components/Onboarding/Steps/Genes/index.tsx
This enables the Next button on the categories step in onboarding so users can complete it.
Related: https://artsyproduct.atlassian.net/browse/GROW-603
> [FIX onboarding] always enable categories step button

- data/schema.graphql
- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Components/ShippingAddress.tsx
- src/Apps/Order/Components/ShippingAndPaymentReview.tsx
- src/Apps/Order/Components/ShippingAndPaymentSummary.tsx
- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Apps/__test__/Fixtures/Order.ts
- src/Components/Forms/support/Field.tsx
- src/__generated__/ShippingAndPaymentReview_order.graphql.ts
- src/__generated__/ShippingAndPaymentSummary_order.graphql.ts
- src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
- bumped metaphysics to include changes from artsy/metaphysics#1265
- Added phone number field to AddressForm, while refactoring it to not have individual change handlers for each field, as discussed in https://github.com/artsy/reaction/pull/1152#pullrequestreview-147370701 and https://github.com/artsy/reaction/pull/1186#discussion_r213277528
https://artsyproduct.atlassian.net/browse/PURCHASE-422
https://artsyproduct.atlassian.net/browse/PURCHASE-397
force screenshots of phone number appearing in:
- review address
- summary address
- shipping address form
> Add phone number, refactor address form

- src/Apps/Order/Components/CreditCardInput.tsx
- src/Apps/Order/Components/__tests__/CreditCardInput.test.tsx
- src/Apps/Order/Routes/Payment/index.tsx
Right now users don't see an error message for the `<CreditCardInput>` as soon as they type, but this PR updates that so users will get immediate feedback. This also moves the message from the `<PaymentRoute>` to the `<CreditCardInput>` so it'll help implement the same, consistent behaviour across the site.
> User sees an error message for credit card input immediately

- src/Apps/Collect/CollectApp.tsx
- src/Apps/Collect/Components/ArtworkGrid/CollectArtworkGrid.tsx
- src/Apps/Collect/FilterState.tsx
- src/Apps/Collect/routes.tsx
- src/__generated__/CollectApp_viewer.graphql.ts
- src/__generated__/routes_CollectAppQuery.graphql.ts
This PR 
- implements pretty URLs for medium filter
- changes default sort to prioritize merchandisable artworks
- fixes some filtering bugs
Closes:
- https://artsyproduct.atlassian.net/browse/GROW-896
- https://artsyproduct.atlassian.net/browse/GROW-871
>  [Collect] add support for collect/<medium> urls

- src/Components/Modal/ErrorModal.tsx
- src/Components/Modal/Modal.tsx
- src/Components/Modal/ModalError.tsx
- src/Components/Modal/ModalWrapper.tsx
- src/Components/Modal/__tests__/ErrorModal.test.tsx
- src/Components/Modal/__tests__/Modal.test.tsx
- src/Components/Modal/__tests__/ModalWrapper.test.tsx
- src/Components/__stories__/Modal.story.tsx
This PR:
- Extracts the "meaty" bits of our existing `Modal` component into a `ModalWrapper` so that it can be re-used for a `ModalError` (named to keep it consistent, but open to change).
- Updates `Modal` to consume the new `ModalWrapper`
- Adds a new `ModalError` which looks like:
I spent a while faffing around trying to extend the existing `Modal` component for this error case, but there was a lot that was coupled in there. The error modal is much simpler and has different styling rules, but it still needs to handle the animations, blur behavior, etc.
If people find that this abstraction doesn't make sense, I am happy to update!
Also... if anyone knows why the `color` isn't being picked up on my `Sans` elements, please let me know. It's coming through in the css as:
which suggests …
> Refactors existing modal and adds new error modal

- src/Components/Publishing/Article.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-887. We lost the auth modal trigger when we removed the old [editorial sign up view](https://github.com/artsy/force/commit/31130073685a018bce2b5e90fce8c40f865284b7). This restores the auth modal by moving the modal trigger to the `componentDidMount` function of the `<Article>` component.
> [FIX authentication] restore auth signup modal on articles

- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/index.ts
- src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- yarn.lock
This addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-438
This uses our generic error modal (in this case not piping in any specific titles or messages).
> Update shipping mutation to show error modal when an error occurs

- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Components/Authentication/Types.ts
- src/Components/Publishing/Article.tsx
While QA'ing https://artsyproduct.atlassian.net/browse/GROW-887 and https://artsyproduct.atlassian.net/browse/GROW-684 I noticed that we should be dynamically passing in the `contextModule` for the steps in the mobile auth modal flow and that the desktop auth mobile displays on mobile when it shouldn't. This PR address those items.
> Auth mobile analytics qa

- src/Assets/Icons/ChevronIcon.tsx
Safari doesn't like `transform` attribute for `<svg>` element. Checkout [this](https://artsy-reaction.netlify.com/?selectedKind=Styleguide%2FComponents&selectedStory=Tabs%20%28Stepper%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=PeterPanen%2Fstorybook-addon-scissors%2Fpanel) **in safari** and you can see chevron icons are facing backward.
Instead added css `transform` tag to a container:
> Fixes safari icon direction

- src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.tsx.snap
- src/Utils/resizer.ts
Addresses https://artsyproduct.atlassian.net/browse/GROW-889
Fixes a bug where gemini resize was called with empty strings, causing long timeouts and impacting article load performance.
> [FIX display] don't call gemini with empty urls

- src/Apps/WorksForYou/index.tsx
Noticed the full page was re-rendering in Force on filter change so wanted to move the Marketing header up and out of the QueryRenderer, thereby avoiding the refetch flash.
> [PATCH wfy] Move MarketingBanner up

- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/createCreditCard.ts
- src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderPayment.ts
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Components/Modal/ErrorModal.tsx
- src/Components/Modal/__tests__/ErrorModal.test.tsx
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-404
This is pretty much the same as https://github.com/artsy/reaction/pull/1240 but for the `<PaymentStep>`.
> User sees error modal if there is an error submitting the mutation to submit the payment form

- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-436
I initially added `disabled` prop to the inputs but replaced them with a `pointer-events: none;` on the parent.
> [FEATURE BNMO] Disable input fields (including radio buttons) when the UpdateShipping mutation is underway

- README.md
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/Artsy/Router/Components/ClientRouter.tsx
- src/Artsy/Router/Components/StorybooksRouter.tsx
- src/Artsy/Router/__stories__/Router.story.tsx
- src/Artsy/Router/client.ts
- src/Artsy/Router/index.ts
- src/Artsy/Router/server.ts
- src/Artsy/index.tsx
- src/Styleguide/Components/__stories__/SelectedExhibitions.story.tsx
- src/Styleguide/Components/__stories__/Tabs.Router.story.tsx
- src/Styleguide/Components/__tests__/RouteTabs.test.tsx
- tslint/relayOperationGenericsRule.js
* `Artsy/Router/index` still exists, but it no longer exports server or client specific code, that has to be imported from either `Artsy/Router/client` or `Artsy/Router/server`.
* Renames `StorybooksRouter` to `ClientRouter`.
* Fixes custom Relay linter rule and makes lint green again.
> [BREAKING] Don’t mix build server and client app

- src/Apps/Collect/Components/ArtworkGrid/CollectArtworkGrid.tsx
- src/Apps/Collect/Components/ArtworkGrid/index.tsx
- src/Styleguide/Components/Pagination.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-909.
- This makes sure the hover state of the pagination link isn't a fixed width and covers the larger numbers.
- This adds the `scrollTo` prop to make sure that page links scroll back tot he top of the page.
> [FIX collect] ensure paginated links scrolls user back to the top of the page

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/__stories__/OrderApp.story.tsx
We were using lower-case state names [when they should be upper-case](https://github.com/artsy/exchange/blob/190b297fd3dc72c7433230523f12e970deb0a46e/app/graphql/types/order_state_enum.rb#L2-L7)...
> Always use upcase state names

- src/Apps/Order/OrderApp.tsx
- src/Apps/__stories__/OrderApp.story.tsx
@yuki24 reported the below error, which seems to be due to to the transition hook firing on the server. It's not needed there, so I moved it to only be registered on the client. 
Also, I noticed an error on pages where the user didn't have access to the order (i.e. it 401s) are throwing an error about `order.state` not being defined. I updated the logic to check for the existence of `order` before accessing `state`. 
```
(apps/order2) Error:  TypeError: protocol.transition is not a function
at /Users/yuki/GitHub/force/node_modules/farce/lib/createHistoryMiddleware.js:35:49
at /Users/yuki/GitHub/force/node_modules/farce/lib/createLocationMiddleware.js:26:20
at /Users/yuki/GitHub/force/node_modules/farce/lib/createTransitionHookMiddleware.js:154:22
at …
```
> Only use transition hook on client, check for order before accessing

- src/Apps/Order/Components/CreditCardInput.tsx
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-472
This is literally a one-line change.
> [FEATURE BNMO] Credit card form should not ask for zip code

- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-442
It's unlikely that we would _ever_ get these errors in this current iteration, since we have strong client-side validation on this form. However, if we change those requirements (especially around things like zip code), that could change. Additionally, this adds the ability to customize the header and detail message for the error modal on the shipping page, which we'll need for subsequent tickets.
> Show specific shipping error if there is an invalid address

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Artsy/SystemContext.tsx
This PR, for [PURCHASE-464](
https://artsyproduct.atlassian.net/browse/PURCHASE-464), follows up on [this Force PR](https://github.com/artsy/force/pull/2931) to consume the new `isEigen` context variable and emit a `<meta>` tag that will disable zoom in Eigen's web view (but not for mobile users more generally). I moved some stuff around in the `OrderApp` tests, let me know what you think.
> Adds viewport meta tag for Eigen to disable zoom

- src/Components/Artwork/Details.tsx
Thanks, didn't notice that warning during storybooks.
B/c one of the lines in this section _already_ linked to the artwork page, I didn't remove it when making the whole area be linkable. This removes it.
> @damassi => [ArtworkBrick] BugFix: Remove all a tags in tombstone

- src/Artsy/Router/Components/ClientRouter.tsx
- src/Artsy/Router/__stories__/Router.story.tsx
- src/__stories__/storiesOf.js
Fixes an issue where the default user isn't retrieved from `.env` file if not explicitly passed to context. Noticed this when clicking the follow button in the artist storybooks app.
> [FIX ClientRouter] Fix .env user auth

- data/schema.graphql
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/__generated__/Payment_order.graphql.ts
- src/__generated__/routes_PaymentQuery.graphql.ts
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-495
* Updates the `<PaymentRoute>` component to pull in the billing address in the order if any
* I looked into pre-populating the credit card input as well, but it's prohibited by Stripe
> [FEATURE BNMO] Payment form should pre-populate with available details when returning to the payment route

- .storybook/webpack.config.js
- src/Apps/__stories__/Apps.story.tsx
- src/Artsy/Relay/createEnvironment.ts
- typings/sharify.d.ts
Adds better logging in development around MP errors: 
This should help surface common issues related to expired authTokens, 404s, etc. 
Also, turned off relay logging in prod.
> [FEATURE middleware] Add errorMiddleware

- src/Apps/Order/Routes/Status/index.tsx
This PR updates the cancellation message to be generic. This has evolved in a recent conversation between @briansw, @joanna20, and myself from where it was at previously. We had previously detailed a cancellation reason, but given the ambiguity and unknowns around the cases when an artwork is rejected by a seller, we've (at least temporarily) adopted this messaging. 
**NEW**
**OLD**
> Updates the cancel copy to be more generic

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/routes.tsx
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-351
We discussed showing the header or not with @briansw @zephraph and @sweir27 and decided this is ok for now.
> User sees appropriate error page when trying to access an order they don't have access to

- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/createCreditCard.ts
- src/Apps/Order/Routes/__fixtures__/MutationResults/index.ts
- src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Apps/__test__/Fixtures/Order.ts
- src/Components/Modal/ErrorModal.tsx
- src/__generated__/ReviewSubmitOrderMutation.graphql.ts
- src/__generated__/Review_order.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-443
We want to handle the following errors (aside from just showing the generic modal):
- `insufficient_inventory`--> show a unique message + link user back to the artist page if they hit "continue"
- `artwork_version_mismatch` --> show a unique message + link user back to the artwork page if they hit "continue"
- `failed_charge_authorize` --> show a unique message (including what we get back from Stripe)
> Handle known errors while submitting an order

- src/Apps/Artist/routes.tsx
Pretty simple, this just redirects all unhandled tabs back to the main artist page. That should fix the cases of `/works`, `/bleh`, etc.
There's a corresponding Force PR that switches the order of app mounting, so deep-linked standalone auction lot pages at `/artist/:artistID/auction-result/:id` still work, and don't get caught here.
> @damassi => Handle all unknown tabs by redirecting to main artist page URL

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/routes.tsx
- src/__generated__/routes_OrderQuery.graphql.ts
- src/__generated__/routes_PaymentQuery.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
We needed to alias the queries or rename all of the `props` fields in [this change](https://github.com/artsy/reaction/pull/1337)-- this seemed like the easiest way.
> [FIX bnmoFlow] Alias all instances of ecommerceOrder

- data/schema.graphql
- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Apps/__test__/Fixtures/Order.ts
- src/Styleguide/Components/CountrySelect.tsx
- src/__generated__/Shipping_order.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
Implements [PURCHASE-477](https://artsyproduct.atlassian.net/browse/PURCHASE-477) by disabling the country field on the Shipping panel when a work is continental US shipping only. A non-US billing address can still be selected.
> [FEATURE BNMO] disable country field when work is continental shipping only

- src/Apps/Order/Routes/Shipping/index.tsx
Displays an error modal using the `unsupported_shipping_location` error validation introduced in https://github.com/artsy/exchange/pull/204.
> [FEATURE BNMO] Display error modal on unsupported shipping location

- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/__generated__/routes_OrderQuery.graphql.ts
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-453
Thanks to @damassi for figuring this out with me! 
This PR moves all routing/redirect logic (that is meant to happen _before_ render) into the root of the `OrderApp`. At first I tried to stick this logic into the sub-routes (i.e. `Payment/index`) but kept getting issues with trying to reference client-side methods on the server. (While doing this I noticed that the existing redirect implementation was also broken for the same reason).
One way to fix that ☝️ is to repeat logic in the `render()` function and in `componentDidMount` in order to redirect (and not render anything server-side), but only in the cases we specify.
This becomes unwieldy. Turns out `found` has redirect handling, and sticking it in the root …
> [FIX BNMOrouting] Extracts redirects for order app into routes config

- src/Apps/Order/Components/TransactionSummary.tsx
- src/__generated__/StatusQuery.graphql.ts
- src/__generated__/TransactionSummary_order.graphql.ts
- src/__generated__/routes_PaymentQuery.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
Implements [PURCHASE-494](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&modal=detail&selectedIssue=PURCHASE-494).
Metaphysics currently defaults to using 0 decimals of precision in fields that use the `amount` money formatting helper: https://github.com/artsy/metaphysics/blob/master/src/schema/fields/money.js#L24-L27. This causes cents values to be rounded to the nearest whole dollar in the order flow. By specifying an argument for `precision`, we can format prices without rounding.
An order with a whole number cost:
An order with a cost that includes cents:
> [FIX BNMO] Specify money field precision to avoid rounding

- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Components/Modal/Modal.tsx
- src/Components/Modal/ModalWrapper.tsx
- src/Components/Modal/__tests__/ErrorModal.test.tsx
- src/Components/Modal/__tests__/ModalWrapper.test.tsx
Implements [PURCHASE-471](https://github.com/artsy/reaction/compare/master...javamonn:purchase-471-responsive-error-modal?expand=1).
Adds an `isResponsive` prop to `ModalWrapper`  to implement the responsive modal styling seen [here](https://app.zeplin.io/project/5ab94282c124db8d58365b47/screen/5b6dca0f88ebbc1cd4521d7c). Right now, the `ErrorModal` is only user of this styling. The alternate way to approach this would've been to add something like a `ResponsiveModalWrapper`, but the behavior appears to be the same outside a few lines of style differences.
As seen in storybook:
> [FEATURE BNMO] Add responsive prop and styling to ModalWrapper

- package.json
- src/Styleguide/Components/Collapse.tsx
- src/Styleguide/Components/__tests__/Collapse.test.tsx
- yarn.lock
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-501
The issue is that the `<Collapse>` component always holds a fixed height and it doesn't change the height when the elements inside of it stretches vertically. I just replaced the implementation with `react-spring` that doesn't have this issue.
> Fixed an issue where the height of <Collapse> is always fixed

- src/Apps/Order/Components/CreditCardInput.tsx
Sets a hardcoded height on the container wrapping `react-stripe-elements/CardElement` so that the size of the input is consistent before and after Stripe is able to initialize. The result:
Hardcoding the height is non-ideal and could present an issue if height of the inner iframe that Stripe mounts changes, but I couldn't find an alternate way to accomplish keeping a consistent input height. Some other approaches we could consider:
- The [demo linked](https://jsfiddle.net/attystripe/xux7qzch/) the [react-stripe-elements](https://github.com/stripe/react-stripe-elements#demo) repo takes the approach of _completely_ hiding the input prior to Stripe initializing. I think this would require us still assuming some height in order to leave empty space for the input in the payment form, or hiding …
> [FIX BNMO] set height of CreditCardInput to prevent size changes

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Collect/Components/ArtworkGrid/index.tsx
- src/Apps/WorksForYou/index.tsx
- src/Components/Artwork/Details.tsx
- src/Components/Artwork/GridItem.tsx
- src/Components/Artwork/Metadata.tsx
You correctly brought up that we should probably have kept the lab feature, and just added the feature flag, rather than replacing the lab feature completely with the feature flag.
In this way, we can still launch/turn off the feature via config change, yet the lab feature continues to allow certain users (admins) to test it out even if while it's turned off.
> @sweir27 => Bring back BNMO lab feature to enable features

- tslint/README.md
The [docs](https://palantir.github.io/tslint/develop/custom-rules/) we link to all talk about writing `.ts` files, though our docs recommended not to do that. I asked @orta and he described how these files are outside our `src` directory, which is the root of our TypeScript, so there's a high cost to including them in our pipeline compared to the value we already get with `@ts-check`. I'd never heard of it so I added a link to the docs where it would've answered my question.
> Adds note about `@ts-check`

- src/Apps/Order/Components/CreditCardInput.tsx
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-493
The reason for WIP is that the vertical text alignment looks a bit off from the center of the input. Some of you are probably already aware of the fact that this is because of the typeface, but we may be able to apply an easy fix.
> [FIX BNMO] Card number text should be 16px and expand the clickable area for the credit card input

- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__stories__/OrderApp.story.tsx
This is the first step for updating our routing to be `/orders/:orderID`. 
Once this version of reaction is deployed, Force will need to be updated to handle the new route!
> [FIX BNMO] Allow order2 and orders as valid paths

- src/Apps/Order/routes.tsx
- yarn.lock
We actually need this on every route because they all depend on data potentially updated and that can be changed by navigating backwards and forwards.
Also, I'm pretty sure I updated yarn yesterday-- is this change to `yarn.lock` in the right direction or the wrong one?
> [FIX BNMO] Refetch data on every path within the orders app

- src/Apps/Artwork/Components/__stories__/ArtworkDetails.story.tsx
- src/Styleguide/Components/ReadMore.tsx
https://artsyproduct.atlassian.net/browse/DISCO-397
Fixes an issue where line breaks were being stripped out in the Read More component.
> [Artist] Fix line breaks

- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Apps/__stories__/OrderApp.story.tsx
This PR fixes [PURCHASE-564](https://artsyproduct.atlassian.net/browse/PURCHASE-564), a bug reported from QA where a user was asked to enter a postal code despite having selected a non-US/Canada country. This was a frontend validation issue, Exchange was fine.
It looks like we were running the validations for everything, but only keeping the component of the address that had changed. This would work if a change in one part of the address form wouldn't affect the validation of another part, but changing your country changes your postal code validation, 
The simplest fix, to me, is to just grab all the validation errors. @erikdstock I'm keen to get your input if that will be okay. I also added test coverage for this front-end validation.
> Updates addressErrors when any component of address is changed

- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/__generated__/routes_OrderQuery.graphql.ts
This fixes [PURCHASE-516](https://artsyproduct.atlassian.net/browse/PURCHASE-516). If we don't have an artwork ID, we fall back to redirecting to artsy.net.
> Fixes redirect loop on abandoned orders

- src/Apps/Order/Components/ShippingAndPaymentSummary.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/Components/Modal/ErrorModal.tsx
- src/Components/Modal/Modal.tsx
- src/Components/Modal/ModalWrapper.tsx
- src/Components/Modal/__tests__/ErrorModal.test.tsx
- src/Components/__stories__/ErrorModal.story.tsx
- src/Styleguide/Components/CountrySelect.tsx
This PR is for [PURCHASE-561](https://artsyproduct.atlassian.net/browse/PURCHASE-561) and addresses the following QA items:
- Corrects case of "RWANDA"
- Several copy changes
- Changing email address for Order app errors to orders@artsy.net (in a way that makes ErrorModal still usable from non-Orders components)
- Makes the error modal narrow (changes `isWide` prop of `ModalContainer` to an enum called `width`, let me know what you think)
- Adds some stories to make testing these changes easier
I've kept these in individual commits so that we can cherry-pick some if one change is blocking or something.
> Buy Now QA Fixes

- src/Styleguide/Components/ReadMore.tsx
Noticed that line breaks were being eaten by force's CSS reset. Not sure how to solve in a wider way ATM, but we need to keep this in mind when stitching components.
> [FIX padding] Accomodate environment padding

- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/DevTools/renderRelayTree.tsx
This PR updates our billing address form in the following ways:
- Never populate it from existing data (since we're always clearing your payment details, it was weird to pre-populate your billing info).
- Clicking hide/show billing address clears the form
> [FIX bnmo] Updates to Billing Address Behavior

- src/Apps/__stories__/OrderApp.story.tsx
We're currently unable to open the storybooks for the order app since they now require `mediator` to be present in the context. 
Note that the `ShippingAndPaymentSummary` storybook is still broken, but for a different reason that will take some more investigation.
> Adds mediator to OrderApp storybooks

- src/Apps/Collect/CollectionApp.tsx
- src/Apps/Collect/Components/Collection/Header/index.tsx
Addresses: https://artsyproduct.atlassian.net/browse/GROW-944
- Change from 4 to 6 lines before truncating
- Move “read more” inline
- Update widths at various breakpoints
- Use `resize` for image size
ToDo:
> Responsive collection header

- src/Apps/Collect/Components/Collection/Header/index.tsx
This mainly fixes the header image for mobile but also addresses some other minor QA items.
- Increases header title and subtitle font size in mobile.
- Replaces category placeholder.
- Removes the padding on the side of description.
Regarding the extra margin at the top, it looks like that is something that would need to be addressed in for as that where it is being set. I noticed that the same also happens on the artist page.
> [PATCH collection] fixes mobile image and other minor QA items

- package.json
- src/Artsy/Router/buildClientApp.tsx
- yarn.lock
https://artsyproduct.atlassian.net/browse/PURCHASE-572
This PR fixes a general problem with our `found` (router) setup. It was not preserving browser behaviour regarding scroll position when navigating between pages. Luckily someone made this `found-scroll` package which is a drop-in decorator providing the correct behaviour. I had a little play around in the order app and it seems to work perfectly.
I tried to calculate what impact it has on bundle size, but webpack keeps running out of memory when I try to build force right now. I'm guessing it's < 1kb judging from the look of the code but could be wrong.
> Use scroll management for found

- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/__generated__/ShippingAndPaymentDetailsQuery.graphql.ts
This PR fixes the `ShippingAndPaymentSummary` story and switches to new `<></>` fragment syntax.
The problem with the storybook was that the query we were feeding in was requesting (and getting back from the mock network layer) an `Order` labelled `ecommerceOrder`, not `order` [as we do in the actual query](https://github.com/artsy/reaction/blob/dc6c47f1927c2f961aa73b09dbff5c24c2ffc64d/src/Apps/Order/routes.tsx#L42).
> Storybook fix

- .storybook/webpack.config.js
Noticed that Netlify was showing progressbar output which was clouding the status window.
> [PATCH webpack] Omit progress bar on CI

- src/Apps/Collect/Components/Collection/Header/index.tsx
Addresses: https://artsyproduct.atlassian.net/browse/GROW-964 
Wraps the title in an `h1` tag.
> add h1 tag to title for SEO

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarMetadata.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarSizeInfo.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarTitleInfo.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarMetadata.story.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkSidebarLive.story.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkDetails.test.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar.test.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarArtists.test.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarMetadata.test.tsx
- src/Apps/__test__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
- src/__generated__/ArtworkSidebarMetadata_Test_Query.graphql.ts
- src/__generated__/ArtworkSidebarMetadata_artwork.graphql.ts
- src/__generated__/ArtworkSidebarQuery.graphql.ts
- src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
- src/__generated__/ArtworkSidebar_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
This brings the metadata to almost production state. We are still missing the explanation modal for Classification sting, but otherwise this should be in a ready to put on artwork page state(just for this component:).
I'll work on classification modal next.
> adding specs for sidebar metadata

- src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
- src/DevTools/MockRelayRenderer.tsx
- src/DevTools/__test__/MockRelayRenderer.test.tsx
- src/DevTools/__test__/MockRelayRendererFixtures.tsx
- src/__generated__/MockRelayRendererFixturesBadQuery.graphql.ts
This PR is a followup from #1438. When we discussed my change in the Purchase team knowledge share the next day, we agreed that better surfacing of errors in storybooks would be helpful for debugging (as there are apparently other broken storybooks in Reaction).
So my solution was to turn `MockRelayRenderer` into an [error boundary](https://reactjs.org/docs/error-boundaries.html), put any caught errors into the component's `state`, and use that state to indicate something went wrong. It looks like `renderWithLoadProgress` _was_ catching errors (as marked in the comments) but was returning `null` instead, leading to blank screens:
A blank screen is probably what we want, for users, so I didn't want to change the behaviour of `renderWithLoadProgress`.
If developers opened the console and …
> MockQueryRenderer improvements

- src/DevTools/__test__/renderUntil.test.tsx
- src/DevTools/enzyme+renderUntil.d.ts
- src/DevTools/renderRelayTree.tsx
- src/DevTools/renderUntil.tsx
- src/setup_jest.ts
In response to https://github.com/artsy/reaction/pull/1462#issuecomment-433348087, with this change it will be possible to easily render updates after e.g. interacting with a React tree and triggering a Relay refetch/pagination.
This can also easily be PR’ed upstream to enzyme.
> [DevTools] make renderUntil an enzyme API extension.

- src/Components/Publishing/Sections/Artwork.tsx
- yarn.lock
Removes unnecessary reference to state from publishing Artwork class declaration.
> [TRIVIAL] Remove null state from Artwork 

- src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkDetails.test.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar.test.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarArtists.test.tsx
This removes some async tests where they are not necessary and moving the get a wrapper call to beforeAll function.
Also adding couple of minot checks. I think both ArtworkDetails and ArtworkArtist details are tested to bare minimum. Going forward we should try to add more comprehensive tests once we discover bugs and that I should be sufficient while moving forward.
Let me know what you think here.
> refactoring some tests

- src/Apps/Collect/__tests__/routes.test.tsx
- src/Apps/Collect/routes.tsx
While I was working on https://artsyproduct.atlassian.net/browse/GROW-976 I noticed that the `sort` options is ignored entirely on Collect and Collection. This PR updates the `prepareVariables` function to respect it properly so the page the page results will be consistent after a page refresh.
> Fix a bug where the sort option is always set to "-decayed_merch" on both Collect and Collection

- src/Components/Authentication/Types.ts
It seems like the `afterSignUpAction` field is never a string, but an object with a required `action` and optional `objectId` and `kind`. This PR makes it more explicit and be type-safe.
> Use a more structured type for ModalOptions.afterSignUpAction

- src/Components/Publishing/Banner/Banner.tsx
finishes https://artsyproduct.atlassian.net/browse/GROW-858
This PR updates the CTA banner on the mobile Article view so that we will be able to automatically opt-in mobile users who sign up from an editorial page to the daily newsletter.
I'm sure this looks like a very weird PR, but the `editorialSignup` action will be added to Force by https://github.com/artsy/force/pull/3049 and Reaction depends on it. It is safe to add an `action`, and once https://github.com/artsy/force/pull/3049 is merged the `checkForAfterSignUpAction` function will automatically start making a call to Sailthru.
> Automatically opt-in mobile users who sign up from an editorial page to the daily newsletter

- src/Components/Publishing/Constants.ts
In staging and development I've observed weird behavior where newly signed-up users are redirected to production. We should be able to switch to `APP_URL` environment variable safely and fall back to `www.artsy.net` so the existing behaviour is preserved.
> Use APP_URL to allow Force to override the APP_URL

- package.json
- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Artsy/Router/Components/Boot.tsx
- src/Artsy/Router/Components/__test__/Boot.test.tsx
- src/Components/ErrorBoundary.tsx
- src/Utils/__test__/errors.test.ts
- src/Utils/__test__/logger.test.ts
- src/Utils/errors.tsx
- src/Utils/logger.ts
- typings/sharify.d.ts
- yarn.lock
~WIP to rebuild commit history -- otherwise, code changes are ready for review.~
Addresses [PURCHASE-570](https://artsyproduct.atlassian.net/browse/PURCHASE-570).
We want to be able to factor in client-side errors into our analysis of the buy now checkout funnel.
Add Sentry to Reaction and capture errors for all apps since currently we don't capture any errors.
- Added `@sentry/browser` package
- Added new `logger` that allows us to add custom behavior before calling out normal `console.*` statements. For `logger.error`, we send an error to Sentry before calling `console.error`.
- Wrapped `Boot` in `ErrorBoundary` component to catch errors
- Replaced `console.error` statements in Order app with `logger.error`
> Add Sentry to Reaction

- src/Apps/Order/Components/TransactionSummary.tsx
This PR makes a few modifications to the `<TransactionSummary>` component, mostly visual. It includes:
1. A refactor of the `<Entry>` helper component into two helper components - `<Entry>` and `<SecondaryEntry>`. `<Entry>` previously took a prop named `secondary`, which toggled the look of the entry item slightly. It was two very separate code paths, though, and refactoring to two separate components made making changes to the entry items more intuitive.
2. Larger font sizes for primary entry items at breakpoints larger than "xs". This was accomplished with the `<Responsive>` component, because I didn't see a way in [palette.artsy.net](https://palette.artsy.net/#/docs-typography) to send an array of font sizes to typographical components. I did raise that question in the #design-system …
> [PATCH makeOffer] Transaction Summary UI tweaks

- src/Apps/Collect/CollectApp.tsx
- src/Apps/Collect/CollectMediumMetadata.ts
- src/Apps/Collect/CollectionApp.tsx
- src/Apps/Collect/__tests__/CollectMediumMetadata.test.ts
- src/Apps/Collect/__tests__/CollectionApp.test.tsx
Addresses:
https://artsyproduct.atlassian.net/browse/GROW-904
https://artsyproduct.atlassian.net/browse/GROW-931
This adds the metadata description for both `/collect` and `/collection/:slug`. It also ensure the collect page uses a custom metadata title.
ToDo:
> add metadata description for collect and collection page

- src/Components/Payment/PaymentForm.tsx
#minor adjustment (we can always revisit later) to scroll to the top of the page after you enter a credit card.
> Scroll payment form to top after entering credit card

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/__tests__/Article.test.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-772
This adds `<PixelTracker>` when there is a sponsor pixel tracking code present. This is depends on an update to the article query in Force: https://github.com/artsy/force/pull/3069
> [FEATURE publishing] add pixel tracking code on articles for sponsors

- package.json
It's more annoying than useful. Working on CI speed upgrades in force w/ @izakp  and this prevents being able to test upgrading force to node v10.
> 🙈🚫 🚒 (delete engines)

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPageviews.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarPageviews.story.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarPageviews.test.tsx
We decided to not show anything when the artwork has < 10 pageviews.
> @iskounen => [ArtworkSidebar] Update Pageviews CTA to not support few pageviews

- src/Apps/Collect/CollectionApp.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/Styleguide/Components/ReadMore.tsx
finishes https://artsyproduct.atlassian.net/browse/GROW-983
This PR adds `{ "context_module": "CollectionDescription", "type": "button" }` to the existing analytics payload. Here is the actual payload sent to Segment:
> Add analytics tracking for "read more" in Collection pages

- src/Components/Publishing/Display/Canvas/CanvasText.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
fixes https://artsyproduct.atlassian.net/browse/GROW-998
It seems that the logo image is already centered and the `width: 100%` could be removed. There may be some historical reasons why this is there, but this seems to be working without it on all the responsive sizes we have support for, with logo images in a different aspect ratio.
> [FIX display] Fixes an issue where display logo is not centered properly

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
This commit updates the sidebar for the Responsive Artwork Page (RAP) to prefer an artwork's associated partner information to the older `collecting_institution` field. We would eventually like to deprecate and remove the `collecting_institution` field altogether.
The `collecting_institution` field on an artwork is a string representation of the institution loaning the work to another partner.
Quoting from a colleague here:
> Basically, at a number of different points we’ve wanted to clean up our institutional artwork records that predate the `Permanent Collection` / `On Loan` statuses, but it’s proved really tough because `collecting_institution` has historically been used for things that are  _both_ on loan _and_ permanent collection.
Additional Context:
- …
> DISCO-513: Prefer partner info to `collecting_institution` field in artwork sidebar

- src/Artsy/Router/buildServerApp.tsx
Noticed these typings were incorrect when converting some force code to TypeScript.
> [FIX types] Fix router types

- src/Apps/Artist/Routes/Overview/index.tsx
Phew, thought there was yet another bug related to the responsive work that we only found out after deploying, but appears to be just a stray curly brace 😅
> [Artist/Overview] Remove stray curly brace.

- src/Apps/Artwork/Components/ImageCarousel.tsx
Currently:
With 100% height set:
Looks like container has a height but the `NavigationButtonContainer` does not.  The icon button intended to be centered in 100% height.
> fix centering of image right/left buttons

- src/Components/Publishing/EditorialFeature/EditorialFeature.tsx
- src/Components/Publishing/EditorialFeature/__tests__/EditorialFeature.test.tsx
Per @xtina-starr's suggestion, renames keys for EOY articles to describe article content/match component names.
> [TRIVIAL] rename EOY keys

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Components/ErrorBoundary.tsx
- src/Components/Payment/PaymentForm.tsx
- src/Utils/__tests__/errors.test.ts
- src/Utils/__tests__/logger.test.ts
- src/Utils/errors.tsx
- src/Utils/logger.ts
This is a somewhat in-the-weeds PR, so please let me know if something doesn't make sense!
In https://github.com/artsy/reaction/pull/1479, I created a [method to send errors to Sentry](https://github.com/artsy/reaction/blob/30b0755443b48f9c64b8000ce2312d5de54548d0/src/Utils/errors.tsx#L18) and added that method to the newly-created [`logger.error` method](https://github.com/artsy/reaction/blob/30b0755443b48f9c64b8000ce2312d5de54548d0/src/Utils/logger.ts#L16). The idea was that if you're logging an error you likely want to send that error to an error-capturing service anyway.
The issue is that the code doesn't capture mutation errors from Metaphysics, and we need it to do that. On mutation error, we receive an object that represents an error and contains multiple relevant fields for the …
> [PATCH logging] Add `ErrorWithMetadata` class and use when logging errors with metadata

- src/Apps/Collections/Components/CollectionsGrid.tsx
Addresses: https://artsyproduct.atlassian.net/browse/GROW-1014
This fixes the spacing issue on the collections page. 
Before:
After:
Thanks for the help @l2succes
> [PATCH collections] fixes spacing on the collections page

- src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
- src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
Clicking make offer, creates the offer order but then goes to a page with error saying we missing amount.
When we create an Offer Order we don't have `myLastOffer` yet since collector hasn't set their offer yet and from the `TransactionDetailItem` component we try to access `order.myLastOffer.amount` to populate transaction summary section.
Add conditional code to check if we have `myLastOffer` and if we don't just show `-`.
> Fix null myLastOffer

- .circleci/config.yml
I've been testing out the queuing behavior from #1615 and I noticed it wasn't queueing as I expected. I expected it to queue if any job from the last build was still running, but it wasn't doing that. Looks like it's due to this config option missing.
> Ensure build queues if any previous job still running

- .gitignore
- .npmignore
- package.json
I noticed that we were shipping a lot of unnecessary stuff with reaction. 
New package size: 1.9MB, 2322 files
Old package size: 2.0MB, 2717 files
Maybe not a _huge_ improvement, but it's better.
> Update npmignore to include only necessary client artifacts

- src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
- src/Apps/Order/Components/__stories__/TransactionDetailsSummaryItem.story.tsx
- src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
- src/Apps/Order/Routes/Status/index.tsx
- src/Apps/__tests__/Fixtures/Order.ts
- src/__generated__/StatusQuery.graphql.ts
- src/__generated__/TransactionDetailsSummaryItemOfferProperties.graphql.ts
- src/__generated__/TransactionDetailsSummaryItemStoryQuery.graphql.ts
- src/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
- src/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
- src/__generated__/routes_OfferQuery.graphql.ts
- src/__generated__/routes_PaymentQuery.graphql.ts
- src/__generated__/routes_RespondQuery.graphql.ts
- src/__generated__/routes_ReviewQuery.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-678
On the `/status` page, we want the `TransactionDetailsSummaryItem` to represent the latest *submitted* offer, which is present on the `lastOffer` field. Meanwhile, on all previous steps of the initial offer flow, we want it to represent the buyer's last *pending* offer, which is available on the `myLastOffer` field.
During the counteroffer flow, we again want it to represent the latest *submitted* offer (https://zpl.io/a8N4opQ), except on the `/review` screen if the user makes a counteroffer (https://zpl.io/bPm8JX6).
So here I added a prop to the `TransactionDetailsSummaryItem` component called `useLastSubmittedOffer` which causes it to use `lastOffer`. By default it uses `myLastOffer`.
The main effect of this is that it can show …
> Parameterize copy in TransactionDetailsSummaryItem

- apollo.config.js
- src/Artsy/Router/Components/PreloadLink.tsx
This relies on our fork of the extension (`Artsy.vscode-apollo`) until there’s movement on: https://github.com/apollographql/apollo-tooling/pull/800
> [vscode] Update vscode-apollo config to ignore unwanted validation

- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/__generated__/routes_OrderQuery.graphql.ts
this PR was originally just adding some extra redirect logic to what we already had, but that code was getting messy and hard to reason about so (╯°□°）╯︵ ┻━┻ 
Here's something declarative and tree-structured which is supposed to be a lot easier to read and modify, if more verbose.
@ashfurrow @williardx When adding new routes for the `/review/decline` and `/review/accept` pages make sure to add redirect logic for them in here too. You can add new children to the existing entry for  `review`, just like you will in `routes.tsx`. Let me know if anything could be clearer! :pray:
*also achieved the original goal of this PR by adding redirect logic for the `respond` page and as a bonus the `offer` page.* https://artsyproduct.atlassian.net/browse/PURCHASE-677 :tada:
> Refactor redirect logic

- src/Apps/__stories__/OrderApp.story.tsx
In #1629 we added a redirect rule for the /respond page but forgot to account for it in the story mock data 🤦‍♀️
> fix /respond story

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
- src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.story.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.test.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.ts
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ArtworkSidebarAuctionPartnerInfo_Test_Query.graphql.ts
- src/__generated__/ArtworkSidebarAuctionPartnerInfo_artwork.graphql.ts
- src/__generated__/ArtworkSidebarQuery.graphql.ts
- src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
This still needs a mediator event in Force for auction Buyer's premium.
Or it might be worth to just rebuild this modal here in reaction. But seems like eigen is also still using Force html page for that, so I figured - I'll go with a mediator call for now.
@cavvia - also adding analytics call for the 'buyer's premium' click. Figured it's not going to hurt to track it.
>  Add auction partner name, estimate and premium

- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextArtist.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextPartnerShow.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/index.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
- src/__generated__/ArtworkContextArtistQuery.graphql.ts
- src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
- src/__generated__/ArtworkContextArtist_artwork.graphql.ts
- src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
- src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
- src/__generated__/ArtworkContextPartnerShow_artwork.graphql.ts
- src/__generated__/PartnerArtworkGrid_artwork.graphql.ts
Noticing the 'default' case (aka artist context), as well as the 'show' case, should include a grid for the partner's works. 
You added that ability to MP in https://github.com/artsy/metaphysics/pull/1405, so this just uses it. Super easy to drop in to the `OtherWorks` structure, and the separator/join even made it so I didn't need to bother with adding a divider, or anything like that.
> @damassi => Add a partner artwork grid to the artwork page for some contexts

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarSizeInfo.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarMetadata.test.tsx
Render radio buttons for each edition set option within the Responsive Artwork Page sidebar for works that are enrolled in either of both of the Buy Now / Make Offer e-commerce programs.
> Track edition set option selection in RAP sidebar for BNMO

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Follow-up to #1651 
Don't show the radio buttons at all if the artwork is not enrolled in either Buy Now or Make Offer programs.
> Don't show radio buttons if artwork is not e-commerce enabled

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/__tests__/Offer.test.tsx
- src/__generated__/OfferMutation.graphql.ts
- src/__generated__/Offer_order.graphql.ts
- src/__generated__/routes_OfferQuery.graphql.ts
Quick bug fix for https://artsyproduct.atlassian.net/browse/PURCHASE-702
Problem: the list price underneath the input on the offer page disappeared
Cause: `itemsTotal` was originally being used as the list price, but we refactored at some point and it became the offer price for offer orders (once an offer has been made, hence it was resolving to `null` on the initial `/offer` page) and `totalListPrice` became the list price field.
Solution: switch to using `totalListPrice`.
> Use totalListPrice for list price in /offer

- src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
- src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
- src/Apps/Order/Components/__stories__/TransactionDetailsSummaryItem.story.tsx
- src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/__generated__/Counter_order.graphql.ts
- src/__generated__/routes_CounterQuery.graphql.ts
- src/__generated__/routes_OrderQuery.graphql.ts
Hello friends!
This implements the initial UI for the counter offer review page. It also does a couple of other things:
- Expands on the the redirect logic refactor from a few days ago to allow decoupling the route hierarchy from the redirect rules hierarchy. e.g. this route and a few others fall under `/review/*` but should not share the same logic as the main `/review` page.
- Builds the `TransactionDetailsSummary` on top of `StepSummaryItem` rather than `StackableBorderBox`, to allow us to specify the `title` and `onChange` props that make this happen:  
- Also updates the `TransactionDetailsSummaryItem` to allow us to specify which 'context' price appears below the main price. e.g. 
vs
Desktop
Mobile
We are still working on the mutation side of things so that will come in a follow-up …
> /review/counter page UI

- src/Apps/Artwork/Components/ArtworkDetails/index.tsx
- src/Apps/Collect/Components/Collection/Header/index.tsx
- src/Styleguide/Components/ReadMore.tsx
Fixes a few issue we were seeing on the artwork page
- Double tracking on read more
- Tabs not firing
- Also updates Collect read more button to track from call-site since this button is shared across a few locations
Updates: https://artsyproduct.atlassian.net/browse/GROW-983
Fixes: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-324&quickFilter=110
> [FIX tracking] Fix tracking on artwork pages

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ImageCarousel.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
Updates carousel to constrain image sizes similar to old artwork page:
> [PATCH artwork] Constrain image area

- README.md
Updates README with some possible steps for debugging CircleCI when it gets into a confused state.
> Update README with semantic-release troubleshooting instructions

- patches/graphql+0.13.2.patch
- src/Apps/Order/Components/__stories__/ArtworkSummaryItem.story.tsx
context: https://artsy.slack.com/archives/C2TQ4PT8R/p1544560372121700
This bug first appeared in https://github.com/artsy/reaction/commit/2334f3006a414b1bab8ee7bb17af03d55172e887
That commit introduced quite a few dependency updates. One of them (I’m guessing the webpack update) caused storybook’s webpack to resolve `.mjs` files in preference of `.js` files if both are present for the same filename, which is fine.
The problem was that we are using a patched version of `graphql` which specifically disabled the ‘__id’ error message shown above. This patch was applied to a `.js` file but I discovered that there is also a `.mjs` version of that file which was now the version being loaded. So I patched that file too and the problem went away.
edit: also fixed the ArtworkSummaryItem story, …
> Patch graphql .mjs file to fix storybooks no-load error

- src/Styleguide/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
#minor.
Also not sure it looks much better without having a loader in there or something. This blank space looks like jittering as well...
> adding key to the avatar used in follow artist popover after following an artist

- src/Apps/Order/Routes/Reject/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__stories__/OrderApp.story.tsx
- src/__generated__/Reject_order.graphql.ts
- src/__generated__/routes_RejectQuery.graphql.ts
This PR fixes [PURCHASE-659](https://artsyproduct.atlassian.net/browse/PURCHASE-659) by adding the ability to select "Decline" and get routed to a(n empty) component. 
This is a work-in-progress because we're seeing the following error get thrown silently in this code:
https://github.com/artsy/reaction/blob/7e1dc1ced96681e46d23dec0c1ed18bac6289843/src/Artsy/Router/buildClientApp.tsx#L68-L72
Here's the error:
```
Error: loadable-components state not found. You have a problem server-side. Please verify that you have called `loadableState.getScriptTag()` server-side.
at loadComponents (loadable-components.es.js?c034:118)
at _callee$ (VM2659 buildClientApp.tsx:110)
at tryCatch (runtime.js?96cf:62)
at Generator.invoke [as _invoke] (runtime.js?96cf:288)
at Generator.prototype.(:9001/anonymous …
```
> Adds empty review/reject component and route

- package.json
All consumers of reaction already have a direct dependency on palette. Having palette as a direct dependency increases the risk of having conflicts between versions in reaction and in the consumer of reaction. This removes that risk by making palette a peer dependency.
> Make palette a peer dependency of reaction

- src/Apps/Collections/Components/CollectionsGrid.tsx
- src/Styleguide/Components/EntityHeader.tsx
fixes https://artsyproduct.atlassian.net/browse/GROW-1043
We are seeing a "Link' not being trace-able by Google. This PR updates the `<EntityHeader>` to use an actual `<a>` tag so Google will be able to recognize links.
> Replace onClick={href} with a normal <a href="..."> in EntityHeader

- src/Artsy/Router/buildServerApp.tsx
Noticed this was being run _after_ data was serialized, leading to locally unreproducible errors in staging and prod logs. 
```sh
reaction/Router/buildServerApp Error serializing data: TypeError: Converting circular structure to JSON
Dec 13 16:29:22 force-web-57597c545f-xt7mp k8s_force-web_force-web-57597c545f-xt7mp_default_6e266681-ff14-11e8-a5ad-0a7e8548888c_0:     at JSON.stringify (<anonymous>)
Dec 13 16:29:22 force-web-57597c545f-xt7mp k8s_force-web_force-web-57597c545f-xt7mp_default_6e266681-ff14-11e8-a5ad-0a7e8548888c_0:     at serialize (/app/node_modules/serialize-javascript/index.js:76:20)
Dec 13 16:29:22 force-web-57597c545f-xt7mp k8s_force-web_force-web-57597c545f-xt7mp_default_6e266681-ff14-11e8-a5ad-0a7e8548888c_0:     at serializeRelayData …
```
> [FIX ssr] Fix circular refs in SSR

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarCommercial.test.tsx
- Adjust spacing between sale message, shipping info, and CTA button
- Update Buy Now / Make Offer commercial action button labels within the Responsive Artwork Page component
Addresses https://github.com/artsy/reaction/pull/1683#issuecomment-446747684
---
**Before**
---
**After**
> Adjust design spec implementation for artwork BNMO sidebar

- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
- src/Apps/Order/Routes/__tests__/Accept.test.tsx
Displays an error modal with the correct title and message if charge capture fails when accepting an offer on `/orders/$orderId/review/accept`.
Addresses [PURCHASE-715](https://artsyproduct.atlassian.net/browse/PURCHASE-715).
> Show error modal on accept offer review page if charge capture fails

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
- src/__generated__/ArtworkSidebarBidAction_artwork.graphql.ts
- src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
- src/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
- src/__generated__/ArtworkSidebarQuery.graphql.ts
- src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
Not sure what is the different between `active_bid` and `most_recent_bid` but Force seem to use `most_recent` to figure out the next increment to bid and `active_bid` for displaying your current win/lose status. Doing it here as well.
This I think addresses https://artsyproduct.atlassian.net/browse/DISCO-577. We still need to take this value from select and pass it bid action.
> the select for the next available max bid should respect your current max bid

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- Update font style for Buy Now / Make Offer artwork page shipping info components
- Swap order of `shippingInfo` and `shippingoOrigin`
---
**Before**
**After**
> Update Buy Now / Make Offer shipping info components

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
- src/Styleguide/Components/AuctionCard.tsx
- src/__generated__/ArtworkApp_artwork.graphql.ts
- src/__generated__/ArtworkRelatedArtists_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
Thanks @mzikherman for walking me through graphQl for this. 
Adding the code and display to put some similar artists on the artwork page as requested by: https://artsyproduct.atlassian.net/browse/DISCO-565
Current look:
This is missing some specs and also probably needs some fiddling with responsive behavior here, but it does seem to work:)
> starting work to display RelatedArtists on Artwork page

- src/Components/Publishing/Layouts/FeatureLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/__stories__/ArticleStandard.story.tsx
CanvasFooter is hidden unless isSuper is false and article is not in a series
>  [PATCH publishing] CanvasFooter does not render if article is super or in series

- src/Apps/Order/Routes/Counter/index.tsx
- src/__generated__/CounterSubmitMutation.graphql.ts
Addresses [PURCHASE-764](https://artsyproduct.atlassian.net/browse/PURCHASE-764).
Fetches `awaitingResponseFrom` in the response for `CounterSubmitMutation` to refresh the cache. Without this, on successfully countering an offer the buyer is redirected from /status back to /respond since `awaitingResponseFrom` is stale.
> Fetch awaitingResponseFrom in response from counter offer submit mutation

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Apps/Artwork/routes.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
Updates overall height of image to be dynamic to viewers screen size (60%) and removes padding when arrows are not present.
> [PATCH Artwork] Update image sizing

- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Addresses: https://artsyproduct.atlassian.net/browse/GROW-793
This is the second part of work that adds social embeds to standard and feature articles. It is dependent on https://github.com/artsy/positron/pull/1825
> [PATCH publishing] adds social embed to sections

- src/Apps/Order/getRedirect.ts
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/__generated__/redirects_order.graphql.ts
- src/__generated__/routes_OrderQuery.graphql.ts
Done in collaboration with @ds300, and in response to feedback from @alloy [on a previously merged PR](https://github.com/artsy/reaction/pull/1711#issuecomment-449001723). 
1. We accidentally committed an "any" default to the `args` property of `RedirectPredicate`. That is removed, and actual types are specified by all implementing types.
2. A new fragment is added, to represent the `Order` that the `RedirectPredicate`s all need.
> Strongly type redirect predicates and create fragment for redirect logic

- src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCard.tsx
- src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCards.tsx
- src/Components/Publishing/RelatedArticles/ArticleCards/Block.tsx
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/ArticleCard.test.tsx
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
- src/Components/Publishing/Sections/VerticalOrSeriesTitle.tsx
- src/Components/Publishing/Sections/__tests__/VerticalOrSeriesTitle.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/VerticalOrSeriesTitle.test.tsx.snap
- src/Components/Publishing/Series/SeriesAbout.tsx
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/VideoAbout.tsx
- src/Components/Publishing/Video/VideoCover.tsx
- src/Components/Publishing/Video/VideoInfoBlock.tsx
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
- src/Components/Publishing/__stories__/RelatedArticleCards.story.tsx
Quick refactor of components related to `series` and `video` article layouts
- Removes `styled-flexbox-grid`
- Use palette responsive components and fonts
- Removes restriction of feature layout `fullscreen` to show series data (is handled at top level)
> Use Palette components for Series & Video

- src/Styleguide/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
Improves the UX a bit so that the user can get some feedback before the swap.
> [PATCH artwork] Add slight delay to follow artist panel swap

- src/Apps/Order/Routes/Status/index.tsx
- src/Apps/Order/__tests__/getRedirect.test.ts
- src/Apps/Order/getRedirect.ts
- src/Apps/Order/redirects.tsx
- src/Apps/Order/routes.tsx
- src/Apps/__tests__/Fixtures/Order.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-765
Also observed some nondeterministic redirect behaviour in storybook, which turned out to be because the mock relay resolver was doing nondeterministic things because we hadn't specified a value for `awaitingResponseFrom`. In fixing that I decided to also add a 'reason' property to redirects so we can debug redirects a bit more easily.
> Fix 'Back to Artsy' link

- .autorc
Enables `Skip Release` as a label to skip the release without specifying a version.
> Add a skip release label

- src/Apps/Artwork/Components/__stories__/ArtworkSidebar.story.tsx
- src/Apps/Artwork/routes.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
- src/Apps/__tests__/Fixtures/Artworks.ts
Using `yarn link` and a Force PR which I'll open momentarily, this has the required behavior, the new page rolled out under /artwork (along with supporting /confirm-bid for legacy purposes).
> @oxaudo => Rollout new artwork page

- src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
- src/Apps/Collect/Components/Filters/__tests__/TimePeriodFilter.test.tsx
finishes https://artsyproduct.atlassian.net/browse/GROW-1057
> Surface only time periods that match a defined list in filters

- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/submitPendingOffer.ts
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
When submitting counter offer, if the artwork doesn't have enough inventory anymore, show proper error message.
Added specific logic to check for `insufficient_inventory` error code coming back from Exchange.
> Add specific error for insufficient inventory

- .autorc
We interpreted the _onlyPublishWithReleaseLabel_ wrong. With this option set you have to include the actual release label for a release to happen. Not just the major, minor, patch label. 
Every since auto-release was updated in #1787 our deployments have stopped. Before that the patch versions were being released because the config wasn't reading properly and it was falling back to the default behavior of releasing everything as a patch. 
This should fix the releases not happening.
> Remove release label requirement

- src/Apps/Order/OrderApp.tsx
Resolves [PURCHASE-779](https://artsyproduct.atlassian.net/browse/PURCHASE-779).
Currently, there is a bit of extra space at the bottom of all the order/offer pages, at xs resolutions. It shows itself especially well on mobile, where it looks like this: 
This PR removes that extra space, like this:
> Remove extra space at bottom of order/offer pages

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-628
Fixes https://artsyproduct.atlassian.net/browse/DISCO-605
628 is only partial however, since FB removed the ability to customize description input and instead relies on the meta tags, which we by design furnish with more info. 
605 was fixed by ensuring that input elements are 16px, otherwise will zoom by default. I bumped the other text up around the area as well.
> [Artwork] Fix share zoom on iOS

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
My previous PR (#1793) was a bit heavy-handed: while correcting spacing on some of the order/offer screens, others need spacing added back. They look like this:
This PR adds a small spacer below some buttons on the order/offer screens. More specifically, pages where the button is the last element in the sidebar. So now they look like this:
> Add spacing below buttons of some order/offer forms

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
Decreases padding here and there and fixes some alignment in order to increase the size:
> [Artwork] Tighten up main Artwork image sizings 

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Tiny follow up to https://github.com/artsy/reaction/pull/1799 that provides a little more padding for the arrows on smaller browsers.
> [Artwork] Tighten up image size (more)

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/__stories__/ArtworkApp.story.tsx
Add a little bottom margin to actions so that views with additional tabs aren't clobbered:
> [Artwork] Padding to actions

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-781
https://artsyproduct.atlassian.net/browse/PURCHASE-782
three things:
1. Added spacing above the MO button (PURCHASE-782)
2. Set the correct flag to 'false' after finishing creating an offer order (PURCHASE-781)
3. Wait for `setState` to complete before changing window.location (PURCHASE-781)
> Fix spacing and state management for BNMO buttons on artwork page.

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
When works are enabled for offerable we should not show contact gallery.
Make sure we show contact gallery if work is not BN/MO enabled
> Not show contact gallery for works enabled for BNMO

- .circleci/config.yml
I recently learned that jobs can actually be shared via orbs. This will vastly simplify our configs and the duplication we have across them. Now if only they shared workflows....
> Grab circle jobs from yarn orbs

- src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/Components/Artwork/FillwidthItem.tsx
- src/Components/Artwork/GridItem.tsx
- src/Components/ArtworkGrid/ArtworkGrid.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Styleguide/Components/ArtistCard.tsx
- src/Styleguide/Components/RecentlyViewed.tsx
This updates the OtherWorks grids with new tracking functionality, but two key parts had to be extended:
- `ArtworkGrid` now accepts an optional `onBrickClick` callback prop
- `GridItem` now accepts an optional `onClick` callback prop
> [Artwork] Add tracking to OtherWorks ArtworkGrid bricks

- src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
- src/Styleguide/Components/RecentlyViewed.tsx
Follow up to https://github.com/artsy/reaction/pull/1816. Each click was missing an `action_type`.
> [Artwork] Add action_types to click

- package.json
Manual bump due to https://circleci.com/gh/artsy/reaction/22029; `auto-release` is a bit in flux atm.
> [version] Bump to 9.3.10

- src/Apps/Order/Routes/Status/index.tsx
- src/Apps/Order/Routes/__tests__/Status.test.tsx
- src/Apps/__stories__/OrderApp.story.tsx
Hi! :wave:
https://artsyproduct.atlassian.net/browse/PURCHASE-784
This ticket was filed because the copy on the status page was wrong for cancelled offer orders. We were incorrectly handing the 'buyer_rejected' cancellation reason and not even handling any of the others. (see here for the full list https://github.com/artsy/exchange/blob/6fb90698b1c0c33c3a50341f460e6a90647f48d4/app/models/order.rb#L39)
Brian and Joanna had a sync and we decided to handle the following four reasons with specific copy: `buyer_rejected`, `seller_rejected`, `seller_lapsed`, and `buyer_lapsed`. The remaining reasons fall under `seller_rejected` for now.
So that's what I've added here.
In addition I decided to refactor the logic for deciding which copy to show on the status page. It was getting messy (which I …
> Fix offer cancelled messages

- src/Assets/Icons/Auction.tsx
- src/Assets/Icons/BlueChip.tsx
- src/Assets/Icons/Book.tsx
- src/Assets/Icons/Fair.tsx
- src/Assets/Icons/Group.tsx
- src/Assets/Icons/Museum.tsx
- src/Assets/Icons/Solo.tsx
- src/Assets/Icons/TopEmerging.tsx
- src/Assets/Icons/TopEstablished.tsx
- src/Styleguide/Components/SelectedCareerAchievements.tsx
- Update svg element attribute names for JSX
JSX expectes camelCased attribute names so these should be translated
from their non-JSX hypen-separated formats.
- Add key prop to ArtistInsight components rendered via insights array  …
Addresses the following React dev-tools warning:
Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `SelectedCareerAchievements`. See
https://fb.me/react-warning-keys for more information.
in ArtistInsight (created by SelectedCareerAchievements)
> Address React warnings found via React Dev Tools

- src/Components/Artwork/Fillwidth.tsx
- src/Components/Artwork/FillwidthItem.tsx
- src/Components/Artwork/GridItem.tsx
- src/Components/Artwork/Metadata.tsx
- src/Components/Artwork/Save.tsx
- src/Components/Artwork/index.tsx
- src/Components/ArtworkGrid/ArtworkGrid.tsx
- src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
- src/Components/ArtworkGrid/__stories__/ArtworkGrid.story.tsx
- src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
- src/Components/__stories__/Artwork.story.tsx
- src/Components/__stories__/ArtworkMetadata.story.tsx
- src/Components/__stories__/Fillwidth.story.tsx
- src/Styleguide/Components/RecentlyViewed.tsx
- src/Styleguide/Components/__stories__/Carousel.story.tsx
- src/Styleguide/Components/__stories__/RecentlyViewed.story.tsx
About a year ago there was an aborted effort to find a way to migrate all of the artwork bricks across force to a standardized format (Reaction). This required a fork in all Relay brick code, since the data coming through force made direct requests to MP or Gravity. This was before we had upgraded our systems with the latest architectural updates and started rebuilding pages completely in Relay. (As soon as that effort began this one was abandoned.) This removes that code.
> [Refactor] Remove useRelay fork code for ArtworkGrid

- src/Artsy/Analytics/Schema/Values.ts
- src/Styleguide/Components/ArtistInsight.tsx
- src/Styleguide/Components/ArtistInsightsModal.tsx
- src/Styleguide/Components/SelectedCareerAchievements.tsx
When users are interacting with the Artist Insights 2.0 data, we want to track user engagement (clicks) on the insights feature so that we can understand if this information impacts commercial activity on Artsy.net.
The context submodule name is derived from the Insight's type. A couple of these are created within the `SelectedCareerAchievements` component:
- `BLUE_CHIP`
- `HIGH_AUCTION`
The others are defined in Metaphysics:
- `SOLO_SHOW`
- `GROUP_SHOW`
- `REVIEWED`
- `COLLECTED`
- `BIENNIAL`
source: https://github.com/artsy/metaphysics/blob/master/src/schema/artist/insights.ts
ticket: https://artsyproduct.atlassian.net/browse/DISCO-656
> DISCO-656: Add event tracking for Read more / Learn more artist insight actions

- src/Components/Publishing/Icon/IconRemove.tsx
Kills error: 
`JSX element type 'IconRemove' is not a constructor function for JSX elements.  Types of property 'state' are incompatible.`
> [Minor] Fix IconRemove component definition

- src/Apps/Artist/Routes/Overview/index.tsx
- src/Assets/Icons/Auction.tsx
- src/Assets/Icons/Group.tsx
- src/Assets/Icons/Solo.tsx
- src/Styleguide/Components/ArtistInsight.tsx
- src/Styleguide/Components/ArtistInsightsModal.tsx
- src/Styleguide/Components/SelectedCareerAchievements.tsx
- Tidy up design for new Artist Insights component
- Sentence case "Selected career achievements"
- Remove "show less" link
- Add period at the end of "Learn more about artist insights"
- Use non-breaking space within "[n] more" link
- Ensure all icon colors are set to #000000
- Reorder artist overview components when displaying Artist Insights v2
- Remove Selected exhibitions component
- Display bio, genes, and consignment above Artist Insights v2
---
**Before**
---
**After**
ticket: https://artsyproduct.atlassian.net/browse/DISCO-662
> Tidy up design implementation and component ordering for Artist Insights v2

- src/Apps/Order/Components/OfferInput.tsx
- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/__tests__/Offer.test.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Artsy/Analytics/Schema/Values.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-791
Only issue is that I couldn't figure out how to use `mockTracking` and `MockBoot` together so had to figure out a new way of mocking the event tracker.
> Add MO speedbump analytics

- src/Apps/Artist/Routes/Overview/index.tsx
- src/Artsy/Analytics/Schema/Values.ts
- typings/sharify.d.ts
`v1` -> Artist Insights v1
`v2_before_bio` -> Artist Insights v2 before bio
`v2_after_bio` -> Artist Insights v2 after bio
> Switch between Artist Insights variations based on A/B enrollment

- src/Components/Modal/ModalWrapper.tsx
- Disable scrolling of background content while modal is open 
This commit disables vertical scrolling of the background content while the modal is open. This covers scrolling while the cursor is positioned off of the modal window and for smaller viewports, scrolling beyond the modal content, which would also cause the background content to scroll.
- Close open modal via escape key
This commit sets up an event listener while the modal is open to close
the modal if the escape key is pressed.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-674
> Modal: Support background scroll locking and close via escape key

- src/Utils/index.ts
- src/Utils/index.tsx
The release step failed here https://circleci.com/gh/artsy/reaction/23038.
I suspect it was because `yarn emit-types` failed yet the `auto-release` cli was consuming error. The error was a result of there being two index files in the `/Utils` folder (erroneously), which TypeScript was unable to merge.
> [Release] Attempt 2 to send out major release

- src/Components/Publishing/Header/Layouts/Components/FeatureSplitHeader.tsx
Missed one component -- this removes the grid library from feature article's "split" header layout.
There is now only one instance of `react-styled-flexboxgrid` in reaction, from the to-be-deprecated `Grid` component.  Not sure how much this is used (a replacement has been in production for a while), will look into it and see if we are safe to remove outside of this PR.
> Remove react-styled-flexboxgrid from feature split header

- src/Components/v2/SelectedCareerAchievements.tsx
Fixes the following issue found during QA:
> Upon clicking "X more" link, the column seems to shift to the right
> slightly. See recording: https://cl.ly/4d787cb60e0d
ticket: https://artsyproduct.atlassian.net/browse/DISCO-676
> Ensure artist insights flex container uses 100% of available space

- src/Components/v2/ArtistInsight.tsx
- src/Components/v2/SelectedCareerAchievements.tsx
By setting the width of individual artist insight components set to 50%, the text can occasionally brush up to the icons in the next columns.
Instead of adding padding, considering we don't know whether a particiular insight will show up on the left or right side, limit the Artist Insight component to 48% width and use `justify-content: space-between`.
**Before**
**After**
> Add gutter space between artist insight components

- src/Apps/Order/Routes/Respond/index.tsx
Addresses [PURCHASE-797](https://artsyproduct.atlassian.net/browse/PURCHASE-797). 
I missed the "respond" page when adding spacing to order pages. 
Before 😮😱🤢 :
After 🙂😄😸:
> Add spacing below button on offer/respond page

- package.json
- yarn.lock
Remove this dependency because it's handled by https://github.com/artsy/orbs/pull/17.
> Remove auto-release-cli as a direct dependency

- src/Apps/Artwork/Components/ArtworkBanner/__tests__/ArtworkBanner.test.tsx
- src/Apps/Artwork/Components/ArtworkBanner/index.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
- src/__generated__/ArtworkBannerQuery.graphql.ts
- src/__generated__/ArtworkBanner_Test_Query.graphql.ts
- src/__generated__/ArtworkBanner_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
Address https://artsyproduct.atlassian.net/browse/DISCO-530
Huge props to @ds300 for simplifying relay mocking here. Unfortunately this still has our original issue here that fields that are redefined for different Contexts come out undefined, but at least the set up here is much simpler. cc @alloy - who originally helped me to figure out this mockResolver.
> ArtworkBanner for auctions should show sale cover image instead of partner profile image

- src/Apps/Artist/Components/ArtistHeader.tsx
finishes https://artsyproduct.atlassian.net/browse/GROW-1032
This PR replaces the responsive sign up modal with the mobile sign up modal in e.g http://staging.artsy.net/artist/charles-arnoldi-1. Our hypothesis is that the mobile sign up modal converts more - I don't have specific numbers right now but is definitely something we want to compare.
> User should see the mobile sign up modal in the artist page

- src/Apps/Collect/Components/Collection/Header/index.tsx
Addresses: https://artsyproduct.atlassian.net/browse/GROW-1053
- Changes font size to body-2 serif
- Truncate to 7 lines
**XL**
**Large**
**Medium**
**Small**
**XS**
> Styling changes to Collections blurb font sizes

- CHANGELOG.md
- package.json
For some reason the auto-release build failed to push a commit that updates the `package.json` but the tag/version `11.1.0` is actually on GitHub/npm. I'm sending this PR to fix the consistency.
> Manually update version

- src/Apps/Order/Utils/__tests__/formValidators.test.tsx
- src/Apps/Order/Utils/formValidators.tsx
Addresses https://artsyproduct.atlassian.net/browse/PURCHASE-785.
This PR will disallow whitespace for **all** fields in the BNMO address form, not just the postal code as the original JIRA issue defines. 
I also added a bunch of unit test coverage of the address validation function.
> Disallow whitespace for address form

- src/Apps/__stories__/ArtworkApp.story.tsx
- src/Components/v2/AuctionCard.tsx
Tiny PR to address [DISCO-678](https://artsyproduct.atlassian.net/browse/DISCO-678), thanks @damassi for helping me navigate Reaction!
Side note: there's some strange behavior with this component in the storybook (I think it's supposed to show up in the [OtherAuctions](https://artsy-reaction.netlify.com/?selectedKind=Apps%2FArtwork%20Page%2FComponents%2FOtherAuctions&selectedStory=Other%20Auctions&full=0&addons=0&stories=1&panelRight=0) section but doesn't, and it instead appears twice in the [OtherWorks](https://artsy-reaction.netlify.com/?selectedKind=Apps%2FArtwork%20Page%2FComponents%2FOtherWorks&selectedStory=Auctions&full=0&addons=0&stories=1&panelRight=0) section). Worth fixing, or is it a moot point since I believe this component is moving to Palette?
> Fixes "related auction" image overlapping with text on RAP

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/__generated__/ArtworkActions_artwork.graphql.ts
- src/__generated__/ArtworkImageBrowserQuery.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
@oxaudo, @zephraph, and myself are working on porting the old View in Room function to the new artwork page. This is a start on the Reaction side of things—there's a sister [WIP Force PR](https://github.com/artsy/force/pull/3388) as well.
There are a few TODOs left here, the biggest of which is figuring out how to actually pass the image to Force since the old View in Room functionality actually expects the full image tag and not just a src url. Justin suggested passing it using the component that wraps ArtworkActions as a prop; I think that's ArtworkActionsFragmentContainer.
One possible hiccup here: the artwork page v2 doesn't actually use an `<img>` tag for the image; it's a `<div>`. Not sure if that means we need to rethink the strategy a bit.
Tracked: …
> [WIP] Start on adding view in room to artwork page v2

- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/Reject/index.tsx
- src/__generated__/Accept_order.graphql.ts
- src/__generated__/Reject_order.graphql.ts
- src/__generated__/routes_AcceptQuery.graphql.ts
- src/__generated__/routes_RejectQuery.graphql.ts
Addresses https://artsyproduct.atlassian.net/browse/PURCHASE-810.
We want to remove the `lastOffer` and `offers` fields from the `Order` type in exchange/metaphysics, as they have been moved to the `OrderOffer` type instead. In order to do this, we need to remove any last references to these fields on the `Order` type. This PR accomplishes that in reaction.
> Pull `lastOffer` from `OrderOffer` instead of `Order`, due to deprecation

- src/Components/v2/Lightbox/Lightbox.tsx
Adds a hook for legacy view-in-room to hook into the artwork image for dimension info.
> Add hook to artwork image for view in room

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
Fixes https://sentry.io/artsynet/force-production/issues/858572548/?referrer=alert_email
Fixes https://artsyproduct.atlassian.net/browse/BUGS-746
This guards against an artist not having images. Tracked it down to the slider throwing perhaps due to a data issue.
> [Bugfix] Guard against missing images on /artwork/id

- data/schema.graphql
Several fields were removed from offer types in metaphysics.
Not updating this promptly was causing the `validate_staging_schema` step to fail - https://circleci.com/gh/artsy/force/14477
> Remove obsolete offer fields from "schema.graphql"

- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Components/Authentication/Types.ts
- src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
partially addresses https://artsyproduct.atlassian.net/browse/GROW-1080
This PR adds the ability to override the title in the sign up form. I wonder if we should do the same to the log in form. Let me know if that is the case.
> Add ability to customize sign up form title

- src/Components/v2/Pagination.tsx
When I migrated `LargePagination` from Reaction to Palette, I brought with it a separator component that is used in Force but not in Volt. I have put the separator component back in Reaction and [removed it from Palette](https://github.com/artsy/palette/pull/236) so that it doesn't become a part of the shared component library.
> Add separator to pagination component

- src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
- src/Components/Publishing/Header/Layouts/Components/FeatureInnerContent.tsx
- src/Components/Publishing/Header/Layouts/StandardHeader.tsx
- src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
- src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
For SEO, adds `<h1>` wrappers for article titles.
This brings up a q for text blocks in articles generally -- we are using `h1` in article body text, but it would probably be better for SEO structure if we bumped the body text to use `h2` rather than `h1`, etc. so that inner text of the article indicates a hierarchy below the title.
> Article titles have h1 headers

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkMorePanel.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkPopoutPanel.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkActions.story.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
This PR addresses https://artsyproduct.atlassian.net/browse/PURCHASE-814 and https://artsyproduct.atlassian.net/browse/PURCHASE-815
In summary, it:
1. Adds labels to the icons in the `ArtworkActions` component (shows up beneath an artwork on the artwork page)
2. On mobile web... if there are > 3 actions, hide the "rest" behind a `More` icon, and display them in a panel.
3. Small refactor. I pulled out `ArtworkPopoutPanel` as a component to serve both the `Share` and the `More` functions.
TODO:
cc @mzikherman
> Adds text labels to ArtworkActions and conditionally renders them for mobile web

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Missed this nuance when I was matching the designs!
For mobile web, we also want the image browser dots to appear centered instead of floated to the right, where they may overlap with the labels.
> Keep actions and image dots centered for mobile web as well

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
🤦‍♀️ 
For the links under `ArtworkActions`, this makes the entire icon + label clickable.
> Make entire link clickable on artwork actions

- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- src/Apps/Collect/Components/Filters/__tests__/FilterContainer.test.tsx
- src/Artsy/Router/Components/Boot.tsx
- src/Components/Artwork/GridItem.tsx
- src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
- src/Components/Publishing/Header/Layouts/Components/FeatureInnerContent.tsx
- src/Components/Publishing/Header/Layouts/StandardHeader.tsx
- src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
- src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
- src/setup_jest.ts
This PR fixes a bunch of SSR errors I discovered when debugging https://artsyproduct.atlassian.net/browse/GROW-1094: 
1) Noticed that SSR and mobile layout was broken on `/collect` with JS turned off on mobile: 
I refactored the view a bit so it's more straightforward and the issue seemed to fix itself. Rather than weaving `<Media at='xs'>` and `<Media greaterThan='xs'>` throughout the same block i made mobile and desktop strictly separate via an acceptable amount of duplication, which allowed us to remove a bunch of intermediate variables for clarity and simplify overall. 
2) Fix SSR rendering on our grid. I've been noticing how pages with grids aways render with grey blocks for a while and tracked that down. With JS turned off: 
Before: 
-----
After:
-----
3) Noticed that our scroll …
> Fix SSR issues on /collect, grid images, tracking and h1 global tags

- src/Apps/Order/Components/OfferInput.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
- src/Components/Authentication/__tests__/Mobile/ResetPasswordForm.test.tsx
- src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
- src/Components/Input.tsx
- src/Components/Onboarding/Steps/Artists/index.tsx
- src/Components/Onboarding/Steps/Genes/index.tsx
- src/Components/PasswordInput.tsx
- src/Components/QuickInput.tsx
- src/Components/__stories__/Input.story.tsx
- src/Components/__tests__/Input.test.tsx
- src/Components/__tests__/PasswordInput.test.tsx
- src/Components/__tests__/QuickInput.test.tsx
- src/Components/__tests__/__snapshots__/Input.test.tsx.snap
- src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
- src/Components/__tests__/__snapshots__/QuickInput.test.tsx.snap
This is ready for review! I'm leaving it as a WIP for now, in case we want to wait until we get more specs from design for the palette version of the inputs.
Collaboration with @jonallured.
We noticed that the "text input" fields were in Reaction, but they feel like something that could belong in palette. Our main goal was to make the text inputs easier to extract into palette. [An issue has been created in palette for the extraction](https://github.com/artsy/palette/issues/253).
While trying to understand how the text inputs worked, we noticed 3 variants of text input - a standard input, a "quick" input where the label for the field is inside the textbox, and a password input where the value is masked rom the user. [Zeplin affirms …
> Refactor Input component in preparation for moving to Palette

- src/Artsy/Relay/createRelaySSREnvironment.ts
Since all of our apps are Node 8 and above realized we could update this: 
https://github.com/relay-tools/react-relay-network-modern#different-builds
> [Lib] Point at proper relay-network-modern-build

- data/schema.graphql
- src/Components/Search/Previews/Grids/Artist.tsx
- src/Components/Search/Previews/index.tsx
- src/Components/__stories__/Search.story.tsx
- src/__generated__/ArtistSearchPreviewQuery.graphql.ts
- src/__generated__/ArtistSearchPreview_artist.graphql.ts
- src/__generated__/OfferMutation.graphql.ts
- src/__generated__/RespondCounterOfferMutation.graphql.ts
Here's an example of how we might start to organize the components for the RHS 'additional context' stuff for autosuggest.
Here's the folder structure: https://github.com/mzikherman/reaction-force/tree/search_context/src/Components/SearchAutoSuggest
This is totally unstyled for now! 😅
> @pepopowitz => [AutoSuggest] Rough implementation of artist handling for previews

- src/Components/Input.tsx
Over on https://github.com/artsy/reaction/pull/1969 @pepopowitz and I removed access to the `innerRef` for `Input` because we thought it wasn't being used - we were wrong!
https://github.com/artsy/positron/blob/010b5d09e27996c997e6b7e6b5d14337dbd59e42/src/client/components/autocomplete2/index.tsx#L205
So here I'm just adding it back to the prop interface so that Positron won't be blocked from bumping Reaction.
Per @damassi, there is some incompatibility with `innerRef` and styled-components so we will have to revisit this at some point. Better to do that work with intention rather than having this PR drop support so suddenly. My thought is to drop that support as we move `Input` over to Palette, but open to other thoughts! ❤️
> Add back access to the innerRef for Input

- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/index.tsx
- src/Components/__stories__/Search.story.tsx
- src/__generated__/SearchBarQuery.graphql.ts
- src/__generated__/SuggestionsSearchQuery.graphql.ts
- src/__generated__/SuggestionsSearch_viewer.graphql.ts
cc @jonallured 
This adds a fragment container/query renderer for the suggestions component. Namely, it can fetch and render results from an auto-suggest query.
Looking like:
This is mergeable, but I left it as a WIP. I'm adding a `SearchBar` component that includes an `Input` and wraps it up with suggestions, to hopefully have a reasonable example of some composition of the components.
> @pepopowitz => [Search] Add suggestions component

- src/Components/Search/Suggestions/index.tsx
- src/__generated__/SearchBarQuery.graphql.ts
- src/__generated__/SuggestionsSearchQuery.graphql.ts
- src/__generated__/SuggestionsSearch_viewer.graphql.ts
cc @jonallured 
This builds upon https://github.com/artsy/reaction/pull/1994 to start roughing in the preview component alongside suggestions. With some minimal `Flex` and widths, and it's starting to look more reasonable (+ responsiveness).
> @pepopowitz => [Search] Prototype for loading previews w/ suggestions

- src/Artsy/Relay/createRelaySSREnvironment.ts
- src/Artsy/Relay/middleware/metaphysicsExtensionsLoggerMiddleware.ts
Adds *a form* of visibility into API complexity during devtime, by providing a collapsed group of info based on the MP data sent about the number of requests made across our rest and graphql APIs.
> Adds some inline logs to highlight metaphysics extensions used in the query

- data/schema.graphql
- package.json
- src/Components/Search/Previews/index.tsx
- src/Components/Search/Spike/SearchBarSpike.tsx
- src/Components/__stories__/Search.story.tsx
- src/__generated__/SearchBarSpikeRefetchQuery.graphql.ts
- src/__generated__/SearchBarSpikeSuggestQuery.graphql.ts
- src/__generated__/SearchBarSpike_viewer.graphql.ts
- yarn.lock
Latest screenshot:
This adds `react-autosuggest` and hooks it up in a Relay context (refetch container- finally using that!), and gets some basic functionality in. The motivation and some ad-hoc discussion about whether this library is a worthy addition to Reaction was done in Slack earlier: https://artsy.slack.com/archives/C2TQ4PT8R/p1549570277663300 
I figured this is worth a look-see and PR b/c a lot of the 'meat' of the functionality is present. Further iterative steps revolve more around understanding and using the library fully, UI work and styling, etc.
> @pepopowitz => [Autosuggest] Use react-autosuggest and start roughing in functionality

- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Components/Authentication/Types.ts
Addresses: https://artsyproduct.atlassian.net/browse/GROW-1080
Because we moved [away from passing the title as a query param](https://github.com/artsy/force/pull/3449#issuecomment-459503584), the custom title wasn't displaying in the mobile signup modal. This passes the artist name as a query param versus the title to build the the custom title in the force router. Note that there is additional force work that needs to be done to complete this but this PR should be merged first.
> [PATCH authentication] pass artist name in query params

- src/Components/v2/AuctionTimer.tsx
Noticing some auctions that don't end (or have the live portion start) on the hour weren't displaying that labeling (although the countdown timer was correctly calculated). Just a moment formatting issue.
> @mzikherman => [AuctionTimer] Make sure to display the minute portion in label

- src/Artsy/Router/Components/Boot.tsx
- src/__stories__/config.js
During SC4 upgrade we no longer had a way to directly inject styles into a head that lacks a react tree, so our RRM styles weren't being injected. I added it to the Boot global styles, leading to a little duplication since its already being passed via SSR. Should always be handled by consumers.
> Fix style injection

- src/Components/Artwork/GridItem.tsx
Adds a fallback for our grid images for when we're yarn linking.
> Add fallback for grid image

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Collect/Components/Filters/MediumFilter.tsx
- src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
- src/Apps/Comparables/Filter/MediumFilter.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
Refactors BorderedRadio and Radio usages to use the new `label` prop (see artsy/palette#290)
In doing so, fixes https://artsyproduct.atlassian.net/browse/PURCHASE-875
> Use `label` prop in BorderedRadio and Radio

- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
- src/Components/__stories__/Search.story.tsx
- src/__generated__/SearchBarRefetchQuery.graphql.ts
- src/__generated__/SearchBarSuggestQuery.graphql.ts
- src/__generated__/SearchBarTestQuery.graphql.ts
- src/__generated__/SearchBar_viewer.graphql.ts
The main thing here is the introduction of a special 'synthetic' first item. This is b/c, based on the comps, the first item that appears when you type in a term: `Search "andy"` for example, _is_ actually pretty much an item in our suggestions. As in, it's selectable/scrollable/clickable, and selecting it should take you to the search results page `/search?q=andy`.
So this PR adds that, and it sort of behaves well! It's kind of a weird idea, but I suspect that trying to handle it 'like' it's an actual suggestion (so you can navigate to it in the list) w/o it _actually_ being a suggestion is going to be even weirder and more of a headache!
> @jonallured => [Autosuggest] More roughing in of UI, introduction of special first item

- src/Artsy/Relay/createRelaySSREnvironment.ts
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
This allows the SearchBar to start off initially w/o making an unnecessary round trip to MP (requesting `viewer {}`), since that's unneeded for the initial state.
This was based off of a discussion in the [Relay Slack chat](https://graphql.slack.com/archives/C0BEXJLKG/p1550598752174300), with this solution (modifying the network layer) seeming to be the most workable.
> @alloy => [Autosuggest] Allow QueryRenderer to return w/o fetching

- src/Components/Search/SearchBar.tsx
This makes sure there's no visible flashing of any input components, along with https://github.com/artsy/reaction/pull/2039
With that latter mentioned PR, we have the network layer being able to return immediately (but still requiring a `Promise.resolve`). Theoretically then the `SearchBar` component can be rendered in its final state immediately, but it's likely there's another render pass to _actually_ do so.
So with this PR, we make sure to always render an `Input`. That way, even in the base case of having JS disabled, a proper `Input` will show up, and then in Force since we'll have a form wrapping it, a user will still be able to type something and get to the search results (even if they're not actually using the autosuggest).
> @jonallured => [Autosuggest] Always render Input

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
- src/Components/Publishing/Layouts/FeatureLayout.tsx
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- Adds boolean prop `showCollectionsRail` to `ArticleProps`
- Passes `showCollectionsRail` to `CanvasFooter` for standard, feature and news articles
> Add showCollectionsRail prop to Articles

- src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/index.tsx
- src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
- src/Components/Search/Previews/Grids/PreviewGridItem.tsx
- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
- src/Components/Search/Suggestions/SuggestionItemContainer.tsx
- src/Components/Search/Suggestions/index.tsx
- src/Components/__stories__/Search.story.tsx
- src/__generated__/ArtistSearchPreviewQuery.graphql.ts
- src/__generated__/ArtistSearchPreview_viewer.graphql.ts
- src/__generated__/MerchandisableArtworksPreviewQuery.graphql.ts
- src/__generated__/MerchandisableArtworks_viewer.graphql.ts
- src/__generated__/RelatedArtworksPreview_viewer.graphql.ts
- src/__generated__/SearchBarRefetchQuery.graphql.ts
- src/__generated__/SearchBarSuggestQuery.graphql.ts
- src/__generated__/SearchBarTestQuery.graphql.ts
- src/__generated__/SearchBar_viewer.graphql.ts
- src/__generated__/SuggestionsSearchQuery.graphql.ts
- src/__generated__/SuggestionsSearch_viewer.graphql.ts
- src/__generated__/TestsQuery.graphql.ts
This PR includes a variety of styling changes, with the goal of matching the auto-suggest search bar to the Zeplin comps.
Included:
Here's what it looks like now!
> Update SearchBar to better match comps

- src/Components/Search/SearchBar.tsx
Pretty minor, this sets the same width as the fully enabled `Input` component to avoid that last bit of flash upon hydration (the component would resize slightly).
Also, this adds `name="term"` to the correspondingly rendered `<input>` component, so when wrapped in a `<form action='/search'>` container in Force, works with just hitting 'Enter' (and no JS needed).
> @pepopowitz => [Autosuggest] Ensure full width on initial load, and correct name prop on input

- src/Components/CollectionsRail/Collection.tsx
- src/Components/CollectionsRail/CollectionsRail.tsx
- src/Components/CollectionsRail/index.tsx
- src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
- src/Components/__stories__/CollectionsRail.story.tsx
- src/__generated__/CollectionEntity_collection.graphql.ts
- src/__generated__/CollectionsRailQuery.graphql.ts
- src/__generated__/CollectionsRail_collections.graphql.ts
Addresses: https://artsyproduct.atlassian.net/browse/GROW-1112
This PR creates the new Collections Rail to be displayed on Standard, Feature, and News Article pages.
**Desktop:**
**Mobiile:**
UI Issues to be addressed:
> Collections Rail

- .storybook/webpack.config.js
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- typings/sharify.d.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-895
The ticket only mentions `ENABLE_OFFER_NOTE` but we also had `ENABLE_MAKE_OFFER` which presumably can be removed too.
> Remove make offer feature flags

- src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
- src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
- src/Components/Search/Previews/index.tsx
- src/Components/Search/SearchBar.tsx
This PR aims to improve the support for more breakpoints, here's some pretty pictures:
There's still work to be done here at XS because I'm simply turning off previews for that breakpoint, but we're supposed to show the default decayed merch preview on focus and on exact match we can show some previews too, but I'm less clear on that.
> DISCO-751: Support more breakpoints for new search bar

- src/Artsy/Analytics/Schema/Values.ts
- src/Components/Search/SearchBar.tsx
This implements the existing autosuggest tracking in the new component, but I very loosely followed the exact schema. This should be mergeable (and does record all the needed data), but will QA with @cavvia to make sure it's workable. I suspect we don't _need_ to match the exact schema from Force, but we can QA this on staging and any tweaks should be straightforward (🤞 )
Tracks:
- on 'focus' into the autosuggest input
- selecting an item from the suggestions (including the first item which takes you to `/search` and isnt a 'real' item)
- performing a fetch based on a new input- this includes whether or not results are returned
> @pepopowitz => [Autosuggest] Implement analytics tracking, replicating existing tracking...approximately

- src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
- src/Components/Search/SearchBar.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-756.
This fixes a timing bug. When a user searches, and they click on a link in the preview pane (right side), the results box closes without going anywhere. This is because the links in the preview pane are removed from the DOM before the browser can follow the link - the `onBlur` event of the search box is triggering a re-render with the clicked link removed.
So, we are grabbing a ref to the container. When the `onBlur` event fires for "leaving" the search box, we check to see if the `relatedTarget` is a descendant of the container ref. If it is, we set a flag indicating to other events that the search results should not dismiss. This allows the browser to actually follow the link.
> Don't dismiss the search results if the user clicked on a descendant component

- package.json
- src/Components/Truncator.tsx
- yarn.lock
Updates to the latest. This applies to our `<Truncator>` component. I checked that this worked in the ArtistCard, seemed all good. 
Noticed that there was some weird back and forth involving our lock file for a few months: https://github.com/artsy/force/commit/a7198c55b40150e13be60355922ec112b8d2cd8f#diff-8ee2343978836a779dc9f8d6b794c3b2L12675
> [Lib] Update react-line-ellipses

- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
Thanks @damassi for the tip, noticed these weren't actually firing outside of storybooks (usually we use `<Boot>` to wrap up apps which gives us this).
> @mzikherman => [Autosuggest] Hook up event dispatch for analytics tracking

- src/Components/Search/Suggestions/SuggestionItem.tsx
- src/Components/__stories__/Search.story.tsx
This PR aims to match the comp for suggestion spacing. We have properly spaced the suggestion title and the enter icon so that the former grows and shrinks, but the latter stays static. If the text of the suggestion title is too long it'll be truncated with ellipses. Here are some pictures for your scrapbook:
> DISCO-761: Match comp for suggestion spacing

- src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/__tests__/index.test.tsx
- src/Components/Search/SearchBar.tsx
- src/__generated__/AcceptTestQuery.graphql.ts
- src/__generated__/Accept_order.graphql.ts
- src/__generated__/routes_AcceptQuery.graphql.ts
- Use absolute URL's to link to collections. This avoids the problem of using search from a relative url (like an artwork page), and getting linked to `/artwork/collection/...`
- Use `e.preventDefault()` when a suggestion is selected. We intend to navigate the user in that case, but when using the keyboard and hitting 'Enter', the form submit was also happening (sometimes before the navigation).
> @jonallured => [Autosuggest] Couple minor QA items

- src/Components/Search/SearchBar.tsx
- src/Components/Search/SearchInputContainer.tsx
This PR adds the search icon to the search bar. Like on #2061, I'm just adding the icon here in reaction, but ultimately I want to get this into Palette and consume from there - this is on the short list of icons to add when I have a moment. Here are some shots:
> DISCO-759: Add search bar icon

- src/Apps/Collect/Components/Collection/Header/index.tsx
Looks like we have a style somewhere that is automatically turning links black, but not sure what side-effects it would result in changing from the top. 
Added a declaration for links in the header to inherit color from their parent, and also added underline/weight based on the spec here: https://app.zeplin.io/project/5b8437e1d4b17846b691835d/screen/5bd228c91311fc09c269bbde
> Fix link styles in Collections header

- src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/__tests__/index.test.tsx
- src/Components/__stories__/Search.story.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-760.
Some artists in the search suggestions do not have marketing collections or artworks. Previously, we were showing the title "Related Artworks" in the right pane, with no actual artworks. 
Now, we'll show this instead: 
There are a couple small things that I'll follow up with in other PR's - I'll point them out in the code.
> DISCO-760: Add an "empty" preview for artists without collections or artworks

- package.json
This removes `@sentry/browser` from being a direct dependency of reaction. Libraries like this that are utilized by the parent project shouldn't be direct dependencies. This was causing a duplication in our upstream webpack dependency in force. 
I'll go through and ensure positron, volt, and whoever else depends on reaction has this dependency specified in their projects.  I'm using [this link](https://github.com/search?q=org%3Aartsy+%22%40artsy%2Freaction%22+filename%3Apackage.json&type=Code) to look through the org for things that depend on reaction and ensure they have sentry too.
> Make @sentry/browser a peer dependency of reaction

- data/schema.graphql
- src/Components/CollectionsRail/index.tsx
- src/__generated__/CollectionsRailQuery.graphql.ts
Addresses: [GROW-1145](https://artsyproduct.atlassian.net/browse/GROW-1145)
This address the last bit of Collections Rail UI by adding the `randomize` argument to the collections query.
> Randomize collections rail

- src/Components/CollectionsRail/CollectionsRail.tsx
- src/Components/CollectionsRail/__tests__/CollectionsRail.test.tsx
- src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
- src/Components/Publishing/RelatedArticles/Canvas/RelatedArticlesCanvas.tsx
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/RelatedArticlesCanvas.test.tsx
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
- src/Components/Publishing/__stories__/ArticleStandard.story.tsx
- Adds separator and updates margins between articles and collections rail per spec here- https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5c59c0e1135eaf355f77a1a1
- Matches font size of `RelatedArticlesCanvas` and `CollectionsRail` titles
- Adds a slight font size bump down for mobile on titles
- Removes capitalization in related articles title 
- Changes 'artworks' to 'works' in collections rail title
> Add separator between RelatedArticlesCanvas and CollectionsRail

- data/schema.graphql
Because there was a breaking change in metaphysic's schema, we have to sync reaction's schema to stop force from failing its builds... ?
> Sync schema to avoid failures in force builds

- src/Apps/WorksForYou/WorksForYouFeed.tsx
When users scroll down even slightly on the `/works-for-you` page, the page kicks off a sequence of exhaustive, paginated requests for every published work ever by followed artists. This can mean thousands of API requests, and we frequently observe server-side errors (timeouts) trying to load the `n`th page of results for users who follow prolific artists. 
Related: [PLATFORM-1237](https://artsyproduct.atlassian.net/browse/PLATFORM-1237)
Upon investigation [and with @mzikherman's help], it seemed like the element whose `clientHeight` we're using to calculate offset was actually one artist's row, not the overall feed as intended. We confirmed that this "fixed" the issue locally but I wonder if there's a better solution or a more fundamental bug causing `this` to correspond to one row …
> Avoid endlessly requesting further pages of followed artists' artworks

- data/schema.graphql
- src/Apps/Order/__tests__/OrderApp.test.tsx
- src/Apps/Order/redirects.tsx
- src/__generated__/redirects_order.graphql.ts
- src/__generated__/routes_OrderQuery.graphql.ts
Blocked by: https://github.com/artsy/metaphysics/pull/1530
We only want people to be able to enter a new credit card if the last attempt to charge their card failed. In order to determine this, we query for `lastTransactionFailed` from exchange.
This PR updates our redirect logic for the `/payment/new` page to account for that.
> [DO NOT MERGE] New payment page will redirect to /status page unless the order's last transaction has failed

- src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
- src/Components/Modal/ModalWrapper.tsx
Follow up on https://github.com/artsy/reaction/pull/1858
Fixes https://artsyproduct.atlassian.net/browse/DISCO-683, https://artsyproduct.atlassian.net/browse/GALL-1430
This issue was surfaced by a broken infinite scrolling experience. Setting `overflow-y` to `auto` on `body` (+ [other requirements](https://drafts.csswg.org/cssom-view/#viewport)) makes it scrollable when the content overflows. Since [scroll events don't bubble on elements](https://drafts.csswg.org/cssom-view/#scrolling-events), they get intercepted by `body`, and that causes `window` that typically [listens to scroll events](https://github.com/artsy/jquery-on-infinite-scroll/blob/ca95a69d30e26443c431f790ba7b9ee8f2a5f781/index.js#L23) to not receive them. Therefore, the infinite scrolling broke. See this …
> Prevent body from intercepting scroll events when modal is not open (GALL-1430, DISCO-683)

- src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
- src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
- src/Components/Search/Previews/Grids/PreviewGridItem.tsx
- src/Components/Search/SearchBar.tsx
Currently, the horizontal padding for our preview pane is dispersed throughout our components. The left padding is taken care of by the container, but the right padding is taken care of by margins on the previews themselves. 
This PR removes that asymmetry, and moves the management of horizontal padding/margin where it belongs. The container handles the left/right padding, and the previews handle any margin in between individual items. 
It's probably not the worst thing in the world to leave the padding/margin asymmetrical, but it caused me headaches when trying to center the "empty" preview, and I anticipate that it would cause more headaches in the future. 
From the end-user's perspective, there should be no changes. This change is purely for maintainability.
One nice side-effect of …
> Refactor search previews css

- src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
- src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
- src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
- src/Components/Search/Previews/Grids/PreviewGridItem.tsx
- src/Components/Search/SearchBar.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
This PR addresses the following Jira tickets:
https://artsyproduct.atlassian.net/browse/DISCO-781
https://artsyproduct.atlassian.net/browse/DISCO-769
https://artsyproduct.atlassian.net/browse/DISCO-762
https://artsyproduct.atlassian.net/browse/DISCO-767
Here is some visual proof:
That last shot shows the known bug where we are able to combine the keyboard and mouse to have two "active" previews because the keyboard has one code path (unstated) and the mouse has another (css hover selector).
> Match comp for active preview items

- src/Apps/Order/Dialogs.tsx
- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
- src/Apps/Order/Routes/__tests__/Accept.test.tsx
- src/Components/Modal/ModalDialog.tsx
- src/__generated__/AcceptTestQuery.graphql.ts
- src/__generated__/Accept_order.graphql.ts
- src/__generated__/routes_AcceptQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-883
This ticket is about redirecting the user to the `/payment/new` page if charging their credit card fails on the `/accept` page.
It handles the 'insuffucient_funds' failure code with unique copy. I don't think it is possible to manually test this one case in staging using the stripe test credit cards, because of the way we use the stripe API. We'd have to re-write the way gravity and exchange handle stripe payments so... 😬 Yeah... Not gonna do that.
> /accept charge failure handling

- data/schema.graphql
- src/Components/CollectionsRail/index.tsx
- src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
- src/Components/__stories__/CollectionsRail.story.tsx
- src/__generated__/CollectionsRailQuery.graphql.ts
Related to https://github.com/artsy/kaws/pull/76
**Issue:**
When passing the same argument parameters, relay rerenders and replaces all instances of the collections rail components with the latest response. This causes all of the collections rails component to show the same rails. 
**Fix:**
We pass the article id as a unique randomization seed in order to make the query argument different.
> sync metaphystics schema and use new randomizationSeed argument

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
- src/Components/Publishing/__tests__/Article.test.tsx
We are limiting articles allowed to have custom layouts to those saved as layout "feature", but this is an unnecessary distinction that reflected the layouts of articles used in our first implementation.
Removes limitation so any layout can be custom, this anticipates conversations around customizing series articles for future projects.
> Remove restriction on layout for EditorialFeatures

- src/Components/Search/SearchBar.tsx
All this does is use the behavior of adding a suggestion placeholder at all breakpoints.
> DISCO-788: Add the placeholder on XS too

- src/Components/Search/state.ts
Addresses https://artsyproduct.atlassian.net/browse/DISCO-778 (hopefully!)
Seems like a pretty straightforward update. Basically, when you use the mouse to hover into the preview pane, we want to unselect any currently selected preview item that's been accessed via keyboard.
This feels pretty good in my testing!
> @jonallured => [Autosuggest] Unselect keyboard when you bring the mouse in to previews

- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
Currently, we are rendering no placeholder for the search bar at xs sizes. We probably did this initially because the usual placeholder took up too much space. 
This PR uses "Search Artsy" as the placeholder at xs.
> Disco 786 xs placeholder

- src/Components/Search/SearchBar.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-785.
There is a little gray bar that shows up at xs when you set focus to the new search box. It looks like this:
This PR removes it, by suppressing render of the `< SuggestionContainer>` when you are focused on the box, at xs, and haven't typed anything yet.
> SearchBar - Don't show suggestions container at xs when there is no query.

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
#minor This fixes an issue where we weren't showing _any_ artwork details if `series`, `publisher`, `manufacturer`, or `image_rights` didn't exist. This needed to be updated since the component now also shows a bunch more fields.
Added a test that would have caught this also.
> Show artwork "additional info" component if any of the fields exist

- src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
- src/Components/Search/Previews/Grids/PreviewGridItem.tsx
Inspired by this stackoverflow answer: https://stackoverflow.com/a/42764495
> add tabIndex={0} to preview links to get Safari to specify e.relatedTarget on blur

- src/Artsy/Relay/renderWithLoadProgress.tsx
While working with @pepopowitz on some styling improvement for the new search bar, we noticed that it's pretty hard to control how the spinner renders because you don't have access to the wrapper. This PR adds the ability to pass one in should you want that sort of control.
In order to feel good about the state of this file, I started by removing commented out code and some old todos. My philosophy is that todos like these are lies we tell ourselves with the best of intentions but are ultimately noise. Further, since this code exists in git, commenting it out is unnecessary. If or when we come back to the concept of retry, we can review the history of this file and get what we need from there. If returning to retry is important and something we don't want to forget to do, then I would …
> Refactor spinner function

- src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
- src/Components/Search/Previews/index.tsx
- src/Components/Search/SearchBar.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-758.
1. We noticed that the way we were getting the "no results" preview vertically centered was with a whole bunch of vertical margin. It's now centered via flexbox.
2. The height of the suggestions/preview box was dependent on the height of the content, so you'd get some dancing around that was distracting & looked not so "quality worthy of art." This PR adds a static height to the preview box, eliminating the dancing, and improving the QWOA factor.
What it looked like before (keep your eye on the bottom of the suggestion/preview box!):
What it looks like now:
> Set static preview height & use flex to vertically center 'no results'

- src/Components/Search/SearchBar.tsx
We had a fix for making sure the suggestions stay when a preview is selected, this does a fix for the same issue when a suggestion is selected.
Fixes https://artsyproduct.atlassian.net/browse/DISCO-825
Fixes https://artsyproduct.atlassian.net/browse/DISCO-826
One fix, 2 JIRA tickets!
> @pepopowitz => [Autosuggest] Ensure suggestions remain when suggestion is selected

- src/Apps/__tests__/Fixtures/SelectedCareerAchievements.ts
- src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
Update “Participated in a major biennial” to "Included in a major biennial"
branches in metaphysics and force
> Artist insights 2.0 - Update biennial badge label

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Addresses: [GROW-1147](https://artsyproduct.atlassian.net/browse/GROW-1147)
When a user logs in with Facebook after clicking the make offer button on an artwork page, they get redirected to the homepage instead of back to the artwork page. I noticed that we weren't passing in a `redirectTo` property to the `open:auth` trigger and that it wasn't included as part of the [`authQueryData`](https://github.com/artsy/reaction/blob/fd1922d49906c2197834bdc69eebb25a62860007/src/Components/Authentication/FormSwitcher.tsx#L200-L203) that gets sent through to Facebook. I'm not able to verify this locally due to Facebook's [requirement of https for login](https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/). I think we can add the property and test it in staging.
> explicitly add redirectTo property for fb auth flow

- data/schema.graphql
- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
- src/Apps/Search/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/NavigationTabs_searchableConnection.graphql.ts
- src/__generated__/SearchApp_viewer.graphql.ts
- src/__generated__/routes_SearchBarTopLevelQuery.graphql.ts
This creates the shell for search results:
- header and total count
- tabs
- placeholder for zero state/results
- footer
I started this off as `/search2` so that it can be added to Force right away, without waiting for it to be AB tested (and admins/anyone can check out current progress by just visiting /search2 instead of /search).
> @dblandin => [SearchResults] Create shell for search2, with a tab navigation

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Artsy/Analytics/Schema/Values.ts
This is a bit of a spike after a pairing session with @damassi. First he noticed that we could simplify things quite a bit if we moved the ContextConsumer into the fragment container, so I followed that refactoring through on a9880ff.
Then I added tracking to the selection of categories using the `@track` decorator on 044d02d. I wasn't wild about how this looked because I had to proxy through a factory function in order to get it to work.
That indirection bothered me enough to simplify things with a26e34a. Here I've moved the proxying up into the `onSelect` in the element, which seems better to me.
Finally, with 923cbac I went another direction entirely and switched to tracking the event through the prop that we get from decoration rather than using the decoration function itself. I think …
> DISCO-739: Add Tracking to Artwork Page Filters

- package.json
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
- src/Apps/Collect/Components/Filters/SortFilter.tsx
- src/Apps/Order/Routes/__tests__/Accept.test.tsx
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
- src/Apps/Order/Routes/__tests__/Reject.test.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.tsx.snap
- src/Components/__stories__/Icons.story.tsx
- src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
- src/Components/v2/Carousel.tsx
- src/Components/v2/__tests__/CountdownTimer.test.tsx
- yarn.lock
Follow-up to https://github.com/artsy/palette/pull/308 which fixes some stuff around 
- No more state full icons; e.g., HeartIcon -> HeartIcon + HeartFillIcon
- No more unnecessary displayNames; since all icons are now SFC's we get displayNames for free
- No more inconsistent colors; interfaces guard against passing anything not defined in theme, and no need for `color` helper
- No more inconsistent heights / widths / size props; these props all inherit from Icon base component
- Icons now have titles, so users and screen-readers and so on can get context.
> [Icons Upgrade] Fix incompatabilities

- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Video/VideoAbout.tsx
Minor, passes props.color to the video credits text, which was rendering black on black without.
Before:
After:
Not sure how long this bug has been around, but noticed that we are currently running a display campaign to direct traffic to the breaking glass video series, so seemed a good time to get those pages looking good.
> Pass props.color to /video credits

- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
- src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
- src/Apps/Search/Routes/Artworks/__tests__/SearchResultsArtworks.test.tsx
- src/Apps/Search/routes.tsx
- src/__generated__/SearchResultsArtistsRoute_viewer.graphql.ts
- src/__generated__/SearchResultsArtworksRoute_viewer.graphql.ts
- src/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
- src/__generated__/routes_SearchResultsArtworkQuery.graphql.ts
- src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
This fleshes out the basic contents for a tab (I went ahead and did two tabs, artwork and artist).
We don't have the nice fallback list item so these are just placeholders for now.
Up next:
- add in pagination
- create fallback list item and add
This will 'complete' the functionality for a given tab, the rest of the tabs should follow.
> @dblandin => [SearchResults] Add basic contents for a tab

- package.json
As [discussed in Slack](https://artsy.slack.com/archives/C02BC3HEJ/p1552399118228900) - 
I am having trouble getting things running locally, and it was suspected that I need to clean my yarn cache. @damassi suggested I add it to the clean task, as well.
> Clean `.cache` as part of `clean` task

- src/Components/Artwork/Save.tsx
I paired with @xtina-starr on this and after some poking around, we figured out that this `SaveButton` component's `handleSave` function could be improved to include a check for `IS_MOBILE` and use that experience when true.
We started by extracting a function called `openDesktopAuth` so that we could keep our logic in `handleSave` nice and neat. From there we investigated how to get access to `sd.IS_MOBILE` and found that it was an import away, so added sharify to the file. That set us up to add a check for that flag and open the mobile sign up by adding a `openMobileAuth` function.
The mobile signup flow encodes details in the URL, including a redirect url, so that's where we'll land after signing up/in.
> DISCO-738: Conditionally open mobile sign up when saving artwork

- src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
#2125 introduced a test failure that only reared it's head after being merged into master. This fixes that.
> test copy fix

- src/Components/v2/ArtistCard.tsx
The `onClick` event handler passed to the `<ArtistCard>` component is not also passed into the rendered result, preventing our analytic tracking behavior from executing as intended.
This commit ensures that the `onClick` handler makes its way down to a rendered element via the `<Link>` styled component from Palette.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-783 :lock: 
Also depends on https://github.com/artsy/force/pull/3718 to fix analytic tracking on the Artwork page overall.
> Pass ArtistCard onClick to <Link> component.

- src/Components/v2/Footer.tsx
The follow up on this one: https://github.com/artsy/force/pull/3716
to address reaction rendered footer.
Will also follow up with one more link update on force. Missed that this link also appears on Fair partner pages.
> updating artsy for galleries link

- src/Apps/__tests__/Fixtures/Collections.ts
- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/__generated__/ArtistCollectionEntity_collection.graphql.ts
- src/__generated__/ArtistCollectionsRailQuery.graphql.ts
- Fetches top 3 merchandisable artworks and includes images in artworks rail
- Displays 2 or 1 images if fewer than 3 are returned
- Displays headerImage as fallback if no artworks are returned
> Add images to ArtistCollectionRail

- src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
This link construction was incorrect and rather than resulting in a 404, the react router just sent us to the overview page. Fixed!
> DISCO-849: Fix the link to related artists

- src/Apps/Artist/Routes/Overview/index.tsx
There's been a lot of evolution on this artist page and the `showGenes` bit got a little wacky so I started by refactoring it down to it's simplest form. Then I took away the concept of showing and hiding genes at all - the goal here is to get an SEO lift from always showing these categories.
Here's how it looks:
> DISCO-851: Always show related categories for artist

- src/Apps/Artwork/ArtworkApp.tsx
This is the only change required to switch Criteo retargeting back on, as we can integrate it via Segment now.
> switch tracking event property for marketing

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
These colors were previously assumed but are now required. Here's what it looks like now:
> Fix bid icon colors

- src/Artsy/Analytics/Schema/Values.ts
Google Ads retargeting was broken during our artwork page redesign. This is an attempt to get it up and running again via Segment. 
* Renames the `Viewed Product` event to adopt the standard [Segment schema](https://segment.com/docs/spec/ecommerce/v2/#product-viewed) which should trigger Segment to notify Google Ads of the product ID.
After release I just need to update the AdRoll and Criteo integrations on the Segment side to use this event name.
> update viewed product analytics event

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/Routes/More/SearchResultsMore.tsx
- src/Apps/Search/Routes/More/__tests__/SearchResultsMore.test.tsx
- src/Apps/Search/routes.tsx
- src/__generated__/SearchResultsMoreQuery.graphql.ts
- src/__generated__/SearchResultsMore_viewer.graphql.ts
- src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
This adds in the 'More' tab in the same boilerplate-y way we have been, but here there's a list of entity types.
We need to handle searching for 'Institutions' in the same way we implemented the 'Gallery' custom thing, since that's the same deal- those aren't their own first-class 'entity', its actually a type of Profile.
> @dblandin => [SearchResults] Add 'more' tab

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarTitleInfo.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-705.
This PR brings back `h1`/`h2` elements to the Artworks pages, for improved SEO. 
As seen below, the artist name is the `h1`; the artwork name & date are the `h2`.
> Add h1/h2 to artwork pages

- src/Apps/Order/Dialogs.tsx
- src/Apps/Order/OrderApp.tsx
- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/Counter/index.tsx
- src/Apps/Order/Routes/NewPayment/index.tsx
- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/Reject/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Utils/__tests__/commitMutation.test.tsx
- src/Apps/Order/Utils/commitMutation.tsx
- src/DevTools/createTestEnv.tsx
- src/__generated__/commitMutationTest1Mutation.graphql.ts
Problems and solutions:
- We had some gnarly spaghetti logic because we were using the raw version of `commitMutation` which is built on callbacks, and things evolved organically over several months. I created a promise-based wrapper for `commitMutation` and did as much as I could to linearize the logic around invoking mutations and handling their results.
- Every page in the order app (except the status page) independently managed the state of whether or not a mutation is being committed. This state is used to show loading spinners and so forth. Here I abstracted that state management out into context land and made the `isCommittingMutation` state an injected prop.
This order app code was all quite well-tested and made it easy to work on this! Huge shout out to @sweir27 for keeping up …
> Refactor commitMutation usage

- src/Artsy/Router/Components/Boot.tsx
This PR removes an h1 reset, because with https://github.com/artsy/palette/pull/333, we have css resets built into palette for h1-h6.
> Remove h1 css reset from Boot now that Palette covers it

- src/Apps/Search/Components/GenericSearchResultItem.tsx
- src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
- src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
- src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
- src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
- src/Apps/Search/Routes/More/SearchResultsMore.tsx
- src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
This gray box will serve as a fallback for search result items that might have an image, but don't currently. We're also discussing new fallback images or icons for entity types that don't currently support an image at all, like City.
> Render a gray box for search result items without an image

- src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
- src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
- src/Components/v2/ArtistCard.tsx
This updates the Related Artist sections to lazy load their images (as those components appear well below the fold).
Most of the work was done in palette. See https://github.com/artsy/palette/pull/334.
> Enable lazy loading on related artist component
