artsy/reaction

.storybook/config.js

[storybook] For deploy we still use webpack, so make config available.

---

.storybook/webpack.config.js
package.json
yarn.lock

[storybook] Don’t typecheck on CI, we just check during dev.

---

.storybook/config.js

[storybook] Link webpack config for deploy tools.

---

src/__stories__/config.js
src/assets/fonts.tsx
src/components/__stories__/login_header.tsx
src/components/__stories__/title.tsx
src/components/icon.tsx
src/components/login_header.tsx
src/components/title.tsx

This adds the title component as well as updates the LoginHeader to use the new title component.  
**Title Component:**
**Updated LoginHeader Component:**

Title component

---

src/__stories__/config.js
src/components/__stories__/grid.tsx
src/components/grid.tsx

```jsx
const boxStyle = {
backgroundColor: '#f8f8f8'
height: '100px',
lineHeight: '100px',
textAlign: 'center'
}
<div style={{margin: '20px'}}>
<Row>
<Col><div style={boxStyle}>1</div></Col>
<Col><div style={boxStyle}>2</div></Col>
<Col><div style={boxStyle}>3</div></Col>
<Col><div style={boxStyle}>4</div></Col>
<Col><div style={boxStyle}>5</div></Col>
<Col><div style={boxStyle}>6</div></Col>
</Row>
<Row>
<Col><div style={boxStyle}>1</div></Col>
<Col><div style={boxStyle}>2</div></Col>
<Col><div style={boxStyle}>3</div></Col>
<Col><div style={boxStyle}>4</div></Col>
</Row>
<Row>
<Col><div style={boxStyle}>1</div></Col>
<Col><div style={boxStyle}>2</div></Col>
<Col><div style={boxStyle}>3</div></Col>
</Row>
<Row>
<Col><div style={boxStyle}>1</div></Col>
<Col><div …
```

Grid system component

---

.vscode/tasks.json
package.json
src/assets/fonts.tsx
src/components/__stories__/artwork.tsx
src/components/__stories__/artwork_grid.tsx
src/components/__stories__/buttons.tsx
src/components/__stories__/grid.tsx
src/components/__stories__/input.tsx
src/components/__tests__/__snapshots__/artwork.test.tsx.snap
src/components/__tests__/artwork.test.tsx
src/components/artwork/contact.tsx
src/components/artwork/details.tsx
src/components/artwork/index.tsx
src/components/artwork/metadata.tsx
src/components/artwork_grid.tsx
src/components/buttons/default.tsx
src/components/buttons/facebook.tsx
src/components/buttons/twitter.tsx
src/components/helpers.tsx
src/components/icon.tsx
src/components/input.tsx
src/components/mixins.tsx
src/components/modal_header.tsx
src/components/text_area.tsx
src/components/text_link.tsx
src/components/title.tsx
tslint.json
yarn.lock

* Adds 2 spaces indentation rule
* Removes extra space after curly brace in JSX. This did not make code more readable imo, especially when there are multiple nested braces, e.g. `<div style={ { … } } />`

Moar linting

---

circle.yml
package.json
src/components/artwork/contact.tsx
src/components/buttons/default.tsx

Small stuff, really.
Wanting to see if this fails on CI as expected.

Misc fixes

---

data/schema.graphql
data/schema.json
src/components/__stories__/artwork_grid.tsx
src/components/artwork/contact.tsx
src/components/artwork/index.tsx
src/components/artwork_grid.tsx

This supersedes #39:
* It is rebased
* Moves data the grid needs into the Grid Relay container
* Fixes type and lint errors

Updated artwork columns

---

src/__stories__/config.js
src/components/__stories__/modal.tsx
src/components/modal/modal.tsx

This is completely un-styled, but it's a start. Just wanted to get something up. I'll be adding the styling/overlay here, will ping once it's ready.

@l2succes => Super basic modal start

---

README.md

removed todo list

---

README.md
package.json

Hopefully not too controversial :)

@l2succes => Tiny bit of README clarifying and removal of pre-push

---

yarn.lock

Thx for pointing it out!
I had to re-add the entry to `package.json`, and then `yarn remove pre-push`.

@alloy => Updated lockfile after removing pre-push

---

package.json
src/apps/loyalty/containers/3w_thank_you/index.tsx
src/apps/loyalty/containers/acb_thank_you/index.tsx
src/apps/loyalty/server/index.tsx
src/components/__stories__/typography.tsx
src/components/__tests__/__snapshots__/artwork.test.tsx.snap
src/components/text.tsx
src/components/text_link.tsx

This is still WIP but would be nice if you could review this.

Loyalty Program thankyou page

---

src/apps/loyalty/containers/inquiries/index.tsx

Need to not only export the Relay container, but also the component itself.
See https://github.com/alloy/relational-theory/commit/2cc900ea216f61c7a4a8096bb9177a648b135129

[dev] Make HMR work on /inquiries.

---

index.js
package.json
src/apps/loyalty/server/index.tsx
yarn.lock

[dev] Mimic Force’s sessions setup and let sessions live for a year

---

.vscode/settings.json
gulpfile.js
package.json
src/apps/loyalty/server/index.tsx
src/apps/loyalty/server/template.tsx
webpack/base.js
webpack/production.js

@alloy => [dist] fixes paths for js bundles

---

src/components/__tests__/__snapshots__/artwork.test.tsx.snap
src/components/artwork/index.tsx
src/components/inquiry_artwork/index.tsx

[Loyalty] adds hover state for artwork brick

---

src/apps/loyalty/containers/inquiries/index.tsx

Another QA item in https://github.com/artsy/collector-experience/issues/228!

Add more space between artwork rows on the inquiries page

---

src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/login/index.tsx
src/components/text_link.tsx

Autofocuses input, and styles the 'or' divider thingie:

@l2succes => Few pieces of login QA

---

index.js
src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/inquiries/__tests__/index.tsx
src/relay/config.ts

@l2success => Use Metaphysics endpoint from env

---

index.js
package.json
src/apps/loyalty/containers/3w_thank_you/__tests__/index.ts
src/apps/loyalty/containers/3w_thank_you/index.tsx
src/apps/loyalty/containers/acb_thank_you/__tests__/index.ts
src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/inquiries/__tests__/index.tsx
src/apps/loyalty/containers/inquiries/index.tsx
src/apps/loyalty/containers/login/__tests__/index.tsx
webpack/base.js
webpack/development.js
yarn.lock

[Inquiries] Conditionally enable submit button.

---

src/apps/loyalty/containers/3w_thank_you/__tests__/__snapshots__/index.ts.snap
src/apps/loyalty/containers/acb_thank_you/__tests__/__snapshots__/index.ts.snap
src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
src/components/buttons/default.tsx

This is one of the QA items in https://github.com/artsy/collector-experience/issues/228

Hovering a button should change the cursor to pointer unless disabled

---

.vscode/settings.json
src/apps/loyalty/containers/3w_thank_you/__tests__/__snapshots__/index.ts.snap
src/apps/loyalty/containers/acb_thank_you/__tests__/__snapshots__/index.ts.snap
src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/inquiries/index.tsx
src/apps/loyalty/server/template.tsx
src/assets/theme.ts
src/components/__tests__/__snapshots__/artwork.test.tsx.snap
src/components/artwork/index.tsx
src/components/grid.tsx
src/components/helpers.tsx
src/components/nav.tsx
src/components/title.tsx

Fixes https://github.com/artsy/reaction-force/issues/100 & https://github.com/artsy/reaction-force/issues/93

@mzikherman => [Loyalty] adds responsiveness (mobile support) to inquiries page

---

circle.yml

https://circleci.com/docs/1.0/npm-continuous-deployment/

[WIP] configures CircleCI to publish to npm automatically

---

package.json
src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/components/__tests__/__snapshots__/artwork.test.tsx.snap
src/components/artwork/index.tsx
webpack/base.js
yarn.lock

Because of the opacity bug in IE11, we needed to give up on the nice transition, but in terms of functionality, it totally works fine now.

Better IE11 and IE Edge support

---

src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/components/buttons/inverted.tsx

Fixes https://github.com/artsy/reaction-force/issues/130

[Button] fixes disabled state styling

---

package.json
src/components/__stories__/save.tsx
src/components/artwork/save.tsx

For the sake of momentum, I'm going to try this extremely simple approach out and see if I can get a version into Force today.

@mzikherman - Save button logged out

---

src/components/artwork_filter/index.tsx

@broskoski - Adds missing tag_id param

---

data/schema.graphql
data/schema.json
package.json
src/components/artwork/save.tsx
src/components/artwork_filter/headline.tsx
src/components/artwork_filter/index.tsx
src/components/bordered_pulldown.tsx

I really [went through a lot](https://github.com/artsy/metaphysics/pull/622) to get the headline to say "Small Butt for Sale". The rest of it is style and bug fixes.

@mzikherman - some smaller fixes for ArtworkFilter

---

src/components/__stories__/artwork_grid.tsx

[grid] Make storybook work again.

---

src/components/__stories__/save.tsx
src/components/artwork/grid_item.tsx
src/components/artwork/save.tsx
src/components/artwork_filter/index.tsx

Thanks for the detailed issues!
Also closes #155

@alloy - Various QA for ArtworkFilter

---

src/apps/loyalty/containers/forgot_password/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/forgot_password/index.tsx
src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/login/index.tsx

We still don't have a signup page implemented yet.

Remove links to signup page

---

data/schema.graphql
data/schema.json
src/__stories__/config.js
src/components/__stories__/artist_follow.tsx
src/components/follow.tsx

@mzikherman - Add follow button component for artists

---

package.json
src/__stories__/config.js
src/apps/loyalty/containers/3w_thank_you/__tests__/__snapshots__/index.ts.snap
src/apps/loyalty/containers/acb_thank_you/__tests__/__snapshots__/index.ts.snap
src/apps/loyalty/containers/forgot_password/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/inquiries/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/login/__tests__/__snapshots__/index.tsx.snap
src/apps/loyalty/containers/repeat_visitor/__tests__/__snapshots__/index.ts.snap
src/components/__stories__/gene.tsx
src/components/__tests__/__snapshots__/artsy.test.tsx.snap
src/components/__tests__/__snapshots__/artwork.test.tsx.snap
src/components/artwork/details.tsx
src/components/artwork/fillwidth_item.tsx
src/components/buttons/ghost.tsx
src/components/gene/artist_row.tsx
src/components/gene/contents.tsx
src/components/gene/index.tsx
src/relay/queries/gene.ts
yarn.lock

~~This isn't totally working yet, still need to wire up the toggling between artist and artwork modes.~~

@mzikherman - Gene filter integration 

---

package.json
src/components/gene/artist_row.tsx
src/components/gene/contents.tsx
src/components/index.tsx
src/index.ts
src/relay/index.ts

As discussed in https://github.com/artsy/force/pull/1492 , some more exports to make it easier to initialize reaction-force components in force

Update reaction-force exports

---

data/schema.graphql
data/schema.json
package.json
src/__stories__/config.js
src/components/__stories__/fair_booth.tsx
src/components/fair/booth.tsx
src/components/follow.tsx
src/components/gene/artist_row.tsx
src/components/text.tsx
src/relay/queries/show.ts

Just getting some code up!
**TODO:**

Adds fair booth component

---

docs/getting_started.md

Based on my discussions with @eessex on porting a JS component into RF.
@anandaroop please read this before we pair tomorrow 👍

[Dev] Adds a getting started guide

---

README.md

My markdown style linter did a bunch of changes, but they aren't visible.
This is the key change:

[Dev] Update the README, for changes due to rename

---

src/components/publishing/__stories__/publishing.tsx
src/components/publishing/__stories__/typography.tsx
src/components/publishing/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/__test__/__snapshots__/imageset_preview.test.tsx.snap
src/components/publishing/__test__/__snapshots__/typography.test.tsx.snap
src/components/publishing/__test__/typography.test.tsx
src/components/publishing/fonts.tsx
src/components/publishing/image.tsx
src/components/publishing/imageset_preview.tsx

- Adds a story/style-guide for typography
- Changes size to font-size in font declarations
- Uses new font-format for imageset
- Adds min-width to image 'view fullscreen' button to prevent line-breaks

@kanaabe => Publishing typography story

---

src/components/publishing/__stories__/publishing.tsx
src/components/publishing/__stories__/typography.tsx
src/components/publishing/__test__/__snapshots__/imageset_preview.test.tsx.snap
src/components/publishing/__test__/__snapshots__/imageset_preview_classic.test.tsx.snap
src/components/publishing/__test__/__snapshots__/typography.test.tsx.snap
src/components/publishing/__test__/fixtures.tsx
src/components/publishing/__test__/imageset_preview.test.tsx
src/components/publishing/__test__/imageset_preview_classic.test.tsx
src/components/publishing/fonts.tsx
src/components/publishing/imageset_preview.tsx
src/components/publishing/imageset_preview_classic.tsx
src/components/publishing/index.tsx

New pr, same code...
- Adds imagesetPreview component for new article layouts
- Renames old image-set preview to 'imagesetPreviewClassic'
- [minor] bumps up min-width for 'view fullscreen' link in images
- adds Unica s12 and s16 sizes

@alloy => Imageset previews

---

src/components/publishing/__stories__/publishing.tsx
src/components/publishing/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/__test__/fixtures.tsx
src/components/publishing/__test__/image_collection.test.tsx
src/components/publishing/artwork.tsx
src/components/publishing/artwork_caption.tsx
src/components/publishing/image.tsx
src/components/publishing/image_collection.tsx
src/components/publishing/image_collection_item.tsx

- Adds responsiveness to `ImageCollection`
- Fixes bug with heights of `ImageCollectionItem`
- Fixes bug with missing info on `Artwork`

@eessex => Patches/Bugs on ImageCollection and Artwork components

---

src/components/publishing/__test__/__snapshots__/header.test.tsx.snap
src/components/publishing/__test__/fixtures.tsx
src/components/publishing/header/author_date.tsx
src/components/publishing/header/feature_header.tsx
src/components/publishing/header/header.tsx
src/components/publishing/header/standard_header.tsx

Thanks for the nice pair sesh! 👭 
- Allow children to be passed to `StandardHeader` and `FeatureHeader` so Writer can use it with Draft! 
- Support missing deck in fullscreen headers

@eessex=> [Pub] Extract children from Header components

---

src/components/publishing/__stories__/typography_examples.tsx
src/components/publishing/__test__/__snapshots__/imageset_preview_classic.test.tsx.snap
src/components/publishing/__test__/__snapshots__/section_container.test.tsx.snap
src/components/publishing/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/__test__/__snapshots__/text.test.tsx.snap
src/components/publishing/__test__/__snapshots__/typography.test.tsx.snap
src/components/publishing/__test__/fixtures/articles.ts
src/components/publishing/fonts.tsx
src/components/publishing/index.tsx
src/components/publishing/sections/section_container.tsx
src/components/publishing/sections/sections.tsx
src/components/publishing/sections/styled_text.tsx

- Exports featureHeader for use in Writer
- Updates fonts and typography examples with new/changed sizes
- Adds mobile text sizes for all layouts
- Sets blockquote width using section's layout attribute rather than searching html

@kanaabe => Responsive text

---

src/components/publishing/__test__/__snapshots__/sections.test.tsx.snap

It's a little concerning that these tests passed in the PR but not the deploy/merge to master -- but we're seeing https://circleci.com/gh/artsy/reaction/826 right now 😞

@alloy => Update section component snapshot

---

src/components/publishing/__test__/__snapshots__/header.test.tsx.snap
src/components/publishing/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/article.tsx
src/components/publishing/header/header.tsx
src/components/publishing/header/standard_header.tsx
src/components/publishing/layouts/standard_layout.tsx
src/components/publishing/sections/section_container.tsx
src/components/publishing/sections/sections.tsx

Minor updates to standard header.  Should span full width (1250) of page (over sidebar).

@kanaabe => Header tweaks

---

src/components/publishing/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/__test__/__snapshots__/header.test.tsx.snap
src/components/publishing/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/__test__/__snapshots__/imageset_preview.test.tsx.snap
src/components/publishing/__test__/__snapshots__/imageset_preview_classic.test.tsx.snap
src/components/publishing/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/__test__/__snapshots__/video.test.tsx.snap
src/components/publishing/header/feature_header.tsx
src/components/publishing/index.tsx
src/components/publishing/sections/artwork.tsx
src/components/publishing/sections/caption.tsx
src/components/publishing/sections/image.tsx
src/components/publishing/sections/imageset_preview.tsx
src/components/publishing/sections/imageset_preview_classic.tsx

- Adds caption or artwork title as alt text for all body images and artworks
- Adds title as alt text for header images
- Updates Caption component to accept children and exports

@kanaabe => Accessible images, caption accepts children

---

package.json
tslint.json
yarn.lock

This _should_ handle the quotes/doubles discussed here: https://artsy.slack.com/archives/C2TQ4PT8R/p1503429113000206

Simplify TSLint rules

---

src/components/publishing/__stories__/images.story.tsx
src/components/publishing/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/__test__/image.test.tsx
src/components/publishing/sections/image.tsx

Small update for Image component to accept children, and send them to the caption component.
Moves comment in image component out of render (was rendering)

@orta => Images send react children to caption

---

src/components/publishing/__stories__/header.story.tsx
src/components/publishing/__stories__/typography_examples.tsx
src/components/publishing/__test__/__snapshots__/typography.test.tsx.snap
src/components/publishing/fixtures/articles.ts
src/components/publishing/fonts.tsx
src/components/publishing/header/__test__/__snapshots__/header.test.tsx.snap
src/components/publishing/header/__test__/header.test.tsx
src/components/publishing/header/author_date.tsx
src/components/publishing/header/author_date_classic.tsx
src/components/publishing/header/classic_header.tsx
src/components/publishing/header/feature_header.tsx
src/components/publishing/header/header.tsx
src/components/publishing/header/standard_header.tsx
src/components/publishing/sections/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/caption.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/section_container.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/text.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/video.test.tsx.snap
src/components/publishing/sections/artwork_caption.tsx
src/components/publishing/sections/caption.tsx
src/components/publishing/sections/styled_text.tsx

- Adds Classic layout component to header
- Adds conditional in header for title & deck (was not showing children in writer)
- Addresses QA points except fullscreen icon [here](https://github.com/artsy/publishing/issues/45)

@kanaabe => Header Updates for Writer

---

src/components/publishing/__test__/__snapshots__/share.test.tsx.snap
src/components/publishing/article.tsx
src/components/publishing/layouts/sidebar.tsx
src/components/publishing/sections/__test__/__snapshots__/section_container.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/sections/section_container.tsx
src/components/publishing/sections/sections.tsx
src/components/publishing/share.tsx

Small QA items to address StandardLayout and Sidebar

@eessex => [QA] Minor Sidebar + StandardLayout

---

src/components/publishing/__stories__/typography.story.tsx
src/components/publishing/header/__test__/__snapshots__/header.test.tsx.snap
src/components/publishing/header/classic_header.tsx
src/components/publishing/header/feature_header.tsx
src/components/publishing/icon/image_fullscreen.tsx
src/components/publishing/index.tsx

- Adds an Icon for fullscreen image UI
- Removes header class selectors & replaces with styled component references
- Sets lead_paragraph width to 100%

@alloy => Icon fullscreen, minor QA

---

src/utils/fillwidth.ts

Also adds a limit on the number of iterations the loop may make.
Fixes #240, at least the freezing aspect. This code still could do with optimising, some layouts take 100s of iterations to calculate.

[fillwidth] Fix a couple of infinite loop bugs.

---

src/components/publishing/__stories__/typography.story.tsx
src/components/publishing/__test__/icon/__snapshots__/icon_imageset.test.tsx.snap
src/components/publishing/__test__/icon/__snapshots__/icon_remove.test.tsx.snap
src/components/publishing/icon/edit_embed.tsx
src/components/publishing/icon/edit_images.tsx
src/components/publishing/icon/edit_text.tsx
src/components/publishing/icon/edit_video.tsx
src/components/publishing/icon/expand.tsx
src/components/publishing/icon/hero_image.tsx
src/components/publishing/icon/hero_video.tsx
src/components/publishing/icon/image_fullscreen.tsx
src/components/publishing/icon/image_set.tsx
src/components/publishing/icon/layout_fullscreen.tsx
src/components/publishing/icon/layout_split.tsx
src/components/publishing/icon/layout_text.tsx
src/components/publishing/icon/remove.tsx
src/components/publishing/index.tsx
src/components/publishing/sections/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/imageset_preview.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/imageset_preview_classic.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/sections.test.tsx.snap

Adds a few more icons for Writer

@kanaabe => More Icons

---

src/components/publishing/__stories__/typography.story.tsx
src/components/publishing/icon/edit_section.tsx
src/components/publishing/index.tsx

One more icon for Writer.  Edit section Icon takes an isClosing prop to toggle display, as well as a fill color.

@kanaabe => Edit section icon

---

src/components/publishing/__test__/email_signup.test.tsx
src/components/publishing/constants.ts
src/components/publishing/email_signup.tsx

- Fixes a bug where the email was not being attached to `body`
- Adds simple client-side email validation based on regex

@eessex => Validation on <EmailSignup/>

---

src/components/publishing/email_signup.tsx

🙈  Missed one more step: I need to set the body to JSON and add the JSON content-type.
Going to self-merge this one since it's #minor!

@kanaabe => Sets email signup POST request content-type to json

---

src/components/publishing/__stories__/display.story.tsx
src/components/publishing/display/__test__/__snapshots__/display_panel.test.tsx.snap
src/components/publishing/display/__test__/display_panel.test.tsx
src/components/publishing/display/display_panel.tsx
src/components/publishing/fixtures/components.ts

Closes https://github.com/artsy/publishing/issues/38

@eessex => [Publishing] Display panel

---

package.json
src/components/gene/contents.tsx

https://artsy.slack.com/archives/C2TQ4PT8R/p1506968028000195

[gene] Fix invalid GraphQL query, `for_sale` filter is a boolean.

---

src/components/__stories__/icons.story.tsx

This adds a storybook for icons.

Add a storybook for icons

---

src/components/__stories__/collector_intent_page.story.tsx
src/components/artwork_filter/dropdown.tsx
src/components/onboarding/__stories__/selectable_link.story.tsx
src/components/onboarding/__stories__/wizard.story.tsx
src/components/onboarding/index.tsx
src/components/onboarding/selectable_link.tsx
src/components/onboarding/steps/artists.tsx
src/components/onboarding/steps/collector_intent.tsx
src/components/onboarding/steps/layout.tsx
src/components/onboarding/steps/step.tsx
src/components/onboarding/types.ts
src/components/onboarding/wizard.tsx

This is a WIP for the new onboarding flow and collector intent question more specifically. The ablility to submit and send the data to gravity along with some styling clean up still needs to be implemented.

@alloy: [Onboarding] created foundation

---

data/schema.graphql
data/schema.json

I'm not familiar with GraphQL, so please correct me if I'm wrong or missing. It seems like running `yarn sync-schema` and making a commit for the diff is necessary to use https://github.com/artsy/metaphysics/pull/770 in reaction.
Either way, the current schema is 3months old, so we should update the schema.

Update Graphql schema

---

src/components/publishing/__stories__/images.story.tsx
src/components/publishing/article.tsx
src/components/publishing/fixtures/components.ts
src/components/publishing/header/__test__/__snapshots__/feature_header.test.tsx.snap
src/components/publishing/header/feature_header.tsx
src/components/publishing/sections/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/caption.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/imageset_preview.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/video.test.tsx.snap
src/components/publishing/sections/artwork_caption.tsx
src/components/publishing/sections/caption.tsx
src/components/publishing/sections/fullscreen_viewer/__test__/__snapshots__/caption.test.tsx.snap
src/components/publishing/sections/fullscreen_viewer/__test__/__snapshots__/fullscreen_viewer.test.tsx.snap
src/components/publishing/sections/fullscreen_viewer/__test__/__snapshots__/slide.test.tsx.snap
src/components/publishing/sections/fullscreen_viewer/caption.tsx
src/components/publishing/sections/fullscreen_viewer/slide.tsx
src/components/publishing/sections/imageset_preview.tsx

Closes https://github.com/artsy/publishing/issues/55
and hits a few points in https://github.com/artsy/publishing/issues/49

[Publishing] QA in ImageSet, FullscreenViewer, etc.

---

src/components/publishing/article.tsx

This is needed to support feature layouts in Super Articles

[Publishing] Adds classname to article content #trivial

---

package.json
src/components/publishing/__stories__/article.story.tsx
src/components/publishing/__test__/email_signup.test.tsx
src/components/publishing/article.tsx
src/components/publishing/email_signup.tsx
src/components/publishing/read_more/__test__/read_more.test.tsx
src/components/publishing/read_more/read_more_wrapper.tsx
src/components/publishing/related_articles/__test__/__snapshots__/related_articles_canvas.test.tsx.snap
src/components/publishing/related_articles/related_articles_canvas.tsx
src/components/publishing/sections/__test__/__snapshots__/artwork.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/image_collection.test.tsx.snap
src/components/publishing/sections/__test__/__snapshots__/sections.test.tsx.snap
src/components/publishing/sections/image_collection.tsx
src/components/publishing/sections/image_wrapper.tsx
yarn.lock

See commit messages for specific fixes

[Publishing] @eessex => Another round of QA

---

src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
src/Components/Publishing/Display/Canvas/index.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap

Adds tracking events to Display Canvas interactions:
- Navigated Slideshow
- Played Video
Also adds some changes to the video component's play event -- using refs to play the video over e.target, and stops using a ternary operator for functions.

@craigspaeth => Display Analytics Tracking

---

src/Components/Publishing/index.tsx

Exports constants so we can start using these in Force!

[Publishing] @eessex => Export constants file #trivial

---

package.json
src/Components/Publishing/__stories__/Images.story.tsx
yarn.lock

The update to storybooks did fix the polyfill issue, thanks @alloy 🙌  I went ahead and updated the Image Collection story to support the fullscreen viewer because it was still hard to use in the simulator on other stories. After testing it out, it seems like it actually does work on iPhone, see below.
I figured I'd PR these updates as they're probably useful anyways.

@kanaabe: Update storybooks & story for image collections

---

src/Components/__stories__/Grid.story.tsx

It seems like there were some interface changes made to `Grid` and the storybook for Grid was broken.

Fix the storybook for grid

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.tsx.snap

Updates: Fullscreen button isn't working https://cl.ly/0s1t111J111i (https://www.artsy.net/article2/artsy-editorial-artist-weeks-animated-episode-broad-city)

@kanaabe => [Bugfix] Fullscreen mode

---

.vscode/settings.json

Reenable formatOnSave

---

src/Utils/Responsive.tsx

Specifically for test envs. 
#quickfix

Make responsive media more safe 

---

src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/__test__/FeatureHeader.test.tsx
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/__stories__/Header.story.tsx

Adds logos and links to Feature Headers for Super Articles.

@damassi => SuperArticle logos in Feature Headers

---

src/Assets/Colors.tsx

Another requirement of https://github.com/artsy/collector-experience/issues/609, we need this color for the introduction of the fair and the date for our public viewing.

Add the gray dark color #999999 to the Colors

---

src/Components/Publishing/Byline/__test__/__snapshots__/Byline.test.tsx.snap
src/Components/Publishing/Constants.ts
src/Components/Publishing/Header/__test__/__snapshots__/ClassicHeader.test.tsx.snap
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Header/__test__/__snapshots__/StandardHeader.test.tsx.snap
src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesPanel.test.tsx.snap

Tiny update to get https://github.com/artsy/force/pull/1843 working fully

@eessex => [Publishing] Update article2 constant

---

src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap

Adds a tracking call to FeatureHeader component, watches for clicks on a SuperArticle partner link.
Closes https://github.com/artsy/publishing/issues/134
Tracking information was taken from existing Force call here: https://github.com/artsy/force/blob/master/desktop/analytics/articles.js#L48

@craigspaeth => "clicked partner logo" event for super article

---

.storybook/webpack.config.js
src/Components/Publishing/Byline/AuthorDate.tsx
src/Components/Publishing/Byline/Byline.tsx
src/Components/Publishing/Byline/Share.tsx
src/Components/Publishing/Byline/__test__/__snapshots__/Byline.test.tsx.snap
src/Components/Publishing/Byline/__test__/__snapshots__/Share.test.tsx.snap
src/Components/Publishing/Constants.ts
src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Fixtures/Components.ts
src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/Header.tsx
src/Components/Publishing/Header/__test__/__snapshots__/ClassicHeader.test.tsx.snap
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Header/__test__/__snapshots__/StandardHeader.test.tsx.snap
src/Components/Publishing/Icon/IconLayoutBasic.tsx
src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/Sections/ArtworkCaption.tsx
src/Components/Publishing/Sections/ImageCollection.tsx
src/Components/Publishing/Sections/Video.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Artwork.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ImageCollection.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Video.test.tsx.snap
src/Components/Publishing/__stories__/Header.story.tsx
src/Components/Publishing/index.tsx
src/__stories__/config.js

Addresses https://github.com/artsy/publishing/issues/116
F1xes https://github.com/artsy/publishing/issues/136
Assocated PR https://github.com/artsy/positron/pull/1370
This PR adds a new "Basic Header" component into the mix:

@eessex => Add <BasicHeader />

---

src/Components/CircleIcon.tsx
src/Components/Onboarding/SelectableToggle.tsx
src/Components/__stories__/Icons.story.tsx

This refactors the budget component to uses dynamic styling and fix the icon for the budget component

[Onboarding] used dynamic styles for select option icon

---

src/Components/Publishing/Header/BasicHeader.tsx

Addresses 
- https://github.com/artsy/publishing/issues/134

@eessex => [Bugfixes / WIP] Fix logo scope click

---

src/Components/Publishing/Article.tsx
src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
src/Components/Publishing/Display/Canvas/index.tsx
src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.tsx.snap
src/Components/Publishing/Email/EmailPanel.tsx
src/Components/Publishing/Email/__test__/__snapshots__/EmailPanel.test.tsx.snap
src/Components/Publishing/RelatedArticles/RelatedArticlesCanvas.tsx
src/Components/Publishing/RelatedArticles/RelatedArticlesPanel.tsx
src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
src/Components/Publishing/__stories__/Article.story.tsx
src/Components/Publishing/__test__/Article.test.tsx

- Moves layout for margins in sidebar out of individual components
- Moves layout for margins in footer components mostly out
- Matches margins for canvas/related to article body

@damassi => More consistent margins

---

src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
src/Components/Publishing/Display/Canvas/index.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
src/Components/Publishing/__stories__/Article.story.tsx

Addresses https://github.com/artsy/publishing/issues/185

@eessex => Publishing canvas ad height

---

src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap

- Only render divider and partner logo if file is present
- Items are centered

@kanaabe => Superarticle header

---

src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/__stories__/Header.story.tsx

@damassi => Allows missing video in Basic header

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.tsx.snap
src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Sections/StyledText.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/SectionContainer.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Text.test.tsx.snap

- Kills this error https://sentry.io/artsynet/force-staging/issues/397512565/#
- Fixes letterboxing in panel video
- Adds bottom margin to feature fullscreen header

@damassi => More qa

---

.vscode/settings.json
src/Components/Publishing/Byline/Byline.tsx
src/Components/Publishing/Byline/__test__/__snapshots__/Byline.test.tsx.snap
src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Fixtures/Components.ts
src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Header/__test__/__snapshots__/ClassicHeader.test.tsx.snap
src/Components/Publishing/Header/__test__/__snapshots__/StandardHeader.test.tsx.snap
src/Components/Publishing/RelatedArticles/RelatedArticleFigure.tsx
src/Components/Publishing/RelatedArticles/__test__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/Sections/Artwork.tsx
src/Components/Publishing/Sections/ImageCollection.tsx
src/Components/Publishing/Sections/ImageSetPreview.tsx
src/Components/Publishing/Sections/ImageWrapper.tsx
src/Components/Publishing/Sections/Sections.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Artwork.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Image.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ImageCollection.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ImageSetPreview.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap

To get around the size-me flicker, this adds a slight fade to image load similar to how we currently do it. 
Addresses: 
- https://github.com/artsy/publishing/issues/188
- https://github.com/artsy/publishing/issues/157

@eessex => Fade images in on load

---

src/Components/Publishing/Sections/Sections.tsx

@damassi => Fix mobile ad

---

src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Sections/Video.tsx

@damassi => Fix aspect ratios

---

src/Components/Publishing/Sections/Sections.tsx

Postscript should appear after the author.

@kanaabe => Change order of postscript

---

src/Components/Publishing/Sections/ImageSetPreview.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/ImageSetPreview.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap

Publishing fix slideshows

---

src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
src/Components/Publishing/Display/Canvas/index.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap
src/Components/Publishing/Sections/VideoControls.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Video.test.tsx.snap

Address https://github.com/artsy/publishing/issues/206

@kanaabe => Fix CanvasDisplayVideo click-out

---

src/Components/Publishing/Byline/Share.tsx
src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Sections/Sections.tsx
src/Components/Publishing/Sections/Video.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.tsx.snap
src/Components/Publishing/__stories__/Article.story.tsx

Addresses 
- https://github.com/artsy/publishing/issues/200
- https://github.com/artsy/publishing/issues/189
https://www.artsy.net/article/artsy-editorial-happened-laurie-simmonss-dolls-life

@kanaabe => Publishing video margin

---

src/Components/Publishing/Header/BasicHeader.tsx

This is remarkably tricky between reaction and force and vimeo / youtube iframes and SSR and responsive breakpoints and what else? 🚬 
Addresses https://github.com/artsy/publishing/issues/188

Basic Margin

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap

@damassi => Only center on mobile

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap

Follow up to: https://github.com/artsy/reaction/pull/366

@craigspaeth => Add video tracking to <DisplayPanel />

---

src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap

Addresses https://github.com/artsy/publishing/issues/184
The margins aren't totally perfect (meaning, the spacing between the end of the ad and the next article inserted after infinite scroll) but we can return to it later as its hardly noticable:

@craigspaeth => Fix slideshow area on mobile

---

src/Components/Publishing/Sections/Video.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Video.test.tsx.snap

Adds a class to the video cover image so it can be targeted for css.

@kanaabe => [Minor] Video cover classname

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/DisplayPanel.test.js
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap

Resolves https://waffle.io/artsy/publishing/cards/5a00c4acc383f500114fed61

Mute-able video in panel unit

---

src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
src/Components/Publishing/Icon/IconPlus.tsx
src/Components/Publishing/Partner/PartnerBlock.tsx
src/Components/Publishing/Partner/PartnerInline.tsx
src/Components/Publishing/Partner/__test__/PartnerBlock.test.tsx
src/Components/Publishing/Partner/__test__/PartnerInline.test.tsx
src/Components/Publishing/Partner/__test__/__snapshots__/PartnerBlock.test.tsx.snap
src/Components/Publishing/Partner/__test__/__snapshots__/PartnerInline.test.tsx.snap
src/Components/Publishing/__stories__/Partner.story.tsx
src/Components/Publishing/__stories__/Typography.story.tsx

- Pulls in [these two components](https://github.com/artsy/force/tree/master/desktop/apps/editorial_features/components/gucci/components/partner) written by @eessex and Typescriptifies them
- Add tracking to these components (**WIP WAITING ON** the rest of info from: https://waffle.io/artsy/publishing/cards/5a032d9aaf310e0030bca7be)
- Adds `IconPlus`

@eessex => Partner components

---

src/Components/Publishing/Byline/Share.tsx
src/Components/Publishing/__stories__/Byline.story.tsx

Updates Share's tracking event to accept props.

@kanaabe => Share tracking accepts props

---

src/Components/Publishing/index.tsx

Export partner components

---

src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Icon/IconPlus.tsx
src/Components/Publishing/Partner/PartnerInline.tsx
src/Components/Publishing/Partner/__test__/__snapshots__/PartnerInline.test.tsx.snap
src/Components/Publishing/__stories__/Header.story.tsx

Related to https://github.com/artsy/publishing/issues/172
- Refactors `FeatureHeader` to user `PartnerInline` component for partner logo and link.
- Adds color prop to `IconPlus`
- (Minor) Update props for `StandardHeader` story with children

@kanaabe => SuperArticle Partner Header

---

src/Components/Publishing/Sections/Author.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Authors.test.tsx.snap

Related to https://github.com/artsy/publishing/issues/244
- Changes font-family/size for author bio, makes twitter handle match size.
- Bumps image size down to 60px

@kanaabe => Author updates

---

src/Components/Publishing/Display/Canvas/CanvasText.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayCanvas.test.tsx.snap

Addresses https://waffle.io/artsy/publishing/cards/5a00a0c66a5a7c0089c6c3b3

@eessex => Updates display logo sizes #minor

---

src/Components/Onboarding/Steps/Artists/ItemLink.tsx

[ItemLink] Working replacement of followed artist with suggested artist.

---

src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Sections/StyledText.tsx
src/Components/Publishing/Sections/Video.tsx
src/Components/Publishing/Sections/__test__/__snapshots__/Video.test.tsx.snap

- Fixes problem in drop-caps, conditional wasn't rendering font-family
- Adds pointer cursor to video covers
- Adds max-width to basic headers

@kanaabe => Minor QA

---

data/schema.graphql
data/schema.json
src/Components/Onboarding/Steps/CollectorIntent.tsx

This adds the actual data submission for the [collector intent question for onboarding](https://github.com/artsy/collector-experience/issues/504).

[Onboarding] sync schema and add collector profile mutation for collector intent

---

data/schema.graphql
data/schema.json
package.json
src/Components/Onboarding/Steps/Artists/ItemLink.tsx
src/Components/Onboarding/__stories__/Artists.story.tsx

cc @xtina-starr , didnt get very far with this! ::(

@alloy => A pitiful stab at updating the UI with the follow mutation

---

src/Components/Onboarding/Steps/Artists/ItemLink.tsx

* adds a patch from https://github.com/artsy/reaction/commit/20ddcf2b20ea9b17accbbec23285c8544d88427b.patch
* fixes the function to execute the follow artist mutation
* replaces `any` with appropriate types

Fix relay modern mutation

---

data/schema.json
src/Components/Onboarding/Steps/Budget.tsx
tsconfig.json

This adds the data submission for the [budget question](https://github.com/artsy/collector-experience/issues/507).

[Onboarding] add data submission for Budget question

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__test__/DisplayPanel.test.js
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
src/Components/Publishing/__stories__/Display.story.tsx

Addresses https://github.com/artsy/publishing/issues/258

@eessex => Support missing logos in the DisplayPanel ad

---

src/Components/Publishing/Fixtures/Helpers.tsx
src/Components/Publishing/Series/ArticleCard.tsx
src/Components/Publishing/Series/SeriesAbout.tsx
src/Components/Publishing/Series/SeriesTitle.tsx
src/Components/Publishing/Series/__test__/ArticleCard.test.tsx
src/Components/Publishing/Series/__test__/SeriesAbout.test.tsx
src/Components/Publishing/Series/__test__/SeriesTitle.test.tsx
src/Components/Publishing/Series/__test__/__snapshots__/ArticleCard.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/SeriesTitle.test.tsx.snap
src/Components/Publishing/__stories__/Series.story.tsx

In anticipation of editing new article types, adds support for rendering children to Series components.

@kanaabe => Series components accept children

---

src/Components/Helpers.tsx
src/Components/Onboarding/SelectableLink.tsx
src/Components/Onboarding/Steps/Artists/index.tsx
src/Components/Onboarding/Steps/Budget.tsx
src/Components/Onboarding/Steps/CollectorIntent.tsx
src/Components/Onboarding/Steps/Genes/index.tsx
src/Components/Onboarding/Steps/Layout.tsx
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap

Start to make collector intent view [mobile responsive](https://github.com/artsy/collector-experience/issues/607).

[Onboarding] make collector intent view mobile responsive

---

src/Components/Publishing/Series/ArticleCard.tsx
src/Components/Publishing/Series/Series.tsx
src/Components/Publishing/Series/__test__/ArticleCard.test.tsx
src/Components/Publishing/Series/__test__/__snapshots__/ArticleCard.test.tsx.snap
src/Components/Publishing/__stories__/Series.story.tsx

Minor changes for editing series/article card in writer:
- ArticleCard does not link out if editable fields are present
- ArticleCard accepts an editable date child
- Export SeriesContainer styled component

@kanaabe => More edit changes for series/article card

---

src/Components/Publishing/Partner/PartnerBlock.tsx
src/Components/Publishing/Partner/__test__/__snapshots__/PartnerBlock.test.tsx.snap
src/Components/Publishing/Series/ArticleCard.tsx
src/Components/Publishing/Series/Series.tsx
src/Components/Publishing/Series/SeriesAbout.tsx
src/Components/Publishing/Series/__test__/__snapshots__/ArticleCard.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/Series.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/SeriesTitle.test.tsx.snap
src/Components/Publishing/index.tsx

Addresses QA points in https://github.com/artsy/publishing/issues/265
Also adds a few exports

@kanaabe => Series qa

---

data/schema.graphql
data/schema.json
src/Components/Onboarding/ItemLink.tsx
src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx

* Adds ability to follow default list of suggested genes 
* Adds the ability to search and follow genes

Add ability to follow default suggested genes, and search and follow genes

---

src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx

This PR adds a filter that excludes duplicate genes when displaying a similar gene from search results. We'll have to implement the same to `<SuggesetedGenes>` but let's just make a small change so we can capture small mistakes early.

Exclude selected genes

---

src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Layouts/SeriesLayout.tsx
src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/__stories__/Article.story.tsx

All in SeriesLayout:
- Uses relatedArticles as prop, rather than related_article_ids
- Adds Nav
- Adds backgroundColor prop and defaults to black
- Adds support to render background images

@kanaabe => Minor Series updates

---

.env.oss
.storybook/webpack.config.js
src/Components/Artsy.tsx
src/Components/Onboarding/__stories__/Artists.story.tsx
src/Components/Onboarding/__stories__/Budget.story.tsx
src/Components/Onboarding/__stories__/Genes.story.tsx
src/Components/Onboarding/__stories__/Wizard.story.tsx
src/Components/__stories__/ArtistFollow.story.tsx
src/Components/__stories__/ArtworkGrid.story.tsx
src/Components/__stories__/Fillwidth.story.tsx
src/Components/__stories__/Gene.story.tsx
src/Components/__stories__/Save.story.tsx
src/Components/__stories__/Tag.story.tsx
src/Components/__tests__/Artsy.test.tsx
typings/gravity.d.ts

Also cleans up some more relics from the loyalty app, we don’t need the user’s name.

 [storybook] Use USER_ID and USER_ACCESS_TOKEN env vars to authenticate.

---

data/schema.graphql
data/schema.json
package.json
src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx

closes: https://github.com/artsy/collector-experience/issues/841

Exclude ids from gene default list

---

src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Video/VideoCover.tsx
src/Components/Publishing/Video/VideoInfoBlock.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoCover.test.tsx.snap
src/Components/Publishing/Video/__test__/__snapshots__/VideoInfoBlock.test.tsx.snap

Needed for proper absolute positioning when using editable props from the Writer side

@kanaabe => Adds relative positioning to a few components #minor

---

gulpfile.js
package.json
tsconfig.json
yarn.lock

@alloy => Updates to allow transpilation of ES6 -> ES5

---

src/Components/Publishing/Fixtures/Components.ts
src/Components/Publishing/Icon/IconVideoFullscreen.tsx
src/Components/Publishing/Icon/IconVideoPause.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoControls.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoPlayer.test.js.snap
src/Components/Publishing/Video/VideoAbout.tsx
src/Components/Publishing/Video/VideoCover.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap
src/Components/Publishing/Video/__test__/__snapshots__/VideoCover.test.tsx.snap

Pretty simple stuff. Commit messages explain the changes!

@eessex => Small Video QA

---

src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Nav/Nav.tsx
src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Partner/PartnerInline.tsx
src/Components/Publishing/Series/SeriesTitle.tsx
src/Components/Publishing/Series/__test__/__snapshots__/SeriesTitle.test.tsx.snap

- Bumps up the max-width on the title logo
- Makes logo link clickable and with better tracking

@kanaabe => More small QA

---

src/Components/Publishing/Layouts/VideoLayout.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Series/SeriesTitle.tsx
src/Components/Publishing/Series/__test__/__snapshots__/SeriesTitle.test.tsx.snap

Updates the SeriesTitle desktop max-width to 240px and fixes a title overflowing

@eessex => Updates logo sizes #minor

---

src/Components/Publishing/Layouts/VideoLayout.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Nav/Nav.tsx
src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Video/VideoCover.tsx
src/Components/Publishing/Video/VideoInfoBlock.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoCover.test.tsx.snap
src/Components/Publishing/Video/__test__/__snapshots__/VideoInfoBlock.test.tsx.snap

Changes explained in commit messages...

@kanaabe => Bmw qa

---

src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
src/Components/Onboarding/Steps/Artists/PopularArtists.tsx

This PR takes care of https://github.com/artsy/collector-experience/issues/842#issuecomment-353200862.

[Onboarding] Prevent already displayed artists from being suggested after following

---

circle.yml
data/schema.graphql
data/schema.json

Also added the compile step to the CI test task so this should make CI red next time.

Fix outdated schema compile error

---

src/Components/Publishing/Layouts/VideoLayout.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Nav/Nav.tsx
src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Series/SeriesAbout.tsx
src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
src/Components/Publishing/Video/Player/Scrubber.tsx
src/Components/Publishing/Video/Player/__test__/__snapshots__/Scrubber.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoControls.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoPlayer.test.js.snap
src/Components/Publishing/Video/VideoAbout.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap

Sorry, I opened the wrong branch. This is the one that fixes stuff for IE.

@damassi => Fixes IE for BMW

---

src/Components/Publishing/Layouts/VideoLayout.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Nav/Nav.tsx
src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Series/SeriesAbout.tsx
src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
src/Components/Publishing/Video/Player/Scrubber.tsx
src/Components/Publishing/Video/Player/__test__/__snapshots__/Scrubber.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoControls.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoPlayer.test.js.snap
src/Components/Publishing/Video/VideoAbout.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap

Revert "@damassi => Fixes IE for BMW"

---

src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Nav/Nav.tsx
src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Series/SeriesAbout.tsx
src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.tsx.snap
src/Components/Publishing/Video/Player/Scrubber.tsx
src/Components/Publishing/Video/Player/__test__/__snapshots__/Scrubber.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoControls.test.tsx.snap
src/Components/Publishing/Video/Player/__test__/__snapshots__/VideoPlayer.test.js.snap
src/Components/Publishing/Video/VideoAbout.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoAbout.test.tsx.snap

3rd time is the charm. Sorry for the multiple PRs, I should have just deleted the commits from my PR and re-applied changes

@damassi => Adds IE fixes without Prettier

---

src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Video/VideoCover.tsx
src/Components/Publishing/Video/__test__/__snapshots__/VideoCover.test.tsx.snap

@kanaabe => One more small IE fix

---

data/schema.graphql
data/schema.json

I'm just trying to get some stuff done while MP is down.

[schema] Update MP data schema

---

src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx

addresses the second task of https://github.com/artsy/collector-experience/issues/811.

[Onboarding] Display the first popular artist if no related artists are found for the artist that are just followed

---

data/schema.graphql
data/schema.json
src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
src/Components/Onboarding/Steps/Artists/PopularArtists.tsx

addresses the first task of https://github.com/artsy/collector-experience/issues/811. This is basically done but ~~I wanted to do more manual testing before merging so WIP~~ done some manual tests and this is working fine.

Follow popular artist without related artists

---

src/Components/Artist/MarketInsights.tsx
src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap
src/Components/index.tsx

Updated font + tweaked email/subject for feedback, and make sure its an available component once published.
looks like:

@mzikherman => Prepare to expose MarketInsights for admin QA

---

data/schema.graphql
data/schema.json
src/Components/Artist/MarketInsights/MarketInsights.tsx

@mzikherman => Only return trusted auction results for market insights

---

src/Components/Artist/MarketInsights/MarketInsights.tsx
src/Components/Publishing/Fonts.tsx
src/Components/Tooltip.tsx
src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap

@mzikherman => Some minor visual tweaks to market insights

---

src/Components/Gene/ArtistRow.tsx
src/Components/Gene/GeneArtworks.tsx
src/Components/Gene/GeneArtworksContent.tsx
src/Components/Gene/index.tsx
src/Components/Tag/TagArtworks.tsx
src/Components/Tag/TagArtworksContent.tsx
src/Components/Tag/index.tsx

Addresses the checked-off items in the first comment in https://github.com/artsy/collector-experience/issues/852  (commits tell the story).
I may feature-creep this with some more commits addressing QA items.

@alloy => Some gene/tag QA

---

src/Components/Tag/TagArtworks.tsx

@mzikherman => Add a bit of spacing in the tag headline

---

src/Components/Publishing/Header/FeatureHeader.tsx
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/__stories__/Header.story.tsx

Also adds some missing stories for children
Addresses https://waffle.io/artsy/publishing/cards/5a208e3ce70832001b3c72b2

@eessex => Use isVideo to check video file on <FeatureHeader>

---

src/Components/Gene/Artists.tsx
src/Components/Gene/index.tsx

I remember doing this minor QA item yesterday, so must have undid it or lost the commit :(

@mzikherman => Always show for sale button in artists mode

---

package.json
src/Components/Input.tsx
src/Utils/Responsive.tsx
yarn.lock

Follow up after noticing https://github.com/prettier/prettier/pull/3331

[Dep] Upgrade TypeScript to 2.6.2 for React <Fragment /> support 

---

src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Fixtures/Components.ts
src/Components/Publishing/Sections/ArtworkCaption.tsx
src/Components/Publishing/Sections/FullscreenViewer/__test__/__snapshots__/Caption.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__test__/__snapshots__/FullscreenViewer.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__test__/__snapshots__/Slide.test.tsx.snap
src/Components/Publishing/Sections/Truncator.tsx
src/Components/Publishing/Sections/__test__/ArtworkCaption.test.js
src/Components/Publishing/Sections/__test__/__snapshots__/Artwork.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ArtworkCaption.test.js.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ImageCollection.test.tsx.snap
src/Components/Publishing/Sections/__test__/__snapshots__/Sections.test.js.snap
src/Components/Publishing/__stories__/Images.story.tsx

Adds support for credits in artworks and restyles captions a bit. Addresses https://github.com/artsy/publishing/issues/306

@eessex => Artwork credits + restyle artwork captions

---

src/Components/Onboarding/ItemLink.tsx
src/Components/Onboarding/SelectableLink.tsx
src/Components/Onboarding/SelectableToggle.tsx
src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
src/Components/Onboarding/Steps/Artists/index.tsx
src/Components/Onboarding/Steps/Budget.tsx
src/Components/Onboarding/Steps/CollectorIntent.tsx
src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
src/Components/Onboarding/Steps/Genes/index.tsx
src/Components/Onboarding/Steps/Layout.tsx

- Replaces hardcoded colors with defined ones
- Use `font.x.style` to get full CSS for `letter-spacing` & `font-smoothing`

@xtina_starr => [Onboarding] Use color library and font styles

---

data/schema.graphql
data/schema.json

This updates reaction to use the latest schema from metaphysics.

update metaphysics schema

---

src/Assets/Icons/CircleBlackCheckIcon.tsx
src/Assets/Icons/CircleWhiteCheckIcon.tsx
src/Assets/Icons/PlusIcon.tsx
src/Components/Onboarding/ItemLink.tsx
src/Components/Onboarding/SelectableToggle.tsx
src/Components/Onboarding/Steps/CollectorIntent.tsx
src/Components/Onboarding/Steps/Layout.tsx

WIP. We can merge this once https://github.com/artsy/reaction/pull/508 is merged.

AR-73: Adjust styling and size of check mark and plus buttons

---

src/Components/Onboarding/Steps/Layout.tsx

finishes:
* [AR-92: Adjust header line height to 6px](https://artsyproduct.atlassian.net/browse/AR-92)
* [AR-93: Gradient should be top aligned with next/finish buttons](https://artsyproduct.atlassian.net/browse/AR-93)

Another round of UI QA

---

src/Components/Onboarding/ProgressIndicator.tsx
src/Components/Onboarding/SelectableToggle.tsx
src/Components/Onboarding/Steps/Artists/index.tsx
src/Components/Onboarding/Steps/Budget.tsx
src/Components/Onboarding/Steps/CollectorIntent.tsx
src/Components/Onboarding/Steps/Genes/index.tsx
src/Components/Onboarding/Steps/Layout.tsx
src/Components/Title.tsx
src/Components/__stories__/Typography.story.tsx

Addresses the "In Progress" cards in: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-69

@yuki24 => [Onboarding] Style QA PT.2

---

package.json

Add `src` to published module code so that we can pull direct TS sources into force

[Toolchain] Add src to `files` package.json entry

---

package.json

Bump to 0.21.0, including `src` access.

[Version] 0.21.0

---

.storybook/webpack.config.js
tsconfig.json

Makes our error messages a little more useful / fast

[Webpack] Cleanup error message

---

package.json

Deploying https://github.com/artsy/reaction/pull/522

[Version] 0.22.0

---

src/Components/Onboarding/Steps/Artists/ArtistList.tsx
src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
src/Components/Onboarding/Wizard.tsx

Addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-96

@yuki24 => [Onboarding] Analytics

---

tsconfig.json

Reverts artsy/reaction#525
Larger discussion [in slack](https://artsy.slack.com/archives/C2TQ4PT8R/p1518730708000414), but looks to me like we'll be shipping ts files for the moment.

Revert "Adds inline type definitions to all files exported by Reaction"

---

src/Components/Onboarding/Steps/Layout.tsx

Addresses the style reverts in: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&selectedIssue=AR-69

@xtina-starr => [Onboarding] Revert some style changes

---

README.md
package.json
src/Components/Publishing/Display/__test__/__snapshots__/DisplayPanel.test.js.snap
src/Components/Publishing/Header/__test__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Nav/__test__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ArtworkCaption.test.js.snap
src/Components/Publishing/Sections/__test__/__snapshots__/ImageSetPreview.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/ArticleCard.test.tsx.snap
src/Components/Publishing/Series/__test__/__snapshots__/SeriesAbout.test.js.snap
src/Components/Publishing/Series/__test__/__snapshots__/SeriesTitle.test.tsx.snap
yarn.lock

Renames package from `reaction-force` to `reaction`

[Dev] renames package

---

src/Components/Onboarding/Wizard.tsx

I removed it in #2163 by accident so I'm adding it back.

[FIX onboarding] Add back redirectTo prop to <Wizard>

---

src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
src/Components/Onboarding/Wizard.tsx
src/Components/Onboarding/__stories__/Wizard.story.tsx

Addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-244

@yuki24 => Update context_module on genes

---

.prettierignore
package.json

Ran into a weird edge-case / race condition in Force around SSR. Downgrading to 2.x fixes it

[FIX lib] Downgrade styled-components peerDep to 2.x

---

src/Components/Buttons/MultiStateButton.tsx
src/Components/Buttons/index.tsx
src/Components/Onboarding/Steps/Artists/index.tsx
src/Components/Onboarding/Steps/Budget.tsx
src/Components/Onboarding/Steps/CollectorIntent.tsx
src/Components/Onboarding/Steps/Genes/index.tsx
src/Components/Onboarding/Steps/Layout.tsx
src/Components/__stories__/Buttons.story.tsx

Fixes [AR-211](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-211).

@yuki24: adds new button to reflect different states

---

src/Components/Onboarding/Wizard.tsx

This is the last piece of the puzzle...

Make sure to specify the correct paths that do not trigger redirection

---

src/Components/Publishing/Fixtures/Articles.ts

Adds fixture for article with layout of "news"

@kanaabe => [Newsfeed] News fixture

---

src/Components/Publishing/Display/DisplayPanel.tsx
src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.js.snap

Addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-251

@eessex => Fixes hover bug on DisplayPanel

---

src/Components/Publishing/Article.tsx
src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Layouts/NewsLayout.tsx
src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/News/NewsHeadline.tsx
src/Components/Publishing/News/NewsSections.tsx
src/Components/Publishing/News/__tests__/__snapshots__/NewsHeadline.test.tsx.snap
src/Components/Publishing/Sections/ImageCollection.tsx
src/Components/Publishing/Sections/ImageCollectionItem.tsx
src/Components/Publishing/Sections/ImageWrapper.tsx
src/Components/Publishing/Sections/NewsSections.tsx
src/Components/Publishing/Sections/SectionContainer.tsx
src/Components/Publishing/Sections/Sections.tsx
src/Components/Publishing/Sections/StyledText.tsx
src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Text.test.tsx.snap
src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.js.snap
src/Components/Publishing/Typings.ts
src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
src/Components/Publishing/__stories__/Article.story.tsx
src/Components/Publishing/__stories__/Text.story.tsx
src/Components/Publishing/__tests__/Article.test.tsx

This adds a NewsLayout and NewsSections components to the mix. The NewsLayout gets used by the main Article component to render a full article.

@sarahscott => News article parent component

---

src/Components/Publishing/Byline/AuthorDate.tsx
src/Components/Publishing/Byline/Byline.tsx
src/Components/Publishing/Byline/NewsByline.tsx
src/Components/Publishing/Byline/Share.tsx
src/Components/Publishing/Byline/__tests__/AuthorDate.test.tsx
src/Components/Publishing/Byline/__tests__/NewsByline.test.tsx
src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
src/Components/Publishing/Constants.ts
src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
src/Components/Publishing/News/NewsSections.tsx
src/Components/Publishing/RelatedArticles/RelatedArticleFigure.tsx
src/Components/Publishing/Sections/Artwork.tsx
src/Components/Publishing/Sections/ArtworkCaption.tsx
src/Components/Publishing/Sections/Caption.tsx
src/Components/Publishing/Sections/Image.tsx
src/Components/Publishing/Sections/ImageCollection.tsx
src/Components/Publishing/Sections/ImageWrapper.tsx
src/Components/Publishing/Sections/SectionContainer.tsx
src/Components/Publishing/Sections/Sections.tsx
src/Components/Publishing/Sections/StyledText.tsx
src/Components/Publishing/Sections/Text.tsx
src/Components/Publishing/Sections/Video.tsx
src/Components/Publishing/Sections/__tests__/SectionContainer.test.tsx
src/Components/Publishing/Series/ArticleCard.tsx
src/Components/Publishing/Typings.ts
src/Components/Publishing/__stories__/Byline.story.tsx

This pr is super long because of prettier!! Apologies for that 🙈 
Desktop:
Mobile:

@kanaabe => News Byline & updated typings

---

src/Components/Publishing/News/NewsSections.tsx
src/Components/Publishing/Sections/SocialEmbed.tsx
src/Components/Publishing/Typings.ts
src/Components/Publishing/__stories__/Article.story.tsx

This doesn't affect functionality; it just makes it easier to keep section types in order 😊

@eessex => stricter section typings

---

data/schema.graphql
src/Components/Publishing/Byline/Byline.tsx
src/Components/Publishing/Fixtures/Articles.ts
src/Components/Publishing/Header/BasicHeader.tsx
src/Components/Publishing/Header/ClassicHeader.tsx
src/Components/Publishing/RelatedArticles/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap

Deprecates contributing_authors in Reaction.
Dependent on updated graphql fetch in Force.

@kanaabe => Replace contributing_authors with authors

---

src/Components/Publishing/Byline/DateAndSource.tsx
src/Components/Publishing/Byline/DateSource.tsx
src/Components/Publishing/Byline/NewsByline.tsx
src/Components/Publishing/Byline/__tests__/DateSource.tsx
src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
src/Components/Publishing/__stories__/Byline.story.tsx

Makes the source of a news article editable. I also separated DateSource from NewsByline since there were two components in that file. Makes it a little easier to test and read.

@eessex => Editable source

---

src/Components/Publishing/Icon/IconLock.tsx

Small warning I noticed over in Positron's console.

@l2succes => Use JSX syntax for IconLock #minor

---

src/Components/Publishing/Display/Canvas/index.tsx
src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.js.snap

@kanaabe => Update copy: Advertisement by -> Sponsored by

---

src/Components/Publishing/Sections/Artwork.tsx
src/Components/Publishing/Sections/ArtworkCaption.tsx
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.js.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap
src/Components/Publishing/__stories__/Images.story.tsx

Before:
After:
Fixes https://artsyproduct.atlassian.net/browse/GROWTH-254

@eessex => nowrap for single artist names; wrap for multiple

---

src/Components/Publishing/RelatedArticles/RelatedArticlesCanvas.tsx
src/Components/Publishing/RelatedArticles/__tests__/RelatedArticlesCanvas.test.tsx
src/Components/Publishing/RelatedArticles/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/__stories__/RelatedArticles.story.tsx

Does not require a vertical and supports some default title. This will be used in News!

@eessex => More flexible RelatedArticlesCanvas

---

src/Components/Publishing/Nav/NewsNav.tsx
src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap

Allows passing a prop for NewsNav fixed top position

@kanaabe => Use props for NewsNav position top

---

src/Assets/Animations.tsx
src/Components/Input.tsx
src/Components/__stories__/Input.story.tsx

This PR adds support for labels on our Input component by setting a `label` prop.

Adds label to Input component

---

src/Components/Publishing/Layouts/NewsLayout.tsx
src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap

Puts back article expand click action, only for desktop.

@xtina-starr => Restore expand on article click for desktop

---

src/Components/Publishing/Byline/NewsByline.tsx
src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
src/Components/Publishing/Layouts/NewsLayout.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
src/Components/Publishing/Nav/NewsNav.tsx
src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
src/Components/Publishing/News/NewsSections.tsx

Addresses [GROW-439](https://artsyproduct.atlassian.net/browse/GROW-439)  & [GROW-440](https://artsyproduct.atlassian.net/browse/GROW-440)
- Fixes margins in news article sections
- Renames 'the news' to 'news' in header nav

@kanaabe => [Newsfeed] QA

---

src/Components/Publishing/Layouts/NewsLayout.tsx
src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx

Addresses https://artsyproduct.atlassian.net/browse/GROW-445

@sarahscott => [News] Small Hover updates

---

src/Components/Publishing/Constants.ts
src/Components/Publishing/Fonts.tsx
src/Components/Publishing/News/NewsPanel.tsx
src/Components/Publishing/News/__tests__/NewsPanel.test.tsx
src/Components/Publishing/News/__tests__/__snapshots__/NewsPanel.test.tsx.snap
src/Components/Publishing/Typings.ts
src/Components/Publishing/__stories__/News.story.tsx

Adds 'NewsPanel' component for entry point to `/news` on the main editorial page.

@sarahscott => NewsPanel component

---

src/Components/Publishing/Byline/DateSource.tsx
src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap

- Adds `target="_blank"` to News source URLs

@sarahscott => Blank target for News source

---

src/Components/Publishing/News/NewsPanel.tsx
src/Components/Publishing/News/__tests__/NewsPanel.test.tsx

Fixes links to article pages in NewsPanel component.

@kanaabe => NewsPanel appends article slug with /news

---

src/Components/Publishing/Article.tsx
src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
src/Components/Publishing/__tests__/Article.test.tsx

Related to https://github.com/artsy/reaction/pull/625-- Adds a commit trigger for layout refactor, renames ArticleLayout component

Rename ArticleLayout as ArticleWithFullScreen

---

src/Components/Authorization/commonElements.tsx

Fixes some `yarn type-check` issues related to WIP work. 
cc @xtina-starr @l2succes

Fix TSC issues

---

src/Components/Publishing/Header/__tests__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.js.snap
src/Components/Publishing/Partner/PartnerBlock.tsx
src/Components/Publishing/Partner/PartnerInline.tsx
src/Components/Publishing/Partner/__tests__/__snapshots__/PartnerBlock.test.tsx.snap
src/Components/Publishing/Partner/__tests__/__snapshots__/PartnerInline.test.tsx.snap
src/Components/Publishing/Series/SeriesTitle.tsx
src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.js.snap
src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap

Addresses [GROW-432](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-432)

@l2succes => Sponsor logo size updates

---

src/Components/Publishing/Layouts/FeatureLayout.tsx
src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx

Use the `seriesArticle` that's already available from `article` instead of as a prop.

@eessex => Use seriesArticle from article instead of a prop

---

src/Components/Publishing/Byline/DateSource.tsx
src/Components/Publishing/Byline/__tests__/DateSource.test.js
src/Components/Publishing/Layouts/NewsLayout.tsx
src/Components/Publishing/Layouts/__tests__/NewsLayout.test.js

Addresses https://artsyproduct.atlassian.net/browse/GROW-460

@eessex => Updates analytics to include new naming

---

src/Components/Publishing/Partner/PartnerBlock.tsx

Adds a few conditionals to the PartnerBlock component to prevent showing title text when no image is present.

@xtina-starr => Conditionally show partner info

---

README.md

Adds note about required context.

@l2succes => Update readme for semantic-release

---

src/Components/Publishing/Fixtures/Components.ts
src/Components/Publishing/ToolTip/Components/ArrowDown.tsx
src/Components/Publishing/ToolTip/Components/FollowButton.tsx
src/Components/Publishing/ToolTip/Components/NewFeature.tsx
src/Components/Publishing/ToolTip/Gene.tsx
src/Components/Publishing/ToolTip/ToolTip.tsx
src/Components/Publishing/ToolTip/__tests__/ToolTip.test.tsx
src/Components/Publishing/ToolTip/__tests__/__snapshots__/ToolTip.test.tsx.snap
src/Components/Publishing/__stories__/ToolTip.story.tsx

- Adds ToolTip that accepts a model and entity data, to display styled box w/ arrow and select sub-component
- Adds GeneToolTip component to show gene data
- Adds placeholder FollowButton with styles, assuming this will be replaced with Relay logic
- Adds NewFeature component to show feedback info
One thing I noticed is that the image is blurry -- changing the quality doesn't fix, maybe there is a better query for this?
Also note that the text is in italics because it is markdown from rich text.

@xtina-starr => ToolTip parent component, GeneToolTip

---

package.json
src/Components/Publishing/Constants.ts
src/Components/Publishing/__tests__/Constants.test.ts

Util methods for tooltips, parses article text for artsy links and returns arrays of artsy ids by models.

@l2succes => Parse text for artsy links

---

src/Components/Publishing/Fixtures/Components.ts
src/Components/Publishing/ToolTip/Artist.tsx
src/Components/Publishing/ToolTip/Components/ArtistMarketData.tsx
src/Components/Publishing/ToolTip/Components/Description.tsx
src/Components/Publishing/ToolTip/Components/FollowButton.tsx
src/Components/Publishing/ToolTip/Components/NewFeature.tsx
src/Components/Publishing/ToolTip/Gene.tsx
src/Components/Publishing/ToolTip/ToolTip.tsx
src/Components/Publishing/ToolTip/__tests__/Artist.test.tsx
src/Components/Publishing/ToolTip/__tests__/ArtistMarketData.test.js
src/Components/Publishing/ToolTip/__tests__/ToolTip.test.tsx
src/Components/Publishing/ToolTip/__tests__/__snapshots__/ToolTip.test.tsx.snap
src/Components/Publishing/__stories__/ToolTip.story.tsx

Artist genes will be covered in a separate PR once Metaphysics work is in.  For now, if `showMarketData` is true and no data is available, it reverts to artist `blurb`.

@l2succes => Artist tooltip

---

src/Assets/Fonts.tsx
src/Assets/Icons/ClosedEye.tsx
src/Assets/Icons/OpenEye.tsx
src/Components/Authorization/AuthForm.tsx
src/Components/Authorization/DesktopHeader.tsx
src/Components/Authorization/DesktopModal.tsx
src/Components/Authorization/LoginForm.tsx
src/Components/Authorization/RegisterForm.tsx
src/Components/Authorization/ResetPasswordForm.tsx
src/Components/Authorization/Validators.ts
src/Components/Authorization/commonElements.tsx
src/Components/Checkbox.tsx
src/Components/Input.tsx
src/Components/Nav/__test__/__snapshots__/MobileMenu.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap
src/Components/TextLink.tsx
src/Components/__stories__/AuthForm.story.tsx
src/Components/__tests__/__snapshots__/Artwork.test.tsx.snap
src/Components/__tests__/__snapshots__/MarketInsights.test.tsx.snap

Lots of little things, most of them outlined in here: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROWTH&modal=detail&selectedIssue=GROW-533

@l2succes => Auth style and validation updates

---

.storybook/webpack.config.js
src/Components/Authorization/Mobile/RegisterForm.tsx
src/Components/Authorization/Mobile/__stories__/RegisterForm.story.tsx
src/Components/Authorization/Validators.ts
src/Components/Authorization/commonElements.tsx
src/Components/Input.tsx
src/Components/Wizard/Wizard.tsx
src/Components/Wizard/types.ts
src/Utils/__test__/metaphysics.test.ts
src/Utils/metaphysics.ts
typings/gravity.d.ts
typings/sharify.d.ts

Included in this PR:
- Extend Metaphysics module to accept XAPP-TOKEN
- Wires up validations and includes custom email validation for mobile
- Adds progress bar and other styling
ToDO to complete mobile UI Auth components:

Mobile ui components

---

data/schema.graphql
data/schema.json
src/Components/FollowButton/FollowGeneButton.tsx
src/Components/FollowButton/__tests__/Button.test.tsx
src/Components/FollowButton/__tests__/__snapshots__/Button.test.tsx.snap
src/Components/__stories__/FollowButton.story.tsx
src/__generated__/FollowGeneButtonMutation.graphql.ts
src/__generated__/FollowGeneButton_gene.graphql.ts

Adds a button with mutations to follow a gene.

@alloy => FollowGeneButton

---

src/Components/Publishing/ToolTip/GeneToolTip.tsx
src/Components/Publishing/ToolTip/__tests__/__snapshots__/ToolTip.test.tsx.snap

Quick swap out to the new button.

@l2succes => Gene tooltip uses relay follow

---

src/Components/Authorization/AuthForm.tsx
src/Components/Authorization/DesktopModal.tsx
src/Components/Authorization/LoginForm.tsx
src/Components/Authorization/Mobile/RegisterForm.tsx
src/Components/Authorization/Mobile/__stories__/RegisterForm.story.tsx
src/Components/Authorization/RegisterForm.tsx
src/Components/Authorization/ResetPasswordForm.tsx
src/Components/Authorization/Types.ts
src/Components/Authorization/commonElements.tsx
src/Components/__stories__/AuthForm.story.tsx

This simplifies the `<ChangeMode>` component to just use the `onClick` property.

use onClick property instead of handleClick for changing the type of modal rendered

---

src/Components/Publishing/__stories__/ArticleFeature.story.tsx
src/Components/Publishing/__stories__/ArticleNews.story.tsx
src/Components/Publishing/__stories__/ArticleSeries.story.tsx
src/Components/Publishing/__stories__/ArticleStandard.story.tsx
src/Components/Publishing/__stories__/ArticleVideo.story.tsx
src/Components/Publishing/__stories__/Artwork.story.tsx
src/Components/Publishing/__stories__/Byline.story.tsx
src/Components/Publishing/__stories__/Display.story.tsx
src/Components/Publishing/__stories__/Header.story.tsx
src/Components/Publishing/__stories__/Image.story.tsx
src/Components/Publishing/__stories__/ImageCollection.story.tsx
src/Components/Publishing/__stories__/ImageSetPreview.story.tsx
src/Components/Publishing/__stories__/News.story.tsx
src/Components/Publishing/__stories__/RelatedArticleCards.story.tsx
src/Components/Publishing/__stories__/RelatedArticles.story.tsx
src/Components/Publishing/__stories__/Sections.story.tsx
src/Components/Publishing/__stories__/Series.story.tsx
src/Components/Publishing/__stories__/Text.story.tsx
src/Components/Publishing/__stories__/ToolTip.story.tsx
src/Components/Publishing/__stories__/Video.story.tsx
src/__generated__/ArtistToolTip_artist.graphql.ts
src/__generated__/FollowArtistButtonMutation.graphql.ts
src/__generated__/FollowArtistButton_artist.graphql.ts
src/__generated__/FollowGeneButtonMutation.graphql.ts
src/__generated__/FollowGeneButton_gene.graphql.ts
src/__generated__/GeneToolTip_gene.graphql.ts
src/__generated__/TooltipsDataLoaderQuery.graphql.ts

A quick re-org of our stories to use the recently added nested subdirectories.  Makes navigation easier, and breaks out layout variations more legibly.

@xtina-starr => Use nested directories in publishing stories

---

src/Components/FollowButton/FollowArtistButton.tsx
src/Components/FollowButton/FollowGeneButton.tsx
src/Components/FollowButton/__tests__/Button.test.tsx
src/Components/Publishing/Article.tsx
src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
src/Components/Publishing/ToolTip/ArtistToolTip.tsx
src/Components/Publishing/ToolTip/GeneToolTip.tsx
src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
src/Components/Publishing/ToolTip/__tests__/GeneTooltip.test.tsx
src/Components/Publishing/ToolTip/__tests__/LinkWithTooltip.test.js
src/__generated__/ArtistToolTip_artist.graphql.ts
src/__generated__/GeneToolTip_gene.graphql.ts
src/__generated__/TooltipsDataLoaderQuery.graphql.ts

@eessex => Adds open auth modal hook to tooltips

[PATCH] update branch

---

src/Components/FollowButton/FollowArtistButton.tsx
src/Components/FollowButton/FollowGeneButton.tsx
src/Components/FollowButton/__tests__/Button.test.tsx
src/Components/Publishing/Article.tsx
src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
src/Components/Publishing/ToolTip/ArtistToolTip.tsx
src/Components/Publishing/ToolTip/GeneToolTip.tsx
src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
src/Components/Publishing/ToolTip/__tests__/GeneTooltip.test.tsx
src/Components/Publishing/ToolTip/__tests__/LinkWithTooltip.test.js
src/__generated__/ArtistToolTip_artist.graphql.ts
src/__generated__/GeneToolTip_gene.graphql.ts
src/__generated__/TooltipsDataLoaderQuery.graphql.ts

The commit message didn't have a CONTEXT in the last one

[PATCH tooltips] bump reaction

---

src/Components/Publishing/Fixtures/Helpers.tsx
src/Components/Publishing/Layouts/StandardLayout.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.js.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.js.snap
src/Components/Publishing/ReadMore/ReadMoreWrapper.tsx
src/Components/Publishing/ReadMore/__tests__/ReadMore.test.tsx
src/Components/Publishing/Sections/StyledText.tsx
src/Components/Publishing/Sections/Text.tsx
src/Components/Publishing/Sections/__tests__/Text.test.tsx
src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.js.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Text.test.tsx.snap
src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.js.snap
src/Components/Publishing/ToolTip/Components/Description.tsx
src/Components/Publishing/ToolTip/Components/NewFeature.tsx
src/Components/Publishing/ToolTip/__tests__/__snapshots__/ToolTip.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
src/Components/Publishing/__stories__/ToolTip.story.tsx

Addresses: [GROW-678](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-678), [GROW-660](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-660), and fixes some issues with link styles inside tooltips.

@l2success => ToolTip QA

---

src/Components/Artist/MarketInsights/MarketInsights.tsx
src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.js.snap

#minor. To make this component look better on smaller screens

Update paddings for MarketInsights

---

src/Components/Authentication/Desktop/Components/DesktopModal.tsx
src/Components/Authentication/Desktop/ModalManager.tsx
src/Components/Authentication/Types.ts

Related to https://artsyproduct.atlassian.net/browse/GROW-628
This adds a modal authentication interface and passes the entire options object via the openModal function.

add authentication modal options interface

---

src/Styleguide/Artwork/Banner.tsx
src/Styleguide/Artwork/__stories__/Banner.story.tsx
src/Styleguide/Elements/Flex.tsx
src/Styleguide/StyledSystemTypes.ts

Second pass at refining the banner for the new artwork page.
The Flex component could likely be shared... also, we'll want to start breaking out the types for styled-system being as it doesn't provide its own.

Implement banner for new artwork page

---

src/Styleguide/Utils/ColorPreview.tsx

Fix palette path 

---

src/Styleguide/Elements/Button.tsx
src/Styleguide/Elements/Flex.tsx
src/Styleguide/Elements/Grid.tsx
src/Styleguide/Elements/__stories__/Button.story.tsx
src/Styleguide/Elements/index.tsx
src/Styleguide/__stories__/Styleguide.story.tsx
typings/styled-system.d.ts

Adding a few elements to the lib. Primary API: 
```jsx
<Button>Click me</Button>
<Button variant='outline'>Click me</Button>
<Button size='small'>Click me</Button>
```
Other common props can be passed through via styled-system, e.g.,: 
```jsx
<Button width='50%' />
```

@zephraph => Add <Button /> element 

---

src/Components/Authentication/Desktop/SignUpForm.tsx
src/Components/Authentication/Validators.tsx
src/Components/Input.tsx

Addresses work in: https://artsyproduct.atlassian.net/browse/GROW-533
Password messaging
Tabbing (i promise i'm tabbing here 😄). Modal heights will be addressed next in https://artsyproduct.atlassian.net/browse/GROW-693

@xtina-starr => Text input QA

---

src/Styleguide/Artist/ArtistCard.tsx
src/Styleguide/Artist/__stories__/ArtistCard.story.tsx
src/Styleguide/Elements/Avatar.tsx
src/Styleguide/Elements/Flex.tsx
typings/styled-system.d.ts

First pass at the artist card

---

.storybook/addons.js
.storybook/devices.json
package.json
yarn.lock

Allows you to preview stories on different "devices" to see how something would look on a certain breakpoint. 
Will be useful designing responsive components.

Add Storybook addon Scissors

---

src/Styleguide/Components/Toggle.tsx
src/Styleguide/Components/__stories__/Toggle.story.tsx
src/Styleguide/Elements/Button.tsx
src/Styleguide/GlobalStyles/Links.tsx

Adds a new `<Toggle />` component (adapted from `<Section>`)

Add <Toggle>

---

package.json

Fixes `yarn watch` in reaction

@anandaroop => [Dev] fixes `yarn watch`

---

src/Components/Follow.tsx

The idea is that we should reuse this component on the new Artwork page as is. For now it's tricky to do the static set up so this change will make it easier. And Thanks @zephraph for helping shuffle things around here.
This should have no effect on existing component.

Slightly tweaking the styles for Follow component so that it's easier to use it for our new responsive static page

---

src/Components/Authentication/Desktop/SignUpForm.tsx
src/Components/Authentication/commonElements.tsx

@kanaabe => [Auth] display desktop global errors

---

src/Styleguide/Components/Footer.tsx
src/Styleguide/Components/__stories__/Footer.story.tsx

@zephraph => Add <Footer />

---

src/Styleguide/Components/AuctionCard.tsx
src/Styleguide/Components/Footer.tsx
src/Styleguide/Elements/Image.tsx
src/Styleguide/Elements/__stories__/Image.story.tsx
src/Styleguide/Pages/Artist/Components/CurrentEvent.tsx
src/Styleguide/Pages/Artist/__stories__/CurrentEvent.story.tsx

@zephraph => Add <CurrentEvent /> and <Image /> primitive 

---

src/Components/Authentication/commonElements.tsx

Fixes some TS errors
https://circleci.com/gh/artsy/reaction/3725

[PATCH Dev] fix build

---

src/Components/Icon.tsx
src/Components/Publishing/Header/__tests__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
src/Components/Publishing/Partner/__tests__/__snapshots__/PartnerInline.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
src/Components/Truncator.tsx
src/Styleguide/Components/Slider.tsx
src/Styleguide/Components/__stories__/Slider.story.tsx
src/Styleguide/Elements/Arrow.tsx
src/Styleguide/Elements/Image.tsx
src/Styleguide/Elements/__stories__/Arrow.story.tsx
typings/styled-system.d.ts

Add <Slider /> component, <Arrow /> element

---

src/Components/Checkbox.tsx
yarn.lock

Addresses checkbox hover issue in https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-475

@xtina-starr => Checkbox QA

---

package.json
yarn.lock

[PATCH lib] Bump palette@1.3.1

---

src/Styleguide/Components/Footer.tsx
src/Styleguide/Elements/Button.tsx

Fixes missing font as well as simplify / cleanup the `<Button />` primitive.

[PATCH cleanup] Fix fonts/ Fix / simplify button

---

yarn.lock

Updates palette to the latest version.

Update palette to the latest version

---

package.json
yarn.lock

Bumps to 1.4.1 
cc @alloy @zephraph @oxaudo

[PATCH palette] Bump palette@1.4.1

---

src/Components/Authentication/Desktop/LoginForm.tsx
src/Components/Authentication/Mobile/LoginForm.tsx
src/Components/Authentication/Mobile/ResetPasswordForm.tsx
src/Components/Authentication/Mobile/SignUpForm.tsx
src/Components/Authentication/Validators.tsx
src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
src/Components/Authentication/__tests__/Mobile/ResetPasswordForm.test.tsx
src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
src/Components/Authentication/__tests__/helpers.test.ts
src/Components/Authentication/commonElements.tsx
src/Components/Authentication/helpers.ts
src/Components/ProgressIndicator.tsx
src/Components/__stories__/Authentication.story.tsx

Flows for Login + Reset Password

@eessex => Mobile Login + Reset Password

---

src/Components/Icon.tsx
src/Components/Publishing/Header/__tests__/__snapshots__/FeatureHeader.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
src/Components/Publishing/Partner/__tests__/__snapshots__/PartnerInline.test.tsx.snap
src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
src/Components/__stories__/Icons.story.tsx
src/Styleguide/Artwork/ImageCarousel.tsx
src/Styleguide/Artwork/__stories__/ImageCarousel.story.tsx
src/Styleguide/Elements/Flex.tsx
src/Styleguide/Utils/Responsive.tsx
typings/styled-system.d.ts
yarn.lock

https://artsyproduct.atlassian.net/browse/EV-190

[Artwork/ImageCarousel] First static pass.

---

src/Components/__stories__/ArtworkGrid.story.tsx
src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Components/Tabs.tsx
src/Styleguide/Elements/Select.tsx
src/Styleguide/Pages/Artist/Overview.js
src/Styleguide/Pages/Artist/index.js

Super WIP - This is rough but gonna merge for presentation tomorrow:

[WIP] Artwork: First pass dropping components in page

---

src/Styleguide/Pages/Artwork/index.js

[Artwork] => Add <ImageCarousel> to artwork

---

src/Styleguide/Pages/Artwork/index.js

[PATCH imageSizes] Fix image sizes

---

src/Styleguide/Components/Artist/CurrentEvent.tsx
src/Styleguide/Components/Artist/__stories__/CurrentEvent.story.tsx
src/Styleguide/Components/Artwork/ImageCarousel.tsx
src/Styleguide/Components/Artwork/OtherAuctions.tsx
src/Styleguide/Components/Artwork/__stories__/ImageCarousel.story.tsx
src/Styleguide/Components/Artwork/__stories__/OtherAuctions.story.tsx
src/Styleguide/Pages/Artist/index.js
src/Styleguide/Pages/Artwork/index.js

Organize /Styleguide directory

---

package.json
yarn.lock

Locks our grid lib to my branch, rather than a commit. 
cc @anandaroop

[PATCH lib] Point grid version at branch

---

src/Styleguide/Components/Tabs.tsx
src/Styleguide/Components/__stories__/Tabs.story.tsx
src/Styleguide/Pages/Artist/index.js
src/Styleguide/Pages/Artwork/index.js

Adds tabs to the artwork page.
Also goes through a refactor of the tabs api to be a bit more declaritive

Add tabs to artwork, refactor

---

src/Styleguide/Pages/Artwork/AboutTheWork.js

Just add some spacing clean-up for the about section to make it look a little nicer

Formatting for about section

---

src/Styleguide/Pages/Artist/Overview.js
src/Styleguide/Pages/Artist/index.js

[PATCH styleguide] Deploy for force

---

src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Components/Slider.tsx
src/Styleguide/Components/Toggle.tsx
src/Styleguide/Elements/Box.tsx
src/Styleguide/Elements/Checkbox.tsx
src/Styleguide/Elements/Select.tsx
src/Styleguide/Elements/__stories__/Button.story.tsx
src/Styleguide/Utils/Section.tsx
yarn.lock

Fix stray spacing

---

src/Styleguide/Pages/Artwork/ImageCarousel.tsx
src/Styleguide/Pages/Artwork/__stories__/ImageCarousel.story.tsx
src/Styleguide/Pages/Artwork/index.js

See the inline comment https://github.com/artsy/reaction/compare/more-artwork-image-carousel-work?expand=1#diff-182d6f0b0c129e245b5c501ddad78c93R29

[Artwork/ImageCarousel] Use aspect ratio so layout doesn’t jump.

---

src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Components/__stories__/ReadMore.story.tsx
src/Styleguide/Components/__stories__/Toggle.story.tsx
src/Styleguide/Elements/Button.tsx
src/Styleguide/Elements/FollowIcon.tsx
src/Styleguide/Elements/__stories__/Typography.story.tsx

Fixes several issues introduced by https://github.com/artsy/palette/pull/23. That PR needs to be merged and deployed before this can move forward.

Palette type fixes

---

src/Styleguide/Pages/Artwork/Sidebar.tsx
src/Styleguide/Pages/Artwork/Sidebar/ExtraLinks.tsx
src/Styleguide/Pages/Artwork/__stories__/Sidebar/ExtraLinks.story.tsx
src/Styleguide/Pages/Artwork/index.js
src/Styleguide/Pages/Fixtures/Artists.ts
src/Styleguide/Pages/Fixtures/Artwork/Sidebar/ExtraLinks.ts
src/Styleguide/Pages/Fixtures/Artworks.ts

I think this is the last piece that makes sidebar for regular artwork look more or less like design.
I need to go back and double check the fonts, but otherwise I think it looks pretty close.

 adding ExtraLinks component to sidebar

---

src/Components/Authentication/Desktop/Components/DesktopModal.tsx
src/Components/Authentication/Desktop/FormSwitcher.tsx
src/Components/Authentication/Desktop/ModalManager.tsx
src/Components/Authentication/Types.ts
src/Components/Authentication/__tests__/Desktop/Components/DesktopModal.test.tsx
src/Components/Authentication/__tests__/Desktop/FormSwitcher.test.tsx
src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
src/Components/Authentication/commonElements.tsx

cc @l2succes @xtina-starr. See [this doc for more details](https://docs.google.com/spreadsheets/d/1hwI_npaZK1sf9o4lsPDky50K5bD79tlK_Xg-O0uT5y4/edit?usp=sharing).
This doesn't include the submission success calls since that will all happen in Force.

@l2succes => Auth Analytics

---

src/Styleguide/Pages/Artwork/Sidebar/Artists.tsx
src/Styleguide/Pages/Artwork/index.tsx

Not sure how that got messed up, but adding it back.

minor: re-add sidebar for artwork page

---

src/Components/Authentication/TermsOfServiceCheckbox.tsx
src/Components/Checkbox.tsx
yarn.lock

Addresses most points in [GROW-726](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-726)
- Fixes hover checkstate
- Adds underlines to text in terms/conditions
- Updates copy in terms/conditions
Facebook/twitter punctuation is covered in https://github.com/artsy/reaction/pull/805

@kanaabe => GDPR Qa

---

src/Styleguide/Pages/Artist/Routes/Shows/ShowBlockItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowContents.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowListItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/index.tsx
src/Styleguide/Pages/Artist/index.tsx
src/Styleguide/Pages/Fixtures/Show.ts
src/__generated__/ShowContentsQuery.graphql.ts
src/__generated__/ShowContents_artist.graphql.ts
src/__generated__/ShowsArtistQuery.graphql.ts

The 'scroll to top' feels a bit odd on the shows tab, since there's 3 paginated components on the page: 'Current', 'Upcoming' and 'Past'.

@damassi => Making shows tab on Artist page dynamic

---

src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/__stories__/ArtistCard.story.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/index.js
src/Styleguide/Pages/Artist/index.tsx

@mzikherman => Add related artists tab

---

src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/__stories__/ArtistCard.story.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsStaticLayout.tsx
src/__generated__/ArtistCard_artist.graphql.ts
src/__generated__/RelatedArtistsQueryRendererQuery.graphql.ts
src/__generated__/RelatedArtistsRefetchContainerQuery.graphql.ts
src/__generated__/RelatedArtistsRefetchContainer_artist.graphql.ts

Makes the props for `ArtistCard` match the ones generated by our GraphQL fragment, and adds in a fragment container.

@damassi => Make ArtistCard fragment container

---

src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
src/Components/Authentication/Desktop/FormSwitcher.tsx
src/Components/Authentication/Desktop/LoginForm.tsx
src/Components/Authentication/Footer.tsx
src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
src/Components/Authentication/Mobile/FormSwitcher.tsx
src/Components/Authentication/Types.ts
src/Components/Authentication/Validators.tsx
src/Components/Authentication/__tests__/Desktop/FormSwitcher.test.tsx
src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
src/Components/Authentication/__tests__/Mobile/FormSwitcher.test.tsx
src/Components/Authentication/__tests__/Mobile/ResetPasswordForm.test.tsx
src/Components/__stories__/Authentication.story.tsx

- Renames `ResetPassword` to `ForgotPassword`
- Fixes Authentication Storybook

@eessex => Rename ResetPassword

---

yarn.lock

Coordinated w/ palette update.

Update styled-system types

---

src/Styleguide/Components/Pagination.tsx
src/Styleguide/Components/__stories__/Pagination.story.tsx
src/Styleguide/Pages/Artist/Routes/Articles/ArticlesRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsStaticLayout.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsStaticLayout.tsx
src/Styleguide/Pages/Artist/index.tsx
src/__generated__/ArticlesQueryRendererQuery.graphql.ts
src/__generated__/ArticlesRefetchContainerQuery.graphql.ts
src/__generated__/ArticlesRefetchContainer_artist.graphql.ts
src/__generated__/AuctionResultsQueryRendererQuery.graphql.ts
src/__generated__/AuctionResultsRefetchContainerQuery.graphql.ts
src/__generated__/AuctionResultsRefetchContainer_artist.graphql.ts
src/__generated__/Pagination_pageCursors.graphql.ts
src/__generated__/RelatedArtistsQueryRendererQuery.graphql.ts
src/__generated__/RelatedArtistsRefetchContainerQuery.graphql.ts
src/__generated__/RelatedArtistsRefetchContainer_artist.graphql.ts
src/__generated__/ShowsQueryRendererQuery.graphql.ts
src/__generated__/ShowsRefetchContainerQuery.graphql.ts
src/__generated__/ShowsRefetchContainer_artist.graphql.ts

Exports a fragment container from `Pagination`.

@damassi => Making a Pagination fragment container

---

src/Router/PreloadLink.tsx
src/Router/__stories__/Router.story.tsx
src/Router/types.ts
src/Styleguide/Pages/Artist/index.tsx

Wires our tabs into router lifecycle

@mzikherman => Wire tab navigation into router

---

src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultItem.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultsRefetchContainer.tsx
src/__generated__/AuctionResultItem_auctionResult.graphql.ts
src/__generated__/AuctionResultsQueryRendererQuery.graphql.ts
src/__generated__/AuctionResultsRefetchContainerQuery.graphql.ts
src/__generated__/AuctionResultsRefetchContainer_artist.graphql.ts

Trying to follow the pattern now!

@damassi => Making an AuctionResultItem fragment container

---

package.json
src/Styleguide/Components/RouterTabs.tsx
src/Styleguide/Components/Tabs.tsx
src/Styleguide/Pages/Artist/index.tsx
yarn.lock

Hooks into our Router and delegates to `<PreloadLink />` under the hood.

@mzikherman => Add <RouterTabs> component

---

src/Styleguide/Pages/Artist/Routes/Overview/ArtworkFilter.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx

Move artwork filter out of Overview

---

src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Artist/Navigation.tsx
src/Styleguide/Pages/Artist/index.tsx
src/Styleguide/Pages/Artist/routes.tsx

Move stuff into more final structure

Restructure into proper artist routes

---

src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Components/__stories__/SelectedExhibitions.story.tsx
src/Styleguide/Pages/Artist/Routes/Overview/ExhibitionHighlightsQueryRenderer.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx
src/Styleguide/Pages/Artwork/__stories__/ArtistInfo.story.tsx
src/Styleguide/Pages/Artwork/index.tsx
src/Styleguide/Pages/Fixtures/SelectedExhibitions.ts
src/__generated__/ExhibitionHighlightsQueryRendererQuery.graphql.ts
src/__generated__/SelectedExhibitions_exhibitions.graphql.ts

cc @zephraph I think this was one of your static components, I just mapped the fields 1-1 to something reasonable from Metaphysics. I noticed the order/items are slightly different than what's on https://staging.artsy.net/artist/pablo-picasso currently, I think Force might be doing some odd grouping/sorting/truncating of its own. Will come back- that should either move here or go to Metaphysics.

@damassi => Make a fragment container for exhibition highlights

---

src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Artist/Components/ArtistHeader.tsx
src/Styleguide/Pages/Artist/Components/ArtistHeaderQueryRenderer.tsx
src/Styleguide/Pages/Artist/__stories__/ArtistHeader.story.tsx
src/__generated__/ArtistHeaderQueryRendererQuery.graphql.ts
src/__generated__/ArtistHeader_artist.graphql.ts

I may have placed this in the wrong place for the SSR stuff, we can chat on Monday!

@damassi => Making a fragment container for artist page carousel

---

.storybook/preview-head.html

No longer needed thanks to latest updates in Palette.

@zephraph => Remove font import

---

src/Styleguide/Pages/Artwork/index.tsx

[Artwork] Fix initial route

---

src/Styleguide/Components/Pagination.tsx
src/Styleguide/Elements/Button.tsx
src/Styleguide/Elements/Select.tsx
src/Styleguide/Elements/Spacer.tsx
src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Artist/Routes/Articles/ArticleItem.tsx
src/Styleguide/Pages/Artist/Routes/Articles/ArticlesRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Articles/index.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultItem.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/CV/CVItem.tsx
src/Styleguide/Pages/Artist/Routes/Overview/ArtworkFilterArtworks.tsx
src/Styleguide/Pages/Artist/Routes/Overview/ArtworkFilterContainer.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/index.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowBlockItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowListItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Shows/index.tsx
src/Styleguide/Pages/Artist/__stories__/Comps/ArtworkFilter.tsx
src/Styleguide/Pages/Artist/__stories__/Comps/RelatedArtistsStaticLayout.tsx
src/Styleguide/Pages/Artist/__stories__/Comps/ShowsStaticLayout.tsx
src/Styleguide/Pages/Artist/index.tsx
src/Styleguide/Pages/Boot.tsx
src/Styleguide/Utils/ScrollIntoView.tsx
src/__generated__/CVItemQuery.graphql.ts
src/__generated__/CVItem_artist.graphql.ts
src/__generated__/routes_CVQuery.graphql.ts

Cleaned up all the tabs except for Overview

[Artist Page] First pass design cleanup 

---

src/Styleguide/Pages/Artist/Routes/CV/CVItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowBlockItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowListItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Shows/index.tsx
src/Styleguide/Pages/Fixtures/Show.ts
src/__generated__/ShowsRefetchContainerQuery.graphql.ts
src/__generated__/ShowsRefetchContainer_artist.graphql.ts
src/__generated__/Shows_viewer.graphql.ts
src/__generated__/routes_ShowsQuery.graphql.ts

Knocking off a couple things from https://github.com/artsy/reaction/issues/887

@damassi => Link to shows and tweak sorts

---

data/schema.graphql
data/schema.json
src/Styleguide/Pages/Artist/Routes/CV/CVItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowBlockItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowListItem.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
src/__generated__/ArtistSearchResultsArtistMutation.graphql.ts
src/__generated__/PopularArtistsFollowArtistMutation.graphql.ts
src/__generated__/RelatedArtistsRefetchContainerQuery.graphql.ts
src/__generated__/RelatedArtistsRefetchContainer_artist.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts

Corrects a place we weren't checking for nulls and leaving trailing commas, and then adds it in a couple places we needed.

@damassi => Better display of city on show and cv items

---

src/Styleguide/Components/Pagination.tsx
src/Styleguide/Pages/Artist/Routes/Articles/ArticlesRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Overview/ArtworkFilterArtworks.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
src/Styleguide/Pages/Fixtures/Pagination.ts
src/__generated__/ArticlesRefetchContainerQuery.graphql.ts
src/__generated__/ArticlesRefetchContainer_artist.graphql.ts
src/__generated__/ArtworkFilterArtworksQuery.graphql.ts
src/__generated__/ArtworkFilterArtworks_filtered_artworks.graphql.ts
src/__generated__/ArtworkFilterQueryRendererQuery.graphql.ts
src/__generated__/AuctionResultsRefetchContainerQuery.graphql.ts
src/__generated__/AuctionResultsRefetchContainer_artist.graphql.ts
src/__generated__/Pagination_pageCursors.graphql.ts
src/__generated__/RelatedArtistsRefetchContainerQuery.graphql.ts
src/__generated__/RelatedArtistsRefetchContainer_artist.graphql.ts
src/__generated__/ShowsRefetchContainerQuery.graphql.ts
src/__generated__/ShowsRefetchContainer_artist.graphql.ts
src/__generated__/routes_ArticlesQuery.graphql.ts
src/__generated__/routes_AuctionResultsQuery.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts
src/__generated__/routes_ShowsQuery.graphql.ts

As you pointed out, we can now use the `previous` data and get that cached properly.

@damassi => Better use of previous for pagination

---

src/Components/Checkbox.tsx

Fixes left alignment of Checkbox component

@l2succes => [PATCH auth] Checkbox position

---

src/Styleguide/Components/__stories__/Slider.story.tsx
src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Fixtures/Slider.ts
src/__stories__/storiesOf.js

This adds a slider example with an ArtworkBrick

Add artwork brick example

---

src/Router/buildClientApp.tsx
src/Router/buildServerApp.tsx
src/Styleguide/Components/RecentlyViewed.tsx
src/Styleguide/Components/Slider.tsx
src/Styleguide/Components/__stories__/RecentlyViewed.story.tsx
src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Artist/routes.tsx
src/__generated__/RecentlyViewed_me.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts

@mzikherman => Add recently viewed block

---

src/Styleguide/Pages/Artist/Routes/Overview/Components/Genes.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx
src/__generated__/Genes_artist.graphql.ts
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

This makes that section on Overview dynamic.

@damassi => Make artist genes dynamic

---

src/Styleguide/Elements/Button.tsx
src/Styleguide/Elements/__stories__/Button.story.tsx

Added it as a property that overwrites both loading and variant.

add disabled option to button

---

src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Artist/NavigationTabs.tsx
src/Styleguide/Pages/Artist/Routes/CV/CVItem.tsx
src/Styleguide/Pages/Artist/routes.tsx
src/__generated__/CVItem_artist.graphql.ts
src/__generated__/NavigationTabs_artist.graphql.ts
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
src/__generated__/routes_CVQuery.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

This queries for the statuses, and conditionally renders the tabs.

@damassi =>Make tab nav dynamic

---

src/Components/Artist/MarketInsights/MarketInsights.tsx
src/Components/Artist/MarketInsights/__tests__/MarketInsights.test.tsx
src/Styleguide/Components/MarketInsights.tsx
src/Styleguide/Components/__stories__/MarketInsights.story.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx
src/Styleguide/Pages/Artwork/ArtworkApp.tsx
src/Styleguide/Pages/Artwork/Components/ArtistInfo.tsx
src/Styleguide/Pages/Artwork/Components/__stories__/ArtistInfo.story.tsx
src/Styleguide/Pages/Fixtures/MarketInsights.ts
src/__generated__/MarketInsightsArtistPage_artist.graphql.ts
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

@damassi => Make market insights dynamic

---

package.json
src/Router/buildClientApp.tsx
src/Router/buildServerApp.tsx
src/Styleguide/Components/ArtistBio.tsx
src/Styleguide/Components/Slider.tsx
src/Styleguide/Pages/Artist/ArtistApp.tsx
src/Styleguide/Pages/Artist/Components/LoadingArea.tsx
src/Styleguide/Pages/Artist/NavigationTabs.tsx
src/Styleguide/Pages/Artist/index.tsx
src/Styleguide/Pages/Artist/routes.tsx
yarn.lock

[PATCH ssr] SSR Cleanup

---

src/Router/AppShell.tsx
src/Router/buildServerApp.tsx
src/Router/types.ts
src/Styleguide/Components/ArtistBio.tsx
src/Styleguide/Components/Slider.tsx
src/Styleguide/Pages/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Styleguide/Pages/Artist/Routes/Overview/Components/CurrentEvent.tsx
src/Styleguide/Pages/Artist/Routes/Overview/index.tsx
src/Styleguide/Pages/Boot.tsx
src/Styleguide/Utils/Responsive.tsx

- Make JSON serialization safer (**TODO**: figure out what's causing circular ref issues *only* on staging)
- Pass in initial breakpoint for responsive SSR rendering
- Fix Current event square
- Fix Overview grid filter layout

[PATCH qa] QA Issues 

---

src/Components/Publishing/Video/VideoAbout.tsx
src/Components/Publishing/Video/VideoInfoBlock.tsx

- Don't show duration if no media is present
- Export Credits styled component

[FIX publishing] minor fixes for positron video

---

src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/index.tsx
src/Styleguide/Pages/Artist/index.tsx
src/__generated__/ArtistCard_artist.graphql.ts
src/__generated__/RelatedArtistsRefetchContainerQuery.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts

@damassi => Get auction result sort working, and quick follow button update

---

src/Styleguide/Components/Pagination.tsx
src/Styleguide/Components/ReadMore.tsx
src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Pages/Artist/Routes/Articles/ArticlesRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Styleguide/Pages/Artist/Routes/RelatedArtists/RelatedArtistsRefetchContainer.tsx
src/Styleguide/Pages/Artist/Routes/Shows/ShowsRefetchContainer.tsx
src/Styleguide/Pages/Artist/index.tsx

Fix key warnings

---

src/Router/state.tsx

[PATCH release] Bump reaction

---

src/Router/state.tsx
src/Router/types.ts
src/Styleguide/Pages/Artist/Components/ArtistHeader.tsx

@mzikherman => [Artist2] Wire up Force-Reaction mediator example 

---

src/Components/FollowButton/FollowArtistButton.tsx
src/Router/Boot.tsx
src/Router/buildClientApp.tsx
src/Router/buildServerApp.tsx
src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/Footer.tsx
src/Styleguide/Components/__stories__/ArtistCard.story.tsx
src/Styleguide/Pages/Artist/Components/ArtistHeader.tsx
src/Styleguide/Pages/Artist/Routes/AuctionResults/AuctionResultItem.tsx
src/Styleguide/Pages/Artist/__stories__/Comps/RelatedArtistsStaticLayout.tsx
src/__generated__/ArtistCard_artist.graphql.ts
src/__generated__/ArtistHeader_artist.graphql.ts
src/__generated__/RelatedArtistsRefetchContainerQuery.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts

This gets the FAQ modals working (from https://github.com/artsy/force/pull/2675), and the correct mediator triggers.
The Force /artist2 page actually has some crash logged out (still chasing it down), but the mediator triggers for the follow button look correct here, was just manually triggering them for now.

@damassi => More misc, trigger mediator in footer, hook up follow button from Force

---

.gitignore
package.json

Add netlify settings for PR build previews of a storybook

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/Components/CurrentEvent.tsx
src/Apps/Artist/Routes/Overview/Components/Genes.tsx
src/Apps/Artist/Routes/Overview/index.tsx
src/Apps/Artist/Routes/Overview/state.ts
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Apps/Artist/Routes/Shows/index.tsx
src/Apps/__stories__/Apps.story.tsx
src/Components/Artist/MarketInsights/MarketInsights.tsx
src/Styleguide/Components/MarketInsights.tsx
src/Styleguide/Components/Pagination.tsx
src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
src/__generated__/ArtworkFilter_artist.graphql.ts
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

Adds support for the sort drop down (kicking off new query, etc.)

@zephraph => Hook up sorting to filter

---

src/Apps/Artist/ArtistApp.tsx
src/Apps/Artist/Components/ArtistHeader.tsx
src/Apps/Artist/Routes/CV/CVItem.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
src/Styleguide/Components/Footer.tsx
src/Styleguide/Components/Pagination.tsx
src/Styleguide/Components/RouteTabs.tsx
src/Styleguide/Components/Tabs.tsx
src/Styleguide/Components/Toggle.tsx
src/Styleguide/Elements/Box.tsx
src/Styleguide/Elements/Checkbox.tsx
src/Styleguide/Elements/FollowIcon.tsx
src/Styleguide/Elements/GlobalStyles.tsx
src/Styleguide/Elements/Radio.tsx
src/Styleguide/Elements/Select.tsx
src/Styleguide/Elements/Separator.tsx
src/Styleguide/Elements/__stories__/Checkbox.story.tsx
src/Styleguide/Elements/__stories__/Radio.story.tsx
src/Styleguide/Utils/Section.tsx
src/__generated__/ArtistHeader_artist.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
yarn.lock

This PR tackles a _lot_. Should've broken it down probably....
- Fixes spacing near footer
- Refactors separator to not be tied to a specific sizing
- Removes several `themeGet` and `props.theme` references in favor of simpler handlers from palette
- Implements all visual states of radio button and checkbox
- Add appropriate spacing between arrow and mini-dropdown options
- Makes images in the top slider clickable

Artist fit and finish [Part I]

---

src/Apps/Artist/Routes/Shows/ArtistShowBlockItem.tsx
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Apps/Artist/Routes/Shows/index.tsx

Just some minor visual updates to get things more in line w/ designs

Minor fit and finish work on shows tab

---

public/_redirects
src/Apps/Artist/Routes/Shows/ArtistShowListItem.tsx
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Styleguide/Elements/Checkbox.tsx
src/Styleguide/Elements/Radio.tsx

This does more work to get the Artist page closer to matching the design specs
- Updates checkbox, radio button with proper hover transitions
- Fixes radio button text hover state
- Fixes a lot of spacing / separator positioning on the shows page
- Fixes names not showing up on some show lists

Artist page fit and finish

---

src/Apps/Artist/Routes/Articles/ArtistArticle.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
src/Apps/Artist/Routes/RelatedArtists/index.tsx
src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/Toggle.tsx

Continuing to bridge style gaps (or margins?) where possible.

Artist Fit and finish Part III -- Night of the undying bugs

---

src/Apps/Artist/__static__/RelatedArtistsStaticLayout.tsx
src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/__stories__/ArtistCard.story.tsx
src/__generated__/ArtistCard_artist.graphql.ts
src/__generated__/RelatedArtistsListQuery.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts

Make sure artist card is a link

Ensure artist card links off to artist page

---

README.md

@mzikherman => [PATCH ArtistPage] Bump version for fix of logged out version of artist page

---

src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx

Minor tweak to correct spacing on xs breakpoint

Fix artist card spacing on mobile

---

src/Styleguide/Components/MarketInsights.tsx

Typo correction

---

data/schema.graphql
data/schema.json
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarBidActionStory.story.tsx
src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.story.tsx
src/Apps/__test__/Fixtures/Artwork/Sidebar/BidAction.ts
src/Apps/__test__/Fixtures/Artwork/Sidebar/CurrentBidInfo.ts
src/__generated__/ArtworkSidebarBidAction_artwork.graphql.ts
src/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
src/__generated__/routes_ArtworkQuery.graphql.ts

Makes use of the following changes to the MP schema: https://github.com/artsy/metaphysics/pull/1146

[Artwork/Sidebar] Make sale components fully dynamic

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
src/Apps/__stories__/Apps.story.tsx

Hides estimates as well as sale prices when logged out.
Restores mediator behavior (you click 'Sign up to see Price' and you get the modal).
Dont truncate when descriptions are null.

@zephraph => Auction result fixes

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx

follow up on https://github.com/artsy/reaction/pull/952
This is just putting @alloy fix to words here. Makes total sense though:)

minor adjustment in Artists in Sidebar

---

src/Components/Authentication/Mobile/LoginForm.tsx
src/Components/Authentication/Mobile/SignUpForm.tsx
src/Components/Authentication/commonElements.tsx

Addresses [GROW-791](https://artsyproduct.atlassian.net/browse/GROW-791)
Color/twitter changes covered in https://github.com/artsy/reaction/pull/977

@l2succes => [Auth QA] Mobile text/style updates

---

src/Components/Authentication/Desktop/LoginForm.tsx
src/Components/Authentication/Desktop/SignUpForm.tsx
src/Components/Authentication/Footer.tsx
src/Components/Authentication/__tests__/FormSwitcher.test.tsx
src/Components/Authentication/commonElements.tsx

Addresses [GROW-790](https://artsyproduct.atlassian.net/browse/GROW-790)

@l2succes => [Auth QA] Color/font updates, remove twitter link

---

src/Apps/Artist/Routes/Overview/Components/Genes.tsx

Correct gene label

---

src/Styleguide/Components/ArtistCard.tsx

Slight visual updates to artist card

Adjust button sizes, vertically align author text

---

src/Components/Authentication/FormSwitcher.tsx

Fixes a 504 error we're getting on static auth pages (/signup and /login)
https://artsyproduct.atlassian.net/browse/GROW-795

[Auth] fix location is undefined error #trivial

---

src/Apps/Artist/Components/ArtistHeader.tsx
src/Apps/Artist/Routes/Articles/ArtistArticle.tsx
src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/index.tsx
src/Apps/Artist/Routes/AuctionResults/state.ts
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/index.tsx
src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
src/Apps/Artist/Routes/RelatedArtists/index.tsx
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Apps/Artist/__static__/ArtworkFilter.tsx
src/Apps/Artist/__static__/RelatedArtistsStaticLayout.tsx
src/Apps/Artist/__static__/ShowsStaticLayout.tsx
src/Components/FollowButton/Button.tsx
src/Styleguide/Components/Pagination.tsx
src/Styleguide/Components/__stories__/Pagination.story.tsx
src/__generated__/ArtistAuctionResults_artist.graphql.ts
src/__generated__/RelatedArtistsList_artist.graphql.ts
src/__generated__/RelatedArtists_viewer.graphql.ts
src/__generated__/routes_AuctionResultsQuery.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts

@zephraph => Bunch of minor tweaks from some of the lower priority cards

---

.circleci/config.yml

Slight oversight...
Thanks @anandaroop for pointing it out during show and tell!

Remove duplicate definition of the docker image

---

data/schema.graphql
data/schema.json
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
src/Apps/__test__/Fixtures/Artwork/Sidebar/BidAction.ts
src/Apps/__test__/Fixtures/Artwork/Sidebar/CurrentBidInfo.ts
src/__generated__/ArtworkSidebarBidAction_artwork.graphql.ts
src/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
src/__generated__/routes_ArtworkQuery.graphql.ts

This should be merged in tandem with https://github.com/artsy/metaphysics/pull/1173

minor name change based on MP tix

---

src/Apps/Artist/Routes/CV/CVItem.tsx
src/Apps/Artist/Routes/CV/ShowEntry.tsx
src/Apps/Artist/Routes/CV/index.tsx
src/Router/Boot.tsx
src/Styleguide/Elements/Box.tsx
src/Styleguide/Elements/Join.tsx
src/Styleguide/Utils/BreakpointVisualizer.tsx
tsconfig.json

Okay, so this is largely done. 
Big issue is that the md breakpoint is behaving very oddly. @mzikherman could you help me look into this?

Fix CV tab spacing

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
src/Styleguide/Components/Pagination.tsx
src/__generated__/ArtistArticlesQuery.graphql.ts
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistShowsQuery.graphql.ts
src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
src/__generated__/Pagination_pageCursors.graphql.ts
src/__generated__/RelatedArtistsListQuery.graphql.ts
src/__generated__/routes_ArticlesQuery.graphql.ts
src/__generated__/routes_AuctionResultsQuery.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
src/__generated__/routes_RelatedArtistsQuery.graphql.ts
src/__generated__/routes_ShowsQuery.graphql.ts

Following the pattern in https://github.com/artsy/reaction/pull/1007 , but for the grid (for pagination updates).

@mzikherman => Trigger mediator w/ page update for artwork grid + bump version

---

src/Components/Authentication/FormSwitcher.tsx
src/Components/Authentication/Mobile/SignUpForm.tsx
src/Components/Authentication/Types.ts

Related: https://artsyproduct.atlassian.net/browse/GROW-786

@xtina-starr => go to homepage or redirectTo when back button is tapped

---

src/Components/Authentication/Mobile/LoginForm.tsx

Addresses https://artsyproduct.atlassian.net/browse/GROW-783

@l2succes: Forgot password for mobile login 

---

src/Apps/Artist/Routes/Overview/index.tsx
src/Styleguide/Components/ArtistBio.tsx
src/Styleguide/Components/ReadMore.tsx

Addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-83 , hides the genes to start, and reveals them when clicking 'Read More'.

@zephraph => Reveal genes when toggling read more in bio

---

data/schema.graphql
data/schema.json
src/Apps/Artist/Components/NavigationTabs.tsx
src/__generated__/NavigationTabs_artist.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts

Uses https://github.com/artsy/metaphysics/pull/1187

@zephraph => Show cv tab when there is at least one show by the artist

---

src/Apps/Artist/Routes/Articles/ArtistArticle.tsx

@mzikherman => Top align article images and make them link to article

---

src/Apps/Order/OrderApp.tsx
src/Apps/Order/routes.tsx
src/Apps/__stories__/Apps.story.tsx
src/__generated__/routes_OrderQuery.graphql.ts

Sets up the basic order app shell with an associated story.

Order shell

---

src/Components/Artwork/FillwidthItem.tsx
src/Styleguide/Components/RecentlyViewed.tsx

got a little ambitious with the branch name :)

@mzikherman => Fix saving RVA works on artist page

---

src/Components/MinimalCtaBanner.tsx
src/Components/__stories__/CtaBanner.story.tsx

This addresses the first part of https://artsyproduct.atlassian.net/browse/GROW-705 by creating the component.

@l2succes: add new minimal cta banner

---

src/Components/__stories__/Modal.story.tsx

Sets default state to open in Modal story.

@l2succes => [Trivial] Modal story is open by default

---

src/Relay/createEnvironment.ts

[Relay] Send browser TZ to MP.

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/state.ts
src/Apps/Artist/routes.tsx
src/Apps/__stories__/Apps.story.tsx
src/Styleguide/Elements/Checkbox.tsx
src/Styleguide/Elements/Radio.tsx

This parses any initial query params and injects it into the current filter state.
It also removes state from `Radio` and `Checkbox`.

@alloy => Set initial filter params from URL on overview tab

---

src/Apps/Artist/Components/NavigationTabs.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
src/Apps/Artist/Routes/RelatedArtists/index.tsx
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts
src/__generated__/NavigationTabs_artist.graphql.ts
src/__generated__/RelatedArtists_viewer.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
src/__generated__/routes_AuctionResultsQuery.graphql.ts

Whoops, noticed this was still hardcoded!

@zephraph => Display actual auction result count for artist page

---

src/Components/Modal/Modal.tsx

Addresses: https://artsyproduct.atlassian.net/browse/GROW-798

[PATCH Modal] remove scrollbars #trivial

---

src/Apps/Artist/Routes/Overview/Components/Genes.tsx

@mzikherman => Correct link to gene page on related categories

---

src/Apps/Order/Components/TwoColumnLayout.tsx
src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/Submission/index.tsx
src/Styleguide/Utils/Placeholder.tsx

This goes a few steps further in laying out the shopping experience. 
- Tweaks the layout spacings to be in line with designs.
- Adds placeholders for each shipping field

Shipping layout

---

package.json
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/__static__/ArtworkFilter.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Styleguide/Elements/Radio.tsx
src/Styleguide/Elements/RadioGroup.tsx
src/Styleguide/Elements/__stories__/Radio.story.tsx
src/Styleguide/Elements/__stories__/RadioGroup.story.tsx
yarn.lock

Add radio group component

---

src/Apps/Order/OrderApp.tsx
src/Styleguide/Components/Stepper.tsx

Just adds the stepper component that @sepans so graciously built to the order app.

Add stepper to order app

---

src/Apps/Order/Components/Summary.tsx
src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/routes.tsx
src/Apps/__stories__/OrderApp.story.tsx
src/Assets/Icons/CheckIcon.tsx
src/Assets/Icons/ChevronIcon.tsx
src/Components/FollowButton/Button.tsx
src/Relay/createMockNetworkLayer.ts
src/Router/StorybooksRouter.tsx
src/Styleguide/Components/Stepper.tsx
src/Styleguide/Components/Tabs.tsx
src/Styleguide/Elements/Button.tsx

This PR fleshes out the entire purchase flow. In the story book you can go from shipping through all the steps to submission.
It hooks into the relay mock interface that @alloy helped me earlier with today to provide some mock data that we can expand on as needed. I haven't fleshed out the Summary page, but I've built on enough patterns that that should be pretty easy for someone else to pick up. 
I've also fixed several react warnings and corrected/added some typings.

Complete purchase flow

---

src/Components/Artwork/GridItem.tsx

Fixes issue where Gemini was receiving an initially invalid image size of 0.

[PATCH bugfix] Fix initial image size

---

src/Components/Artwork/Contact.tsx

Fixes https://sentry.io/artsynet/force-production/issues/627143503/

[PATCH bugfix] Fix partner line

---

src/Components/Artwork/GridItem.tsx

@mzikherman => Dont crash when no initial breakpoints passed in for gene/tag pages

---

src/Components/Artwork/GridItem.tsx

@damassi => Match breakpoint for grid sizing in a more functional manner

---

README.md
src/Styleguide/Elements/GlobalStyles.tsx

Removes flash on elements when tapping on mobile web.

@zephraph => [PATCH css] Remove tap flash

---

src/Styleguide/Components/StepSummaryItem.tsx
src/Styleguide/Components/__stories__/StepSummaryItem.story.tsx

[jira](https://artsyproduct.atlassian.net/browse/PURCHASE-307)

step summary item

---

src/Assets/Icons/ChevronIcon.tsx

Just dropping by to add the remaining directions to this chevron so that I can use it in Volt. Per @sepans's advice, I'm also switching to rotate so it's a little easier to read. 🌸

Add two more directions to chevron

---

src/Apps/Order/Routes/Shipping/index.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-337
This PR depends on the following PRs:
* https://github.com/artsy/reaction/pull/1070
* https://github.com/artsy/reaction/pull/1072
* https://github.com/artsy/reaction/pull/1073
I haven't consolidated components yet but am open to feedback and suggestions!

User can see actual form fields

---

src/Apps/Artist/Components/ArtistHeader.tsx
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
src/Apps/__stories__/Apps.story.tsx
src/Router/types.ts
src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Components/Slider.tsx

Bugfixes for a few sentry issues:
- https://sentry.io/artsynet/force-production/issues/631148420/
- https://sentry.io/artsynet/force-staging/issues/631167912/
- https://sentry.io/artsynet/force-staging/issues/631382778/
Refers to `/artist/andrea-facco`

@mzikherman => [FIX artistPage] More partner guard issues

---

src/Router/Boot.tsx

https://github.com/artsy/reaction/pull/1089 also failed to deploy, trying one last time and then calling in the troops

[PATCH artistPage] Bump reaction

---

src/Apps/Order/Components/ShippingAndPaymentDetails.tsx
src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
src/Styleguide/Components/StepSummaryItem.tsx
src/Styleguide/Elements/Box.tsx
src/Styleguide/Elements/__stories__/BorderBox.story.tsx
src/Styleguide/Elements/icons/CreditCardIcon.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-311
https://zpl.io/25qjjq3
This PR shares a commit with #1091 – How do we handle stacked PRs here? It doesn't seem to be doable when working with forks.
Need to update the icon set to match https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5acf57cbc958883984ec6abd or use stripe's icons.

Shipping and payment details

---

src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
src/Components/Authentication/commonElements.tsx
src/Components/Publishing/Header/Layouts/Components/FeatureFullscreenHeader.tsx
src/Components/Publishing/Header/Layouts/Components/FeatureSplitHeader.tsx

Addresses
https://artsyproduct.atlassian.net/browse/GROW-832
https://artsyproduct.atlassian.net/browse/GROW-815
https://artsyproduct.atlassian.net/browse/GROW-679

@l2succes => QA - mobile auth/article headers

---

src/Apps/Artist/Routes/CV/index.tsx
src/Router/AppShell.tsx
src/Router/buildClientApp.tsx
src/Router/buildServerApp.tsx
src/Router/getUser.ts

Trying to track down why staging / prod is throwing this error:

[PATCH artistPage] Add canary for SSR logs issue

---

src/Router/AppShell.tsx
src/Router/buildClientApp.tsx

Adds `circular-json` to help guard against issue we're seeing in staging / prod. 
Idea came from this PR fix from Vue: https://github.com/vuejs/vue-devtools/commit/2a626a3232e97bdacd13b461aa2e7218858139ff

[PATCH artistPage] Extra guard against circular JSON

---

src/Router/AppShell.tsx
src/Router/buildClientApp.tsx
src/Router/buildServerApp.tsx

[PATCH artistPage] Attempt to manually strip out circular refs

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/state.ts

PR updates from @damassi , plus publishes Reaction so that users w/ the lab feature will see the new filters in Force.

@mzikherman => ES6 includes instead of indexOf !== -1, and publish reaction

---

src/Components/Authentication/TermsOfServiceCheckbox.tsx

Addresses https://artsyproduct.atlassian.net/browse/GROW-819

@l2succes => [Auth QA] Don't show checkbox error if checked

---

src/Components/Authentication/Mobile/LoginForm.tsx
src/Components/Authentication/Mobile/SignUpForm.tsx
src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx

https://artsyproduct.atlassian.net/browse/GROW-829

@xtina-starr => display server errors on mobile auth forms

---

src/Apps/Artist/ArtistApp.tsx
src/Apps/Artist/Routes/Articles/ArtistArticle.tsx
src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/TableColumns.tsx
src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
src/Apps/Artist/Routes/CV/CVItem.tsx
src/Apps/Artist/Routes/CV/index.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/index.tsx
src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
src/Apps/Artist/Routes/RelatedArtists/index.tsx
src/Apps/Artist/Routes/Shows/ArtistShowListItem.tsx
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Apps/Artist/Routes/Shows/index.tsx
src/Apps/Artist/__static__/CVStaticLayout.tsx
src/Apps/Artist/__static__/RelatedArtistsStaticLayout.tsx
src/Apps/Artist/__static__/ShowsStaticLayout.tsx
src/Apps/__stories__/Apps.story.tsx
src/Styleguide/Components/MarketInsights.tsx
src/Styleguide/Components/SelectedExhibitions.tsx
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-173
See https://www.artsy.net/artist/wei-tan
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-131
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-177
- need to qa
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-176
(dup)

@mzikherman => [Artist Bugfixes] Misc Jira tickets

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Styleguide/Elements/Radio.tsx

This PR updates the `<Radio>` component to pass in the selected value to the `onSelect()` callback. Once this is merged there needs to be a quick QA against e.g. https://www.artsy.net/artist/andy-warhol. Other than that this PR should be good to merge.

Update <Radio> to pass in value in to onSelect callback

---

src/Apps/Artist/ArtistApp.tsx
src/Apps/Artist/Routes/CV/CVItem.tsx
src/Apps/Artist/Routes/CV/index.tsx
src/Apps/Artist/Routes/Shows/ArtistShows.tsx
src/Apps/Artist/Routes/Shows/index.tsx
src/Apps/Artist/routes.tsx
src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
src/Apps/__stories__/Apps.story.tsx
src/Components/Artwork/FillwidthItem.tsx
src/Router/buildClientApp.tsx
src/Router/buildServerApp.tsx

- Add dynamic Gemini images
- Fix padding around missing sections under /shows
- Remove extra CV hz line (need to use `last-child` in css since sections might be missing)

[BUGFIX artist] Various UI fixes

---

src/Apps/Artist/routes.tsx
src/Apps/__stories__/Apps.story.tsx

[PATCH artist] Update route default

---

src/Apps/Order/Components/ItemReview.tsx
src/Apps/Order/Components/__stories__/ItemReview.story.tsx

[Jira](https://artsyproduct.atlassian.net/browse/PURCHASE-309)
[Zeplin](https://zpl.io/bzWx4KE)
This component is currently only used on desktop.

Add ItemReview component

---

src/Apps/Order/Routes/Shipping/index.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-326
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-327
Alright finally...

User should see additional content or shipping form depending on the shipping option selected

---

src/Apps/Order/Components/ItemReview.tsx
src/Apps/Order/Components/__stories__/ItemReview.story.tsx
src/Apps/Order/Routes/Submission/index.tsx
src/Apps/__stories__/OrderApp.story.tsx
src/__generated__/ItemReview_artwork.graphql.ts
src/__generated__/Submission_order.graphql.ts
src/__generated__/routes_SubmissionQuery.graphql.ts

I accidentally did this as part of the work to connect the Status page to Metaphysics, but it's part of the Review page which @sweir27 is working on.

@sweir27 => Connect ItemReview to Metaphysics

---

data/schema.graphql
data/schema.json
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/index.tsx
src/Apps/Artist/Routes/Overview/state.ts
src/Apps/__stories__/Apps.story.tsx
src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
src/__generated__/ArtworkFilter_artist.graphql.ts
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

@mzikherman => Update filter from ecommerce -> acquireable

---

src/Styleguide/Components/ReadMore.tsx
src/Styleguide/Components/__stories__/ArtistBio.story.tsx
src/Styleguide/Components/__stories__/ReadMore.story.tsx
src/Styleguide/Components/__tests__/ArtistBio.test.tsx
src/Styleguide/Components/__tests__/ReadMore.test.tsx

Little fix to autoExpand if maxChar is less than total count

[FIX artistPage] ReadMore: Dont show read more if less than maxChar

---

src/Components/MinimalCtaBanner.tsx
src/Components/Publishing/Article.tsx
src/Components/Publishing/__tests__/Article.test.tsx

This addresses the QA items in https://artsyproduct.atlassian.net/browse/GROW-844.
- Increases the CTA font-size
- Changes banner height
- Addresses animation delay
- Fixes z-index problem
- Passes the `redirect-to` as a query param
- Prevents multiple CTA banners from showing up on infinite scroll articles

@eessex: addresses mobile cta banner qa items

---

src/Styleguide/Elements/Message.tsx
src/Styleguide/Elements/__stories__/Message.story.tsx

Adds a new `size` prop to `<Message>`

@zephraph => [FEATURE message] Add size prop to Message

---

src/Components/Authentication/Desktop/LoginForm.tsx
src/Components/Authentication/Desktop/SignUpForm.tsx
src/Components/Authentication/Mobile/LoginForm.tsx
src/Components/Authentication/Mobile/SignUpForm.tsx
src/Components/Authentication/__tests__/Desktop/LoginForm.test.tsx
src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
src/Components/Wizard/Wizard.tsx

[Auth] use new method to display errors, add spinner for last onsubmit

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/MobileActionSheet.tsx
src/Apps/Artist/Routes/Overview/state.ts

Fixes https://artsyproduct.atlassian.net/browse/DISCO-154?focusedCommentId=13540&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13540

[BUGFIX artistPage] Fullscreen overlay

---

src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.test.tsx

Cleanup from #1139 that fell out of Show&Tell this morning. Also addresses TODO from https://github.com/artsy/exchange/pull/106.

Cleanup from #1139.

---

src/Components/Authentication/Desktop/ModalManager.tsx

https://artsyproduct.atlassian.net/browse/GROW-828

[PATCH auth] add lifecycle hooks to ModalManager

---

data/schema.graphql
data/schema.json
src/Styleguide/Components/WorksForYou/WorksForYouArtist.tsx
src/Styleguide/Components/WorksForYou/WorksForYouContents.tsx
src/Styleguide/Components/WorksForYou/index.tsx
src/Styleguide/Components/__stories__/WorksForYou.story.tsx
src/__generated__/WorksForYouArtistPaginationQuery.graphql.ts
src/__generated__/WorksForYouArtist_viewer.graphql.ts
src/__generated__/WorksForYouContentsPaginationQuery.graphql.ts
src/__generated__/WorksForYouContents_viewer.graphql.ts
src/__generated__/WorksForYouQuery.graphql.ts

This is the last prop that the sidebar should be passing in.

@damassi => Allow a for sale or all toggle to be passed in for works for you

---

data/schema.graphql
data/schema.json
src/Assets/Icons/ChevronIcon.tsx
src/Styleguide/Components/WorksForYou/WorksForYouArtist.tsx
src/Styleguide/Components/WorksForYou/WorksForYouContents.tsx
src/Styleguide/Components/WorksForYou/index.tsx
src/__generated__/WorksForYouArtistPaginationQuery.graphql.ts
src/__generated__/WorksForYouArtist_viewer.graphql.ts
src/__generated__/WorksForYouContentsPaginationQuery.graphql.ts
src/__generated__/WorksForYouContents_viewer.graphql.ts
src/__generated__/WorksForYouQuery.graphql.ts

Displaying counts, date of the bundle, some visual polish

@mzikherman => WorksForYou, some updates/QA

---

src/Styleguide/Components/WorksForYou/WorksForYouArtist.tsx
src/Styleguide/Components/WorksForYou/WorksForYouContents.tsx
src/Styleguide/Components/WorksForYou/index.tsx

@mzikherman => Pass current user down for /works-for-you components

---

src/Styleguide/Components/WorksForYou/index.tsx

This winds up looking pretty nice testing locally!

@mzikherman => Add a spinner for the loading state in WorksForYou

---

package.json
yarn.lock

to include changes from artsy/palette#64

bump palette version

---

src/Apps/WorksForYou/WorksForYouArtist.tsx
src/Apps/WorksForYou/WorksForYouContents.tsx

@mzikherman => Add spinner to inf scrolling on WorksForYou components

---

src/Apps/WorksForYou/WorksForYouArtist.tsx
src/Apps/WorksForYou/WorksForYouContents.tsx

@mzikherman => Move to 3 column layout for WFY

---

src/Apps/WorksForYou/WorksForYouArtist.tsx
src/Apps/WorksForYou/WorksForYouContents.tsx
src/__generated__/WorksForYouArtistPaginationQuery.graphql.ts
src/__generated__/WorksForYouArtist_viewer.graphql.ts
src/__generated__/WorksForYouContentsPaginationQuery.graphql.ts
src/__generated__/WorksForYouContents_viewer.graphql.ts
src/__generated__/WorksForYouQuery.graphql.ts

looks like <img width="354" alt="screen shot 2018-08-23 at 5 27 39 pm" src="https://user-images.githubusercontent.com/1457859/44552934-e0992300-a6f9-11e8-8fe0-68b9826bbdc7.png">

@mzikherman => Add image and some QA from Brian for WorksForYou

---

package.json

Adding alias suggested in https://github.com/artsy/artsy.github.io/pull/479

Add script for node inspect alias

---

.circleci/config.yml

A start to adding some clarification/comments to Reaction's CircleCI config. This is meant to be a companion to the blog post I'm working on but also generally just to demystify the config a bit.

Adds some comments to the circle config

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx

Quick bugfix for https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-167

[FIX artistPage] Expand link

---

src/Apps/WorksForYou/Components/MarketingHeader.tsx
src/Apps/WorksForYou/WorksForYouArtist.tsx
src/Apps/WorksForYou/index.tsx
src/Styleguide/Elements/Box.tsx

This adds the (currently WIP, from design perspective) `<MarketingHeader />` component to the Works For You page: 
@mzikherman - should this be gated behind a Feature Flag? or is it already gated at the Force level?

@mzikherman => [WorksForYou] Add <MarketingHeader /> component

---

src/Apps/WorksForYou/index.tsx
src/Apps/__stories__/WorksForYou.story.tsx

There was a bit of PR overlap between old and new React context pattern 
Fixes https://sentry.io/artsynet/force-staging/issues/665731048/

@mzikherman => [FIX worksForYouPage] Replace old context with new

---

data/schema.graphql
data/schema.json
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Artist/Routes/Overview/index.tsx
src/Apps/Artist/Routes/Overview/state.ts
src/Apps/Artist/routes.tsx
src/Apps/__stories__/Apps.story.tsx
src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
src/__generated__/ArtworkFilter_artist.graphql.ts
src/__generated__/Overview_artist.graphql.ts
src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts

Whoops, I forgot to do this (after doing the backend filtering/indexing). Came up in the demo today.

@damassi => Hook up inquireable_only filter

---

.babelrc
src/Artsy/Relay/createEnvironment.ts
tsconfig.json
typings/json.d.ts

Improving the captured information in datadog slightly.

[relay] Include version in user-agent header.

---

src/Artsy/Analytics/Schema/Values.ts
src/Components/Authentication/FormSwitcher.tsx
src/Components/Authentication/Mobile/SignUpForm.tsx
src/Components/Authentication/Types.ts

This addresses https://artsyproduct.atlassian.net/browse/GROW-684 and adds analytic events for successfully clicking the next button on the email and password steps of the mobile signup flow.

@l2succes: [FEATURE Authentication] add analytics to mobile wizard steps

---

src/Apps/Collect/Components/ArtworkGrid/CollectArtworkFilterRefetch.tsx
src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/__generated__/ArtworkGrid_viewer.graphql.ts
src/__generated__/routes_CollectAppQuery.graphql.ts

- Adds period filter
- Hooks up isLoading to display indicator when fetching new data

[Collect] adds period filter and loading indicator

---

src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWork.tsx
src/Apps/Artwork/Components/ArtworkDetails/index.tsx
src/Apps/Artwork/Components/__stories__/ArtworkDetails.story.tsx
src/__generated__/ArtworkDetailsQuery.graphql.ts

So that ArtworkDetails can be viewed as a stand alone component.
Thanks @damassi for the pairing on this one!

add ArtworkDetailsQueryRenderer

---

src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
src/Styleguide/Components/__stories__/ReadMore.story.tsx

This is mostly super minor changes to Artwork details. Also added a test just to illustrate how input with special characters will look in ReadMore. Does not do anything about it for now but wanted to have an example.
I'll self merge that for faster deploy but please let me know of any feedback here.

[PATCH artwork] Artwork details implementation

---

package.json
src/Apps/Collect/Components/ArtworkGrid/CollectArtworkFilterRefetch.tsx
src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/Collect/FilterState.tsx
src/Apps/Collect/routes.tsx
src/__generated__/ArtworkGrid_viewer.graphql.ts
src/__generated__/CollectArtworkFilterRefetchQuery.graphql.ts
src/__generated__/CollectArtworkFilterRefetch_viewer.graphql.ts
src/__generated__/routes_CollectAppQuery.graphql.ts
yarn.lock

This isn't styled at all, (and I'm not sure how to yet, I'm just importing the base CSS), but it works!

@l2succes => [WIP] Working price slider

---

src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/Collect/Components/Filters/PriceRange.tsx
src/Styleguide/Elements/Range.tsx
src/Styleguide/Elements/__stories__/Range.story.tsx

[Collect] Styles price range filter

---

src/Apps/Order/Components/AddressForm.tsx
src/Apps/Order/Routes/Payment/index.tsx

Ash and I spotted a couple of issues with #1217 after it was merged. This stuff is trivial so I'm just going to merge it myself.

Fix a couple of things from phoneNumber PR

---

src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/__generated__/PaymentRouteCreateCreditCardMutation.graphql.ts
src/__generated__/PaymentRoutesetOrderPaymentMutation.graphql.ts
src/__generated__/Payment_order.graphql.ts
src/__generated__/routes_PaymentQuery.graphql.ts

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-331
I was having trouble writing tests due to the Stripe elements requiring `context`. I'll follow up and add more test coverage once I solve the issue in mocking `context`.
(Here is [a high quality MP4](https://artsy.slack.com/archives/C9YNS4X32/p1536183131000100) in case the screenshot below isn't helpful.)

User can submit payment details

---

src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
src/Apps/__stories__/Apps.story.tsx
src/__generated__/ArtistArticlesQuery.graphql.ts
src/__generated__/ArtistArticles_artist.graphql.ts
src/__generated__/routes_ArticlesQuery.graphql.ts

🙈 This was just displaying the date incorrectly formatted (which caused it to appear out of order as well). The sort was correct, it was a formatting thing.

@damassi => [Bugfix] Proper published display for articles

---

data/schema.graphql
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
src/__generated__/ReviewSubmitOrderMutation.graphql.ts
src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts

Coordinated with: 
- https://github.com/artsy/exchange/pull/172
- https://github.com/artsy/metaphysics/pull/1276
- https://github.com/artsy/force/pull/2879
- https://github.com/artsy/eigen/pull/2683
⚠️  As soon as the metaphysics one goes in, this one needs to have it's metaphysics submodule bumped to master before being merged.

[COORDINATED MERGE] Incorporate new ecommerce error shape

---

src/Artsy/Router/__test__/buildServerApp.test.tsx

This adds a test to cover some functionality added in #1241. Also did some refactoring to make `getWrapper` a little more useful.

Add a test for react-head SSR

---

src/Apps/Collect/CollectApp.tsx

Closes: https://artsyproduct.atlassian.net/browse/GROW-900

[Collect] Adds footer

---

src/Components/Artwork/Contact.tsx

Fixes https://sentry.io/artsynet/force-production/issues/687093866/

[FIX bids] Fixes undefined prop issue

---

.storybook/webpack.config.js
package.json
src/Apps/WorksForYou/Components/MarketingHeader.tsx
src/Apps/WorksForYou/WorksForYouContents.tsx
src/Apps/WorksForYou/index.tsx
src/Apps/__stories__/WorksForYou.story.tsx
src/Components/__tests__/__snapshots__/ErrorPage.test.tsx.snap
typings/sharify.d.ts
yarn.lock

@oxaudo => [WFY] Add Buy Now video header

---

data/schema.graphql
src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.test.tsx
src/Apps/__test__/Fixtures/Order.ts
src/__generated__/Shipping_order.graphql.ts
src/__generated__/routes_ShippingQuery.graphql.ts

Added a flag to check if artwork is able to be picked up. If it is not UI does not display radio buttons with options to ship or pickup, rather it just displays a shipping address form.

Purchase419

---

package.json

Move relay-mock-network-layer to deps

[PATCH package] Move relay-mock-network-layer to deps

---

src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/__tests__/OrderApp.test.tsx
src/Apps/Order/routes.tsx
src/Apps/__stories__/OrderApp.story.tsx
src/__generated__/routes_OrderQuery.graphql.ts

Ashley and I have been pairing to work through this. 
Turns out that programmatic redirects are a bit tricky with found. We still have to write tests too.

Redirect to status page if order not pending

---

src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/__tests__/Review.test.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-348
This is pretty much the same as #1252. Skipping screenshots since we've done this twice already but happy to for people who don't have context.

[FEATURE BNMO] User sees generic error modal if there is an error when submitting an order

---

src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/Collect/FilterState.tsx

Addresses the analytics aspect of https://artsyproduct.atlassian.net/browse/GROW-893. This ensures we fire analytic events for changes on the price and sort filter.
**Price:**
**Sort:**

[FIX collect] adds price and sort to setFilter

---

src/Components/Grid.tsx
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
src/Components/Publishing/Video/VideoCover.tsx
src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
src/Components/__stories__/Grid.story.tsx
src/Components/__stories__/Icons.story.tsx
src/Components/__stories__/PopoverExamples/DisplayPopoverOnClickExample.tsx

Reverts removing the legacy `Grid` component in favor adding a deprecation message as it's still being used in some components in Force.

[Grid] revert removing grid component and fix type errors

---

src/Apps/Order/Components/AddressForm.tsx
src/Apps/Order/Components/Helper.tsx
src/Apps/Order/Components/ShippingAndPaymentReview.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.test.tsx
src/Apps/__stories__/OrderApp.story.tsx

This PR updates the copy for the BN flow to match the final version defined [here](https://www.notion.so/artsy/Product-Copy-BNMO-Collector-3080fe4cbb594e2c8314b2614dad56b2).

Finalize copy for BN flow

---

package.json
src/Apps/Artwork/Components/ArtistInfo.tsx
src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
src/Apps/Artwork/Components/__stories__/ArtistInfo.story.tsx
src/Apps/Artwork/Components/__stories__/ArtworkDetails.story.tsx
src/Apps/Artwork/Components/__stories__/ArtworkSidebar.story.tsx
src/Apps/__test__/Fixtures/ArtistBio.ts
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Styleguide/Components/ArtistBio.tsx
src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/EntityHeader.tsx
src/Styleguide/Components/MarketInsights.tsx
src/Styleguide/Components/SelectedExhibitions.tsx
src/Styleguide/Components/__stories__/EntityOverline.story.tsx
yarn.lock

**Blocker:**
https://github.com/artsy/palette/pull/93
**Addresses:** 
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&view=planning&selectedIssue=DISCO-299
**Zeplin:** 
- https://zpl.io/an9njYY
TODO:
Will follow up with a second PR that wraps things in a QueryRenderer for Force.

@oxaudo => Update <ArtistInfo /> component and add <EntityOverview />

---

src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/__tests__/Review.test.tsx

finishes https://artsyproduct.atlassian.net/browse/PURCHASE-473
This PR just removes the checkbox in the review step.

[FEATURE BNMO] Remove checkbox on review step

---

.vscode/settings.json
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.test.tsx

This is a followup to @yuki24 's  comments at the bottom of https://github.com/artsy/reaction/pull/1265. It's close to ready but I'll wait until reaction is faffed out and healthy again (plus it is Friday).

Refactor #1265 per yuki24's comments

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx

Previous version:
Updated version:
[See Original JIRA ticket here:](https://artsyproduct.atlassian.net/browse/DISCO-221)

Spacing and text case changes in Buy Now filter text

---

src/Apps/Order/Components/AddressForm.tsx

Just noticed the TypeScript errors, will pick it up from there tomorrow.

Adds HTML attributes for iOS web views

---

src/Components/Artwork/Details.tsx

tiny bugfix and then @briansw gives the ok on the bricks!

@mzikherman => [ArtworkBrick] Bugfix: dont make multiple artists separate lines

---

src/Components/Artwork/Details.tsx
src/Components/Artwork/Metadata.tsx

Since we're including these new brick styles in with the badges and overall BNMO lab feature, switch to that.

@mzikherman => [ArtworkBrick] Move to BNMO lab feature, vs its own

---

src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/__stories__/Apps.story.tsx

Addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&modal=detail&selectedIssue=GROW-920

@l2succes => Time filter is open, fix storybooks

---

package.json
src/Apps/Artist/routes.tsx
src/Apps/Collect/routes.tsx
src/Apps/Order/routes.tsx
src/Artsy/Router/Components/ClientRouter.tsx
src/Artsy/Router/buildServerApp.tsx
src/Artsy/Router/index.ts
src/Utils/__test__/trace.test.ts
src/Utils/trace.ts
yarn.lock

Related to 
https://artsyproduct.atlassian.net/browse/PLATFORM-724

[Artist] Add DataDog tracing around SSR work

---

src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx

DISCO 303: Move select dropdown icon to fix inside container margins

---

src/Apps/Order/Components/AddressForm.tsx
src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Review.test.tsx

This covers a few small items:
- Fixes spacing on the views by reducing the top margin (https://artsyproduct.atlassian.net/browse/PURCHASE-500)
- Adds margin to bottom of every page (https://artsyproduct.atlassian.net/browse/PURCHASE-503)
- Fixes spacing under phone number field (https://artsyproduct.atlassian.net/browse/PURCHASE-502)
- Makes the `change` links actually link back to the correct pages (https://artsyproduct.atlassian.net/browse/PURCHASE-347)
Phone number + bottom spacing:
Top-margin:

Checkout flow visual QA + enabling "change" links on review step

---

src/Apps/Collect/Components/ArtworkGrid/MobileActionSheet.tsx
src/Apps/Collect/Components/ArtworkGrid/index.tsx

[Collect] responsive UI for mobile

---

src/Apps/WorksForYou/Components/MarketingHeader.tsx
src/Artsy/Analytics/Schema/Values.ts

Adds tracking to the WFY page. @mzikherman - I've never used this new tracking system (nor really had to mess with tracking at all in Force) but it _seems_ self-explanatory -- does my usage seem ok? This is the snippet that @cavvia pasted into the ticket:
```js
analytics.track('Click', { 
type: 'Link', 
context_module: 'BNMO Banner', 
destination_path: $destination_path 
})
```
**JIRA**: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-239

[PATCH wfy] Add tracking to WFY page

---

.storybook/webpack.config.js
src/Apps/Artist/Components/ArtistHeader.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/ArtistInfo.tsx
src/Apps/Artwork/Components/__stories__/ArtistInfo.story.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/Status/index.tsx
src/Apps/__stories__/Apps.story.tsx
src/Artsy/SystemContext.tsx
src/Components/Artwork/FillwidthItem.tsx
src/Components/Artwork/GridItem.tsx
src/Components/Artwork/Save.tsx
src/Components/ArtworkGrid.tsx
src/Styleguide/Components/ArtistCard.tsx
src/Styleguide/Components/EntityHeader.tsx
src/Styleguide/Components/Footer.tsx
src/Styleguide/Components/SelectedExhibitions.tsx
src/__generated__/ArtistInfoQuery.graphql.ts
src/__generated__/ArtistInfo_artist.graphql.ts
typings/sharify.d.ts

**Follow-up post merge**: https://github.com/artsy/force/pull/2942
Adds a new `<ArtistInfo />` component and `QueryRenderer` for use in the old and new Artist Page

@oxaudo => [Artist Page] Connect <ArtistInfo /> to live data

---

src/Components/Artwork/Contact.tsx

Fixes https://sentry.io/artsynet/force-production/issues/704791349/

[FIX artwork] Make artwork safer

---

package.json
src/Apps/WorksForYou/WorksForYouContents.tsx
src/Apps/__stories__/WorksForYou.story.tsx
src/Components/Publishing/Byline/__tests__/__snapshots__/Byline.test.tsx.snap
src/Components/Publishing/Byline/__tests__/__snapshots__/Date.test.tsx.snap
src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
src/Components/Publishing/Byline/__tests__/__snapshots__/ShareDate.test.tsx.snap
src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/VerticalOrSeriesTitle.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
yarn.lock

[This issue links to a change in @artsy/palette](https://github.com/artsy/palette/pull/97/files)

Disco860 no text wrap

---

src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
src/Apps/Order/OrderApp.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderPayment.ts
src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
src/Apps/Order/Routes/__tests__/Review.test.tsx
src/Apps/Order/routes.tsx
src/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
src/__generated__/ReviewSubmitOrderMutation.graphql.ts
src/__generated__/ShippingAndPaymentDetailsQuery.graphql.ts
src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts
src/__generated__/routes_OrderQuery.graphql.ts
src/__generated__/routes_PaymentQuery.graphql.ts
src/__generated__/routes_ReviewQuery.graphql.ts
src/__generated__/routes_ShippingQuery.graphql.ts
src/__generated__/routes_StatusQuery.graphql.ts

Updates mutations and queries related to order to use the ecommerce prefix. This is necessary for stitching to exchange.

Update order mutation and queries to use ecommerce prefix

---

src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/Collect/Components/Filters/PriceRange.tsx
src/Apps/Collect/FilterState.tsx
src/Apps/Collect/__tests__/FilterState.test.tsx

Fixes an issue where the filter state for the price filter was not reflected properly in the UI

[FIX Collect] fix Price Range filter state bug

---

src/Components/Artwork/GridItem.tsx

[See DISC0-222](https://artsyproduct.atlassian.net/browse/DISCO-222)

DISCO:222 add link to artwork on Buy Now badges

---

src/Apps/Artist/Components/ArtistHeader.tsx

Fixes weird alignment issue related to something else being fixed:
Bug:

[FIX artisButton] Fix button alignment

---

package.json
src/Apps/Artist/Components/ArtistHeader.tsx
src/Apps/Artwork/Components/ArtistInfo.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/WorksForYou/MarketingHeader.tsx
src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
src/Apps/WorksForYou/WorksForYouFeed.tsx
src/Apps/WorksForYou/index.tsx
src/Apps/__stories__/WorksForYou.story.tsx
src/Styleguide/Components/Carousel.tsx
src/Styleguide/Components/EntityHeader.tsx
src/Styleguide/Components/__stories__/Carousel.story.tsx
src/Styleguide/Components/__stories__/EntityHeader.story.tsx
src/Styleguide/index.tsx
src/__generated__/ArtistHeader_artist.graphql.ts
src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
src/__generated__/WorksForYouArtistFeed_viewer.graphql.ts
src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
src/__generated__/WorksForYouFeed_viewer.graphql.ts
src/__generated__/WorksForYouQuery.graphql.ts
src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
yarn.lock

Addresses: 
- [Avatar, name, and meta line should all link to artist's page](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-342)
- [Bullet separating the meta info from the follow button should be #666](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-343)
- [WFY (web) - Update wording for sub-header and description](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-336)
- [Artist page carousel is too tall](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-306)
- [Works for you spacing issues](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=deta …

@mzikherman => Various Tickets / Fixes 

---

data/schema.graphql
src/Components/FollowButton/FollowProfileButton.tsx
src/Components/__stories__/FollowButton.story.tsx
src/__generated__/FollowProfileButtonMutation.graphql.ts
src/__generated__/FollowProfileButton_profile.graphql.ts

This is a copy/paste mostly from FollowArtist button. Did not add old button style here because we have no usage for it now.

add FollowProfile button to be used for partner follow

---

src/Apps/Artist/Routes/Overview/index.tsx
src/Apps/Artwork/Components/ArtistInfo.tsx
src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx
src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
src/Styleguide/Components/ArtistBio.tsx

Addresses: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&modal=detail&selectedIssue=DISCO-344
Updates character count cap from 300 to `100` in xs and `320` for rest.

[PATCH characterCount] Updates character count based on xs

---

src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Payment.test.tsx
src/Apps/Order/Routes/__tests__/Shipping.test.tsx
yarn.lock

Tracked in: https://artsyproduct.atlassian.net/browse/PURCHASE-498
This PR makes region and postalCode address validations required only for US and CA countries.

Address Validations

---

package.json
src/Apps/__stories__/Apps.story.tsx
src/Components/Artwork/GridItem.tsx
yarn.lock

SH'ed with @briansw for the last changes.

@damassi => Tweak to artwork badge display

---

src/Apps/Collect/Components/ArtworkGrid/MobileActionSheet.tsx
src/Apps/Collect/Components/Filters/PriceRange.tsx

Addresses https://artsyproduct.atlassian.net/browse/GROW-923.
- Ensures price filter slider is visible on mobile.
- Centers "Filter" title.

@l2succes: Mobile collect styling fixes

---

src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/Collect/FilterState.tsx
src/Components/Publishing/Byline/__tests__/__snapshots__/Byline.test.tsx.snap
src/Components/Publishing/Byline/__tests__/__snapshots__/Date.test.tsx.snap
src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
src/Components/Publishing/Byline/__tests__/__snapshots__/ShareDate.test.tsx.snap
src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
src/Components/Publishing/Sections/__tests__/__snapshots__/VerticalOrSeriesTitle.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
yarn.lock

- Fixes sort selector error
- Bumps palette

[Collect] fix sort selector

---

.storybook/webpack.config.js
src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
src/Apps/Collect/Components/ArtworkGrid/index.tsx
src/Apps/WorksForYou/index.tsx
src/Apps/__stories__/Apps.story.tsx
src/Components/Artwork/Details.tsx
src/Components/Artwork/GridItem.tsx
src/Components/Artwork/Metadata.tsx
typings/sharify.d.ts

I haven't linked this in Force and tested there, but works in storybooks (setting/unsetting `ENABLE_NEW_BUY_NOW_FLOW` as an env var).

@sweir27 => Replace buy now lab feature with feature flag

---

src/Apps/WorksForYou/MarketingHeader.tsx

Updates copy based on Zeplin spec: https://app.zeplin.io/project/5aabc5d2e01881c81138e58e/screen/5b6c7276066fc661d0dc99c8

[PATCH WFY] Update copy
