artsy/reaction

- data/schema.graphql
- src/Apps/Search/Components/GenericSearchResultItem.tsx
- src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
- src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
- src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
- src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
- src/Apps/Search/Routes/More/SearchResultsMore.tsx
- src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
- src/__generated__/SearchResultsAuctionsQuery.graphql.ts
- src/__generated__/SearchResultsAuctions_viewer.graphql.ts
- src/__generated__/SearchResultsCategoriesQuery.graphql.ts
- src/__generated__/SearchResultsCategories_viewer.graphql.ts
- src/__generated__/SearchResultsCollectionsQuery.graphql.ts
- src/__generated__/SearchResultsCollections_viewer.graphql.ts
- src/__generated__/SearchResultsGalleriesQuery.graphql.ts
- src/__generated__/SearchResultsGalleries_viewer.graphql.ts
- src/__generated__/SearchResultsMoreQuery.graphql.ts
- src/__generated__/SearchResultsMore_viewer.graphql.ts
- src/__generated__/SearchResultsShowsQuery.graphql.ts
- src/__generated__/SearchResultsShows_viewer.graphql.ts
- src/__generated__/routes_SearchResultsAuctionsQuery.graphql.ts
- src/__generated__/routes_SearchResultsCategoriesQuery.graphql.ts
- src/__generated__/routes_SearchResultsCollectionsQuery.graphql.ts
- src/__generated__/routes_SearchResultsGalleriesQuery.graphql.ts
- src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
- src/__generated__/routes_SearchResultsShowsQuery.graphql.ts
Show the `descriptions` from `SearchableItem` results returned from Metaphysics. Metaphysics should handle the formatting of the description. Reaction may truncate the attribute as needed.
> Thread through description to search result items

- src/Components/Artwork/GridItem.tsx
- src/Components/ArtworkGrid/ArtworkGrid.tsx
Refactors the `GridItem` component in the artwork grid to use palette's `Image` component with its new `lazyLoad` prop to manage lazy loading. 
There was a minor change to the API of `GridItem` to use `lazyLoad` instead of `preloadImage` to be more consistent with how we enable lazy loading.
> Use palette image for lazy loading

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
- src/Apps/Search/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Artsy/Router/Components/PreloadLink.tsx
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/Components/v2/RouteTabs.tsx
- src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Updates our `queryMiddleware` to support query in-router query params. See [documentation](https://github.com/4Catalyzer/farce#querymiddleware-and-createquerymiddleware) for more info. 
Also adds a `preload` boolean prop to `PreloadLink` which, if `false`, means that we bypass upfront loading in favor of an immediate route transition, then load, then display. It's not as nice UX but it's the only way we can get around the inability to access `prepareVariables` in an async fashion. See https://graphql.slack.com/archives/C0BEXJLKG/p1553118312208200.
> [Router] Add queryParam support

- src/Apps/Search/Components/SendFeedback.tsx
- src/Apps/Search/Components/ZeroState.tsx
- src/__generated__/SendFeedbackSearchResultsMutation.graphql.ts
Looks like:
and on the artworks tab:
This works for logged in users!
Still to do:
- ~~when user is logged out, there's additional fields for name/email~~
- ~~proper success/error handling~~
- specs
> @dblandin => [SearchResults] Add send feedback component, for logged in users only

- src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
- src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
On artworks without dimensions this code was failing. I provided a default value for `get` so it wouldn't return undefined. 
Something to look into later: Why didn't the types catch this?
> Ensure SEO parsing doesn't fail if no dimensions

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/v2/ArtistCard.tsx
This PR is a sibling of https://github.com/artsy/reaction/pull/2151 and aims to fix the other places where the mobile sign in should be triggered. There were four places I zeroed in on per the Jira ticket:
https://artsyproduct.atlassian.net/browse/DISCO-846
* following artists from the sidebar
* following partners from the partner section
* following artists from their bio section
* following artists from the related artists grid
In each case I have verified by linking my local force to my local reaction that when viewed from a mobile device, the correct flow is rendered:
To do this, I worked backwards from the `ArtworkApp` drilling down to find where we could make a choice about which type of auth experience to trigger. What I found was that in each case there was an `onOpenAuthModal` …
> DISCO-846: Fix other artwork page follows

- src/Apps/Search/Components/SearchMeta.tsx
- src/Apps/Search/Components/__tests__/SearchMeta.test.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
The existing meta tags for the search results page is pretty simple: https://github.com/artsy/force/blob/eaeac419cc7512833946f76b1f851dc3e0c58b00/src/desktop/apps/search/templates/meta.jade
There didn't seem to be any structured data or other SEO/tags found for this. I'll bring up in #seo that we have an opportunity to make some worthy changes to the new search page. But for now, this just implements the existing tags.
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-855 (for now...)
> @pepopowitz => [SearchResults] Add meta tags

- data/schema.graphql
Looks like a breaking change was made to the api. Syncing the schema assuming that these were intentional. I'll crosspost in #graphql to ensure they were intended.
> Sync schema with upstream changes

- src/Apps/Collect/CollectApp.tsx
- src/Apps/Collect/Components/Base/CollectRefetch.tsx
- src/Apps/Collect/Components/Filters/MediumFilter.tsx
- src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
- src/Apps/Collect/FilterState.tsx
- src/Artsy/Analytics/Schema/Values.ts
Very...rabbit-hole-y!
If you go to www.artsy.net/collect, and click a radio button filter (Medium, or Time Period), and select it by clicking the label- you see something strange. It immediately selects and de-selects. There seems to be an `onSelect`/`onClick` being fired twice for the `<Radio>` component, but only when clicking the label portion.
Switching to using `<RadioGroup>` _still_ results in a double fire, but due to a friendlier API you can accomplish the desired goal of the UI being consistent (it remains checked once you select it, vs checking on and off previously).
This implements that here for Collect. However, when doing so I ran into an issue that the analytics tracking would be fired twice (😭 ). So, I refactored that a bit to use decorators.
> @damassi => [Collect] Fix radio buttons which double fire when clicking the label

- src/Apps/Search/FilterState.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
- src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
This correctly initializes the filter fetch, as well as the filter UI, based on params from the URL (so clicking a deep link like `/search2?medium=photography&term=kaws` works.
It also uses `window.history.pushState` to update the URL when interacting with the filter. Propagating the `router` prop and doing a `router.push` seems to trigger 'active' navigation and reloading, whereas for these query params a 'shallow' route is desired.
> @damassi => [SearchResults] Correct URL behavior for filter interactions

- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
Oddly enough this was part of the `Sort` component, which was removed (no sorting for V1). This should just be part of the container and not the sort component.
> @mzikherman => [Search] Bring back Filter for xs breakpoint

- data/schema.graphql
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- src/Apps/Search/Routes/Entity/__tests__/SearchResultsEntity.test.tsx
- src/Apps/Search/SearchApp.tsx
- src/Components/Search/SearchBar.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
- src/__generated__/SearchApp_viewer.graphql.ts
- src/__generated__/SearchBarRefetchQuery.graphql.ts
- src/__generated__/SearchBarSuggestQuery.graphql.ts
- src/__generated__/SearchBarTestQuery.graphql.ts
- src/__generated__/SearchBar_viewer.graphql.ts
- src/__generated__/SearchResultsEntityQuery.graphql.ts
- src/__generated__/SearchResultsEntity_viewer.graphql.ts
- src/__generated__/routes_SearchBarTopLevelQuery.graphql.ts
- src/__generated__/routes_SearchResultsEntityQuery.graphql.ts
"displayType" more accurately reflects the purpose of the attribute, to be a presentation value vs the underlying type of the item.
> Transition uses of `searchableType` to `displayType`

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/SearchApp_viewer.graphql.ts
- src/__generated__/routes_SearchBarTopLevelQuery.graphql.ts
Good call on this one! We need to fetch the count for artworks separately (since it's from the filter endpoint). This also means we need to get the 'total' for search results differently: namely, summing up the aggregations from search _sans_ artwork, and this more accurate artwork count.
Looking good for 'gagosian' now:
Closes https://artsyproduct.atlassian.net/browse/DISCO-884
> @cavvia => [Search] Make sure to get artwork tab count from filter endpoint aggregation

- src/Components/Gene/GeneArtworksContent.tsx
- src/Components/__stories__/Gene.story.tsx
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-866
We used to have 'issues' with infinite scroll where it would start going haywire and eventually start to make requests with really high page numbers. Ship bug to users, have them keep their browser tabs open, and you've just DDOS'ed yourself!
So, we made this very conservative check where: if you ever got back _less_ than the page size, we would just stop paging. The assumption being, even if `hasNextPage` is incorrectly coming back true, once we hit an empty page we would stop.
Relax this check somewhat to still protect us against DDOS and the infinite scroll component behaving badly, but allow for some occasional gaps in data and pages (as we seem to …
> @pepopowitz => [Gene] Relax paging check which stops paging early

- src/Apps/Search/Components/FallbackIcon.tsx
- src/Apps/Search/Components/GenericSearchResultItem.tsx
We're supporting specific fallback icons for Auction, Article, Artist, City, Fair, Institution, Page, and Tag entity types. All others will fallback to the NoImageIcon.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-864
> Show fallback icon when search result item has no image url

- src/Apps/Search/Components/GenericSearchResultItem.tsx
The image returned from Metaphysics isn't desired by the design comps so always render the FallbackIcon for City entity types.
We could also make a change upstream but that would affect both old and new search result pages. We can follow up with that upstream change to Metaphysics once this new page fully rolls out.
> Force search result items of City type to use FallbackIcon

- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/__tests__/index.test.tsx
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCard.tsx
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/ArticleCard.test.tsx
Related to https://artsyproduct.atlassian.net/browse/GROW-1102
I think there was an API change that affected the date display on the `ArticleCard` component.  Some articles have a `media: null` saved, while others have `media: { cover_image_url: null, ... }`.
This PR checks for both types of null media before choosing which date display to use.
> Check for null media keys in RelatedArticleCard

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
There's a larger story around making these navigation tabs proper Palette components, but that feels like a worthy follow-up or upkeep item, rather than a QA item at this point.
Closes https://artsyproduct.atlassian.net/browse/DISCO-890
> @dblandin => [Search] Tweak display of count within tabs

- src/Apps/Order/Routes/Accept/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
changed failure_code to decline_code in check for insufficient funds message
> Fixed error modal for insufficient funds on accept page

- src/Components/Search/SearchBar.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
- src/__generated__/SearchBarRefetchQuery.graphql.ts
- src/__generated__/SearchBarSuggestQuery.graphql.ts
- src/__generated__/SearchBarTestQuery.graphql.ts
- src/__generated__/SearchBar_viewer.graphql.ts
This is a QA PR so here's the ticket:
https://artsyproduct.atlassian.net/browse/DISCO-886
And here's my visual proof:
The only code thing that might be worth considering is the way I split up the rendering of the first suggestion from the rest. I ended up adding the `totalCount` to the first suggestion item and then split up the `SuggestionItem` into a `FirstSuggestionItem` so that I could more easily render these things differently.
That leave us with some duplication in `src/Components/Search/Suggestions/SuggestionItem.tsx`, but it's the sort of duplication that offends me least - open to other ideas though!
Finally, I did not address adding a comma to the total count - is there a MP helper for this? /cc @damassi
> DISCO-886: Search bar QA

- src/Components/Search/SearchBar.tsx
New search results page accepts `term`
> @mzikherman => [Autosuggest] Use term when linking to search results

- src/DevTools/README.md
This was a little past-due 😬 
Realised when writing this that it doesn't support query variables yet 😞 I guess we never needed them in the order app. Should be pretty trivial to add when needed.
> Add basic docs for createTestEnv

- src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/__generated__/ArtistRecommendationsQuery.graphql.ts
- src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
- src/__generated__/ArtistRecommendations_artist.graphql.ts
Addresses
This is a small change to return 3 recommended artists instead of 1. 
Here's what it looks like now! (It's hard to get all three artists in one screenshot, sorry...)
Here are the metaphysics calls for the "ArtistRecommendations" component now:
> User can see top three recommended artists

- src/Components/Search/SearchBar.tsx
cc @jonallured 
Interesting bug! Basically, we were assigning this value _before_ the actual refetch, so it was stale.
> @dblandin => [Autosuggest] Fix tracking of whether results were returned for a query

- src/Apps/Search/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Artsy/Router/Utils/Route.tsx
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-911
Since we have a custom `render`, we don't get the nice `if (!props) Spinner...` behavior from the default `Route`, so we need to provide that.
> @damassi => [SearchResults] Add loading spinner when navigating to entity tab

- .storybook/webpack.config.js
- src/Artsy/index.tsx
Noticed that builds were failing on Netflify, but wasn't sure why due to output being truncated by extraneous progress bar output. 
This updates our Webpack build config to storybooks' [full control mode](https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode) and away from the deprecated 'extend mode'. In full control mode we can silence the default progress bar.
> [Toolchain] Fix CI deployment output

- src/Components/Publishing/Icon/IconImageFullscreen.tsx
Removes null state from icon, which causes type errors in Positron
> [TRIVIAL] Remove null state from IconImageFullscreen

- src/Components/v2/Carousel.tsx
- src/Components/v2/__stories__/Carousel.story.tsx
Follow up to https://github.com/artsy/reaction/pull/2279
Makes the Carousel slighly more customizable by providing `renderArrow` callbacks with a ref to the carousel and some defaults.
> [Carousel] Add arrow render callback

- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
- src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
- src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
- src/Components/v2/Carousel.tsx
Addresses: [GROW-1167](https://artsyproduct.atlassian.net/browse/GROW-1167)
- Center carousel arrow based on image
- Allow for carousel items to scroll infinitely
- Add overlay to images
- Remove "works" text in "works from $$$"
> address qa items for artist collections rail

- .storybook/webpack.config.js
Just noticed the dreaded [hooks error](https://github.com/facebook/react/issues/13991) yesterday -- this should fix it.
> [Toolchain] Make Storybooks hooks-safe

- src/Components/Search/SearchBar.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-925.
* I'm checking against window.location for the current query string, instead of using the `found` router, because this component is stitched in via Force. As far as I can tell, it is not a child of the router, so it doesn't have access to its location. I don't feel great about this approach, but I'm hopeful it is only temporary until @damassi gets the NavBar rewritten.
* I've added what I think is adequate test coverage to the function that parses the term from the query string...let me know if you think any cases are missing.
* I left the `getSearchTerm` function as part of `SearchBar.tsx` because I didn't want to glorify it with its own file. This function feels like a sub-optimal way to identify the current route, and …
> Preserve search term in SearchBar, based on window.location.search

- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
- src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
Addresses: [GROW-1185](https://artsyproduct.atlassian.net/browse/GROW-1185)
- Adds proper overlay and removes gray margins in between images
- Removes gray highlight when tapping rail links
- Changes copy from "Browse by series" to "Browse by iconic collections"
> [PATCH] fix qa items

- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/__generated__/ArtistRecommendationsQuery.graphql.ts
- src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
- src/__generated__/RecommendedArtist_artist.graphql.ts
This addresses https://artsyproduct.atlassian.net/browse/DISCO-907.
Feedback from @cavvia was that we should be sorting artworks within artist recommendations by published date descending; this change makes that happen.
> Sort recommended artworks by published date descending

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
- src/Components/Artwork/FillwidthItem.tsx
- src/Components/v2/RecentlyViewed.tsx
Adds more image lazy loading. This time it applies to the `Recently Viewed` component as well as the Artwork grid. There was _some_ lazy loading happening on the Artwork grid, but this makes it much more aggressive for mobile optimizations.
> Lazy load more images on Artist and Artwork pages

- src/Components/Search/SearchBar.tsx
When tapping the magnifying glass icon, users were getting directed to the homepage instead of the search results page. What was happening was: [react-autosuggest](https://github.com/moroshko/react-autosuggest) was intercepting `onBlur` from the input and calling `onSuggestionsClearRequested`, which cleared the search bar of text. _Then_ the button press would submit the form, directing to `/search?term=`, which Force redirects back to `/`. 
Because of how `SearchInputContainer` and `Autosuggest` refs work, checking the `form` property was the easiest way to make ignore button-press events (this piggy-backed on existing code to ignore other click events). I'm open to suggestions, though!
Fixes [DISCO-934](https://artsyproduct.atlassian.net/browse/DISCO-934).
> Fixes search bar button press getting redirected to homepage

- src/Components/Search/SearchInputContainer.tsx
Added [here](https://github.com/artsy/reaction/commit/ae033ae7011d4b839b6257579c03127fc2ed3df9), the explicit typing was for a supertype of what was actually returned. This makes it more obvious, as discussed in today's Show & Tell.
> Updates type to be more specific

- src/Components/Search/SearchBar.tsx
- src/Components/Search/SearchInputContainer.tsx
I was hoping to be able to specify form-level enabled-ness, but the form itself is housed in Force, so instead we have to add the following logic:
- When blurring from search because the icon button was clicked, only mark a descendant as being clicked if the search query is non-empty.
- When pressing enter to submit the form, only submit the search form if the query is non-empty.
- When handling click events on the icon button, only submit the search form if the query is non-empty.
This kind of DOM manipulation is kind of tricky to test, or at least I'm unfamiliar with it and there weren't any existing tests at this level of granularity. If tests would be appropriate for this PR, maybe we could pair on them? 
Follow-up from #2298. Fixes DISCO-934.
> Prevents search bar from submitting with empty query.

- src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/GridItem.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
Re-position the loading skeleton to more closely match the layout rendered by the hydrated search results app.
> Update search results loading skeleton

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/Apps/__stories__/ArtistApp.story.tsx
Turns out there was still a place in Reaction to be defensive about missing images.
cc @cavvia lots of the newer auction result data has missing images (was causing some issues due to an assumption about images being present), as well as `Sotheby's Manual` being set as the organization:
> @kierangillen => [Auction Results] Be defensive about missing images

- package.json
- yarn.lock
Latest version has a smaller payload size.
> Update moment-timezone to reduce payload size

- src/Apps/Artist/Routes/Overview/index.tsx
Addresses A/B test issue brought up in slack: https://artsy.slack.com/archives/C9SATFLUU/p1556042747076600
The experiment viewed event was not firing for the control group. This was because we were only conditionally firing the event in the `componentDidMount` function. We actual want to fire the experiment viewed event at all times. This PR addresses that. This was likely overlooked in [this refactor](https://github.com/artsy/reaction/pull/2172/files).
> ensure experiment viewed event is fired

- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/__generated__/ArtistRecommendationsPaginationQuery.graphql.ts
- src/__generated__/ArtistRecommendationsRendererQuery.graphql.ts
- src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
- src/__generated__/RecommendedArtist_artist.graphql.ts
Addresses https://artsyproduct.atlassian.net/browse/DISCO-948.
This is a pretty straightforward change, but it does increase the chances of seeing "empty" artist recommendations, like this:
We have that work accounted for in a separate issue, though - https://artsyproduct.atlassian.net/browse/DISCO-949.
> DISCO-948: Exclude artworks that aren’t for sale from artist recommendations.

- src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
- src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
This commits adds responsive props to render the loading skeleton optimized for mobile devices.
> Add mobile styling for search results page loading skeleton

- src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
This commit updates styling for various responsive breakpoints.
> Update responsive grid styling for search results skeleton

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Collect/Components/Base/CollectRefetch.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
- src/Artsy/Analytics/Schema/Values.ts
This one was fairly simple, we were missing tracking on 'Ways to Buy' and also the price range slider. When going to add them individually (as the one for the radio button category filter was added), I realized there's a central place we refetch a new filter result set from, so that's the best and most generic place to put the tracking code, and it will cover all the filters w/o needing to add tracking individually to all of them.
This winds up matching how we do it on search results: https://github.com/artsy/reaction/blob/312fcabafe19e2414e2a51d834cc37b764eedeef/src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx#L33
Also, renames the event name to match the current schema.
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISC …
> @pepopowitz => Adjust filter tracking on artist page, make sure to cover all filters

- src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
This commit accounts for a minor differences in placement between Storybooks and Force.
> Adjust header margin on mobile search results skeleton

- .storybook/addons.js
- data/schema.graphql
- package.json
- yarn.lock
As we're writing more styled-system responsive-prop-based components these days we need a way to  trigger breakpoint layouts within storybooks. Thankfully there's an official storybooks plugin, [@storybook/addon-viewport]( https://github.com/storybooks/storybook/tree/master/addons/viewport). 
Users can select a device mode from the dropdown, or more usefully assign a device mode to a given story via config parameter: 
```js
storiesOf("Components/NavBar", module).add("Mobile NavBar", () => {
return <NavBar />
}, {
viewport: { 
defaultViewport: 'iphonex' 
}
})
```
A list of available defaults can be [found here](https://github.com/storybooks/storybook/blob/master/addons/viewport/src/defaults.js).
> [Toolchain] Add @storybook/viewport plugin

- src/Apps/Artist/Routes/Overview/index.tsx
- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
https://artsyproduct.atlassian.net/browse/GROW-1214
Added a condition around the impression tracking event: if there are no collections (Artist page in control group) don't fire the event.
Here's the full list of 54 artist pages that the test should only fire on: https://www.notion.so/artsy/Artist-pages-that-include-series-collections-rail-in-A-B-Test-5945e7d8d6f146b4b6bdf4fc6a76147f
> [Artist] don't trigger tracking event in control group

- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
- src/Components/v2/SelectedExhibitions.tsx
If an artist doesn't have artist insights, don't show the button
https://cl.ly/3dbfd53503a3
https://www.artsy.net/artwork/suzanne-heintz-the-tree
The "Show artist insights" button was displaying when the MarketInsights and SelectedExhibitions were not for the above artist and possible others.
It turned out that the artist in question did have an exhibition, but the SelectedExhibitions component had a minimum number of exhibitions (2) or it wouldn't render. I adjusted the logic controlling the "Show artist insights" button so that it wouldn't render if the number of exhibitions did not meet the minimum.
> changed logic for displaying 'Show artist insights' button to account for minimum exhibitions

- src/Components/v2/CarouselV2.tsx
CarouselV2 component was not calling `onArrowClick` anymore which broke tracking on the Artist page
JIRA: https://artsyproduct.atlassian.net/browse/GROW-1222
> [Carousel] Add onArrowClick call back

- data/schema.graphql
- src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
- src/__generated__/ArtistRecommendationsPaginationQuery.graphql.ts
- src/__generated__/ArtistRecommendationsRendererQuery.graphql.ts
- src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
- src/__generated__/ArtistRecommendations_artist.graphql.ts
Uses the MP schema from https://github.com/artsy/metaphysics/pull/1686
Tested it locally, seems good. For instance `Robert Delauney` no longer shows up in this section for Pablo Picasso.
> @ashfurrow => [Artist Recommendations] Exclude artists with less than 7 for sale works

- src/Artsy/SystemContext.tsx
- src/Components/NavBar/NotificationsBadge.tsx
#trivial 
We can't access per-request data via sharify in a static way; needed to pass things in via `SystemContext` from force and access them that way.
> [NavBar] Fix notification count

- src/Apps/Artwork/Components/PricingContextModal.tsx
- src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
__User story__
As a user on an artwork page with a histogram
When I click the ? mark and open the FAQ modal
Then I can see the last line of text that says
"If you have feedback or questions let us know."
And the words "let us know" are a mailto link that goes to support@artsy.net
__Before:__
__After:__
> User can see and click on feedback link in FAQ Modal

- src/Components/v2/CarouselV2.tsx
- Carousel arrows now have a `0.25s` fade
- Fixes purple highlight on first slide image
> Carousel arrows now fade and fixes first slide highlighting

- src/Apps/Artwork/Components/PricingContext.tsx
- src/Apps/Artwork/Components/PricingContextModal.tsx
Small positioning and style changes to the question mark icon 
__Before:__
__After:__
> Move question icon next to chart title and change color

- src/Apps/Artwork/Components/PricingContextModal.tsx
> Add space between 2nd and 3rd paragraph in FAQ modal

- src/Components/Publishing/Article.tsx
This PR pushes the AdScript component for serving ads externally below the article component.
> Moves ad script component below article layout component

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
- src/__generated__/ArtworkApp_artwork.graphql.ts
- src/__generated__/routes_ArtworkQuery.graphql.ts
This commit removes the nested QueryRenderer for the ArtistInfo component on the Artwork page, allowing the component to render server-side. This allows search engines to index the data.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-953 :lock:
> Render artwork page artist info component server-side

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
- src/Components/v2/Lightbox/Lightbox.tsx
- src/Components/v2/__stories__/Lightbox.story.tsx
- Followup to https://github.com/artsy/reaction/pull/2365
- Artwork SSR images were still rendering as `<div>`, this PR renders them in `<img>` elements for SEO purposes and adds an `alt` to the image.
- https://artsyproduct.atlassian.net/browse/DISCO-920
> Uses <Img> instead of <div> for SSR artwork image

- src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
There was a small bug in #2369. It made the assumption in `<CollectArtworkGrid>` that the URL was `/collect`...but that component is used by both the `/collect` and `/collection/:collectionId` routes. The result was that paging through results on https://staging.artsy.net/collection/art-of-polka-dots would change the URL to https://staging.artsy.net/collect?page=X. 
This change pulls the path from the current location, instead of a hardcoded value.
For the record, #2369 has been merged & deployed to staging. This fix would ideally also get merged before our next production deploy of Force.
> Use the current URL to determine the paginated URL in a shared component

- patches/react-flickity-component+3.2.0.patch
- Patches Flickity to remove `renderPortal()` to prevent flicker on page load. 
- Will remove this patch once https://github.com/theolampert/react-flickity-component/pull/64 is merged.
> Creates patch for react-flickity-component to fix flicker

- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
- src/Components/v2/CarouselV2.tsx
- src/Components/v2/CarouselV3.tsx
- src/Components/v2/__stories__/CarouselV3.story.tsx
- src/Components/v2/__tests__/Carousel.test.tsx
- Updates ArtworkImageBrowser to use `Flickity`
- Adds page dots to small carouselV3
> Removes slick from ArtworkImageBrowser

- src/Apps/Collect/Components/Collection/Header/index.tsx
Addresses: [GROW-1227](https://artsyproduct.atlassian.net/browse/GROW-1227) & [GROW-1236](https://artsyproduct.atlassian.net/browse/GROW-1236)
This adds some UI Improvements to the collection header per the design [spec](https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5cd1af05e05b3067d84963cd)
> [GROW-1227] - change existing title & breadcrumb placements

- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Desktop/ModalManager.tsx
- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Footer.tsx
- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Components/Authentication/TermsOfServiceCheckbox.tsx
- src/Components/Authentication/Types.ts
- src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
- src/Components/Authentication/__tests__/FormSwitcher.test.tsx
- src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
- src/Components/Authentication/commonElements.tsx
- src/Components/__stories__/Authentication.story.tsx
Related to work adding reCAPTCHA to auth forms, this PR adds an optional google disclaimer text.  Currently this is only available on the signup form, and uses a prop from Force to be turned on when we are ready.
Some updates were made to the footer text generally (design point-person: Jeffrey), with some minor refactoring to replace fonts and colors from `/Assets` with their Palette equivalents. 
Props for `onTwitterLogin` have been removed, because we no longer have the links to allow login/signup with this method.
Also added `ModalType` in a few places, which kills some errors that appear when linking Reaction and Force.
> Auth footer updates

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- Fixes two bugs introduced in new ArtworkImageBrowser
- Passes `flickityRef` to small carousel for view in room feature
- Removes image height to prevent image being squashed
> Passes ref and fixes image height

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- src/Components/v2/CarouselV3.tsx
- Disables small carousel when only one slide by setting `draggable` and `pageDots` to false
> Enable smallCarousel pageDots & draggable only when length > 1

- .storybook/webpack.config.js
- .vscode/settings.json
- src/Components/Publishing/Ads/EnabledAd.ts
- src/Components/Publishing/Ads/__tests__/EnabledAd.test.ts
- src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
- src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
- src/Components/Publishing/Layouts/Components/__tests__/CanvasFooter.test.tsx
- src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
- src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- typings/gravity.d.ts
- typings/sharify.d.ts
This PR temporarily adds the CURRENT_USER field to the Sharify Global Data object. Currently Typescript throws an error because CURRENT_USER isn't a property of the Global Data object. To work around this we have to use Lodash's Get method, which disallows the other type checking benefits of Typescript. As we only need the CURRENT_USER to check if a CURRENT_USER is either an Admin or Allowlisted user to hide the new externally hosted ads, this change is temporary. Once the new ad implementation is production ready, we won't need to hide it behind these checks or feature flags.
> Temporarily adds CURRENT_USER to Sharify Global Data 

- src/Components/Publishing/Ads/EnabledAd.ts
Latest master fails in Force/Reaction due to missing current user: https://circleci.com/gh/artsy/positron/3634
https://circleci.com/gh/artsy/force/23904#tests/containers/1
Adds a check to confirm user exists before looking for properties on it.
> Check if user exists before diving

- src/Components/Publishing/Display/Canvas/index.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Typings.ts
The work to migrate ads to Google Ad Manager (GAM) is still in progress, so for now the props used to populate ad components with GAM hosted data does not need to be required until the migration is complete.
> Changes adUnit and adDimension props from required to optional

- src/Apps/Collect/CollectionApp.tsx
- src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
- src/Apps/Collect/Components/Collection/Header/index.tsx
- src/__generated__/CollectionAppTestQuery.graphql.ts
- src/__generated__/CollectionApp_collection.graphql.ts
- src/__generated__/CollectionFilterContainer_collection.graphql.ts
- src/__generated__/Header_artworks.graphql.ts
- src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Addresses: [GROW-1229](https://artsyproduct.atlassian.net/browse/GROW-1229)
This adds a new header fragment to the collection header that aggregates artists in the collection. It also includes updates for the layout when there are one or multiple artists.
__One artist:__
__Multiple artists:__
To Do:
__Correctly handle singular and plural form:__
__Handle artist with no metadata:__
> Add featured artist module to collection header

- src/Utils/__tests__/repcaptcha.test.ts
- src/Utils/repcaptcha.ts
Disables firing of recaptcha events if `sd.RECAPTCHA_KEY` is missing.
> Do not fire reCAPTCHA actions unless sd.key is present

- src/Artsy/Relay/renderWithLoadProgress.tsx
- src/Components/NavBar/Menus/NotificationsMenu.tsx
Fixed a weird issue with collapsing `<figure>` element in force, due to global css defining a margin of 0, which differs in reaction (reaction has not set css on the figure element at all). The `padding: 22px` could probably be done better, but for now it works and only impacts the Spinner component as rendered within `fetchWithLoaderProgress`. 
#trivial
> [NavBar] Fix padding around spinner fetch

- src/Components/Publishing/Display/Canvas/index.tsx
- src/Components/Publishing/Display/DisplayPanel.tsx
- src/Components/Publishing/Display/NewDisplayCanvas.tsx
- src/Components/Publishing/Display/NewDisplayPanel.tsx
- src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
- src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
- src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
- src/Components/Publishing/Display/__tests__/NewDisplayPanel.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayoutNewAds.test.tsx
- src/Components/Publishing/__stories__/Display.story.tsx
External testers were not seeing the new Google Ad Manager (GAM) hosted ads on 100% of articles because how often ads appear is contingent upon the Share of Voice (SOV) percentage.  One ad campaign has an SOV of 20%, this means that in order to see the new ads on 100% of articles we would have to activate 5 campaigns in the Staging Artsy Writer each day (as Staging Artsy Writer data is overwritten with Production data every night). Rather than doing this and having the logic of how new ads (GAM hosted ads) and current ads intertwined, this PR moves the new ads into their own component. Now the new ads will render on 100% of Standard Articles, on Staging, but they remain only viewable to Admin and/or Allowlisted users.
> Move new hosted ads to their own components in Standard Articles

- src/Components/Artwork/FillwidthItem.tsx
- src/Components/Artwork/__tests__/FillwidthItem.test.tsx
This PR prevents the FillwidthItem from blowing up when there is no image associated. 
We had an issue today where a specific artwork was published with no image. We think that our system protects this from happening, but it happened somehow.
As a result, users were seeing a blank page when they visited https://artsy.net/artist/nadezda-nikolova-kratzer. (You can currently see this in staging - https://staging.artsy.net/artist/nadezda-nikolova-kratzer - at least, until data is sync'ed down from production, or this PR is deployed.)
Investigation into how this artwork was published with no images is happening separately.
> Make FillwidthItem more forgiving of empty artwork images

- src/Apps/Search/Components/NavigationTabs.tsx
Simple PR to add (parens) to the result counts in the search bar:
Fixes DISCO-1023.
> [DISCO-1023] Adds parens to result counts.

- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
- src/Apps/Collect/Components/Base/CollectRefetch.tsx
- src/Apps/Collect/Components/Collection/CollectionRefetch.tsx
- src/Apps/Collect/FilterState.tsx
- src/Apps/Search/FilterState.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
- src/Apps/Search/__tests__/FilterState.test.ts
Addresses https://artsyproduct.atlassian.net/browse/DISCO-1029.
During my work on pagination for the /collect, /collection/:id, and /artist routes, I learned more about the interactions between these routes and their corresponding state containers. This led me to a pattern in #2392 for managing browser history in the /artist route; I think it does a good job of consolidating "state" changes in one place. This PR applies that pattern to the /collect, /collection/:id, and /search routes. 
I'm also optimistic that these changes will make it easier to apply a fix for https://artsyproduct.atlassian.net/browse/DISCO-1032.
> DISCO 1029 - Consolidate url history management in state containers

- src/Components/Artwork/FillwidthItem.tsx
- src/Components/Artwork/__tests__/FillwidthItem.test.tsx
This PR addresses some feedback on PR #2420. 
* Call logger.error with string instead of Error, so that missing image data errors don’t pollute Sentry
* Use a smaller hammer to pass an invalid artwork (without an image) to FillwidthItem
> Address feedback for #2420

- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
- This PR removes page dots from the `LargeCarousel` from `ArtworkImageBrowser` if there's only one image.
> Dont display pageDots if only one image

- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Collect/FilterState.tsx
- src/Apps/Collect/__tests__/FilterState.test.tsx
- src/Apps/Search/FilterState.tsx
- src/Apps/Search/__tests__/FilterState.test.ts
This PR addresses https://artsyproduct.atlassian.net/browse/DISCO-1035.
At any of these URLs: /collect, /collection/:id, /artist/:id, or /search...
If you would select a time period filter, then click back, then click forward, the page would stop working or the results would stop updating. This was because in the constructors of the state containers for these Apps, we were initializing the `major_periods` state property improperly. 
We were setting it to an array of the value passed in through props. Unfortunately, the value passed in through props was _already_ an array, so it was effectively initializing the `major_periods` state property to `[ [ "1990" ] ]` (if I had selected 1990). This caused GraphQL to yell about the type - it was expecting an `Array<string>`, not an …
> DISCO-1035 - Set the `major_periods` state property correctly when constructing the Artist, Collect, and Search apps.

- src/Apps/Artwork/Components/PricingContext.tsx
- src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
- src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1102
This is follow-up from artsy/metaphysics#1696
I checked all the fields, these are the only relevant cases in reaction.
Also, this is safe to merge, the related change in MP is now in production.
> PURCHASE-1102 Remove handling of `null` from the `amount` helper in MP

- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
- src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
Signup form passes `recaptcha_token` returned from google along with other form values to `handleSubmit`.
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-1389
> Signup form includes recaptcha_token on handleSubmit

- src/Apps/Collect/Components/Collection/Header/index.tsx
- src/__generated__/CollectionAppTestQuery.graphql.ts
- src/__generated__/Header_artworks.graphql.ts
- src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Addresses: [GROW-1249](https://artsyproduct.atlassian.net/browse/GROW-1249) and some of [GROW-1250](https://artsyproduct.atlassian.net/browse/GROW-1250)
This refactors the collections header component from being a class component to a functional component. It also addresses the following collection header QA items:
- Removes text shadow form page title
- Only truncates description blurb on smaller viewports
- Use 8 column grid for description blurb on XL screen
- Fixes follow button
- Fixes single artist placement
Leaving out tracking for now and will address in a separate PR.
> Collection header qa refactor

- renovate.json
The automerge settings are already included in the `artsy:lib` workflow. Having them here makes it redundant.
> Clean up renovate config to remove redundant options

- src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-1046
We were setting the `Radio`.`selected` property on the time period that matched the param in the URL, but it had no effect because our `Radio`s are inside of a `RadioGroup`. It seems that `Radio`.`selected` is overridden by `RadioGroup`.`defaultValue` when the radios are located inside a group. 
This PR specifies the default via `RadioGroup`.`defaultValue`. I'll submit a second PR to palette, making a note for users that `Radio`.`selected` is overridden by `Radio`.`defaultValue`.
> Select default time period filter selection via RadioGroup instead of Radio

- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Collect/AnalyticsProvider.tsx
- src/Apps/Collect/FilterState.tsx
- src/Apps/Collect/__tests__/CollectApp.test.tsx
- src/Apps/Collect/__tests__/urlBuilder.test.ts
- src/Apps/Collect/routes.tsx
- src/Apps/Collect/urlBuilder.ts
- src/Apps/Search/FilterState.tsx
~This is an incomplete PR. I wanted to put it out for people to look at while I am out tomorrow.~ This PR is green & ready for review/merge!
Addresses https://artsyproduct.atlassian.net/browse/DISCO-1032
In our `urlFragmentFromState` helpers in the Collect app's `FilterState`, we are tracking all state properties in the querystring. This is correct for all params *except* `medium`. 
We have special routes for the /collect page when filtered by `medium`: `/collect/:medium`. These URLs are indexed by bots, and we like them and want to use them. 
We have special logic to get the medium from the path instead of querystring, so going directly to the url `/collect?medium=photography` does _not_ filter by `medium=photography`. Going to `/collect/photography` _does_ filter by …
> DISCO-1032 Apply `medium` filter in path instead of querystring on /collect

- package.json
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MoreNavMenu.tsx
- src/Components/NavBar/Menus/NotificationsMenu.tsx
- src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
- src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/NotificationsBadge.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
- src/Components/NavBar/__tests__/NavItem.test.tsx
- src/Components/__stories__/NavBar.story.tsx
- src/Utils/BreakpointVisualizer.tsx
- src/Utils/Hooks/useMedia.ts
- yarn.lock
As this is a lot of individual QA changes I'll comment inline where appropriate. 
**Zeplin Spec:**
https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5c649937a981283c0b74cc63
**JIRA:**
https://artsyproduct.atlassian.net/browse/PLATFORM-1409#add-comment?atlOrigin=eyJpIjoiOWZlY2ZhOWFlYzM4NDUzMzhjN2ZmZTEzYWZiZDFlMmMiLCJwIjoiaiJ9
- It would be great if the sign-out link would work by default HTML means (eg when JS is broken)
> [NavBar] Address QA items

- package.json
- src/Artsy/Analytics/useTracking.ts
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
- src/Components/Search/SearchBar.tsx
- src/Components/Search/SearchInputContainer.tsx
- src/Utils/Hooks/useMedia.ts
More NavBar feedback:
1) New "tablet" mobile menu which has larger font, different spacing, etc: 
2) It supports tap highlights: 
3) Bigger open close icons on mobile: 
4) Ensure top nav bar is 60px
- Fixes weird missing icon / input text flash when SearchBar renders on the server
- Updated `react-tracking` to latest, which allows us to remove our custom `useTracking` hook code.
- Renamed `useMedia` hook to `useMatchMedia` and then created a new `useMedia` hook that's specifically tied to Palette's theme file and can be used like so: 
```tsx
import { useMedia } from "Utils/Hooks/useMedia"
const App = () => {
const { xs, sm, md, lg, xl } = useMedia()
return <div>Mobile view? {xs || sm}</div>
}
> [NavBar] QA round 2

- src/Apps/Collect/FilterState.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-1053.
This is a very small change that unsets the "time period" filter properly when you remove it. 
Without this change, if you remove a time period from your filters, you end up with "no results", because it's filtering by `major_periods[0]=null`.
After this change, if you remove a time period from your filters, you end up with the correct results. 
* I couldn't find a good place to add a test for this. I did think about adding a test to [FilterState.test.ts](https://github.com/artsy/reaction/blob/29336af3928e1f20aa885e815ea53ab9fe941acf/src/Apps/Collect/__tests__/FilterState.test.tsx#L3), but it felt very much like a test of an implementation detail that would eventually just get deleted. It feels more like a UI test would be …
> DISCO-1053 - Remove major_periods filter properly from FilterState in /collect & /collection/:id apps

- src/Apps/Collect/Components/Collection/Header/index.tsx
Addresses: [GROW-1250](https://artsyproduct.atlassian.net/browse/GROW-1250)
Ensures "View more" is Unica Medium 14px font.
> [Collection Artist Module] fix font styles for View More truncation element

- renovate.json
Just stops the peril warnings about too many assignees.
> Reduce the assignees on the renovate config

- src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
We're no longer exporting `BarBox` from palette, so we can't use it to match in our tests.
> Match on Bar instead of BarBox to make tests work

- data/schema.graphql
Syncs up some changes from https://github.com/artsy/metaphysics/pull/1728 (which just puts the schema back to a previous state). 
See the above issue for more context.
> Sync with some metaphysics id changes

- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MoreNavMenu.tsx
- src/Components/NavBar/Menus/UserMenu.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/NotificationsBadge.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
- src/Components/NavBar/__tests__/NavItem.test.tsx
- src/Utils/Hooks/useMedia.ts
Fixes an issue where the top nav bar links were only clickable on the text, and not the hover area.
Additionally, fixes
- Safari display issue
- Missing `action_type` tracking prop
> [NavBar] Fix click-area

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Collect/Components/Filters/SortFilter.tsx
New palette's SelectSmall.
Old version of artist:
and new one:
And collect:
old:
new:
> replace use of SmallSelect with SelectSmall

- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
Fixes two issues caught in analytics QA testing:
- When a user has zero notifications, the badge is hidden, with its hover event. Adds a trackable hover event to the bell icon proper
- When there are zero notifications in the cookie, it comes back undefined, which is stripped out by analytics. If undefined, assume 0.
> [NavBar] Fix notification count for zero notifications

- src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- src/Apps/Collect/Components/Filters/SortFilter.tsx
- src/Apps/Collect/Components/Filters/SortFilterSortTypes.tsx
- src/Apps/Collect/Components/Filters/__tests__/FilterContainer.test.tsx
- src/Apps/Collect/Components/Filters/__tests__/SortFilter.test.tsx
- src/Apps/Collect/Components/Filters/__tests__/SortFilterSortTypes.test.tsx
- src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
This PR implements [GROW-1253](https://artsyproduct.atlassian.net/browse/GROW-1253).
This adds a flag in the props of `CollectionFilterContainer` that gets injected into `SortFilter` to let it know when it's being used in a collection page context. If that flag is present it adds two new options to the available sorts: price ascending and price descending.
There was an issue around items that had a price but whose price was hidden showing in the search results. That required a fix to gravity which you can find [here](https://github.com/artsy/gravity/pull/12373).
I've added specs everywhere it seemed appropriate, let me know if you'd like any additional coverage!
> Add price/-price to SortFilter for collections

- src/Components/Search/SearchBar.tsx
- src/Components/Search/SearchInputContainer.tsx
- src/Components/Search/Suggestions/SuggestionItem.tsx
- https://artsyproduct.atlassian.net/browse/DISCO-1051
- The empty suggestion box is redundant with the search input placeholder, this PR removes the empty suggestion box and only displays auto suggestions once a user starts typing 
- Before
- After
- https://artsyproduct.atlassian.net/browse/DISCO-946
- After change
> DISCO-1051/DISCO-946 - Adjustments to search input styling and behavior 

- src/Components/Publishing/Sections/Embed.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Embed.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Addresses: [GROW-1264](https://artsyproduct.atlassian.net/browse/GROW-1264)
While updating the custom editorial embedded `iFrame`, we discovered a pre-existing bug where the embedded `iFrame` was creating extra margin and causing a horizontal window scroll in mobile. This fixes that.
**Before:**
**After:**
> prevent embedded iframe from creating extra margin

- src/Components/NavBar/Menus/UserMenu.tsx
Oops, forgot an item from the list in https://github.com/artsy/reaction/pull/2499. Instant.page was making a request to a nonexistent endpoint.
> [NavBar] Fix instant page issue

- src/Apps/Collect/Components/Collection/Header/index.tsx
This addresses a featured artists module bug reported in [slack](https://artsy.slack.com/archives/C9SATFLUU/p1559758088059500). 
When there are no artworks for a collection there in turn are no featured artists. Currently we display "0" when there are no featured artists which is a bug. This PR strengthens conditional to only display when we have at least one featured articles.
**Before:**
**After:**
> [Collections] do not render featured artist module when there are not featured artists

- src/Artsy/SystemContext.tsx
- src/Components/Artist/ArtistCollectionsRail/index.tsx
As suggested in [another PR](https://github.com/artsy/reaction/pull/2489#discussion_r289566039), this adds a custom react hook for accessing the SystemContext. In addition, it refactors the `ArtistCollectionRail` to use `useSystemContext`.
> add a custom hook for accessing the SystemContext

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Layouts/FeatureLayout.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Typings.ts
This PR re-introduces the new GAM hosted ads on Featured Articles, hidden behind the `areHostedAdsEnabled` feature flag.
> [Article] Add GAM Hosted Ads to Featured Articles 

- package.json
- src/Components/WithCurrentTime.tsx
- src/Components/v2/__tests__/CountdownTimer.test.tsx
- yarn.lock
- This PR updates Reaction to use Luxon in components using Palette components also using Luxon. This also includes tests where Luxon's `Settings` API needed to be mocked to pass local timezone.
- Bumps Palette version to version where Luxon is introduced
> Prepare Reaction for Palette luxon updates 

- src/Components/v2/ArtistCard.tsx
Addresses https://artsyproduct.atlassian.net/browse/DISCO-1070.
This PR modifies the `ArtistCard` component to better handle long artist names/origins, in two ways:
1. It removes the static `margin-top` from the Follow button, replacing it with `margin-top: auto`. This allows the button to flow to the end of the parent container, instead of being placed relative to the ending of the artist text.
2. It applies `text-overflow:ellipsis` (and associated styles) to the artist origin, so that it doesn't flow to a second line. I did not use the `<Truncator>` component, for the reason described at the end of this PR.
These changes are only applied to the `LargeArtistCard`; mobile is not affected.
Weirdly, I found that using the `<Truncator>` component to handle long text on the artist origin …
> DISCO-1070 - Better handling of long artist names/origins

- package.json
- Removes `jsx` and `js` files from test regex as all files should be typescript
> Removes jsx and js from test regex

- src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
- https://artsyproduct.atlassian.net/browse/DISCO-1031
- Hides Related Artworks carousel if there are no artworks to display
- Adds comment describing why we filter `For Sale` artworks
> DISCO-1031 - Don't render related artworks without artworks to display

- src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
- src/Apps/Artist/Routes/Shows/ArtistShows.tsx
- src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- After clicking `next` or a different page number on a search results' tab the page should scroll to top.
- Had implemented a fix for this on Artworks without adding to all tabs
> Scroll to top on all search results pagination

- src/Apps/Collect/Components/Collection/Header/__tests__/Header.test.ts
- src/Apps/Collect/Components/Collection/Header/index.tsx
Address: [GROW-1262](https://artsyproduct.atlassian.net/browse/GROW-1262) 
**Work In Progress:**
This PR handles displaying featured artist based on `artist_ids` if they are explicitly provide and then falling back to `merchandisable_artists` when there is no value for `artist_ids`.
> [CollectionFeatureArtists] only use aggregate artists when there is not explicit artist_ids

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/__tests__/Fixtures/Artist/Components/ArtworkFilter.tsx
This PR is early stage preparation for unifying the 3 different-but-similar FilterState components. It moves the management of the mobile action sheet from Artist/...state.ts into Artist/...ArtworkFilter.ts, so that the three filter state components are even more similar. 
* Tests were added to guide the refactor. 
* Test fixture data was moved into the Fixtures folder.
* I did not modernize ArtworkFilter or state.ts with hooks, because I was more focused on moving the outliers out of state.ts. Hooks conversion will come in future work.
> Extract action sheet management from Artist/state into Artist/ArtworkFilter

- src/DevTools/__tests__/createMockNetworkLayer.test.ts
- src/DevTools/createMockNetworkLayer/index.ts
While writing a test using `renderRelayTree`, I found that I failed to set up some mock data, but the error message didn't fully point me to _which_ mock data I needed to set up. Original slack conversation: https://artsy.slack.com/archives/C2TQ4PT8R/p1560442571197200
This PR adds a little more context to the error messages returned by the mock network layer - specifically, the operation name. In my specific situation, that information would have tipped me off that there was another query I wasn't considering in my test.
> Add more context to mock relay errors (the operation name)

- src/Components/Publishing/News/NewsPanel.tsx
- src/Components/Publishing/News/__tests__/NewsPanel.test.tsx
This PR fixes a bug caused by the upgrade from `moment` to `luxon` that caused some dates to render incorrectly. 
[Links to GROW-1309](https://artsyproduct.atlassian.net/browse/GROW-1309)
Before:
After:
> Fixes date regression bug in News Header 

- src/Components/NavBar/NavBar.tsx
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1553
Fixes a z-index issue in auto-suggestions when the mobile nav is open: 
#trivial
> [Bugfix] Fix navBar zIndex #trivial 

- data/schema.graphql
used `yarn run sync-schema` to update MP schema. Schema update might include vortex partner analytics breaking changes. Better to be safe than blocking force deploy.
> Update MP schema with vortex breaking changes

- src/Apps/Artist/Routes/Overview/index.tsx
Addresses: [GROW-1277](https://artsyproduct.atlassian.net/browse/GROW-1277) & [GROW-1270](https://artsyproduct.atlassian.net/browse/GROW-1270)
This removes the tracking logic and boolean flag for the artist collections rail a/b test.
> remove a/b test tracking logic

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Ensures we send integer type data in Buy Now click events - stripping out dollar signs and commas. Fixes Criteo conversions.
> fix price format in buynow click events

- src/Apps/Collect/Components/Collection/Header/index.tsx
This implements [GROW-1316](https://artsyproduct.atlassian.net/browse/GROW-1316). Easy enough, removed the responsive positioning logic and the module now sits in the same place regardless of screen size. @xtina-starr tagging you for PR #3 today, woo! :)
> featured artists now always positioned below summary

- src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
addresses: [GROW-1332](https://artsyproduct.atlassian.net/browse/GROW-1332)
In this PR, we addresses the following:
- remove dots in the bottom
- group by 4
- do not strip anything from collections title
> [RelatedCollectionsRail]  fix related collections carousel

- src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
- src/Components/Artist/ArtistCollectionsRail/index.tsx
Fixes an issue where the arrows where vertically centered according to the entire carousel height, which includes a top title, thereby throwing off the alignment of the center arrows according to the visual content in the center.
Also fixes missing `renderWithLoadProgress` spinner.
> [ArtistRecommendations] Fix carousel alignment

- src/Apps/Collect/Components/Collection/Header/index.tsx
Addresses: [GROW-1333](https://artsyproduct.atlassian.net/browse/GROW-1333)
This is follow-up to https://github.com/artsy/gravity/pull/12357 which allows us to show a maximum of 12 featured artists. This PR implements truncation for desktop where it was previously only implemented for mobile. The [design spec](https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5cd31ca42e4f02039b718fd7) for reference.
**Before:**
**After:**
> [FeaturedArtistModule] refactor featured artist module to truncate on both desktop and mobile

- src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCard.tsx
This PR fixes a bug introduced from the upgrade to the Luxon library causing invalid dates to appear on these pages.
[Links to GROW-1324](https://artsyproduct.atlassian.net/browse/GROW-1324)
> Fixes DateTime Bug on Sponsored Series Video Landing Page

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/DisplayTargeting.tsx
- src/Components/Publishing/Display/NewDisplayCanvas.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
This PR fixes the padding on 300x50 mobile leaderboard display ads.
Links to GROW-1339(https://artsyproduct.atlassian.net/browse/GROW-1339)
Pre-fix:
Post-fix:
> Bring padding on mobile leaderboard ads up to spec

- src/Apps/Order/Routes/Respond/index.tsx
- src/__generated__/RespondCounterOfferMutation.graphql.ts
- src/__generated__/RespondTestQuery.graphql.ts
- src/__generated__/Respond_order.graphql.ts
- src/__generated__/routes_RespondQuery.graphql.ts
The bug is that currently, after countering, the user is not redirected to the `review` page.
This appears to be an error since we removed `moment`. (Specifically, [this change](https://github.com/artsy/reaction/commit/eca55f2cd40f634ebb2dfbca51235ee5427260ce#diff-99e28aa2a4cbde0ce6ae302e0fd18499R142)).
We've been failing to return `myLastOffer` from a counter response, but it was obscured because of this [odd moment behavior](https://github.com/moment/moment/issues/2697).
> Return myLastOffer so we can correctly redirect

- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Typings.ts
This PR addresses the following:
On Sponsored Features ads should be 300x250, on non Sponsored Features ads should be 300x50. 
[Links to GROW-1356](https://artsyproduct.atlassian.net/browse/GROW-1356)
Post-fix:
Pre-fix:
> Corrects ad dimensions in mobile ads on feature articles

- src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
- src/Components/Publishing/Typings.ts
This PR corrects the ad dimensions on news article mobile ads.
[Links to GROW-1357 ](https://artsyproduct.atlassian.net/browse/GROW-1357)
**Post-fix:**
**Pre-fix:**
> Updates mobile ad dimensions on news articles

- src/Components/Publishing/Display/DisplayAd.tsx
This PR adds a boolean from the `react-gpt` API to collapse empty divs when no ad content is served.
> Handle Flicker Affect When Ad Server Content is Empty

- src/Apps/Collect/Components/Filters/SortFilterSortTypes.tsx
- src/Apps/Collect/Components/Filters/__tests__/SortFilterSortTypes.test.tsx
This shouldn't be merged until [this gravity PR](https://github.com/artsy/gravity/pull/12409) lands. This will force sold items to be sorted to the end of price-sorted collections, regardless of their price.
> updates price sort string to account for "sold" #DONTMERGE

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
- src/Components/v2/Carousel.tsx
- src/Components/v2/RouteTabs.tsx
- src/Components/v2/__stories__/Tabs.Router.story.tsx
- https://artsyproduct.atlassian.net/browse/PURCHASE-1197
- Adds solution for overflow tabs. On desktop when tabs exceed the viewport width an arrow will appear for the user to advance through the tabs in a carousel. On mobile the tabs are simply rendered in a `Flex` element which allows for swiping right and left.
- Depends on https://github.com/artsy/palette/pull/529
> PURCHASE-1197 - Adds TabCarousel

- src/Components/Authentication/Desktop/ModalManager.tsx
- src/Components/Authentication/Types.ts
- src/Components/Modal/Modal.tsx
- src/Components/Modal/__tests__/Modal.test.tsx
Addresses: [GROW-1314](https://artsyproduct.atlassian.net/browse/GROW-1314)
This updates the ModalManager and ModalOptions interfaces to be able to accept an image url so that we can have signup modals that support images. There is a subsequent force PR that makes use of the  image property.
> [GROW-1314] refactor to be able to use image with authentication modal

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
- src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
This PR removes the large empty div on articles when ad blockers are enabled.
> Handles empty divs when ad blocker is enabled

- src/Components/Publishing/Display/DisplayAd.tsx
This PR sets the updateCorrelator option to true to prevent a bug that caused GAM to be unaware of which pages ads were being served on.
[For context on correlators in GAM visit this link](https://support.google.com/admanager/answer/183281?hl=en)
> change sync correlator to true

- src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Apps/__stories__/ArtistApp.story.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
We saw this when testing the ES5 branch. It resulted in some odd sorting and returning artworks that lacked artists. Since artworks _can_ in fact lack artists, this component should just be a bit more defensive (in constructing the alt text).
> @joeyAghion => [Collection Rail] Be more defensive about missing artists in artwork results

- src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-1345.
1. Updates some tests that have gotten out of date, for FeaturedLayout.tsx.
2. Removes `<NewDisplayCanvas>` from Sections.tsx, in favor of rendering `<DisplayAd>` directly.
3. Refactors tests for Section.tsx to remove duplicated lines & improve readability.
> Deprecate old ads from featured articles

- src/Components/Modal/ModalWrapper.tsx
This is related to [GROW-1314](https://artsyproduct.atlassian.net/browse/GROW-1314). Based on the viewport width size for modals with images, we determine to render the modal ModalContainer at 900px for larger screens and 780px for medium size screens. 
Medium (< 900):
Large (> 900):
> [GROW-1314] handle modal width for medium screens

- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
This PR addresses:
Per this Slack discussion: https://artsy.slack.com/archives/GK7Q3BZ6K/p1563203452000700
Design and Content Marketing have updated the ad server requirements such that Featured articles are now expected to render a maximum of 2 ads per article.
[Links to GROW-1401](https://artsyproduct.atlassian.net/browse/GROW-1401}
> Update featured articles to only render a max of 2 ads

- src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Apps/Collect/CollectionApp.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
Address : [Grow-1391](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1391)
- L(<-) , R(->) arrow are centered.
- Related collections carousel shows 16 collections, not 8.
- correctly show the name of the collection page you’re on
- add a hairline to the bottom 
**************************************************************************************
**************************************************************************************
> grow-1391 Collections carousel tweaks QA for artist series and related collections

- src/Apps/Collect/Components/Collection/Header/index.tsx
https://artsyproduct.atlassian.net/browse/GROW-1257
Tricky bit was getting the header element to break out of the confines of the Force div where the Reaction app gets mounted. (H/t to @xtina-starr for the good css suggestions 🙌 )
> Update collections header image GROW-1257

- src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
- src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
- src/Components/v2/ArtworkFilter/index.tsx
- src/__generated__/ArtworkFilterQuery.graphql.ts
- src/__generated__/ArtworkFilter_viewer.graphql.ts
This removes an entire call, just to get the list of mediums available for the given query. The underlying component, since it hardcodes the valid total list of mediums, and can potentially display the shorter list: https://github.com/artsy/reaction/blob/db559d3f92f70f81a309bf3771c3d65ad3da22e6/src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx#L15 , means that we can just drop this call entirely, in favor of simply displaying the fuller list.
I suppose, on mobile, the list of mediums might be slightly increased...but we save an expensive call!
> @damassi => [ArtworkFilter] Remove unneeded call for medium aggregations

- data/schema.graphql
- package.json
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
- yarn.lock
Upgrades to latest, which fixes a false-positive warning thrown by earlier version of Styled Components: 
> It looks like you've wrapped styled() around your React component (Component), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component.
> Upgrade styled-components@4.3.2

- src/Components/Modal/Modal.tsx
Fixes some UI issue with the Modal component with image when rendered on a smaller screen. It should take the full with but only renders on half.
> Fix Modal with image on smaller(xs) screens

- src/Apps/Auction/AuctionApp.tsx
- src/Apps/Auction/Components/ConditionsOfSaleCheckbox.tsx
- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/Auction/routes.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/__generated__/AuctionApp_sale.graphql.ts
- src/__generated__/RegistrationFormCreateBidderMutation.graphql.ts
- src/__generated__/RegistrationFormCreateCreditCardMutation.graphql.ts
- src/__generated__/routes_AuctionQuery.graphql.ts
This implements one of our existing auction registration flows which
creates a payment method and registers the user to bid in the auction.
Zeplin spec :lock: :
https://app.zeplin.io/project/5c59f1624a2d813589f91e07/screen/5d123fbcd17e52705b13ae42
Jira ticket :lock: : https://artsyproduct.atlassian.net/browse/AUCT-462
Items to follow-up on:
- Show an error modal when a mutation against Metaphysics fails.
- Redirect routing if a user already has a payment method or if they're
already registered to build
- Update Country select input to accept onBlur/onChange events and add
to form
- Look into using `isCommittingMutation` helper instead of Formik's
`isSubmitting` for loading indicator
Co-authored-by: @erikdstock
> Add initial auction registration flow

- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
- src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
- src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
- src/__generated__/SearchResultsArtworks_viewer.graphql.ts
- src/__generated__/SearchResultsFilterContainer_viewer.graphql.ts
- src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
This repeats https://github.com/artsy/reaction/pull/2626 , but in the search results page filter component.
The only thing this wholly extra call was doing, was providing a potentially smaller truncated list of mediums. Since this is...pretty minor (plus we have nice 'zero states'), let's just remove it.
The search results filter now just makes 1 request to the filter endpoint, for any operation (pagination, filtering, initial render).
> @damassi => [SearchResults] Remove unneeded call for medium aggregations

- .vscode/launch.json
This PR updates the VSCode launch configurations related to running Jest tests with a debugger attached. They're adapted from this resource from Microsoft's VSCode Recipes:
https://github.com/microsoft/vscode-recipes/tree/851693ce90da46a36a28edeb743e09b3da6b6e6f/debugging-jest-tests
The formerly defined "Run Tests With Debugger" launch configuration used an explicitly defined and deprecated `node debug` invocation and wouldn't attach properly without some adjustments.
I couldn't get the "Launch Server" or "Launch Chrome" tasks to work so I've removed those as well thinking that they're probably not used, but let me know if I'm mistaken.
cc/ @dleve123 because you were asking about testing with a debugger in artsy/reaction recently!
> Update VSCode launch configurations

- src/Components/Publishing/Series/FixedBackground.tsx
- src/Components/Publishing/Series/__tests__/FixedBackground.test.tsx
- src/Components/Publishing/Series/__tests__/__snapshots__/FixedBackground.test.tsx.snap
This PR is in support of [GROW-1444](https://artsyproduct.atlassian.net/browse/GROW-1444). The real change for that PR is in Positron, but _this PR should be merged first_.
As the JIRA ticket describes, this is a temporary fix so that videos can be added without causing a crash.
Diff Analysis: 
```
{
"total_files_changed": 3,
"test_files_changed": 2,
"by_type": {
"tsx": 2,
"snap": 1
}
}
```
> Video Headers Won't Crash

- src/Components/v2/RecentlyViewed.tsx
- src/Components/v2/__stories__/RecentlyViewed.story.tsx
Noticed that our `RecentlyViewed` carousel hadn't been updated with some of our more recent patterns (show hide arrows, alignment, etc); this brings it in line.
> [RecentlyViewed Carousel] Make consistent with recent patterns

- src/Apps/Order/Routes/Offer/index.tsx
- src/Apps/Order/Routes/Respond/index.tsx
- src/Apps/Order/Routes/__tests__/Offer.test.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Apps/__tests__/Fixtures/Order.ts
- src/__generated__/OfferTestQuery.graphql.ts
- src/__generated__/Offer_order.graphql.ts
- src/__generated__/RespondCounterOfferMutation.graphql.ts
- src/__generated__/RespondTestQuery.graphql.ts
- src/__generated__/Respond_order.graphql.ts
- src/__generated__/routes_OfferQuery.graphql.ts
- src/__generated__/routes_RespondQuery.graphql.ts
This PR updates the buyer UI to correctly show prices in the order's currency (be it USD or otherwise).
The biggest changes were in [Exchange](https://github.com/artsy/exchange/pull/456) and [Metaphysics](https://github.com/artsy/metaphysics/pull/1858). Now all `amount`-wrapped fields on `Offer`s and `Order`s coming from metaphysics will display in the correct currency.
This just updates the few places where we display a currency symbol based on the `currencyCode` of the `Order` (previously this just used USD).
cc @mdole @iskounen in case this is relevant to the work on the CMS-side!
> PURCHASE-1282: Updates offer views to handle non-USD currencies

- src/Apps/Auction/__tests__/AuctionApp.test.tsx
- src/Apps/Auction/routes.tsx
- src/Apps/__tests__/Fixtures/Sale.ts
- src/__generated__/routes_AuctionQuery.graphql.ts
Add redirects within the bidder registration flow for the following cases:
- Requested sale is not an auction
- Auction is not in a preview or open state
- Registration window for auction has already closed
- Authenticated user is already registered to bid in the auction
Some open questions:
- I'm not sure I'm covering every scenario here. Would be great to brainstorm other appropriate redirects.
- Some of the redirect structure here is based on what I found in the OrderApp. Is there anything worth abstracting? Maybe the `Redirect` interface with path + reason?
cc/ @ds300
> Add redirects to AuctionApp bidder registration flow

- src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
address: [Grow-1391](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1391)
- Based on the feedback from Jeffrey. On the collection page, "Related to [collection name] " -> "More like [collection name]" 
- Also on the collection page, 
**before changing**, carousel shows 4 items by each clicking on the arrow button. Even though there are less than 4 items, it shows empty space after showing the items. See below.
**after changing**, no more empty space. Also, I found out same story is happen on the artist page. So, for the artist page,  I made the same changing like I did on the collection page. See below.
> Grow-1391,Collections carousel tweaks QA for artist series and related collections

- src/Apps/Collect/CollectApp.tsx
- src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
- src/Apps/Collect/Components/Filters/FilterContainer.tsx
- src/Apps/Collect/Components/Filters/MediumFilter.tsx
- src/Apps/Collect/Components/Seo/SeoProductsForArtworks.tsx
- src/__generated__/CollectAppTestQuery.graphql.ts
- src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
- src/__generated__/CollectApp_viewer.graphql.ts
- src/__generated__/CollectFilterContainer_viewer.graphql.ts
- src/__generated__/CollectionAppTestQuery.graphql.ts
- src/__generated__/SeoProductsForArtworks_artworks.graphql.ts
- src/__generated__/routes_CollectAppQuery.graphql.ts
- src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
This implements https://github.com/artsy/reaction/pull/2638 , but for the Collect page.
Basically, we have an separate call just to fetch the medium aggregations (AKA, the list of mediums and their counts). We then trim off the full [hardcoded list of mediums](https://github.com/artsy/reaction/blob/befdd355f160b717ab6760005600bedd7941adf7/src/Apps/Collect/Components/Filters/MediumFilter.tsx#L33). Since we have a zero-state (and with so much inventory it's very difficult to construct a query where the list is truncated at all), I think it's worth removing this call (especially in light of ongoing Elasticsearch issues....the less queries the better there!).
There was one other thing I noticed, in relations to the SEO 'product' list generated, will comment inline.
> @yuki24 => [Collect] Remove unneeded medium aggregation call

- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/__stories__/Apps.story.tsx
- src/Components/Auction/AuctionRegistrationModal.tsx
- src/Components/Auction/ConditionsOfSaleCheckbox.tsx
- src/Components/Auction/__stories__/AuctionRegistrationModal.story.tsx
- src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
Related Force PR: artsy/force#4346
This PR:
- copies some common registration logic from `Apps/Auction` to `/Components/Auction` (some bits of the app can source from this now)
- Creates a modal in reaction that can do bidder registration using the same mutation as the full registration form. *It uses the new artsy/palette Modal.*
There is a discrepancy with the Zeplin Spec's desktop modal width. This is not configurable in the Reaction Modal as far as I can tell but I will look into it when palette's modal is ready for testing.
> Auct-463 auction registration modal

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VideoBackground.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Adds support for displaying video headers in Artsy Vanguard. Related to https://artsyproduct.atlassian.net/browse/GROW-1425
> [Vanguard] Display video in headers/intro

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
- src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
This PR updates our metadata display based on this spec: zpl.io/beKOzqP
Large breakpoint:
Medium breakpoint:
Small breakpoint:
XS breakpoint:
> PURCHASE-1285: Updates Artwork Details display

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
See screenshots here: https://github.com/artsy/reaction/pull/2668 
I forgot to push up this last change to add the `xs` breakpoint based on the spec! zpl.io/beKOzqP
> Handle xs breakpoint with metadata field

- src/Apps/Auction/routes.tsx
If provided, a `render` function in a [found][] router implementation will execute before and after a Relay response is available. To account for the early invocation, guard against the presence of `props`.
[found]: https://github.com/4Catalyzer/found
Co-authored-by: @dleve123
> Fix render implementation in AuctionApp routes

- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
- src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artist/Routes/Overview/state.ts
- src/Apps/Artist/routes.tsx
- src/Apps/__tests__/Fixtures/Artist/Components/ArtworkFilter.tsx
- src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
- src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
- src/__generated__/ArtworkFilter_Test_Query.graphql.ts
- src/__generated__/ArtworkFilter_artist.graphql.ts
- src/__generated__/Overview_artist.graphql.ts
- src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
This does some rearranging in order to consolidate the backend requests needed to load the artist page filter, down to one.
However, there is a case where we can't consolidate the requests down to one. That's the case of navigating to the artist page with a filter applied in the URL, like `?partner_id=...` (or whatever).
Taking a partner that only has sculpture works by an artist, for example, navigating to the page directly with a filter applied for that partner, would return `Sculpture` as the only available medium. However, we want to display all categories available for the artist (w/o any partner filter applied). It is for this reason that we generally want to fetch aggregations w/ no filter applied. Luckily that can be consolidated, and is the most common case (just visiting the …
> @damassi => [Artist] Consolidate aggregations and grid request for filter, when possible

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/Sections/ImageCollection.tsx
- src/Components/Publishing/Sections/SectionContainer.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/SectionContainer.test.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Related to https://artsyproduct.atlassian.net/browse/GROW-1432
Updates `Sections` and related components to accommodate a `customWidth` prop, which overrides widths based on `article.layout`.  This also updates the image sizes passed down to image sections.
> [Vanguard] SectionsList can accommodate custom widths

- src/Components/Publishing/Article.tsx
- src/Components/Publishing/Constants.ts
- src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
- src/Components/Publishing/ToolTip/TooltipsDataProvider.tsx
- src/Components/Publishing/__tests__/Constants.test.ts
Our `FullscreenProvider` was doing double duty, because it also contained logic related to fetching Tooltip data -- this PR separates the tooltip logic into its own component, `TooltipsDataProvider`. 
I ran into issues with the co-location when working on changes to slideshows in the Vanguard project, this should unblock that work.
> Extract tooltip provider from fullscreen logic

- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Components/Auction/AuctionRegistrationModal.tsx
- src/Components/Auction/ConditionsOfSaleCheckbox.tsx
- src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
This PR updates the Auction registration conditions of sale checkbox (used in both registration form and modal) to use the palette checkbox, which has more consistent performance and avoids a breaking issue on touch interfaces.
Paired with @dblandin
> Refactor ConditionsOfSaleCheckbox to use palette checkbox

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Currently, we are not expecting to render ads on the 2019 Artsy Vanguard article series.
This PR adds a boolean property we can use to render/hide display ads.
> Adds prop to hide ads from feature articles for vanguard development

- src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
- src/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Addresses: [GROW-1355](https://artsyproduct.atlassian.net/browse/GROW-1355)
Addresses the follow QA items:
- Only show the remaining items in the carousel when there is an odd number (prevents showing whitespace)
- Ensure the component tiles have a 2px radius border
- Change the border color from black-10 to black-60 on hover
> [GROW-1355]: Address OtherCollectionsRail QA items

- src/Components/Publishing/Fixtures/Articles.ts
Changed the `SuperArticle` fixture incorrectly, it does indeed use `related_articles` and not the newer `related_article_ids` (https://github.com/artsy/reaction/pull/2694/files), breaking Force tests.
> [TRIVIAL] Put back super article related_articles

- src/Components/Auction/AuctionRegistrationModal.tsx
- src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
This PR fixes the same issue that we found in https://github.com/artsy/force/pull/4411.
~🚧 WIP 🚧 : As shown in the gif below the palette modal is showing scrollbars. I'm going to hold off on this until we have a clear path forward on that. _Fixed in artsy/palette#565 so just need that to get merged into reaction and this will be unblocked_~
Once merged, that force PR will need to be updated to include this change.
In short both changes are the same. We had a modal close handler that looked like this:
```
handleClose(){
setModalVisible(false)  // state hook
setReduxModalType(null)  redux handler passed in as a prop
}
```
Because they were called next to each other, the changes were batched together.
Because they were batched together, the second change (in a parent component, force's …
> Call modal onClose only after show has been set to false

- src/Apps/Collect2/Components/Base/CollectArtworkGrid.tsx
- src/Apps/Collect2/Components/Base/CollectFilterContainer.tsx
- src/Artsy/Router/Utils/RenderStatus.tsx
Fixes zIndex of loader overlay so that it doesn't cover top nav. 
Also fixes issue on /collection/id where window would scroll to the top on pagination change and confuse focus, vs scrolling to the top of the grid where content updates. 
#trivial
> [Router] Fix zIndex #trivial

- src/Components/Checkbox.tsx
- src/Components/Input.tsx
- src/Components/Modal/Modal.tsx
- src/Components/ProgressIndicator.tsx
- src/Components/Publishing/ReadMore/ReadMoreButton.tsx
- src/Components/Publishing/ReadMore/ReadMoreWrapper.tsx
- src/Components/Spinner.tsx
- src/Components/Text.tsx
- src/Components/TextArea.tsx
- src/Components/TextLink.tsx
- src/Components/Title.tsx
- src/Components/Tooltip.tsx
Use JSDoc deprecation notices to encourage use of artsy/palette components when available.
cc/ @pepopowitz
> Mark components with clear artsy/palette equivalents as deprecated

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
- src/Artsy/Analytics/Schema/index.ts
I closed https://github.com/artsy/reaction/pull/2712 in favor of this PR that has the relocated CollectionHubsRail component. This adds the `item_number` to the analytics tracking data and renames the `onClickLink` -> `handleClick`.
> [CollectionHubs] adds item_number to analytics tracking

- src/Apps/Collect2/Routes/Collections/index.tsx
- src/Artsy/Router/Utils/RenderStatus.tsx
- src/Artsy/Router/Utils/Route.tsx
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
Adds a redirect to an error page if an error is encountered from MP. Currently we've just been throwing, which we've needed to fix for a while.
Right now, because we don't have consistent error's that we can parse from MP, I'm passing a generic 404, which I think is less alarming than a 500. 
Note that this routing stuff is still something of a moving target and will likely change in minor ways over the next few weeks. Once it's stable will update test coverage where missing.
> [Router] Add ErrorPage handler

- README.md
This commit fixes the very cool ascii banner text in the README.
Wrapping the text in explicit code blocks should prevent it from breaking again in the future. It's likely that a script ran some sort of string strip command on the contents of the README, removing all leading and trailing whitespace, causing the implicit code block, marked by indentation, to break.
h/t to @orta for reporting :+1:
Addresses #2675
---
**Before**
**After**
> Bring back the cool ascii banner text in the README

- src/Components/Auction/PostRegistrationModal.tsx
- src/Components/Auction/__stories__/AuctionRegistrationModal.story.tsx
- src/Components/Auction/__stories__/PostRegistrationModal.story.tsx
- src/Components/Auction/__tests__/PostRegistrationModal.test.tsx
Tracked in https://artsyproduct.atlassian.net/browse/AUCT-571
This PR moves the confirm registration modal from force [here](https://github.com/artsy/force/blob/329ce6874381f6e5574c11333c7b06df875c97b1/src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx) to reaction to be alongside its sibling modal, the AuctionRegistrationModal. This allows a better consolidation of styles and modal rendering/unmounting logic in a single place and also updates the modal to use the new hotness, the palette modal.
> Auction post-registration modal (migrating from force)

- src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Noticed a prod bug that we needed to fix in the new filter
> [ArtworkFilter] Ensure page is reset to 1 on filter change #trivial

- package.json
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoBackground.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoPrimarySeries.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoSubseries.tsx
- yarn.lock
Handles responsiveness and resizing issues on the Video in SVG Blobs.
[Links to GROW-1469](https://artsyproduct.atlassian.net/browse/GROW-1469)
> Add Reponsiveness to Primary and Subseries SVG Videos 

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/DisplayTargeting.tsx
- src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
This PR adds article vertical data to the targeting data sent to the 3rd party ad server.
[Link to Slack discussion for context](https://artsy.slack.com/archives/GK7Q3BZ6K/p1565272756001100)
[Links to GROW-1459](https://artsyproduct.atlassian.net/browse/GROW-1459)
> Update Targeting Data in Ad Server

- src/Components/v2/CollectionsHubsNav.tsx
- src/Components/v2/ImageLink.tsx
- src/Components/v2/__stories__/ImageLink.story.tsx
https://artsyproduct.atlassian.net/browse/GROW-1481
The hubs entrypoint nav for /collect was causing the layout to stutter as images were loaded.
Following @damassi's tip, the solution here is to use Palette's `ResponsiveImage`, which fills its containing element's available space, and takes an aspect ratio so that it can reserve a fixed-height space in the layout before the image is loaded.
---
---
And here it is with fixed height images.
> Update ImageLink to use a fixed aspect ratio and avoid jitter

- src/Components/v2/CollectionsHubsHomepageNav.tsx
- src/Components/v2/CollectionsHubsNav.tsx
- src/Components/v2/__stories__/CollectionsHubsHomepageNav.story.tsx
- src/__generated__/CollectionsHubsHomepageNavQuery.graphql.ts
- src/__generated__/CollectionsHubsHomepageNav_marketingCollections.graphql.ts
https://artsyproduct.atlassian.net/browse/GROW-1360
subtask: https://artsyproduct.atlassian.net/browse/GROW-1485
This creates the component that we will insert into the homepage, to allow direct navigation to our set of initial collection hubs.
Another Force PR will be required to stitch this into place, in the existing Jade template for the homepage.
> Create Collection Hubs entrypoint nav component for homepage

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
This PR fixes a spacing issue on FeaturedCollections. This PR conditionally displays price guidance on FeaturedCollections when it's available.
**Before**
> [CollectionHubsRails] minor UI fixes

- .env.oss
- src/__stories__/config.js
Problem
Some app, particularly the new Auction app, requires a meaningful
STRIPE_PUBISHABLE_KEY for `yarn start` to start storybooks correctly.
It's kind of hard to know this though as there's no explicit call out
of this.
Solution:
- Add entry for `STRIPE_PUBISHABLE_KEY` to .env.oss
- Add instructions on how to get this from Force
> Add STRIPE_PUBISHABLE_KEY to .env.oss

- src/Apps/Order/Routes/NewPayment/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/fixFailedPayment.ts
- src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
- src/__generated__/NewPaymentRouteSetOrderPaymentMutation.graphql.ts
- src/__generated__/StatusQuery.graphql.ts
- src/__generated__/Status_order.graphql.ts
- src/__generated__/routes_StatusQuery.graphql.ts
current failed payment flow works when a seller accepts an offer and payment doesn't go through, we send email to buyer about the failed payment and they fix their issue.
we need to make sure this works also for the case were we confirmed setupintent and later when seller accepts offer we tried to process off-session payment intent but that fails
The NewPayment page is not currently set up to handle SCA authentication, so payments requiring SCA will always fail.
I updated the NewPayment page with similar logic to what already exists in the Review page so it will display the SCA modal if authentication is required.
[PURCHASE-1428]: https://artsyproduct.atlassian.net/browse/PURCHASE-1428
> PURCHASE-1428: Get failed payment flow working with case where payment intent of a already confirmed setupintent fails when seller accepts offer

- src/Apps/Order/Components/PaymentPicker.tsx
- src/Apps/Order/Components/__mocks__/PaymentPicker.tsx
- src/Apps/Order/Routes/NewPayment/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
A new user received a generic error message when attempting to add a card on the payment page. We should be displaying the error message in the dialog, or a custom message based on the decline code.
https://artsy.slack.com/archives/CB110C6LE/p1566571791008000
https://exchange.artsy.net/admin/orders/db831680-b90c-46e2-96a2-09fe8d440025
While I was unable to reproduce the error in the same as the customer received it, I figured out that that a blank error modal displays when the error detail is null. I was able to trigger a different error where detail was null and added a new error type "internal error" for these types of errors. The  error dialog message is the default error contact message and the title is 'An internal error occurred' so we can differentiate between these errors and …
> PURCHASE-1432: Improve error messaging for generic declines on the payment page

- src/Apps/Auction/Components/RegistrationForm.tsx
Problem:
On mobile safari the registration form was asking the user to scan their
credit card for _all_ form elements and was placing the credit card
number on the first billing info line for reasons unknown to human kind.
Solution:
Rename "Credit card number*" to "Credit card". This is more consistent
with our BN/MO flows as well.
Jira: https://artsyproduct.atlassian.net/browse/AUCT-596
> Rename "Credit card number*" to "Credit card" to fix scan cc on mobile

- src/Components/v2/CollectionsHubsHomepageNav.tsx
I realize that this is only temporary data until we get real data, but until then, we're getting hydration mismatch errors in the console, when the server returns a different random subtitle than the client.
This approach chooses a subtitle based on the item index, instead of randomly.
> De-randomize subtitles in homepage hubs nav to eliminate hydration mismatches

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Addresses: [GROW-1488](https://artsyproduct.atlassian.net/browse/GROW-1488)
Addressing the following:
- Ensures the carousel arrows are the same size.
- Long titles line-break on smaller screens (we also truncate more of the description).
> Ensure carousel arrows are the same size and long titles line-break

- src/Apps/Auction/Routes/__stories__/Register.story.tsx
- src/Apps/Auction/__tests__/redirects.test.ts
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/routes.tsx
Prepares us for a Force change that'll look for the Reaction component
on /auction-registration
Co-authored-by: Daniel Levenson <dleve123@gmail.com>
> Host new registration form on `/auction-registration`

- src/Apps/Auction/Routes/Register/index.tsx
Matches the 100px bottom margin configured for the current registration form: https://github.com/artsy/force/blob/f5a63c987af9b10b3644400bd91c08919f5282a0/src/desktop/apps/auction_support/stylesheets/index.styl#L19
**Before**
> ![screenshot 1567624006](https://user-images.githubusercontent.com/123595/64283542-a88c0900-cf25-11e9-94f7-d073d75e0b43.png)
---
**After**
> ![screenshot 1567623986](https://user-images.githubusercontent.com/123595/64283555-ae81ea00-cf25-11e9-8238-ba87c00becfb.png)
> Add bottom margin to viewports > XS on bidder registration form

- src/Components/v2/RecentlyViewed.tsx
Fixes https://artsyproduct.atlassian.net/browse/GROW-1496
This fixes the white screen of death some users were [experiencing](https://cl.ly/10c5211b1b55) after they had viewed certain pathological artworks that were missing images altogether. (Missing whyyyy 😱  — follow-up ticket at https://artsyproduct.atlassian.net/browse/GALL-2132)
When those artworks were subsequently displayed in the Recently Viewed rail, scrolling down to that rail would trigger a lazy load, which in turn would result in trying to reference an `aspect_ratio` on a null image.
The solution is simply to use the well-established Force convention for safe access of nested properties, so that `aspect_ratio` will have a fallback value of `1` in the pathological case.
> Defensively access images' aspect ratio in Recently Viewed rail

- src/Components/v2/Lightbox/Lightbox.tsx
- We had been returning `null` if an image had zoom disabled, which would remove the image from the render. This PR allows for images to be returned that are not zoomable.
> Allow images without zoom

- src/Artsy/Router/Utils/__tests__/queryStringParsing.test.ts
- src/Artsy/Router/Utils/queryStringParsing.ts
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
Kind of a weird one, lmk what you think!
This is a client-side update for https://github.com/artsy/metaphysics/pull/1939.
Basically, sending a string of "true" or "2" used to work, for boolean and integer inputs in GraphQL, respectively.
Generally this isn't an issue when sending variables (we have type checking, use POSTs). However, we sometimes parse incoming URLs (like someone linking a friend to a filter URL of the form: `/?acquireable=true&page=4`).
There, the query string parsing produces `{"acquireable": "true", "page": "4"}`, and we send that directly to Metaphysics. This modifies the parsing middleware to make sure incoming URLs are parsed. I can't immediately think of a downside to this (although I'm sure there is one!).
> @damassi => [QueryString] When parsing query strings for apps, coerce Ints and Bools

- data/schema.graphql
- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/__generated__/ReviewSubmitOfferOrderMutation.graphql.ts
[PURCHASE-1470]
Reaction should pass confirmedSetupIntentId so that the same confirmed setup intent is used when the order is submitted a second time
[PURCHASE-1470]: https://artsyproduct.atlassian.net/browse/PURCHASE-1470
> PURCHASE-1470: Reuse SetupIntent for make offer

- src/Apps/Collect2/Components/Collection/Header/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
Addresses: [GROW-1499 ](https://artsyproduct.atlassian.net/browse/GROW-1499) & [GROW-1500](https://artsyproduct.atlassian.net/browse/GROW-1500)
- This PR adds space in between the header and breadcrumb in mobile.
- Line breaks long titles.
**BREADCRUMB**
**WRAPPED TITLE**
> Collection hub title

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
As a part of Vanguard 2019 QA fixes, this PR prevents article content from expanding beyond container width so that side frame text does not cover it. 
[Links to GROW-1514](https://artsyproduct.atlassian.net/browse/GROW-1514)
g Screen Shot 2019-09-11 at 3.13.18 PM.png…]()
> Prevent Side Frame from overlapping with Article Content

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
[Links to GROW-1516](https://artsyproduct.atlassian.net/browse/GROW-1516)
> replace up/down arrows with underline on read more button

- data/schema.graphql
- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
- src/Apps/__tests__/Fixtures/Order.ts
- src/__generated__/ReviewSubmitOfferOrderMutation.graphql.ts
- src/__generated__/ShippingTestQuery.graphql.ts
- src/__generated__/Shipping_order.graphql.ts
- src/__generated__/routes_ShippingQuery.graphql.ts
If I'm buying a work that can only be shipped domestically, when I enter my shipping information, the shipping form has the artwork's origin country selected, and I cannot select any other country.
Previously, this only happened for US works and the copy said "continental US" instead of "domestic".
> PURCHASE-1476: If work can only ship domestically, the shipping form only displays the artwork's origin country

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Address [Grow 1498](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1498)
To fix the broken scrolling in small size. This PR is going to remove the condition check on "draggable". Then it going to use its default value, which is true.
The condition check should be work, but it doesn't. There will be another ticket to investigate.
> Grow 1498 fix the broken scrolling in small size

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
Addresses: [GROW-1501](https://artsyproduct.atlassian.net/browse/GROW-1501)
[`max-context`](https://caniuse.com/#search=max-content) is not supported in internet explorer so to prevent word-wrapping we use `white-space: nowrap`.
> [GROW-1501]: fixes word wrapping in ie

- src/Apps/Order/Routes/Review/index.tsx
- src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
- src/Apps/Order/Routes/__tests__/Review.test.tsx
This is a follow up on https://github.com/artsy/exchange/pull/508 where we introduced new `payment_method_confirmation_failed` processing error which is the case where payment method confirmation fails on Stripe end and show proper new message.
more discussions about copy: https://artsy.slack.com/archives/C9YNS4X32/p1568669811033800
> Handle case for payment_method_confirmation_failed

- package.json
- scripts/quicklink-to-project.sh
The publishing mechanism for `yalc` was tied directly into `yarn watch` for simplicity when designing that workflow. That said, `yarn link` or just local development in reaction is slowed down by having that publishing step backed into `yarn watch`, so this pulls them apart. 
Thanks @damassi for the recommendation!
> Don't tie `yalc` publishing to `yarn watch`

- src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/__stories__/CollectionsHubRails.story.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Collect2/Routes/Collections/Components/CollectionsGrid.tsx
An experiment related to https://artsyproduct.atlassian.net/browse/PLATFORM-1780
Turned on strict null checking for typescript, and converted the `Apps/Collect2` directory to pass all checks. I've disabled strict null checking for the moment so there is a chance these changes could be accidentally removed. 
Next steps: 
- implement a strategy to turn on type-checking selectively by path.
- Develop list of apps that have greatest need for checking so we can prioritize these changes.
> Collect2 app passes strict null checks

- src/Components/v2/CollectionsHubsHomepageNav.tsx
- src/Components/v2/CollectionsHubsNav.tsx
This PR updates the images for the fake hubs tiles to something less jarring, and hopefully less likely to prompt inquiries into whether the rail is broken.
The tiles look like this: 
It's still all temporary/fake data...until we can figure out how to get genes fully automated for the 6 hubs.
> Update fake hubs data with more accurate fake images

- src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
This PR attempts to address the flickering effect when navigating between various collection hubs (the header switches on initial page load). 
[Links to GROW-1506](https://artsyproduct.atlassian.net/browse/GROW-1506)
> Handle collections header flicker

- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
The PR is related to https://github.com/artsy/reaction/pull/2838. After this was merge I was still seeing the delay on staging. I thought it might be because the key needs to be unique. I made the minor adjustment.
> [GROW-1506] use unique key

- src/Apps/Order/Routes/NewPayment/index.tsx
- src/Apps/Order/Routes/Payment/index.tsx
- src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
- src/Apps/Order/Routes/__tests__/Payment.test.tsx
[PURCHASE-1091]
Desired Behavior:
Heading: Your card was declined
Body: Please enter another payment method or contact your bank for more information.
CTA: Continue
__Before:__
__After:__
[PURCHASE-1091]: https://artsyproduct.atlassian.net/browse/PURCHASE-1091
> PURCHASE-1091: Buyer receives a more friendly, informative error when their card is declined in checkout

- src/Artsy/Relay/createRelaySSREnvironment.ts
- src/Artsy/Relay/middleware/metaphysicsErrorHandlerMiddleware.ts
- src/Artsy/Relay/middleware/principalFieldErrorHandlerMiddleware.ts
- src/Artsy/Relay/middleware/searchBarImmediateResolveMiddleware.ts
- src/Artsy/Router/Utils/Route.tsx
aka unleash partial renders.
Doing some testing of this locally, and it seems to do what we want!
I ran Reaction linked with Force, pointing to local Metaphysics.
I then went into the resolvers for some of the leafs used in the artwork page, and intentionally threw errors there (to mimic an upstream service/fetch failing).
Intentionally threw an error when fetching some of the grids in 'Other Works', threw an error when fetching sale data and threw an error when fetching Vortex price histogram data.
In all cases without this change, a 500 was served. With this change, the page rendered with a 200, and at least in these specific examples, there didn't seem to be any negative affect on UI/layout.
Some info was just missing, an entire artwork grid in 'Other Works' was gone, but the page …
> @eessex => [Error Handling] Only serve non 2XX pages on principalField errors

- package.json
- scripts/codemod.sh
This is a really small change just to make running codemods easier in reaction. 
I'll likely pull this out into `artsy/cli` later, but for the MPv2 efforts it'll be a time saver. 
Just run it like this:
```
yarn codemod <codemod-file-name>
```
> Add codemod command to simplify running codemods in reaction

- src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
- src/Apps/Artwork/Components/__tests__/OtherWorks.test.tsx
Fixes https://sentry.io/organizations/artsynet/issues/1244747616/?project=159064&query=is%3Aunresolved&statsPeriod=14d
Checking out the [resolver for the `layer` field](https://github.com/artsy/metaphysics/blob/9ace7f1313817939f6128c4388c3072e4b306eb4/src/schema/v1/artwork/index.ts#L486), and we see that it can certainly error or not return a layer, and thus be `null`. Nested destructuring is thus a problem, so we should switch to the safer `get`.
> @joeyAghion => [RelatedArtworks] Be defensive about missing layer

- src/Apps/Artist/Routes/Overview/index.tsx
Testing locally, and this works the way we want! 😅 
Previously, the fetch would happen server-side. The data would fill-in client-side, with a spinner (which isn't needed since the data is already there). Hitting the page w/ JS disabled and you would see a spinner.
Now, when curl'ing or viewing the page w/ JS disabled there is no spinner (the component isn't rendered at all), and the fetch doesn't happen. When the client loads, the request is kicked off and the component loads (spinner, and then rail).
This...should help our response time and error rate!
> @damassi => [Artist] Defer collection rail to client

- src/Apps/Collect2/Routes/Collection/index.tsx
Re-adds missing price sort to `/collection/id`. (Based on old code [here](https://github.com/artsy/reaction/blob/ea30e243d868ab47fd09179a225ce0f498e53ff2/src/Apps/Collect2/Components/Filters/SortFilterSortTypes.tsx#L6-L23).)
> [Collection/Id] Re-add missing price sort

- src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
- src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
- src/Apps/__tests__/Fixtures/Collections.ts
- src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
- src/__generated__/ArtistCollectionEntity_collection.graphql.ts
- src/__generated__/ArtistCollectionsRailQuery.graphql.ts
- src/__generated__/ArtistSeriesEntity_member.graphql.ts
- src/__generated__/CollectionRefetch2Query.graphql.ts
- src/__generated__/CollectionsHubRailsStoryQuery.graphql.ts
- src/__generated__/RelatedCollectionEntity_collection.graphql.ts
Addresses https://artsyproduct.atlassian.net/browse/GROW-1533
Addresses  https://artsyproduct.atlassian.net/browse/GROW-1541
The `ArtistCollectionsRail` that  appears on the artist page — the one that shows a few triplets of thumbnails  — was breaking in two ways:
- erroring as it tried to display (non-existent) thumbnails for deleted works (GROW-1533)
- showing incorrect thumbnails unrelated to the given artist (GROW-1541)
There are currently two ways of accessing a collection's artworks via MP:
1. `marketingCollection.artworks.hits`
2. `marketingCollection.artworks.artworks_collection`
My investigation showed that method 1 was broken and ignoring input parameters in a way that explained both 1533 and 1541.
This turned out to be due to underlying bug in Gravity that @mzikherman diagnosed …
> Fix ArtistCollectionsRail's fetching of collections' artworks

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
- src/Components/v2/Carousel.tsx
Addresses: [GROW-1547](https://artsyproduct.atlassian.net/browse/GROW-1547)
This PR ensures that the collection rails increment by one at smaller breakpoints.
> [GROW-1547] increment correctly at smaller breakpoints

- src/Components/NavBar/Menus/NotificationsMenu.tsx
- src/Components/NavBar/NotificationsBadge.tsx
cc @alloy 
Closes https://artsyproduct.atlassian.net/browse/PLATFORM-1831
We were seeing up to 3 server side queries happening on the artist page, with 2 in parallel, and 1 happening after the first 2.
The first 2 are intentionally separated: querying for 'top level' content above the tabs, and then a query for the tab's contents. (As we roll out client side routing everywhere, we might revisit this design decision).
The last one, is for the notifications dropdown, and only appears when logged in. This might also be pretty slow, plus we use a cookie to immediately render the badge, so should definitely be deferred.
This affects any pages using the new NAV/shell (not just artist).
> @damassi => [Nav] Move notifications dropdown fetching to client

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Addresses: [GROW-1574](https://artsyproduct.atlassian.net/browse/GROW-1574) & [GROW-1575](https://artsyproduct.atlassian.net/browse/GROW-1575)
- Fixes OtherCollectionsEntity when there is a missing thumbnail image (ensure a fixed height)
- Truncate long titles for ArtistSeriesEntity component
> Collection hubs QA

- src/Apps/Order/Components/PaymentPicker.tsx
In order to properly test the payment flow with cypress, we need to be able to hook into these elements on the payment page.
Cypress recommends [`data-test`](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements) as the selector to use for this purpose.
> Add hooks for cypress in the PaymentPicker

- src/Apps/Order/Routes/__tests__/Accept.test.tsx
- src/Apps/Order/Routes/__tests__/Counter.test.tsx
- src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
- src/Apps/Order/Routes/__tests__/Reject.test.tsx
- src/Apps/Order/Routes/__tests__/Respond.test.tsx
- src/Components/WithCurrentTime.tsx
- src/Components/v2/__tests__/CountdownTimer.test.tsx
- src/Components/v2/__tests__/Timer.test.tsx
- src/Utils/__tests__/time.test.ts
- src/Utils/time.ts
- src/__generated__/timeQuery.graphql.ts
- src/setup_jest.ts
This replaces our use of `metaphysics` with `fetchQuery`, from `relay-runtime`. It piggybacks on our network layer.
> [Refactor] Update Utils/time to use `fetchQuery`

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artist/Components/ArtistMeta.tsx
- src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
- src/Components/v2/Seo/Person.tsx
- src/__generated__/ArtistApp_artist.graphql.ts
- src/__generated__/ArtistMeta_artist.graphql.ts
- src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
cc @joeyAghion 
This ports over the [current meta](https://github.com/artsy/force/blob/1e76040170d882695a2f73bd4578e3b07f6cc634/src/desktop/apps/artist/components/Meta.js) component from Force into Reaction, using `react-head` and adding a fragment into the overall SSR query.
This Reaction update goes in hand with a Force update that removes this fetch and component from Force.
> @damassi => [Artist] Port meta tags and structured data from Force

- src/Utils/fillwidth.ts
Addresses https://sentry.io/organizations/artsynet/issues/912351641/
Fillwidth components were failing on artworks without images, because calculations of size expected `image.aspect_ratio`. 
This change ensures we reach the more descriptive error logging in the `FillwidthItem` component:
> Fillwidth doesn't fail when image is absent

- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Addresses: [GROW-1587](https://artsyproduct.atlassian.net/browse/GROW-1587)
At smaller breakpoints the content below the header didn't respond to image resizing. This PR adds a style rule to address that.
**Before:**
**After:**
> [GROW-1587] Ensure content below collection header image respond to image resize at small breakpoint

- src/Apps/Order/Components/AddressForm.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
If we're rendering a billing form, prompt for "Name on card" otherwise prompt for "Full name".
> Swap name prompt in address form based on billing prop

- src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
- src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
- src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
- src/Apps/__tests__/Fixtures/Collections.ts
- src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
- src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
- src/Utils/resizer.ts
- src/__generated__/ArtistCollectionEntity_collection.graphql.ts
- src/__generated__/ArtistCollectionsRailQuery.graphql.ts
- src/__generated__/CollectionRefetch2Query.graphql.ts
- src/__generated__/RelatedCollectionEntity_collection.graphql.ts
Address: [Grow-1482](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1482)
This PR is going to do 3 things. You can see below.
1. For the header image, the resized will transfers the format from PNG to JPG on the collection page. You can see the image below, see the size is much smaller.
2. For the images in the collection rail and related collection rail, it will get a secure URL when it does the query.
3. Based on the Zeplin, [Zeplin Collection Page](https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5cd1af05e05b3067d84963cd), [Zeplin Artist Page](https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5c7403e192623b407fcec158),
In order to fit the requirement in the Zeplin, this PR changes the size a …
> Grow-1482 collection rail images are insecure and oversized

- package.json
- src/Components/Publishing/Sections/Text.tsx
- yarn.lock
See CI results of https://github.com/artsy/force/pull/4668
Revert "Merge pull request #2897 from artsy/use-react-html-parser-fork-without-htmlparser2-dependency"
This reverts commit 0aed477fc42ca696cad6d2af2afef0e76a6cda38, reversing
changes made to 769c6be0060794379723f23d2863f07b3155f845.
> Revert dropping htmlparser2 for now due to difficulty running Force test suite

- package.json
- src/Components/Publishing/Constants.ts
- src/Components/Publishing/Sections/Text.tsx
- yarn.lock
Alright, re-applying https://github.com/artsy/reaction/pull/2897 and adding an additional change to drop usage of cheerio, which depends on parse5, in favour of DOMParser.
> Drop htmlparser2 and parse5 deps from runtime deps

- src/Components/Publishing/index.tsx
We were exporting test fixtures through modules that are used in client bundles.
> [Publishing] Do not include test fixtures in main exports and bundles

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
Addresses: [GROW-1580](https://artsyproduct.atlassian.net/browse/GROW-1580)
Because we were previously truncating by character count in some cases the description would lead to different container sizes. This PR refactors to use the truncation to be based on line count which eliminates this UI issue.
**Before:**
**After:**
> [GROW-1580] truncate featured collection description by line count vs characters

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Addresses: [GROW-1587](https://artsyproduct.atlassian.net/browse/GROW-1587) (also sneaking [GROW-1583](https://artsyproduct.atlassian.net/browse/GROW-1583) in here)
After [fixing the default header](https://github.com/artsy/reaction/pull/2892) I saw the custom header image had the wrong image height which causes the collection title to lay over top of the image. This PR fixes the custom header image per the [spec](https://app.zeplin.io/project/5aabc5e0786bbb29b6e3dc7f/screen/5cd98bcd27264913e9451971). 
This PR also formats the price guidance for featured collections rail with a comma (i.e. $1,600).
**Before:**
**After:**
**Formatted price guidance:**
> [GROW-1587] ensure custom collection header image height is correct at small breakpoint

- src/Apps/Collect2/Routes/Collections/Components/CollectionsGrid.tsx
Because of the positioning of the navigation bar, when a user clicks on a breadcrumb to nav back to the collections index, the top of the collection title appears to be pushed down the page.
This PR adds an offset to push the collections title below the nav bar.
[Links to GROW-1505](https://artsyproduct.atlassian.net/browse/GROW-1505)
The Fix:
The Problem:
> Collections breadcrumb navigation bug fix

- package.json
- src/Components/Publishing/Constants.ts
- src/Polyfills/DOMParser.ts
- yarn.lock
This so clients don’t need HTML parser deps, which the browser already provides, but for some components we obviously need to render on both server and client.
> Add DOMParser polyfill for the server

- src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
This reverts the change to our ToolTip rendering code so that the article pages can SSR render. 
See [this thread](https://artsy.slack.com/archives/CC56D129X/p1571058681060700) for more info.
> [Publishing] Revert SystemQueryRenderer change

- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Uncovered while adding integration tests, we should use an `h1` for page title.
> Use h1 element for page title

- src/Components/v2/Carousel.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-1591.
This PR removes the snapping effect from all instances of `<SmallCarousel>`, which is effectively all carousels in Reaction at the "xs" breakpoint.
In iOS 13, the snapping action made it really difficult to swipe through the carousel (see below video). [This is a known issue in the flickity library](https://github.com/metafizzy/flickity/issues/959). We're going to add a follow-up ticket to try to address it, but for now we're removing the snapping effect to move forward with a launch of collection hubs.
---
---
---
> Remove snapping effect from mobile carousels because it causes weirdness in iOS 13.

- src/Apps/Artist/Routes/Shows/__tests__/Shows.test.tsx
- src/__generated__/Shows_Test_Query.graphql.ts
Is this the kind of change that makes it easier to perform code mods on as we begin the V2 update?
If so, I think the rest of the updates to tests should be reasonable (there were 22 separate tests affected).
Is there a need to change this for storybooks? There's a solid number of storybooks still using `RelayStubProvider`.
> @damassi => [Test] Convert artist shows to use renderRelayTree

- .vscode/settings.json
- src/Apps/Auction/__fixtures__/routes_BidQuery.ts
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/getRedirect.ts
- src/Apps/Auction/routes.tsx
- src/__generated__/routes_BidQuery.graphql.ts
[Jira Ticket](https://artsyproduct.atlassian.net/browse/AUCT-655) 🔐
This PR sets up some basic redirects with tests for the new confirm bid route. It also reorganizes some of our redirect handling code.
@damassi suggested that we should consider doing redirects in the route components themselves rather than a separate `render` prop on our route config. I'm not sure the best way to organize some of the shared types in this case, but open to it.
> Define redirects on Confirm Bid route

- src/Apps/Artist/Routes/Overview/__tests__/Index.fixture.tsx
- src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.test.tsx
- src/Components/v2/ArtistBio.tsx
- src/Components/v2/__tests__/ArtistBio.test.tsx
- Show Artist's full bio and related categories by removing "Read More": https://artsyproduct.atlassian.net/browse/PURCHASE-1569
- Update consignment links to mention consign instead of learn more: 
https://artsyproduct.atlassian.net/browse/PURCHASE-1579
cc: @samchieng
> SEO Improvements to the Artist page

- src/Apps/Order/Utils/commitMutation.tsx
Part of https://artsyproduct.atlassian.net/browse/PLATFORM-1890
As this leads to graphql-js being included in Force's client bundles.
> [Order] Don't refer to graphql-js at runtime.

- src/Artsy/Relay/createRelaySSREnvironment.ts
- src/Artsy/Router/buildClientApp.tsx
- src/Artsy/Router/buildServerApp.tsx
Fixes [PURCHASE-1140](https://artsyproduct.atlassian.net/browse/PURCHASE-1140).
It was reported that many of our orders were being created with a user agent of something like `Reaction/16.7.0; Metaphysics`. This user agent is first set in reaction (see below) then appended to in metaphysics. 
https://github.com/artsy/reaction/blob/501d18091180abed728680661456b57f82ad27a8/src/Artsy/Relay/createRelaySSREnvironment.ts#L34
Essentially we just needed to prepend what's in reaction with the UA from the request (or the window if it's on the client).
> Don't overwrite the User-Agent header for relay operations

- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/__stories__/Collect.story.tsx
(Pair sesh with @mbilokonsky)
This fixes an issue where the CollectionHubs nav component wasn't properly SSR rendering due to a configuration issue around A/B tests in force.
Comments inline.
> [Collection] Pass COLLECT_HUBS a/b test to context

- src/Components/v2/Carousel.tsx
- iOS introduced an issue with how Flickity is handling touch events
- Uses this fix: https://github.com/metafizzy/flickity/issues/740#issuecomment-485562201
> Fixes carousel for iOS 13

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Components/PricingTransparency.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
- src/Apps/Auction/Routes/__stories__/Register.story.tsx
- src/Apps/Auction/__fixtures__/routes_BidQuery.ts
- src/Apps/Auction/__tests__/routes.test.ts
This PR sets up a skeleton component with hard-coded values for pricing transparency. It has an accompanying view in storybook and can be triggered by adding `pt=1` to the query string (once the view is mounted in force).
It also includes some #minor cleanup.
> Auct 465 pricing stub

- src/Utils/Hooks/useWindowSize.ts
The useLayoutEffect hook can only be used client-side, so this PR adds a check so the hook isn't called until a window object is present.
> Add a check for window obj before useLayoutEffect hook

- package.json
- src/Components/v2/Carousel.tsx
- yarn.lock
https://staging.artsy.net/artist/simon-linke/cv is currently broken:
This PR adds the typings for Flickity, but that surfaced another few places where, according to the types at least, we’re incorrectly using the API. Either the typings are incorrect and should be updated or we actually have other issues.
Further work that should be done is to use the Flickity typings in other places where Flickity API/Options are referenced.
@kierangillen Can you take this to completion?
> [Carousel] Fix incorrect invocation of `Flickity.prototype.destroy()`

- src/Utils/Hooks/useWindowSize.ts
This should resolve the "Cannot read property 'width' of null" errors currently in staging, which were a result of returning `null` on the server in #2919.
> Return default object on server from useWindowSize, instead of null

- src/Components/v2/Carousel.tsx
Fixes `window is not defined` issue when SSR'ing in Force, which reverts [this line from #2927](https://github.com/artsy/reaction/pull/2927/files#diff-46847d5408e9ceb7bf8d5b5f1c59f0b5L208)
#trivial
> [Carousel] Ensure we only import flickity on client

- src/Artsy/Analytics/Schema/Values.ts
- src/Components/v2/CollectionsHubsHomepageNav.tsx
- src/Components/v2/CollectionsHubsNav.tsx
- src/Components/v2/ImageLink.tsx
Address: [Grow-1577](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1577).
This PR : 
1. Adding the `onClick` property to `imagelink`, then the clicking action becomes trackable.
2. For the `CollectionsHubsHomepageNav`. Adding the `track()` as the higher(higher than the relay) order component. Because `useTracking ` still need to wrap the component with decorator or hoc, this is the FC, so here I used hoc.
3. For the `CollectionHubsNav`. He has a parent component(which is `CollectApp`, it already wrapped up with `track()` ), so, I just added `useTracking` in `CollectionHubsNav`.
4. I found out these two nav components do not have test suites.
> Grow-1677 Analytics tracking for hub entry points

- src/Apps/Collect2/Routes/Collection/index.tsx
During a QA session we mentioned removing the bottom RelatedCollectionsRail from Collection Hubs and only showing them on regular collection pages. This PR does that.
**Collection Hubs Page**
**Regular Collections Page**
> [Collection Hubs] only display Related Collections Rail on non-hubs collections

- src/Components/Authentication/__tests__/helpers.test.ts
- src/Components/Authentication/helpers.ts
There was a place where we were expecting an object to exist but it didn't. I've added a guardrail check and a unit test to cover this edge case, I think we should be good now?
Diff Analysis: 
```
{
"total_files_changed": 2,
"test_files_changed": 1,
"by_type": {
"ts": 2
}
}
```
> this hopefully fixes the broken login flow on mobile

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/getRedirect.ts
- src/Apps/Auction/routes.tsx
- src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
- src/__generated__/ConfirmBidValidTestQuery.graphql.ts
- src/__generated__/routes_ConfirmBidQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/AUCT-645
paired with @erikdstock 
**Acceptance Criteria**
- ensure that the confirm bid page is moved to reaction
- current page: https://github.com/artsy/force/blob/3e8e7cc0b0a12a3fd39df59e5e4609b744ecd188/src/mobile/apps/feature/templates
- A developer is able to place a bid in Reaction’s storybooks
- Reaction app has tests
> Submit bid via new ConfirmBid page

- src/Apps/Auction/Routes/__tests__/Register.test.tsx
- src/Apps/Order/Components/AddressForm.tsx
Problem:
It was discovered that users weren't able to enter country codes or
white-space when providing a phone number when registering for an
auction. Moreover, due to the way that HTML5 validations work, users were
getting generic "Please match the requested format" messages, which is a
confusing UX.
Solution:
* Change the `pattern` attribute for the phone `Input` so that only
letters are not allowed in client side validations.
+ This is in-sufficient to ensure that all phone numbers are
deliverable, but notably there are multiple ways to specify a phone
number on Artsy, including the settings page on www.artsy.net, so
additional constraints should likely be implemented at the API layer.
* Set the input type to `tel` to make the DOM as semantic and HTML5 nice
* Add a placeholder that …
> Loosen rules on phone numbers in AddressForm for international numbers.

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/GROW-1616
Per @abhitip, we want to remove the pageview tracking of hubs modules for now.
> Remove pageview tracking from hubs modules

- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/__fixtures__/routes_RegisterQuery.ts
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
- src/Components/v2/__tests__/ArtistBio.test.tsx
- src/Utils/typeSupport.ts
This PR makes it easier to define fixtures in the Auction app by simplifying our ConfirmBid mock query resolver code to use deep merge. In order to do that we brought in a mapped type from the [`ts-essentials`](https://github.com/krzkaczor/ts-essentials/commit/9536fd57a0c89ba358a16dd657054cf7960bdb59#diff-f0110f871bbb78393553f89381b8a4fdR9) package (we did not add it to node_modules because of its educational value).
Extra context: This allows us to define `{me: null}` when calling the fixture factory function rather than saying `fixture.me = null` (see https://github.com/artsy/reaction/commit/a438ffbe6fa8e462ef341f6bcc518248e27e047d) after creation, which in turn allows us to _not_ make the fixture a special `DeepWriteable` type to avoid `readonly` errors. It also drastically simplifies …
> Create typeSupport & simplify relay fixture creation

- src/Apps/Artist/Components/ArtistMeta.tsx
Fix a minor error discovered in force acceptance tests where `makesOffer` could  be null if no artworks are contained in the payload. 
https://circleci.com/gh/artsy/force/33987
> Ensure makesOffer isn't null before getting length

- src/Apps/Artist/Components/ArtistMeta.tsx
cc @sepans @joeyAghion
We're seeing an increased rate of errors in production because not all of the `listPrice` ranges have a min or max value? Not sure why that would happen, but this guard should put a band-aid on the issue until we can dig deeper.
> Be defensive about list price accessors

- src/Apps/Auction/Components/__stories__/PricingTransparency.story.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
This PR creates a rudimentary story for the pricing transparency component stub and removes the query parameter that can trigger it so that it won't accidentally be visible (in theory) in force's `bid2` route.
> remove pricing transparency query param, make a story for it

- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Components/v2/CollectionsHubsNav.tsx
This PR moves the 'Experiment Viewed' event to the base Collect component to ensure we fire it for _both_ the control and the experiment  group.
For more context see: https://artsy.slack.com/archives/C9SATFLUU/p1572022915428900?thread_ts=1571949171.406700&cid=C9SATFLUU
> [Collection Hubs Entry Points] Moves Experiment Viewed to collect app

- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1916
Renames the top nav-bar text from `Magazine` to `Editorial`.
> [NavBar] Rename `Magazine` to `Editorial`

- src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
Addresses https://sentry.io/organizations/artsynet/issues/1239198076/?project=28316
Stops using `!` for null checks.
> Collection SeoProducts description 

- src/Apps/Auction/Routes/ConfirmBid/index.tsx
Problem
* Title was previously "Auction Registration"
Solution
* Name the page "Confirm Bid | Artsy"
+ consistent with naming convection of other pages
+ there isn't a title for the Force-backed page
-  [example page][0] (must be registered for sale to see the page render)
Related Jira: https://artsyproduct.atlassian.net/browse/AUCT-667
[0]: https://staging.artsy.net/auction/shared-live-mocktion/bid/john-l-doyle-clown?bid=190000
> Fix title of Confirm Bid route

- src/Components/v2/CollectionsHubsHomepageNav.tsx
Address : [1577](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1577)
Previous PR: https://github.com/artsy/reaction/pull/2922
On staging, tracking does not work.
Based on the previous PR, I added `dispatch: data => Events.postEvent(data)`.
Since @xtina-starr is working on the AB test for the Collection Hub on the Collect App.
Some requirements (it needs to track entry point on the homepage and the collect page) from the ticket will be ignored temporally. 
In this PR, I only changed the CollectionHubEntry point on the homepage.
> QA for Grow 1577 Analytics tracking for hub entry points 

- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBar/__tests__/NavBarTracking.test.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Footer.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Nav/Nav.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
Follow up to https://github.com/artsy/reaction/pull/2955
- Replaces "Magazine" in mobile nav with "Editorial"
- Removes instances of "magazine" in repo
- Remove errant console.log
> Remove Magazine from mobile nav

- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
- src/Artsy/Analytics/Schema/AuctionInfo.ts
- src/Artsy/Analytics/Schema/CriteoInfo.ts
- src/Artsy/Analytics/Schema/Interaction.ts
- src/Artsy/Analytics/Schema/index.ts
See commits:
- 07af125
```
* Create a ProductInfo interface in analytics schema
+ I have no idea if this is the right place to place this type, but
wanted to start somewhere.
* Add tests for product info for bid success case
* Still need to get this working for submission failed
Jira: https://artsyproduct.atlassian.net/browse/AUCT-667
```
- 3f12b2b
```
Why?
* This allows us to use the type schema, better protecting ourselves
incorrect tracking code.
* It also allows better factor common tracking components by replacing
dependency injection with composition with common properties defined
at the component level.
Details
- add common tracking properties to HOC call and delete commonProperties
- Remove incorrect assertion about `order_id` in failing case
- Extend analytics schema with Criteo …
```
> WIP: Add retargetting tracking to confirm bid

- .storybook/webpack.config.js
- src/Apps/Collect2/Routes/Collect/index.tsx
- typings/sharify.d.ts
Addresses: [GROW-1639](https://artsyproduct.atlassian.net/browse/GROW-1639)
This removes a/b test logic for the collection hubs entry points on the collect page and rolls the entry points out to 100%. Related to https://github.com/artsy/force/pull/4779.
> [GROW-1639] close collection hubs entry points a/b test on the collect page

- src/Apps/Order/Components/ArtworkSummaryItem.tsx
to prevent integrity tests failing because of slow staging gemini
Fixes [PURCHASE-1620](https://artsyproduct.atlassian.net/browse/PURCHASE-1620)
without image URL:
> Safe access to artwork image in `ArtworkSummaryItem`

- src/__stories__/storiesOf.js
Comment out analytics tracking in publishing storybooks for now, which breaks entire storybook tree.
> Re-enable storybooks

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/BidderPositionQuery.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/routes.tsx
- src/DevTools/createTestEnv.tsx
- src/__generated__/BidForm_me.graphql.ts
- src/__generated__/BidForm_saleArtwork.graphql.ts
- src/__generated__/BidderPositionQuery.graphql.ts
- src/__generated__/ConfirmBidValidTestQuery.graphql.ts
- src/__generated__/routes_ConfirmBidQuery.graphql.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-712
**Do not squash the commits as each commit has a meaningful message.** 
Adds polling logic that checks the bidding status and redirects the user to the artwork page when the user is winning.
> User should be redirected to artwork page after confirmation that a bid is winning

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
I was taking a look at the remaining blocker for V2 (basically BNMO mutations not working), and while this is a blind change 🙈 , I bet it's the correct one!
We want to pass our Mongo id for an edition set (aka `internalID`) into the mutation, and not the opaque Relay `id`.
> @sweir27 => [v2] Use correct id for edition set in BNMO mutations

- src/Apps/Artist/routes.tsx
- src/Apps/Collect2/Utils/urlBuilder.ts
- src/Apps/Collect2/collectRoutes.tsx
- src/Apps/Search/routes.tsx
- src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
- src/Components/v2/ArtworkFilter/Utils/__tests__/urlBuilder.test.tsx
- src/Components/v2/ArtworkFilter/Utils/urlBuilder.tsx
- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
As discussed.
This updates URL's based on filter interactions to be **snake-cased** (`?inquireable_only=true`, vs. `?inquireableOnly=true`). This matches the format of URL's we've already been generating.
Additionally, this continues to support that format of URL's, by converting them to camel case before passing in to filter queries.
> @joeyAghion => [v2] Strictly support and generate snake case filter params in URLs

- src/Apps/Collect2/Routes/Collect/Components/CollectMediumMetadata.ts
- src/Apps/Collect2/Routes/Collect/index.tsx
Reported by @sweir27 during QA.
Also noticed the key for `/collect/sculpture` was incorrect, so that page showed the default title title as well.
> @eessex => [v2] Correct title for medium-based collect pages

- src/Artsy/Router/buildServerApp.tsx
This should (hopefully) fix [PURCHASE-1140](https://artsyproduct.atlassian.net/browse/PURCHASE-1140).
This was originally introduced in https://github.com/artsy/reaction/pull/2923 and accidentally reverted in https://github.com/artsy/reaction/pull/2935. 
For context, this is required so that the original user agent is passed all the way through the system. Otherwise it gets dropped and isn't recorded in our analytics.
> Ensure user agent gets passed from SSR Relay Environment

- src/Components/Payment/SavedCreditCards.tsx
- src/Components/Payment/__tests__/SavedCreditCards.test.tsx
Fixes https://www.notion.so/artsy/Unable-to-delete-a-credit-card-from-the-payment-settings-page-c9873f59433c4bd8863453cd9f3e94cb
> [Payment] Fix CC removal by using internalID

- src/Apps/Artist/Routes/Overview/index.tsx
- src/Components/v2/ArtistInsight.tsx
- src/Components/v2/SelectedCareerAchievements.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1608
-  Move Artist Insights to the right side of bio
- Remove current events
cc: @samchieng
> Moved artist insights to the right PURCHASE-1608

- src/Components/Payment/PaymentForm.tsx
further proof, if any were needed, that noImplicitAny is a win.
> PaymentForm __id -> id

- src/Artsy/Analytics/Schema/Values.ts
- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Fixtures/Components.ts
- src/Components/Publishing/Layouts/NewsLayout.tsx
- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
- src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
- src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/__tests__/Article.test.tsx
[Ad Server Analytics Tracking--GROW-1545](https://artsyproduct.atlassian.net/browse/GROW-1545)
Adds click and impression tracking to ads being served through the 3rd party ad server.
> Track ad impressions and clicks on 3rd party served ads

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Components/CreditCardInstructions.tsx
- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/routes.tsx
- src/__generated__/ConfirmBidValidTestQuery.graphql.ts
- src/__generated__/ConfirmBid_me.graphql.ts
- src/__generated__/routes_ConfirmBidQuery.graphql.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-465
paired with @bhoggard 
This PR adds a way for unregistered users without credit cards to big and register at the same time. Most of the code is taken from the `Register.tsx` component and there may be a good refactoring opportunity, but in terms of functionality this is good to go.
> User without an existing credit card should be able to bid and register

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Components/CreditCardInstructions.tsx
- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/BidderPositionQuery.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
- src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
- src/Apps/Auction/routes.tsx
- src/DevTools/createTestEnv.tsx
- src/__generated__/ArtistInfo_Test_Query.graphql.ts
- src/__generated__/BidForm_me.graphql.ts
- src/__generated__/BidForm_saleArtwork.graphql.ts
- src/__generated__/BidderPositionQuery.graphql.ts
- src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
- src/__generated__/ConfirmBidValidTestQuery.graphql.ts
- src/__generated__/ConfirmBid_me.graphql.ts
- src/__generated__/routes_ConfirmBidQuery.graphql.ts
The Auctions production team has been working off of the `auct-pt-master` release branch while efforts to migrate `master` to use the Metaphysics V2 API was in-progress and other product work was frozen.
This PR includes rebased commits from the following PRs:
- User without an existing credit card should be able to bid and register #3011 
- User should be notified of an outbid or (any non-winning status) when attempting to confirm a bid #3000 
- User should be redirected to artwork page after confirmation that a bid is winning #2980 
jira ticket :lock:: https://artsyproduct.atlassian.net/browse/AUCT-746
> Meta: Merge recent auctions team product work into master

- src/Apps/Artist/Components/ArtistMeta.tsx
- src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
- src/__generated__/ArtistMeta_artist.graphql.ts
- src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Fixes [PURCHASE-1610](https://artsyproduct.atlassian.net/browse/PURCHASE-1610)
Background: only `lowPrice` is required for `AggregateOffer` so we can still produce metadata for artworks with only `minPrice`
> [PURCHASE-1610] Allow offer metadata for artworks with min-price

- src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
- src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
Doing QA on https://github.com/artsy/reaction/pull/3019 realized seller image is required by google (thanks invoicing demo partner for surfacing this problem)
> Do not include seller in structured data when no partner profile image

- src/Components/Gene/GeneRelatedLinks.tsx
- src/Components/Gene/__tests__/GeneRelatedLinks.test.tsx
- src/__generated__/GeneRelatedLinksQuery.graphql.ts
- src/__generated__/GeneRelatedLinks_Test_Query.graphql.ts
- src/__generated__/GeneRelatedLinks_gene.graphql.ts
Adds the related links view from the gene page to reaction. 
Currently the markup structure is preserved from what exists on the gene page and no additional styling was added. This is largely due to the fact that the gene page isn't in line with our current design system and updating the whole gene page to match feels out of scope for this ticket.
> Create gene links view

- src/Components/v2/CollectionsHubsHomepageNav.tsx
This removes the entry points impression event from `src/Components/v2/CollectionsHubsHomepageNav.tsx`. We remove it here because it fires too early and should be fired from [force](https://github.com/artsy/force/pull/4784) upon the user scrolling within a specific area.
I closed https://github.com/artsy/reaction/pull/3021 in favor of this PR to not include the generated files.
> Remove impression event

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Components/RegistrationForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-465
It adds the `<OnSubmitValidationError>` component to rack validation errors from Formik.
@dblandin @erikdstock I'm not sure if I'm using it right, but let me know if there's anything I should update.
> Track validation errors and registration submitted events

- src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
- src/Apps/Artwork/Components/TrustSignals/TrustSignal.tsx
- src/Apps/Artwork/Components/TrustSignals/__tests__/AuthenticityCertificate.test.tsx
[PURCHASE-1605]
__Motivation__
COA is a non homogenous standard across the art Industry. In order to help our collector make the best decision, it is important to show more information about how COAs are created etc.
__Story__
As a user, When I view an artwork that has a certificate of authenticity, If I click on the Certificate of Authenticity link in the COA Trust Signal text, I see a modal that provides more explanation about certificates of authenticity.
__Acceptance Criteria__
COA Info Modal upon click on COA Trust Signals link
Change copy on the Badge to display: “A certificate of authenticity is included with purchase”
[PURCHASE-1605]: https://artsyproduct.atlassian.net/browse/PURCHASE-1605
> Add modal to "Certificate of Authenticity" Badges with explanation of COA

- src/Apps/Collect2/Routes/Collections/Components/CollectionsGrid.tsx
Address : [Grow 1479](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1479)
Object: If there is no custom image header, it shows a gray circle. 
Those circle things are using `EntityHeader` from Palette. In Palette, we have [this](https://github.com/artsy/palette/blob/0ce2ed7da2cdce43bbad51709ae4bebe4545bf03/packages/palette/src/elements/EntityHeader/EntityHeader.tsx#L49). And then, the `EntityHeader` actually import `avatar`. Inside the avatar, it has condition checking(see [here](https://github.com/artsy/palette/blob/0ce2ed7da2cdce43bbad51709ae4bebe4545bf03/packages/palette/src/elements/Avatar/Avatar.shared.tsx#L66)), if it has imgURL, then it shows headerIMG, otherwise, it shows `initials string`. 
So, I just pass an …
> Grow-1479 Blank thumbnail on collections with generated banner 

- src/Apps/Auction/Components/BidForm.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Artsy/Analytics/Schema/AuctionInfo.ts
- src/Artsy/Analytics/Schema/Values.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-773
> Track "selected max bid" events on the confirm bid page

- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
fixes https://artsyproduct.atlassian.net/browse/AUCT-774
It seems like the actual prop in [`found`](https://github.com/4Catalyzer/found) looks like `props.match.location` instead of `props.location`. The test was passing because it was injecting to `props.location`, but in the actual browser it was actually missing. I updated it to properly confirm the interface. I also dropped the `qs` dependency since `found` already does this and we don't need to parse it out by ourselves.
> Fixes a bug where your max bid is not pre-selected on the new confirm bid page

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Adds a specific identifier to this element so we can select it in our integrity tests!
> PURCHASE-1649: Adds data-test attribute to the sale message on artwork view

- src/Apps/Artwork/Components/ArtworkBanner/index.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
Noticed while looking into Google Search Console issues that we were throwing a 500 on a few pages due to this error: https://sentry.io/organizations/artsynet/issues/1247032632/?project=28316&query=is%3Aunresolved&statsPeriod=14d
This should fix! (So would null checks cc @zephraph 😄)
> Handle missing partner on artwork page

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artist/Components/ArtistHeader.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1678
Removed dots by passing `pageDots` options from artists page and changed the height to 180 to reflect the new size.
cc: @samchieng
> Remove dots from the artist images

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
Ad server analytics tracking still wasn't firing as expected. This PR modifies the tracking event to fire as the waypoint leaves the viewport, rather than on entering, with an offset added to push the waypoint's boundaries up now that the event is firing on leave.
[Links to GROW-1678](https://artsyproduct.atlassian.net/browse/GROW-1678)
Firing Events Before Fix:
Firing Events After Fix:
> Modifies waypoint method call

- src/Apps/Auction/Components/LotInfo.tsx
- src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
Before
After
---
Also references more static auction information in the stories for ConfirmBid
Jira: https://artsyproduct.atlassian.net/browse/AUCT-718
> Maintain proper aspect ratio for image on confirm bid

- src/Apps/Artist/Components/ArtistHeader.tsx
Arrows for artwork images on artist page are gone after #3036 
We removed `HorizontalPadding` around carousel to remove padding from carousel on mobile, but removing that we also removed it from desktop which didn't change the look when we looked at the previous PR results but looks like it makes carousel going over the arrow icon.
Wrap desktop version of the carousel with `HorizontalPadding`.
> Bring back arrows removed by #3036

- src/Artsy/Analytics/Schema/Values.ts
- src/Components/NavBar/Menus/NotificationsMenu.tsx
- src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
Addresses: [GROW-1681](https://artsyproduct.atlassian.net/browse/GROW-1681)
This adds missing analytics coverage for the notification dropdown bar in preparation for the navigation a/b test.
**View All**
**Alert items**
> [GROW-1681] adds analytics events to the navbar notification menu

- package.json
- yarn.lock
Fixes an issue w/ `react-lazy-load-image-component` where lazy loading is broken when using intersection observers because of a faulty SSR check. 
cc @pepopowitz
> Bump version of lazy-load lib to fix SSR issue

- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
- src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
While investigating image lazy loading issues on the collection page I noticed that the `RelatedCollectionRail` didn't have its images lazy loaded. I went ahead and implemented that while I was here. 
Note that until https://github.com/artsy/reaction/pull/2985 is deployed, lazy-loading won't work in prod. (That's a known bug that I'm working through)
> Add lazy loading to collections rail

- src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
Small change to adjust lazy loading threshold on artwork grid from 9 to 6.
> Bump down threshold for lazy-loading on artist artwork grid

- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NotificationsBadge.tsx
Addresses: [GROW-1633](https://artsyproduct.atlassian.net/browse/GROW-1633)
When a logged in user hovers over the notification bell we fire two hover analytics events. This PR removes the hover event located in the NavBar component and relies solely on the hover tracking event in the NotificationsBadge component. The event in the NavBar is dependent on a cookie that is calculated and set in the NotificationsBadge so I think we can assume that's the best source of truth.
> [GROW-1633] remove duplicate hover analytics event

- src/Components/Publishing/Display/DisplayAd.tsx
- src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
- src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
This PR corrects the impression tracking of display ads.
Impressions of ads will only be tracked once, when the user first views them.
I accomplished this by removing our use of waypoints, and relying on Google to manage when the ad is viewed, with the `onImpressionViewable` event. The rules Google uses to identify if an ad is viewable are [in their docs](https://support.google.com/admanager/answer/4524488?hl=en&visit_id=637116147923101672-4119934528&rd=1). 
If a user scrolls very quickly past an ad, it is possible that we *won't* track an impression for it, but that seems correct to me, since they didn't truly look at it.
Along the way, I refactored the DisplayAd component to be a functional component instead of a class, as I found that easier to work with. 
~Tests are also broken; I'll …
> Updates to display ad tracking

- src/Components/NavBarTest/NotificationsBadge.tsx
This PR is related to https://github.com/artsy/reaction/pull/3050 and also addresses [GROW-1633](https://artsyproduct.atlassian.net/browse/GROW-1633). The NavBarTest component was cloned before we merged the fix for the double hover event. This PR adds the fix to the NavBarTest as well.
> [GROW-1633] fix double hover event in new navbar

- src/Components/Modal/ModalWrapper.tsx
fixes [PURCHASE-1686](https://artsyproduct.atlassian.net/browse/PURCHASE-1686)
**Problem:**
Closing modal leaves the `overflow-y: hidden` on `Body` tag:
**Solution:**
It turned out the component is unmounted before `this.prop.show` (coming from `state.ts`) is being set to false when closing the modal
In general it is not a bad idea to clean up side effects so added the functions cleaning up to `componentWillUnmount`
Also add a check to avoid setting multiple key event listeners when other props change
> Fix scrolling issue after modal is closed

- src/Components/NavBar/NavBar.tsx
https://artsyproduct.atlassian.net/browse/GROW-1698
Minor pre-existing Q/A issue that turned up while developing the [soon-to-be launched a/b test](https://github.com/artsy/force/pull/4860)
(Pretty subtle — check the spacing to the left of Artworks and to the right of More 🔍 )
> [GROW-1698] Fix whitespace in global nav

- 2
Checked the history and it looks like this might be an artifact from the `yarn integrate reaction` process in force-- shouldn't be here!
> Remove linking artifact

- src/Utils/catchLinks.tsx
There were some bug reports about wonky behavior with the 'Next' button in pagination.
Turns out, Prev/Next are [implemented](https://github.com/artsy/palette/blob/eab9b059edade3cc2ff918ff8285596e46e7258b/packages/palette/src/elements/Pagination/Pagination.tsx#L176) as empty anchor tags with custom `onClick` handlers. This just seems to be an oversight from early development of pagination. That doesn't work well with our link interception strategy for client side routing.
For that particular component, it should most likely be a valid anchor tag with href. However, since there might be other examples of these (we've found and fixed a few during work on the client side router in Reaction), plus Palette work and fixes deserves a lot of care, let's just go with this fix for now.
> @mzikherman => [CatchLinks] Dont attempt to handle empty anchor tags

- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Components/ArtistIndicator.tsx
- src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
- src/Components/v2/SelectedCareerAchievements.tsx
[PURCHASE-1700] Artist Page Tweaks
Center-align the number of followers with the label
Blue chip / emerging / established badge should always come before the auction record badge
Add “Representation” after Blue chip / established / emerging on both the top level badges and in career achievements
i.e. “Blue Chip Representation” (Title case on the badge)
“Blue chip representation” (sentence case in career achievements)
Adjust the icon size from 18px to 20px in badges
Add padding-top: 2px to text within badge to better align with the icon
[PURCHASE-1700]: https://artsyproduct.atlassian.net/browse/PURCHASE-1700
> PURCHASE-1700: Artist Page Tweaks

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Collect2/Routes/Collections/__tests__/CollectionsApp.test.tsx
- src/Apps/Collect2/Routes/Collections/index.tsx
- src/Apps/Search/SearchApp.tsx
- src/Apps/Search/__tests__/SearchApp.test.tsx
- src/Components/Search/SearchBar.tsx
- typings/sharify.d.ts
This moves the AB test events out of Force, and into Reaction. The enables them to fire whenever any Reaction page is rendered, no matter 'how' the client navigated to that page.
Places where the app was already functional went with `useEffect`, and in places where the app was a class went with `componentDidMount` (we want this analytics call to be fired when mounted).
The Force PR that ingests this will be pretty trivial, just removing the AB test events. 
**This still needs an updated experiment name.**
> @joeyAghion => [Analytics] Fire AB test events for client side routing

- src/Apps/Artist/Components/ArtistHeader.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1705
We show number of followers twice on the artist page on mobile.
> Remove showing follower numbers twice on mobile

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Collect2/Routes/Collections/index.tsx
- src/Apps/Search/SearchApp.tsx
- src/Artsy/Analytics/trackPageViewWrapper.tsx
- src/Components/Search/SearchBar.tsx
- typings/sharify.d.ts
First, a brief story about pageview tracking. Initially, this code all lived in Force, and upon page load, would fire. As we moved UI code into Reaction, this was less than ideal since this analytics code still lived in Force, but it was ok. We were doing full page reloads, and everything still worked.
We discovered, when wanting to trigger these while doing client side navigation, that it made sense to move analytics out of Force, and into Reaction. Additionally, since we only want the analytics call to fire on the client, we used `componentDidMount`. This was in https://github.com/artsy/reaction/pull/3067. So far so good, everything was checked and seemed to work fine.
However, consider the case of navigating from an artist page, to a related artist. Or from a collection, to a different …
> @joeyAghion => [Analytics] Correctly trigger pageviews using componentDidUpdate

- src/Apps/Collect2/Routes/Collect/Components/CollectMediumMetadata.ts
- tslint.json
While working on #3007, I ran into a tricky bug that was a result of accidentally falling through the `case` of a `switch`. It makes sense to me to disallow fall-through, as it has only ever caused me headaches. I'm PR'ing this change instead of making it directly in master, to allow others to speak up against disallowing fall-through.
There was only one place (CollectMediumMetadata) that was taking advantage of fall-through, and it might have been an accident.
> Add "no-switch-case-fall-through" tslint rule

- package.json
- yarn.lock
Updating `react-lazy-load-image-component` off of the beta version it's on
> Update `react-lazy-load-image-component` version

- src/Artsy/Router/RouterLink.tsx
- src/Artsy/Router/__tests__/RouterLink.test.tsx
We use this component in several collect related places. This enables client-side routing on the collect suite of pages, for instance (since all of those are mounted in the same router), as well as when navigating from a non-collect page, with full client side routing enabled.
However, when navigating from a non-collect page, such as when linked to from a rail on the artist page, and _without_ global client side routing enabled, this component incorrectly checks whether you're in a router context, whereas it should be checking that you're in a router context _and it's a supported route_.
cc @damassi as a sanity check. This should keep all the existing behavior (client-side routing is enabled in collect pages), while restoring the full reload when linked to from outside the collect suite. …
> @pepopowitz => [RouterLink] Tweak check to decide whether to route

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
We want to prevent users from right-clicking on images in the auction results section of the artist page.
> Prevent right click on auction results images

- src/Components/ArtworkGrid/ArtworkGrid.tsx
- src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
In digging more into [PURCHASE-1658](https://artsyproduct.atlassian.net/browse/PURCHASE-1658) I noticed something very strange. Many more images were being  preloaded than what was specified via the top level artwork grid. We usually default to 6, but I was seeing 11 (on mobile). 
Was scratching my head trying to figure out what prop was being passed down improperly, but then I realized I just goofed up the math.
> Fix artwork grid preloading too many images

- src/Components/NavBar/NavBar.tsx
- src/Components/__stories__/NavBar.story.tsx
https://artsyproduct.atlassian.net/browse/GROW-1725
Follow-up to https://github.com/artsy/reaction/pull/3062
One more minor tweak to the nav bar. This time accounts for all four permutations, as follows:
This^ comes from the story that is also added in this PR.
> [GROW-1725] Fix global nav bar spacing

- package.json
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
- src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
- src/Utils/Responsive/DeprecatedResponsive.tsx
- src/Utils/Responsive/index.tsx
- yarn.lock
Turns out reaction was still using react-responsive-media! Whoops. This updates it to use fresnel (which is the same library, just renamed).
> Remove react-responsive-media and add fresnel

- src/Artsy/Router/Utils/matchingMediaQueriesForUserAgent.ts
Fixes [PURCHASE-1712](https://artsyproduct.atlassian.net/browse/PURCHASE-1712).
This updates our device detection to check for googlebot's UA. If the mobile UA is present it only sends one breakpoint down the wire.
It's only detecting mobile because we've been switched over to mobile first indexing by Google. Also, the UA isn't _exact_ so there's potential that some device or service that's spoofing or using a partial of Google's UA gets swept up in this. We have access to what the full UA would be [here](https://support.google.com/webmasters/answer/1061943?hl=en). 
I'm fine with it being loose, but I'm interested to hear other's thoughts.
> Only render one breakpoint for mobile googlebot

- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Search/Components/NavigationTabs.tsx
- src/Artsy/Analytics/trackPageView.ts
- src/Artsy/Analytics/trackPageViewWrapper.tsx
- src/Artsy/Router/RouterLink.tsx
- src/Artsy/Router/__tests__/RouterLink.test.tsx
You called it in https://github.com/artsy/reaction/pull/3076#discussion_r362671969 .
This wound up overtriggering on tabbed pages.
This additional tweaked check seemed to work as desired in my local testing, but now I'm wondering if we should revert this approach entirely (and leave things on `componentDidMount`).
That would definitely remove over-triggering, but it puts us back in the position we were for the A/B test, where we were dropping all those subsequent calls. My gut tells me we have to get these lifecycle/hook calls correct in order to capture all those analytics properly.
> @damassi => [PageView Tracking] Correct for over-tracking on tabbed routes

- src/Apps/Order/Routes/Status/index.tsx
We want to be able to find the newly created order's `code` in Integrity so we can test proper emails.
Wrap code around a `span` and add `data-test` for it so we can find this element in the UI during integrity.
> Add `data-test` attribute to Order code so we can use it in integrity

- src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Fixes [1692](https://artsyproduct.atlassian.net/browse/PURCHASE-1692)
If a user paginates in the artwork grid then applies a filter it preserved the paginated state and could sometimes show no results. This update resets the pagination whenever a filter is set or unset.
> Reset pagination on artwork filter updates

- src/Artsy/Router/makeAppRoutes.tsx
This is a companion to https://github.com/artsy/reaction/pull/3086 , specifically the changes made in [`RouterLink`](https://github.com/artsy/reaction/blob/1ca5ca626cd744a07ff08426406187b7a0e15b1a/src/Artsy/Router/RouterLink.tsx#L51). Those were made to accommodate collection pages linking among themselves.
So, we still had the same issue that plagued our initial AB test. Namely, clicking on an artwork from an artwork page, keeps you in the same app, and we don't fire that subsequent pageview.
So this updates our global link interception to do the same thing we did in `RouterLink` for pageview tracking.
There's one sketchy thing, which I'll comment on in-line.
> @damassi => [PageView Tracking] Ensure pageviews are counted for navigation in the same page type

- src/Components/NavBar/NavBar.tsx
Noticed that the new react header doesn't use a `<header>` html tag -- this caused some issues with Integrity's login tests, where we couldn't find the 'log in' button on fully react pages. 
Adding header will have effects on accessibility, making nav clearer/more semantic for screen readers.
> Wrap main page header in header tags

- src/Apps/Order/Components/AddressForm.tsx
- There's an existing iOS bug which uppercases the first two letters when `autoCapitalization="word"` is enabled, so we are for now removing autoCapitalization on mobile
- WebKit bug report from 2016: https://bugs.webkit.org/show_bug.cgi?id=157410
- [MX-104]
- https://artsyproduct.atlassian.net/browse/MX-104
[MX-104]: https://artsyproduct.atlassian.net/browse/MX-104
> MX-104 - Fix double capitalized letters in iOS inputs

- package.json
- yarn.lock
See https://github.com/artsy/palette/pull/628 for more context. 
TL;DR sometimes (esp on chrome) images were downloading twice when lazy loading. Updating the library resolves that issue.
> Fix double image load issue by updating lazy load library

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Collect2/Routes/Collections/index.tsx
- src/Apps/Search/SearchApp.tsx
- src/Components/Search/SearchBar.tsx
- typings/sharify.d.ts
This is a draft until the NAV AB test is closed. This relaunches the test w/ experiment viewed events under a new test name. The analytics around pageview tracking should hopefully be resolved 🤞 .
Take 53!
> @joeyAghion => [Client Side Routing] Reenable AB test

- src/Artsy/Analytics/trackExperimentViewed.tsx
- src/Artsy/Router/RouterLink.tsx
- src/Artsy/Router/makeAppRoutes.tsx
This _might_ work if needed (still playing around locally).
Basically, we weren't always triggering a subsequent experiment viewed event (generally on subsequent navigation of the same 'type'). Very akin to the pageview triggering.
So, this adds explicit experiment viewed events alongside the places we had to specially handle the pageview triggering. Logical, right?
I attempted reconfiguring in various ways in order to try to properly use our `tracking` functionality, using hooks, using React lifecycle methods, rewriting a class to a functional component, etc.
None of them worked! So this winds up just reaching into `window.analytics`, etc.
> @joeyAghion => [Analytics] More explicitly track AB test events

- src/Artsy/Analytics/trackExperimentViewed.tsx
Since this is using `window.analytics` directly, the format of the argument is slightly different (+ no typing to help...)
> @mzikherman => [Analytics] Proper structure for experiment viewed event

- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBarTest/Menus/MobileNavMenu.tsx
- src/Components/NavBarTest/Menus/__tests__/MobileNavMenu.test.tsx
- src/Components/__stories__/NavBar.story.tsx
https://artsyproduct.atlassian.net/browse/FX-1692
This brings the mobile web nav menu inline with the desktop nav, so that they have the same items in the same order:
This also similarly updates the A/B experiment version of the nav bar — which is currently disabled but not definitively retired yet.
> [FX-1692] Reorder mobile nav items to match desktop

- src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
- src/Apps/Artwork/Components/ArtworkDetails/__tests__/RequestConditionReport.test.tsx
When creating a new account for a user via a request for a condition report on an artwork in a sale, skip the onboarding flow so that the user can quickly return to the artwork page to complete their condition report request.
> Use open:auth with redirectTo option to skip signup onboarding

- src/Artsy/Relay/SystemQueryRenderer.tsx
- src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
- src/DevTools/MockRelayRenderer.tsx
- tslint.json
- tslint/README.md
- tslint/noQueryRendererImportRule.js
Starting out with a naive rule using just string comparison...will see if an AST if needed.
This is a WIP since it's still not actually working. Getting:
> Error: Severity for rule 'noQueryRendererImport' not found
> @zephraph => [TSLint] Rule to warn about using QueryRenderer

- src/Apps/Order/Routes/Shipping/index.tsx
- src/Apps/Order/Routes/__tests__/Shipping.test.tsx
This is a follow up to fix a regression that I accidentally caused with my phone number field PR.
When I place an order
if I select shipping
and enter a shipping address
I should be required to enter a phone number
Currently, I'm able to advance without entering my phone number.
__After:__
> User should not be able to advance to the payment page without entering a phone number with their shipping address

- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Desktop/SignUpForm.tsx
- src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/Mobile/SignUpForm.tsx
- src/Utils/__tests__/recaptcha.test.ts
- src/Utils/recaptcha.ts
- Renames misspelled `repcaptcha` instances
- Adds new impression types to `recaptcha`
> Rename 'repcaptcha' to 'recaptcha', add new types

- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
- src/__generated__/CollectionRefetch2Query.graphql.ts
- src/__generated__/Header_artworks.graphql.ts
https://artsyproduct.atlassian.net/browse/FX-1675
Our performance investigations a while back uncovered some potential improvements. This is a small one, but does look to reduce page weight a little.
These images — up to 12 of them — are only 45px square but were being rendered from the 230px version, and with the original, variable quality settings (some times up to quality: 100).
In this PR we use the `artist.image.resized` field to reduce these in size to match the design, and in compression quality to our recommended value of quality: 80.
Here's a sample collection and the reduction in image weight:
https://www.artsy.net/collection/street-art-now
(All images reduced from 230px square to 45px square)
|Img|Quality before|Bytes before|Quality after|Bytes after|
|---|---|---|---|---| …
> [FX-1675] Resize collection header artist images

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
Addresses: [FX-1684](https://artsyproduct.atlassian.net/browse/FX-1684)
After investigating the performance on the collection page, we identified that the featured collections rail used an image that was larger than necessary (over 900px). This PR use the resize util to pull in a smaller images (500px) as a means of improving the page's performance. 
**Featured Collections Rail**
> [FX-1684] use resizer for featured collection image

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsCount.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
- src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/__generated__/ArtistAuctionResultsQuery.graphql.ts
- src/__generated__/ArtistAuctionResults_artist.graphql.ts
- src/__generated__/AuctionResultsCount_results.graphql.ts
- src/__generated__/AuctionResults_Test_Query.graphql.ts
- src/__generated__/routes_AuctionResultsQuery.graphql.ts
This PR:
- Removes the sidebar (which will be re-added with filters)
- Updates the results to be on top of the auction results list
- Slightly updates the result language
A few learnings from this
- When we add the filtering we'll have to pay special attention to how we do the `Showing X of Y results`
- We need to make sure we're properly co-locating components
> Update the auction result layout

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
Addresses: [FX-1775](https://artsyproduct.atlassian.net/browse/FX-1775)
The "Browse by category" rail is another instances where we were pulling in larger images than are needed. This PR uses the resize util to resize the collection thumbnail to 60x60.
> Resize category rail

- package.json
Reaction isn't doing anything special that would require a constraint like this -- just running storybooks and compiling files with babel. However, when upgrading other apps that consume reaction, this constrain often gets in the way and requires more coordination than necessary. This removes that friction.
> Remove Node verson requirement

- src/Components/Publishing/Sections/Text.tsx
- src/Components/Publishing/Sections/__tests__/Text.test.tsx
We have been applying the Backbone follow button on the client, despite already fetching the necessary follow data for tooltips. 
This PR updates the text component to display Relay artist-follow buttons wherever the 'artist-follow' class is present on a link.
Related PR: https://github.com/artsy/force/pull/5004
> Article text components use relay follow buttons

- README.md
The URL for Storybooks in the Reaction README took me to a scary place:
Looks like that domain has expired
Changed the url to link to their current documentation.
> Update URL for storybooks documentation

- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
- src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
- src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
- src/Components/Publishing/__tests__/ArticleMeta.test.tsx
- src/Utils/resizer.ts
https://artsyproduct.atlassian.net/browse/FX-1773
We have multiple approaches for requesting on-the-fly resized images. One of them is to use these `resize`  and `crop` utility functions from within Reaction code.
While working on image optimizations related to collections, I noticed that the `crop` default was still set to 95, even though [we had settled on 80 a while back](https://github.com/artsy/force/pull/2226), and even though `resize` in this file itself had been [similarly updated previously](https://github.com/artsy/reaction/pull/1491).
This just carries that change through to `crop` as well.
> [FX-1773] Adjust default jpeg quality for cropped images

- src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
https://artsyproduct.atlassian.net/browse/FX-1675
One more quickie optimization, thanks to Calibre's [report for hub pages](https://calibreapp.com/teams/artsy/artsy-net?page=9cd7a86b-b201-4479-8730-004f75cda411), which alerted me to the fact that we still had a few inappropriate PNGs on the page.
> Ensure PNG → JPG in Collection Hubs's related rail

- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
- src/Artsy/Analytics/trackingMiddleware.ts
Fixes an issue that was observed by @anipetrov: 
From [Slack message](https://artsy.slack.com/archives/CA8SANW3W/p1581028242462600?thread_ts=1580919019.365800&cid=CA8SANW3W): 
1. tracking pageview referrers from within reaction is producing referrers that are paths eg referrer: "/collection/post-war". in our transformations, we expect those to be urls, eg. referrer: "https://www.artsy.net/collection/post-war" we use external libraries to parse pageview referrers to define when a session is external and give proper channel attribution (eg if someone is coming from google, we parse that to search). those libraries expect urls.
2. the url property on reaction pages is inconsistent, eg in this case, the path is correct, referring to collection/roy-lihtenstein-landscapes but the url is the url …
> [Tracking Bugfix] Fix url and referrer tracking

- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
- src/Artsy/Analytics/trackingMiddleware.ts
Missed the requirement that the path, too, be absolute.  cc @mzikherman
> [Tracking Bugfix] Make path absolute

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Analytics/trackingMiddleware.ts
Caught a small bug on staging related to how we handle page-view tracking differently in the Artwork app. Had to update with the full path.
> [Tracking Bugfix] Fix artwork page 1-off

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
- src/Artsy/Analytics/trackingMiddleware.ts
@anipetrov pinged this morning and mentioned that the path doesn't need to be full -- communication mixup on my side. 
```
path: "/collection/post-war-print-renaissance"
url: "https://www.artsy.net/collection/post-war-print-renaissance"
referrer: "https://www.artsy.net/collection/post-war"
```
> [Analytics] Path is relative

- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBarTest/Menus/MobileNavMenu.tsx
- src/Components/NavBarTest/NavBar.tsx
Noticed a little bug in the mobile nav: When the new app shell is enabled, the mobile nav doesn't close on `/collect` link click because there's not a full page transition.
> [Bugfix] Ensure nav closed on clienside routes

- src/Artsy/Router/Utils/RenderStatus.tsx
We're speculating that this might be what impacted inquiries on mobile during the A/B test -- meaning, a user has clicked a link, and they can't see that a loader is going by on the top of the screen and they think the page may have timed out? This puts it in the middle, and dims the background a bit. After the A/B test results we'll need to go back to design for something a more permanent.
> [Clientside Routing] Update mobile page loader to be more obvious

- data/schema.graphql
Adding new diffusion `sizes` param and removes `organization` (not being used in prod yet)
> Updates MP schema

- src/Apps/Auction/Routes/ConfirmBid/index.tsx
fixes https://artsyproduct.atlassian.net/browse/AUCT-835
We were seeing the following warning as well as the issue described in the ticket:
The reason why this is occurring is that we are dynamically creating a trackable component while rendering in `ConfirmBid/index.tsx`: 
https://github.com/artsy/reaction/blob/98f689f4bda9f53b09b92135fedb2d376806a8fc/src/Apps/Auction/Routes/ConfirmBid/index.tsx#L360-L366
And here the `Component` variable always holds a reference to a newly created object. When this component is passed into the React VDOM and a re-render is triggered, the newly created component is considered to be a "diff" even though it's essentially the same thing. As a result of this, all the components below it would get thrown away once the new trackable component gets in, making …
> Fixes a bug where unregistered users who bid and register and don't meet the reserve do not get feedback that their bid did not meet the reserve

- 2
- src/Components/Publishing/Byline/ClassicByline.tsx
- src/Components/Publishing/Byline/__tests__/ClassicByline.test.tsx
- src/Components/Publishing/Byline/__tests__/__snapshots__/ClassicByline.test.tsx.snap
- src/Components/Publishing/Constants.ts
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Fixtures/Articles.ts
- src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
- src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
- src/Components/Publishing/Layouts/ClassicLayout.tsx
- src/Components/Publishing/Typings.ts
Some updates to enable displaying classic articles in React
- Use palette fonts
- Show channel name when provided for byline
- add share components
> Remove deprecated fonts from classic articles, fix bylines

- README.md
Adding a few steps: 
1. Update `package.json`, set version to a canary version, e.g. `2.0.0-canary-<PR#>`, `3.1.5-canary-<PR#>`, ...
1. Run `npm publish --tag canary` to publish the package under the canary tag
1. Run `yarn add @artsy/reaction@canary` to install canary package
1. Running `npm dist-tag ls` can be helpful to see what tagged packages are available
> Update README with info on publishing canary

- .storybook/webpack.config.js
- src/Artsy/Router/__tests__/buildServerApp.test.tsx
- src/Artsy/Router/buildServerApp.tsx
Fixes issue where injected bundle-split scripts aren't prefixed with CDN url when `CDN_URL` is available. 
This mirrors how our [assetMiddleware](https://github.com/artsy/force/blob/master/src/lib/middleware/assetMiddleware.ts#L23) function works over in force.
A future refactor would be to pass back concrete script src elements that can be individually piped into the asset helper.
> [Bugfix] Prefix injected split tag scripts with CDN_URL

- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/Search/Routes/Artworks/index.tsx
- src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
- src/Apps/Search/routes.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/Artsy/Router/server.ts
- src/Components/Search/SearchBar.tsx
- src/Utils/Hooks/useDidMount.ts
Adding bundle splitting to the SearchApp, and also fix SSR rendering on the search input in the nav bar, which flashes in because on client-side load initial render is behind a QueryRenderer.
> Bundle split search; fix SSR search input

- src/Artsy/Router/makeAppRoutes.tsx
- src/Components/Search/SearchBar.tsx
Fixes issue where search result item urls not within the global router context returned 404; e.g., https://staging.artsy.net/pushkin-house.
> [Bugfix] Ensure all search-bar nav items navigate properly

- .circleci/config.yml
This uses https://github.com/artsy/orbs/pull/86 to automatically publish canaries from any branch PRs added to reaction. 
We'll need to consider if it'll create too much noise for automated PRs like renovate. 
<details>
<summary>📦 Published PR as canary version: <code>25.11.1-canary.3168.51833.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.11.1-canary.3168.51833.0
yarn add @artsy/reaction@25.11.1-canary.3168.51833.0
```
</details>
> Add canary deployment to reaction PRs

- README.md
Just a small update to note that canaries are auto published. 
<details>
<summary>📦 Published PR as canary version: <code>25.11.2-canary.3172.51862.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.11.2-canary.3172.51862.0
yarn add @artsy/reaction@25.11.2-canary.3172.51862.0
```
</details>
> Note that canaries are auto published

- src/Artsy/Router/RouterLink.tsx
Since our RouterLink component stips unauthorized props we needed to allowlist `data-test`.
> Pass data-test down through RouterLink #trivial

- src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
- src/Apps/Collect2/Routes/Collect/index.tsx
- src/Apps/Collect2/Routes/Collection/index.tsx
- src/Apps/Search/Routes/Artworks/index.tsx
Fixes [PURCHASE-1793](https://artsyproduct.atlassian.net/browse/PURCHASE-1793)
Noticed the event is already being tracked [here](https://github.com/sepans/reaction/blob/faf119874fbe9d518cddbd7d4704f06e9c6e14ba/src/Components/v2/ArtworkFilter/index.tsx#L127) inside the component so there is no need to track it using the `onFilterClick` prop. Today during grooming realized this has been also reported by #data-team.
> [PURCHASE-1793] Fix artwork filter events being tracked twice.

- .gitignore
- 2
`yarn integrate` likes to create this file which accidentally gets checked in. Not sure what it's for, but it doesn't need to be in git. 
<details>
<summary>📦 Published PR as canary version: <code>25.11.7-canary.3180.52017.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.11.7-canary.3180.52017.0
yarn add @artsy/reaction@25.11.7-canary.3180.52017.0
```
</details>
> Remove weird 2 file generated by yarn integrate

- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Order/OrderApp.tsx
- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
Fixes a browser-level alert guard when navigating away from completed order -> status page. Don't need it there.
Also fixes double tracking on artwork page.
> [Clientside Nav] Fix double track on artwork page

- src/Apps/Artist/routes.tsx
- src/Apps/Artwork/routes.tsx
- src/Apps/Auction/routes.tsx
- src/Apps/Collect2/collectRoutes.tsx
- src/Apps/Conversation/routes.tsx
- src/Apps/Order/routes.tsx
- src/Apps/Search/routes.tsx
Noticed an issue where async chunk requested from the parent of an async chunk doesn't fetch from our CDN url, only top-level chunks. 
Breadcrumbs of previous work: 
- Ensure top-level chunks are served from `CDN_URL`: https://github.com/artsy/reaction/pull/3159 
The current flow in production is: 
1) Webpack will compile out all of our chunks and create a manifest
1) We check if we're in a prod environment, and prefix a cloudfront CDN url via our [asset helper](https://github.com/damassi/force/blob/c2ce1db7b7007721d768497439ae81e64380395b/src/lib/middleware/assetMiddleware.ts#L20-L27)
1) In reaction, when loadable components dynamically injects scripts into the page *_on the first render_* [we do the same](https://github.com/artsy/reaction/blob/master/src/Artsy/Router/buildServerApp.tsx#L …
> [BundleSplitting] Comment out for now

- src/Artsy/Relay/renderWithLoadProgress.tsx
Companion PR: https://github.com/artsy/palette/pull/640
This fixes the issue thats frequently seen on our artist, artwork and collect and search pages where we conditionally render content in query renderers on the client. For a large number of pages we never render these sections, yet we always see a preloader that flashes while we make a request, and shifts our layouts all around in an ugly unstable way. 
This adds a default delay of 800ms until we show the preloader, which covers cases when a request takes an unreasonable amount of time. 
In most cases though, the area will return empty, and no loader will show, keeping the layout stable.
> [QueryRenderers] Delay showing spinner

- src/Apps/Conversation/Components/ConversationSnippet.tsx
- src/Apps/Conversation/Components/Message.tsx
- src/Apps/Conversation/Mutation/SendConversationMessage.ts
- src/Apps/Conversation/__tests__/ConversationApp.test.tsx
- src/Apps/__tests__/Fixtures/Conversation.ts
- src/__generated__/Message_message.graphql.ts
- src/__generated__/SendConversationMessageMutation.graphql.ts
- src/__generated__/routes_DetailQuery.graphql.ts
Add Image and PDF attachments to conversation messages.
This is a follow up on #3173 where we added conversations to admins but in there we were not showing message attachments.
> Add attachments to each message

- .babelrc
- package.json
- src/Apps/Artwork/ArtworkApp.tsx
- src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/Apps/Artwork/Components/OtherWorks/Header.tsx
- src/Artsy/Analytics/trackingMiddleware.ts
- src/Artsy/Relay/renderWithLoadProgress.tsx
- src/Artsy/Router/makeAppRoutes.tsx
- src/Utils/getENV.tsx
- tsconfig.json
- typings/sharify.d.ts
- yarn.lock
See https://github.com/artsy/force/pull/5099 for more info. 
This updates our `getENV` isomorphic ENV lookup util with another server-side layer:
- First, check to see if `SOME_ENV` var exists within the request / response cycle, stored within express-http-context. If so, return that value. Useful for A/B testing.
- If undefined, fall back to `process.env.SOME_ENV`
> Simplify A/B test lookup via `express-http-context`

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.test.tsx
- src/Apps/Artist/Routes/AuctionResults/state.ts
- src/Artsy/Analytics/Schema/Values.ts
When on any auction results page other than the initial page, expanding an auction card would bring you back to the first page and expand whatever auction card was at that position on the first page. 
The index of the expanded card was previously stored as a filter. When we updated the filter logic to not reset the page we were puzzled when it continued to reset anyway. After some exploration, we discovered a different bug where pagination disregards the page provided by the filters: it just always resets to 1 when a filter changes. This isn't an issue normally because the default expected behavior is to go back to the first page when a filter is changed. In this case though, we wanted to keep the current page.
Instead of fixing that larger underlying bug, which very likely would require …
> Fix issue where expanding auction result changed page

- data/schema.graphql
- src/Components/NavBar/Menus/NotificationsMenu.tsx
- src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
- src/Components/NavBar/NotificationsBadge.tsx
- src/Components/NavBar/__tests__/NotificationsBadge.test.tsx
- src/__generated__/NotificationsMenuQuery.graphql.ts
This PR updates the `NotificationsBadge` (just the "count") to reference the unread notifications count that we keep track of in gravity. This will correctly go to 0 when notifications are dismissed.
Note that this doesn't make any changes to the feed or the dropdown.
Old:
New:
Actual data:
Gif showing dismissal:
> Update field used for notifications badge count

- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Components/ArtistIndicator.tsx
- src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
User experience feedback: The new labels Highest auction result and Career Stage feel/look tappable – could also lead users to Auction Result / Career Highlights?
I updated the indicators so that the auction record indicator links to the auction results tab, and the career stage indicator links to the cv page.
[PURCHASE-1782]: https://artsyproduct.atlassian.net/browse/PURCHASE-1782
> Link header badges to Auction Result / Career Highlights

- src/Utils/recaptcha.ts
Logs from https://github.com/artsy/gravity/pull/12774 indicate that signups are coming through Force regularly that do not include the `recaptcha_token`. 
I believe all signups besides the Inquiry flow use Reaction's `FormSwitcher`, which should include tokens with all signup requests. This logging (which can be removed in the future) is to help us nail down if the errant Force signups are being routed through Reaction's signup form, and if they are caused by missing `recaptcha` lib on the window or a missing key.
> Log recaptcha misses on signup

- src/Components/NavBar/menuData.ts
https://artsyproduct.atlassian.net/browse/FX-1702 
Co-authored-by: Christina Thompson
This roughs in a data structure that can be re-used across the new menu components we are creating for mobile and for desktop.
The file includes data for simple urls, as well as for nested submenus. Our expectation is that the eventual components for these new menus will import this data file and transform them as needed into the appropriate UI, whether for mega dropdowns (desktop) or for animated transitions (mobile).
The file is based on work done by CCE and documented [here](https://docs.google.com/spreadsheets/d/1WLQq6xRH8fa-LribPv5NiwnSuBQHQtjmMObm2GLIGY0/edit#gid=112964129)
> Add data file to describe new menu structure (for mobile and desktop)

- package.json
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/Apps/Auction/Routes/Register/index.tsx
- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/routes.tsx
- src/Apps/Order/OrderApp.tsx
- src/Artsy/Analytics/trackingMiddleware.ts
- src/Artsy/Router/Utils/RenderStatus.tsx
- src/Artsy/Router/buildServerApp.tsx
- src/Artsy/SystemContext.tsx
- src/Components/NavBar/Menus/MobileNavMenu.tsx
- src/Components/Search/SearchBar.tsx
- src/Utils/getENV.tsx
- yarn.lock
This moves things to a conventional A/B test structure. 
@mzikherman - I keep revisiting the strange production-only edgecase around the ENV var being unset when clicking `/collect` and want to play it safe because we can't afford to get incorrect metrics. We can't repo it locally. If there's a chance that things get out of sync we might be over or under reporting a given A/B test state. 
I don't know if it has anything to do with `express-http-context`, but I'd rather be 100% sure that it's safe for a change as big as this, especially if it has to do with concurrency.
> [Clientside Nav] Move to more conventional A/B test structure

- data/schema.graphql
- package.json
- Tooling: Fix `yarn schema-schema`
- Update schema to use MP's schema at mp@rename-wizard-to-flow
Merge after: https://github.com/artsy/metaphysics/pull/2203
<details>
<summary>📦 Published PR as canary version: <code>25.21.2-canary.3205.52776.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.21.2-canary.3205.52776.0
yarn add @artsy/reaction@25.21.2-canary.3205.52776.0
```
</details>
> [step 2] Update schema to use MP's schema at mp@rename-wizard-to-flow

- src/Components/NavBar/Menus/MobileNavMenu.tsx
https://artsyproduct.atlassian.net/browse/FX-1828
I picked off some of the purely visual work from the [parent ticket](https://artsyproduct.atlassian.net/browse/FX-1702).
The Figma designs include updates to typography (Unica) and spacing (tighter padding overall, and around the horizontal dividers.
Here's what that looks like:
> [FX-1828] Update typography and spacing in mobile menu

- package.json
- src/Apps/Artist/routes.tsx
- src/Apps/Artwork/routes.tsx
- src/Apps/Auction/routes.tsx
- src/Apps/Collect2/collectRoutes.tsx
- src/Apps/Components/AppShell.tsx
- src/Apps/Order/routes.tsx
- src/Apps/Search/routes.tsx
- src/Artsy/Router/buildServerApp.tsx
- yarn.lock
When we added bundle splitting we had a WIP item to figure out how to ensure that the split bundles were loaded once the route transitioned so as to mitigate the split-second white-screen flash. This PR adds a new pattern to address: 
```tsx
const MyApp = loadable(() => import('./MyApp')
const routes = [{
path: '/path/to/app',
getComponent: () => MyApp,
prepare: () => {
MyApp.preload()
},
... 
}]
```
Whenever routes transition in the new router, `prepare` is called, which in turn calls the `preload` fn added by [loadable-components](https://loadable-components.com/docs/prefetching/). Since data is usually being fetched before the transition, the bundle loads in parallel leading to a stable page once the transition completes. 
I need to do one more "add tests" PR to wrap up this work; will …
> [Clientside Nav] Add async bundle preloading pattern to router

- .circleci/config.yml
- .gitignore
This upgrades our `yarn` orb to 4.0.2 which contains a change in where we look for jest test results. This _should_ fix our test results tracking so that we can get some performance data about our tests. 
<details>
<summary>📦 Published PR as canary version: <code>25.22.2-canary.3215.52969.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.22.2-canary.3215.52969.0
yarn add @artsy/reaction@25.22.2-canary.3215.52969.0
```
</details>
> Update yarn orb to track tests via circle again

- src/Apps/Artist/Components/ArtistCollectionsRail/index.tsx
- src/Apps/Collect2/collectRoutes.tsx
Noticed that on the artist "Works" tab the layout is unstable due to the collections rail always making a request even though the data has already been fetched, which also applies if there's no rail for a given artist, leading to a loading state to empty content. This fixes both things and ensures a stable layout.
Wondering if there was a deliberate reason for forcing a refetch every time? 
(Note that we have a relay cache expiration of 15 minutes, so unless the collections rail has rapidly changing results we should be ok.)
> [Artist] Visual QA

- src/Apps/Search/SearchApp.tsx
- src/Components/Search/SearchBar.tsx
Fixes a few visual qa items on search:
In the new app shell when performing a search the query stays in the input, since there's no longer a hard jump between pages to clear it out. Now it clears on enter: 
The search title is a function of url bar state. Now, when transitioning away from the page the url changes and the title updates, but before a full page transition. This ensures that things only update when changed: 
Before: 
After:
> [Search] Visual QA

- src/Apps/Auction/__tests__/routes.test.ts
- src/Apps/Auction/routes.tsx
- src/Artsy/Analytics/trackingMiddleware.ts
- typings/sharify.d.ts
Updates client-side A/B test name from `CLIENT_NAVIGATION_V3` to `CLIENT_NAVIGATION_V4` just so we can be sure that the data is consistent, accounting for a mid-day deploy on Thursday after test was released.
> Update AB test name to CLIENT_NAVIGATION_V4

- .circleci/config.yml
- package.json
- yarn.lock
This sets up a package I wrote this weekend called [lint-changed](https://github.com/artsy/lint-changed). It's very similar in theory to `lint-staged` except it's intended to be useful for CI. 
The premise is that linting has a 1-to-1 relationship with files and running linting over the entire codebase is pretty wasteful. On a PR this will only lint  the files that have changed since `origin/master`. On master this will only lint the files that have changed since the last tag.
This is in the same vein of doing less duplicative work on CI. 
<details>
<summary>📦 Published PR as canary version: <code>25.22.3-canary.3220.53079.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.22.3-canary.3220.53079.0
yarn add …
```
> Only lint changed files

- .circleci/config.yml
- package.json
- yarn.lock
Reverts artsy/reaction#3220
cc @eessex going to revert until I can dig in further. 
<details>
<summary>📦 Published PR as canary version: <code>25.24.3-canary.3228.53249.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.24.3-canary.3228.53249.0
yarn add @artsy/reaction@25.24.3-canary.3228.53249.0
```
</details>
> Revert "Only lint changed files"

- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Mobile/LoginForm.tsx
This adds hooks to our auth modals for more reliable detection during integration testing. 
<details>
<summary>📦 Published PR as canary version: <code>25.25.0-canary.3234.53369.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.25.0-canary.3234.53369.0
yarn add @artsy/reaction@25.25.0-canary.3234.53369.0
```
</details>
> Adds hooks to login modals for integration tests

- src/Apps/Components/AppShell.tsx
This adds a mechanism to tell cypress that we're ready to start testing. This is a mechanism we can use to avoid timing issues w/ rehydration. 
It will need to be followed up with an integrity update to check for this after page visits. 
<details>
<summary>📦 Published PR as canary version: <code>25.25.0-canary.3233.53368.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.25.0-canary.3233.53368.0
yarn add @artsy/reaction@25.25.0-canary.3233.53368.0
```
</details>
> Add attribute to body when app is ready to be tested

- src/Apps/Components/AppShell.tsx
Fixes something I [forgot to commit](https://github.com/artsy/reaction/pull/3233/files#r388025165) earlier. 
Essentially when we're writing tests with crypress we have a pattern of adding attributes like `data-test="SomeThing"` whereas I have historically (in past jobs) just added boolean attributes like `data-test-some-thing`. 
This updates the selector to follow our established conventions.  
<details>
<summary>📦 Published PR as canary version: <code>25.26.1-canary.3236.53413.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.26.1-canary.3236.53413.0
yarn add @artsy/reaction@25.26.1-canary.3236.53413.0
```
</details>
> Update attribute to follow pre-established testing patterns

- src/Components/NavBar/Menus/UserMenu.tsx
- src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
Fixes [PURCHASE-1820](https://artsyproduct.atlassian.net/browse/PURCHASE-1820)
This changes conversations from being available to admins to being behind a lab feature flag. This is necessary to test because it's somewhat impossible to submit an inquiry as an admin. 
<details>
<summary>📦 Published PR as canary version: <code>25.27.0-canary.3241.53560.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.27.0-canary.3241.53560.0
yarn add @artsy/reaction@25.27.0-canary.3241.53560.0
```
</details>
> Move conversations behind lab feature flag

- src/Components/v2/Carousel.tsx
@sweir27 - caught a reload bug issue, which I tracked down [to here](https://sentry.io/organizations/artsynet/issues/1514677136/?project=28316&query=is%3Aunresolved+flickity&sort=freq&statsPeriod=14d). 
In a super alpha version of the shell I noticed an issue with flickity, and to be safe I added this guard that was never removed, and I haven't seen the issue reappear in many months. However, when some bad MP data came through to the carousel, it would catch in the error boundary and trigger a reload, versus failing back to error page which we now have in place. 
https://github.com/artsy/reaction/pull/3208 fixed the data issue.
> [Carousel] Remove error boundary

- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
`sd` is a bit smarter than `getENV` since it converts `'false'` (the string) to `false` (the boolean.) Because this was only checking the presence of the value, the string value `'false'` was always evaluating to truthy regardless of what is set to it, causing the lot condition report feature to always be on for every sale.
> Replace getENV with sd for now

- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
- src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
- src/Components/Artwork/Save.tsx
- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Authentication/Types.ts
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/FollowGeneButton.tsx
- src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
- src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
- src/Components/Publishing/Article.tsx
- src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
- src/Components/Publishing/ToolTip/__tests__/GeneToolTip.test.tsx
- src/Components/v2/ArtistCard.tsx
- src/Utils/__tests__/openAuthModal.test.ts
- src/Utils/openAuthModal.ts
Several options are passed through follow buttons to open auth modals for unregistered users.  Some of these follow implementations are not behaving as expected while opening the modal, or completing their `afterSignUpAction`. 
In anticipation of more strictly typed analytics auth events, this PR updates helpers for auth modals to use the `ModalOptions` type our auth forms expect. 
<details>
<summary>📦 Published PR as canary version: <code>25.26.3-canary.3239.53491.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.26.3-canary.3239.53491.0
yarn add @artsy/reaction@25.26.3-canary.3239.53491.0
```
</details>
> Helpers for opening auth modals are strictly typed

- src/Apps/Collect2/Components/SeoProductsForCollections.tsx
Fixes https://sentry.io/organizations/artsynet/issues/1529814294/?project=28316&query=is%3Aunresolved&statsPeriod=24h
See https://www.artsy.net/collection/faile-posters for error. 
Saw that there was unsafe object access; updated with optional chaining to make a bit safer.
> [Bugfix] => Make `SEOProductsForCollections` safer

- src/Apps/Artwork/Components/OtherWorks/index.tsx
Noticed there was an elastic search data issue at https://staging.artsy.net/artwork/chip-hughes-untitled and digging in, saw that we could add a bit more safety. See [this thread](https://artsy.slack.com/archives/C9YNS4X32/p1583767239172700).
Also noticed here that this revealed a bug in the `get` function itself -- if the initial object being passed in is null, then it will still error out, versus being safe all the way through the chain. (Right now, any _subsequent_ properties can be null / undefined). Either way, we can now use optional chaining so get is no longer nececessary.
> Make hide grids function a bit safer

- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Components/Artwork/Save.tsx
- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Authentication/Types.ts
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/FollowGeneButton.tsx
- src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
- src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
- src/Components/Publishing/Article.tsx
- src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
- src/Components/Publishing/ToolTip/__tests__/GeneToolTip.test.tsx
- src/Utils/__tests__/openAuthModal.test.ts
- src/Utils/openAuthModal.ts
Reopens #3239
Companion PR in Force: https://github.com/artsy/force/pull/5189
Updates the `openAuthModal` helper, which is used by follow and save buttons to construct `ModalOptions` for the Artist page. 
This PR is part of an effort to strictly type all arguments passed to mediator when opening auth modals. This is related to efforts to strictly type authentication analytics events. 
https://artsyproduct.atlassian.net/browse/PLATFORM-2286
<details>
<summary>📦 Published PR as canary version: <code>25.27.6-canary.3252.53757.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.27.6-canary.3252.53757.0
yarn add @artsy/reaction@25.27.6-canary.3252.53757.0
```
</details>
> Type openAuthModal helpers

- src/Artsy/Router/Boot.tsx
Follow up to https://github.com/artsy/reaction/pull/3233, which expands coverage a bit for all kinds of components / pages that use `<Boot>`.
> Add Integrity-ready flag to boot

- src/Apps/Conversation/ConversationApp.tsx
- src/Apps/Conversation/Routes/Conversation/index.tsx
- src/Apps/Conversation/__tests__/ConversationApp.test.tsx
This is the over half of the work needed to move the inquiries view from behind admin to behind the lab feature flag. 
I didn't realize it was gated both in the menu and in the app.
> Move conversations app to be behind lab feature instead of admin flag

- package.json
- yarn.lock
We're seeing some [issues](https://sentry.io/organizations/artsynet/issues/932987046/?project=28316&query=is%3Aunresolved&sort=freq&statsPeriod=24h) on mobile related to openseadragon. This update hopefully includes some bug fixes that'll help reduce the occurrences of those errors. 
<details>
<summary>📦 Published PR as canary version: <code>25.27.14-canary.3260.53895.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.27.14-canary.3260.53895.0
yarn add @artsy/reaction@25.27.14-canary.3260.53895.0
```
</details>
> Update openseadragon to try to fix some mobile bugs

- src/Components/v2/Carousel.tsx
Still trying to fix the unreproducible  
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
```
error around flickity as seen in this [sentry](https://sentry.io/organizations/artsynet/issues/1497212332/?project=28316&query=removeChild&statsPeriod=24h) ticket. 
This [stack overflow](https://stackoverflow.com/a/54882016/1038901) comment made me think we might be using a fragment somewhere in the carousel around images, and indeed we were. 
🤞
> Attempt to fix Flickity error

- src/Apps/Components/AppShell.tsx
- src/Artsy/Router/NetworkOfflineMonitor.tsx
- src/Artsy/Router/NetworkTimeout.tsx
- src/Artsy/Router/RenderStatus.tsx
- src/Artsy/Router/buildAppRoutes.tsx
Addresses 
- https://artsyproduct.atlassian.net/browse/PLATFORM-2283
- https://artsyproduct.atlassian.net/browse/PLATFORM-2284
This adds a new component to our routing framework that will appear if a request is taking longer than 10 seconds, showing our standard ErrorDialog component and prompting the user to retry, which will reload the page. 
--- 
Also added a `NetworkOfflineMonitor` component that will check if the network is offline, and shows a Banner alerting the user: 
(Can test this via chrome dev tools.)
> [Clientside Nav] Add <NetworkTimeout /> & <NetworkOfflineMonitor /> components

- src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultHeader.tsx
- src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
- src/__generated__/ArtistAuctionResultsQuery.graphql.ts
- src/__generated__/AuctionResultHeader_artist.graphql.ts
- src/__generated__/AuctionResults_Test_Query.graphql.ts
- src/__generated__/routes_AuctionResultsQuery.graphql.ts
Update header text for auction results page
Jira Ticket: https://artsyproduct.atlassian.net/browse/PURCHASE-1818
Ran `yarn relay` to get the artists.slug graphql data for the text.
Here's what it looks like in storybooks:
Kinda hardcoded the new copy with some dynamic links for `/cv` and the information article url. Any tips on doing this a little bit better?
<details>
<summary>📦 Published PR as canary version: <code>25.28.0-canary.3262.53966.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.28.0-canary.3262.53966.0
yarn add @artsy/reaction@25.28.0-canary.3262.53966.0
```
</details>
> [PUR-1818] Update header text for auction results page

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Router/RenderStatus.tsx
We have enough data now where we don't need to continue showing the loader in the middle of the screen on mobile. This removes that weirdness.
> [Clientside Nav] Remove mobile loader test

- src/Components/v2/Carousel.tsx
Fixes an alignment bug that [originated here](https://github.com/artsy/reaction/pull/3265) that only appears during SSR render / when JS is disabled.
> [Carousel] Fix alignment in image

- src/Artsy/Router/Boot.tsx
- src/Artsy/Router/__tests__/Boot.test.tsx
- src/Artsy/Router/__tests__/buildClientApp.test.tsx
- src/Components/ErrorBoundary.tsx
- src/Components/NavBar/MinimalNavBar.tsx
- src/Components/Payment/__tests__/PaymentForm.test.tsx
- src/Components/__tests__/ErrorBoundary.test.tsx
While browsing Sentry I've noticed [occasional errors](https://sentry.io/organizations/artsynet/issues/1564753432/?project=28316&query=is%3Aunresolved+chunk&statsPeriod=24h) appear that look like 
> Loading chunk 24 failed. (error: https://d1s2w0upia4e9w.cloudfront.net/assets/Routes-Works.22820.adcce79ed4f87e3fc6ed.js)
This typically happens when a user (often on a mobile phone) is navigating between routes and their network connection goes out, which leads to a split JS bundle failing to load. 
We've already [added retry support](https://github.com/artsy/force/pull/5186) on the Force side of things, which will re-try the request up to five times. However, that doesn't handle absolute failures, nor does it gracefully degrade with UI that can lead to a recovery.
According to React's [code …
> [Clientside Nav] Add more safety around network failures with fallback UI

- src/Apps/Collect2/Routes/Collection/index.tsx
- src/__generated__/CollectionAppQuery.graphql.ts
- src/__generated__/Collection_collection.graphql.ts
Addresses: [FX-1758](https://artsyproduct.atlassian.net/browse/FX-1758)
**Problem:**
When links for collection pages are shared on social media the display appears with a small photo. This is because for most collection pages we don't have a header image and the meta data for the image gets pulled from the images in the artwork grid.
**Fix:**
This PR introduces a new fallback image that is a larger, resized version of the first image in the artwork grid. The logic checks for the headerImage first and if it's not present uses the resized image.
> [FX-1758] add a fallback image when there is no headerImage

- src/Components/ErrorBoundary.tsx
- src/Components/__tests__/ErrorBoundary.test.tsx
This adds a generic error handler for catch-alls runtime errors. I realized we needed this when working in storybooks and hitting a syntax error and thinking things through: if `getDerivedStateFromError` is present, then it will rerender the component for a fallback, but if theres an error, it will call `getDerivedStateFromError`, which will rerender -- etc. So this adds more safety for all other cases, which should be in place anyway.
> [ErrorBoundary] Add generic error handler

- src/Apps/Search/Components/NavigationTabs.tsx
Somewhere the spacing between the tabs in the search bar disappeared: 
Before: 
After: 
#trivial
> [Search] Fix tab UI spacing

- src/Apps/IdentityVerification/Processing.tsx
- src/Apps/IdentityVerification/__tests__/routes.test.tsx
- src/Apps/IdentityVerification/routes.tsx
completes https://artsyproduct.atlassian.net/browse/AUCT-930 :lock: 
A user is sent to this URL by our ID verification service, not by any internal routing, so I'm not sure if/how to test?
Desktop view
Mobile view
<details>
<summary>📦 Published PR as canary version: <code>25.32.6-canary.3274.54648.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.32.6-canary.3274.54648.0
yarn add @artsy/reaction@25.32.6-canary.3274.54648.0
```
</details>
> [AUCT-930] static id verification processing page

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Moves all remaining auth modal triggers to use `openAuthModal` helper. Follow up to #3264
> Update remaining mediator calls

- src/Components/Authentication/FormSwitcher.tsx
- src/Components/Authentication/__tests__/FormSwitcher.test.tsx
Links to the reset password page will often include a query param including the target user's email address. This commit uses that value to prepopulate the reset password form, simplifying the experience.
Co-authored-by: @anandaroop 
jira :lock: : https://artsyproduct.atlassian.net/browse/TRUST-92
> Prepopulate email input from URL query string on forgot password page

- src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/__tests__/Sections.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
The 3rd ad on Standard Articles should be 300x250 on mobile and desktop. This PR updates that from 970-250 on desktop.
https://artsyproduct.atlassian.net/browse/FX-1837
Desktop:
Mobile:
> Updates size on 3rd display ad on standard desktop

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
Fixes [PURCHASE-1844](https://artsyproduct.atlassian.net/browse/PURCHASE-1844)
When adding the year created filter I forgot to pass the new those new parameters to the refetch container which caused pagination to break. 
We should follow up on Monday with a test. 
<details>
<summary>📦 Published PR as canary version: <code>25.34.5-canary.3295.55024.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.34.5-canary.3295.55024.0
yarn add @artsy/reaction@25.34.5-canary.3295.55024.0
```
</details>
> Fix broken pagination on auction results page

- src/Artsy/Router/NetworkTimeout.tsx
- src/Components/ErrorBoundary.tsx
- src/Components/__tests__/ErrorBoundary.test.tsx
Updates the language on the network timeout to be something a bit more specific:
"An error occurred" => "Network timeout"
Also removes the faux nav from the ErrorBoundary state as it conflicts with a few different scenarios (app sections that don't have a nav, etc).
> Update NetworkTimeout language

- src/Components/Publishing/Sections/Sections.tsx
Social Embed sections types were missing from the logic that determines if an ad should be rendered in a standard article section, this PR addresses that.
After fix:
Before fix:
> Adds social_embed section type to ad insertion logic

- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/Components/FilterResetLink.tsx
Fixes [1841](https://artsyproduct.atlassian.net/browse/PURCHASE-1841)
Adds a `Reset` link to the year created filter to easily reset it back to the defaults. 
Based on some feedback Sam C. I added a short fade in animation. 
<details>
<summary>📦 Published PR as canary version: <code>25.36.0-canary.3302.55170.0</code></summary>
<br />
```sh
npm install @artsy/reaction@25.36.0-canary.3302.55170.0
yarn add @artsy/reaction@25.36.0-canary.3302.55170.0
```
</details>
> Add year created filter reset link

- src/Artsy/Analytics/Schema/Values.ts
- src/Components/NavBar/Menus/MobileLink.tsx
- src/Components/NavBar/Menus/NewMobileNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MobileLink.test.tsx
- src/Components/NavBar/Menus/__tests__/NewMobileNavMenu.test.tsx
Addresses: [FX-1829](https://artsyproduct.atlassian.net/browse/FX-1829)
This PR adds analytics tracking to mobile nav menu.
> Mobile nav menu analytics

- src/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
- src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
This is due to a failure to direct the user to the identity verification
flow, probably because that `push()` function is intended for navigating
programatically within the found router on the same domain.
[Bug report on slack](https://artsy.slack.com/archives/CA3D02SDN/p1585152180005500) 🔒
> Switch props.router.push back to window.locaion.assign for idv flow

- src/Components/AddressForm.tsx
- src/Components/__stories__/AddressForm.story.tsx
The issue here is that when the Form loads technically there is nothing selected. But once the user starts interacting with country select - we need to let this interaction manage the state. The fact that we just set selected to whatever was passes as origin country broke this state interaction.
Hope that fixes this issue: https://artsyproduct.atlassian.net/browse/GALL-2703
Also @lilyfromseattle I think moved the AddressForm to the general components from Order. So I reshuffled the story a bit as well.
> the Address Form component should respect country selection for Euro only shipping

- src/Components/Publishing/ArticleMeta.tsx
- src/Components/Publishing/__tests__/ArticleMeta.test.tsx
This PR fixes a bug in the article meta tags causing a the text 0 to render at the top of video editorial series pages. 
https://artsyproduct.atlassian.net/browse/FX-1875
The Bug:
The Fix:
> Video meta bug

- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
The original logic check here was checking for an `undefined` type but those results could be `null` too. 
I updated the logic to check for a `number` which is the _exact_ type we're expecting.
> Ensure year created check doesn't error on nulls

- src/Components/NavBar/Menus/NewMobileNavMenu.tsx
This moves chevron down to be more accurately centered.
Image of the issue below:
> [Mobile Nav Menu] adjust chevron position

- src/Apps/Artist/Components/ArtistConsignButton.tsx
- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Components/__stories__/ArtistConsignButton.story.tsx
- src/Apps/Artist/Components/__tests__/ArtistConsignButton.test.tsx
- src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
- src/Apps/Artist/__tests__/routes.test.tsx
- src/Apps/__tests__/Fixtures/Artist/Components/ArtistHeader.tsx
- src/Artsy/Analytics/Schema/Values.ts
- src/__generated__/ArtistConsignButtonQuery.graphql.ts
- src/__generated__/ArtistConsignButton_Test_Query.graphql.ts
- src/__generated__/ArtistConsignButton_artist.graphql.ts
- src/__generated__/ArtistHeader_Test_Query.graphql.ts
- src/__generated__/ArtistHeader_artist.graphql.ts
- src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Addresses 
- https://artsyproduct.atlassian.net/browse/CSGN-90
- https://artsyproduct.atlassian.net/browse/CSGN-92
Adds a new responsive `ArtistConsignButton` that covers two cases: "Top 20", and everything else.
We're not implementing "Target Supply" version yet because we don't yet know how to get data from RedShift over to Metaphysics.
> [Consignments] Add ArtistConsignButton

- .gitignore
#minor
This PR adds a line to gitignore node diagnostic reports. It is copied from https://gitignore.io/api/node.
> gitignore node diagnostic reports

- src/Components/ErrorBoundary.tsx
- src/Components/Modal/ErrorModal.tsx
- src/Components/Modal/__tests__/ErrorModal.test.tsx
- src/Components/__tests__/ErrorBoundary.test.tsx
Adds stack trace output in `development`. Formatting could likely be improved at a later date.
> [ErrorBoundary] Add stack trace in development

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
Little SSR edgecase -- if `shuffle` is used, it will execute once on the server, and then once more on the client, leading to dom mismatch. Need to think this through a bit better.
> [Consignments] Remove shuffle on recently sold

- src/Components/Publishing/Nav/NewsNav.tsx
- src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
This is a hotfix for the /news page, where date updates on the top nav are preventing users from scrolling past the point of the last fetch: 
Updates so that only the word "News" appears, as the dates still show in the articles themselves. 
---
> [HotFix] Comment out NewsNav date

- src/Apps/Artist/Components/ArtistConsignButton.tsx
- src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
- src/Apps/Artist/Routes/Overview/index.tsx
- src/__generated__/Overview_artist.graphql.ts
- src/__generated__/routes_OverviewQuery.graphql.ts
Addresses: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=86&projectKey=CSGN&modal=detail&selectedIssue=CSGN-109
This adds the new consign  button to the Artist/Overview page:
> [Artist] Add ConsignButton to Artist/Overview page

- src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
- src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
- src/Apps/WorksForYou/WorksForYouFeed.tsx
- src/Components/NavBar/Menus/NotificationsMenu.tsx
[PURCHASE-1787]
https://www.artsy.net/works-for-you =>sort should be “most recent”
Activity feed bell => Sort should be “most recent”
Works by artists you follow rail 
From Search bar, Artist
They should land on Work For Sale
[PURCHASE-1787]: https://artsyproduct.atlassian.net/browse/PURCHASE-1787
> Land on Work for Sale tab when coming from internal links

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
- src/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.test.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Apps/Artist/Routes/Consign/index.tsx
- src/Apps/Artist/routes.tsx
- src/Apps/__stories__/ArtistApp.story.tsx
Noticed that `artsy.net/artist/genieve-figgis/consign` has no recently sold artworks, but is still in the microfunnel, and thus breaks as the assumption was that only artists with sold items were in this list. This guards against this case in the future by hiding the section entirely. 
#trivial
> [Consignments] Guard against missing data

- src/Components/NavBar/Menus/MoreNavMenu.tsx
- src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
Addresses: [FX-1885](https://artsyproduct.atlassian.net/browse/FX-1885)
This restructures the main desktop nav menu to expose Artworks, Artists, Auctions, and Editorial and place everything else in the More menu.
**Before Nav Menu Change:**
**After Nav Menu Change:**
> [FX-1885] restructure the main nav menu

- src/Components/NavBar/Menus/MobileNavMenu/index.tsx
- src/Components/NavBar/menuData.ts
Addresses: https://artsyproduct.atlassian.net/browse/FX-1880
> Use "Artsy for Galleries" instead of "Partner with Artsy" naming in mobile nav

- src/Apps/Artist/Components/ArtistConsignButton.tsx
- src/Apps/Artist/Components/__tests__/ArtistConsignButton.test.tsx
Was flagged that tracking was missing from the button click and noticed that `action` was missing from the schema props. 
Raised the issue here in an effort to make things a little more frictionless: https://artsy.slack.com/archives/C0KEQD4B0/p1585865660062300
#trivial
> [Bugfix] Add missing `action` call to ArtworkConsignButton

- src/Apps/Artist/routes.tsx
- src/Artsy/Router/Route.tsx
- src/Artsy/Router/__tests__/buildServerApp.test.tsx
- src/Components/Modal/ErrorModal.tsx
- src/Components/Modal/ModalDialog.tsx
We have the loader split between a few different styles, from the spinner to the top purple bar. Rather than default to spinner on route transition, which was in place before the router work, lets use the purple bar by default unless we explicitly want the spinner. (Spinner is good for nested content like artist tabs)
Also cleans up error modal stack trace a bit by making it wider in development and respecting `\n` breaks:
> [Clientside Nav] Use app shell top-loader by default

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
Hotfix follow up to Analytics changes.
<details>
<summary>📦 Published PR as canary version: <code>26.0.2-canary.3343.56457.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.0.2-canary.3343.56457.0
yarn add @artsy/reaction@26.0.2-canary.3343.56457.0
```
</details>
> Remove contextModule from auction redirect

- src/Artsy/Router/Route.tsx
This reverts a change in https://github.com/artsy/reaction/pull/3342.
In short, I noticed that we were masking errors in our routing layer by only throwing if it was an HTTP error. If a non-http error throws in the stack during a fetch it would get quietly consumed. In most cases this is fine as we surface these errors in other ways (such as our ErrorBoundary) but if something threw inside of our graphql stack [as this test shows](https://github.com/damassi/reaction/blob/914699fbe737dba9ece6bc9ff8e48ef6bdd3c7e1/src/Artsy/Router/__tests__/buildServerApp.test.tsx#L233-L253) we would never know about it. 
This ended up failing our acceptance test because it surfaced a masked error related to fixture data (or something):
In any case, reverting that change and simply logging the error so that …
> [Route] Log generic errors but throw on HttpError

- src/Artsy/Relay/createRelaySSREnvironment.ts
Noticed an issue where clicking an artist, clicking follow, then clicking an artwork, then clicking back to an artist the follow button wasn't selected because we had a cache hit on artist view. 
There's a config setting in our network layer to bust cache on mutations. Setting this to true.
> [Clientside Nav] Clear cache on mutation

- src/Apps/FeatureAKG/Components/Feature.tsx
- src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
We have 3 different videos (one for the top and 2 sections in the middle), with two different assets depending on the breakpoint.
> Adds video support for the Art Keeps Going campaign

- src/Apps/Artist/ArtistApp.tsx
[PURCHASE-1853]
Currently on the cv, shows, and article pages there's a Back to <artist> link that the top which points to the root artist page (/). Given that we're doing redirects now when a user is logged in to the works-for-sale tab, it won't take logged in users who navigated to that page explicitly back to the overview which is a confusing experience. 
We should change all of those links to go specifically to /overview
Here's an example of what the link on https://www.artsy.net/artist/andy-warhol/cv
[PURCHASE-1853]: https://artsyproduct.atlassian.net/browse/PURCHASE-1853
> Update `back to <artist>` links to point directly to the overview page

- src/Components/NavBar/Menus/UserMenu.tsx
- src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
PURCHASE-1855
Add envelop icon that links off to the conversations app when clicked. We should also clean up the link to inquires under the user settings menu. UserMenu.tsx#L59-L63 
Out of scope for this ticket:
showing the dropdown menu
indicating unread messages
Notes:
Uses EnvelopeIcon from Palette
Links to /user/conversations
Should be behind the User Conversations View lab feature flag. 
See this link for an example: ConversationApp.tsx#L18 
__Before:__
__After:__
Hover:
> Add desktop menu item for navigating to conversations

- src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
[PURCHASE-1854]
Add the ability to navigate to the conversations app from the mobile nav menu. 
For this ticket, don’t worry about the number of unread messages. We’ll get to that later. 
Uses EnvelopeIcon from Palette
Links to /user/conversations
Should be behind the User Conversations View lab feature flag. 
See this link for an example: ConversationApp.tsx#L18 
[PURCHASE-1854]: https://artsyproduct.atlassian.net/browse/PURCHASE-1854
> Add inbox to mobile nav menu

- src/Apps/FeatureAKG/Components/Feature.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
- src/Utils/resizer.ts
Couple of performance wins:
- Images were being uploaded a `png`s-- this explicitly converts them to jpeg.
- Added a `poster` attribute for the video so if someone has a setting or otherwise that doesn't let it autoplay, they get the first contentful frame vs. a white screen.
> Convert images to JPG and add poster for video

- src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
Fixes [PURCHASE-1858](https://artsyproduct.atlassian.net/browse/PURCHASE-1858)
Currently in production for users on the mobile site can't log out. The FX team has some places around updates to the mobile nav experience, so this just temporarily adds logout back in until the new nav updates happen. 
<details>
<summary>📦 Published PR as canary version: <code>26.8.0-canary.3360.57003.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.8.0-canary.3360.57003.0
yarn add @artsy/reaction@26.8.0-canary.3360.57003.0
```
</details>
> Add log out link back to mWeb

- src/Apps/Artist/ArtistApp.tsx
- src/Apps/Artist/Components/NavigationTabs.tsx
- src/Apps/Artist/__tests__/routes.test.tsx
- src/Apps/Artist/routes.tsx
- src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
There was somewhat of an [unfortunate misunderstanding](https://artsy.slack.com/archives/C9YNS4X32/p1586370735303100) related to this feature. 
It was never intended for _all_ logged in users to be redirected to `/works-for-sale` but only logged in users specifically coming from google. Given that this is causing issues with tracking anyway, we're just going to revert.
<details>
<summary>📦 Published PR as canary version: <code>26.8.1-canary.3368.57095.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.8.1-canary.3368.57095.0
yarn add @artsy/reaction@26.8.1-canary.3368.57095.0
```
</details>
> Revert /works-for-sale redirect

- src/Artsy/Analytics/v2/Schema/Authentication.ts
- src/Artsy/Analytics/v2/Schema/ContextModule.ts
- src/Components/MinimalCtaBanner.tsx
- src/Components/Publishing/Banner/Banner.tsx
- src/Components/Publishing/Banner/__tests__/Banner.test.tsx
The tracking on the `MinimalCtaBanner` component was double-firing, because we get an `authImpression` event once we hit `/sign_up`.
This updates the link href for the banner to use updated auth tracking args and helpers, and removes the extraneous impression.
> Use auth helpers for minimalCTABanner tracking args

- src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
Give that FX is intending more changes to the menu (especially on mobile), I'm going to remove the inbox icon for now.  
<details>
<summary>📦 Published PR as canary version: <code>26.8.4-canary.3375.57220.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.8.4-canary.3375.57220.0
yarn add @artsy/reaction@26.8.4-canary.3375.57220.0
```
</details>
> Remove inbox icon from menu

- src/Artsy/Router/NetworkTimeout.tsx
Looking at sentry we're getting a lot of timeout errors: 
I bumped the timeout from 10s to 15s -- but maybe its better that the dialog with the reload button appears at 10, forcing an action in order to jog MP in some way?
> Bump timeout

- src/Artsy/Router/PageLoader.tsx
- src/Artsy/Router/RenderStatus.tsx
Follow-up to https://github.com/artsy/palette/pull/665
Moving the top loading bar logic back over to reaction so that we can have more control. 
Eventually want to replace this with something like https://github.com/klendi/react-top-loading-bar, or at least match the functionality better.
> [Clientside Nav] Move Pageloader from Palette

- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
Use logger instead of console.error so we get results reported to sentry. 
<details>
<summary>📦 Published PR as canary version: <code>26.8.7-canary.3379.57276.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.8.7-canary.3379.57276.0
yarn add @artsy/reaction@26.8.7-canary.3379.57276.0
```
</details>
> Use logger instead of console.error to capture missing data reports

- src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
- src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
Similar to the `data-test` attribute on the login and signup forms, this allows us to query `ForgotPasswordForm` elements in the DOM during Cypress integration testing.
@eessex I followed the Login/SignUp examples found elsewhere. I wonder if we should at some point create a typed Cypress-specific schema which we can use in the artsy/integrity codebase similar to the analytics schema: https://github.com/artsy/reaction/blob/master/src/Artsy/Analytics/Schema/index.ts
Maybe we can also be more explicit in marking components as "queryable" within a Cypress test suite.
> Add data-test attribute on ForgotPassword forms

- src/Apps/Conversation/Components/Conversation.tsx
- src/Apps/Conversation/Components/Message.tsx
- src/Apps/Conversation/Components/TimeSince.tsx
- src/__generated__/Conversation_conversation.graphql.ts
- src/__generated__/routes_DetailQuery.graphql.ts
Addresses [PURCHASE-1866](https://artsyproduct.atlassian.net/browse/PURCHASE-1866) and starts to address [PURCHASE-1865](https://artsyproduct.atlassian.net/browse/PURCHASE-1865)
Before:
After: 
The design:
This is not complete, but a PreMVP piece of work to push the state of the conversation view forward. I'll follow up with tests. 
<details>
<summary>📦 Published PR as canary version: <code>26.13.0-canary.3389.57478.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.13.0-canary.3389.57478.0
yarn add @artsy/reaction@26.13.0-canary.3389.57478.0
```
</details>
> Update conversations UI to be closer to design spec

- src/Components/Publishing/__stories__/ToolTip.story.tsx
Follow-up to https://github.com/artsy/reaction/pull/3388
Starting at some version between v5.1.10 and v5.3.18 of Storybook, separator chars like `/` should only be used to separate path parts and not present at the end of a path string, otherwise the UI breaks. /shrug
```
Error: Invalid part '', leading to id === parentId
('publishing-tooltips'), inside kind 'Publishing/ToolTips/'
Did you create a path that uses the separator char accidentally, such as
'Vue <docs/>' where '/' is a separator char? See
https://github.com/storybookjs/storybook/issues/6128
```
> Remove trailing separator char from Storybook story path

- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
- src/Artsy/Analytics/Schema/Values.ts
Adds an additional property to our "Request a price estimate" button calls: `flow: Consignments`
> [Consignments] Add `flow: consignments` to tracking

- package.json
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarArtists.test.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
- src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
- src/Apps/Auction/Routes/__tests__/Register.test.tsx
- src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
- src/Apps/Order/Routes/__tests__/Accept.test.tsx
- src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
- src/Apps/Order/Routes/__tests__/Review.test.tsx
- src/Components/Authentication/__tests__/FormSwitcher.test.tsx
- src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
- src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
- src/Components/Search/__tests__/SearchBar.test.tsx
- src/Utils/__tests__/openAuthModal.test.ts
- yarn.lock
Update jest to use JSDOM v16 via the `jest-environment-jsdom-sixteen` package.
> Update Jest to use JSDOM v16

- data/schema.graphql
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.test.tsx
- src/__generated__/ArtistAuctionResultsQuery.graphql.ts
- src/__generated__/ArtistAuctionResults_artist.graphql.ts
Add a checkbox to the year created filter toggle that allows users to filter results by the presence of date information.
Checkbox will be selected by default
Link to JIRA Ticket: https://artsyproduct.atlassian.net/browse/PURCHASE-1852
Metaphysics changes: https://github.com/artsy/metaphysics/pull/2314
Diffusion API changes: https://github.com/artsy/diffusion/pull/226
<details>
<summary>📦 Published PR as canary version: <code>26.15.0-canary.3397.57718.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.15.0-canary.3397.57718.0
yarn add @artsy/reaction@26.15.0-canary.3397.57718.0
```
</details>
> [PURCHASE-1852] Add checkbox and filtering for lots with nil date information

- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
This spec is flaky on CI. We could skip it but might be better to give the spec a bit more time to complete and follow-up on why it's slow.
```
FAIL  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx (14.473s)
● ArtworkFilter › desktop › renders default UI items
: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
49 |
50 |   describe("desktop", () => {
> 51 |     it("renders default UI items", async () => {
|     ^
52 |       const wrapper = await getWrapper()
53 |       expect(wrapper.find("ArtworkFilterArtworkGrid").length).toEqual(1)
54 |       expect(wrapper.find("SortFilter").length).toEqual(1)
at new Spec …
```
> Bump timeout of "ArtworkFilter/desktop/renders default UI items" spec

- src/Apps/Search/Components/NavigationTabs.tsx
- src/Apps/Search/routes.tsx
I noticed that, although we index them, we weren't exposing static pages in our search results/autocomplete.
This (along with https://github.com/artsy/metaphysics/pull/2316) fixes that! Pages show up under the `More` tab:
> Expose static pages in search results/autocomplete

- src/Components/UserSettingsTwoFactorAuthentication/Components/BackupSecondFactorMethod.tsx
- src/Components/UserSettingsTwoFactorAuthentication/Components/__stories__/BackupSecondFactorMethod.story.tsx
- src/Components/UserSettingsTwoFactorAuthentication/UserSettingsTwoFactorAuthentication.tsx
Introduce the 2FA backup codes UI. Hook up the modal and 'Set up' / 'Regenerate' controls.
> Add mocked UI for the 2FA backup codes

- src/Apps/Conversation/Components/Conversation.tsx
Before:
After:
The layout here isn't perfect. We really should only show this when we're for certain rendering the first image. It's hard to do that given how we currently calculate things on the client though. There's a ticket to add `isFirstMessage` to metaphysics to help w/ this though, so we can follow up after. 
<details>
<summary>📦 Published PR as canary version: <code>26.15.0-canary.3393.57577.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.15.0-canary.3393.57577.0
yarn add @artsy/reaction@26.15.0-canary.3393.57577.0
```
</details>
> Update artwork preview in conversation

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
- src/Artsy/Analytics/trackExperimentViewed.tsx
- src/Artsy/Analytics/trackingMiddleware.ts
When looking closely at analytics data an edge-case was discovered around referrer being lost in events other than page views. 
Since we're now in a single-page-app context, we need a way to store referrers as the user progresses across clicks:
1) Compute the referrer in our analytics middleware as we have been
1) Store the refer on the global segment.js `window.analytics` object under `window.analaytics.__artsyReferrer`. 
1) In force, where we funnel analytics calls from Reaction, check to see if `__artsyReferrer` is populated and manually set the `referrer` before a `track` call is fired.
> [Clientside Nav] Fix referrer edgecase

- package.json
- src/Components/UserSettingsTwoFactorAuthentication/__tests__/UserSettingsTwoFactorAuthentication.test.tsx
- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
- yarn.lock
We unfortunately discovered that some other specs are taking longer and hitting timeouts so we're going to postpone this library upgrade for now.
Partially revert https://github.com/artsy/reaction/pull/3400
Back out the library update but keep the `Object.defineProperty` mock updates which are backwards-compatible and should make a future upgrade attempt easier.
Also remove the timeout bump added in https://github.com/artsy/reaction/pull/3402.
Related issue thread on Jest 25 performance: https://github.com/facebook/jest/issues/9457
> Rollback JSDOM v16 upgrade

- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
- src/Artsy/Analytics/trackingMiddleware.ts
We want to propagate queryParams across pages too, if they're there.
> [Clientside Nav] Add search to referrer

- src/Components/NavBar/Menus/DropDownMenu.tsx
- src/Components/NavBar/Menus/DropDownSection.tsx
- src/Components/NavBar/Menus/TwoColumnDropDownSection.tsx
- src/Components/NavBar/Menus/__tests__/DropDownMenu.test.tsx
- src/Components/NavBar/Menus/__tests__/DropDownSection.test.tsx
- src/Components/NavBar/Menus/index.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/menuData.ts
Addresses: [FX-1887](https://artsyproduct.atlassian.net/browse/FX-1887)
This is a WIP PR that introduces a new DropDownMenu component. It's blocked by some work on [palette Menu component](https://github.com/artsy/palette/pull/664). This PR includes most of the styling and layout structure in addition to hiding the new drop down behind a feature flag.
Missing the following ToDos:
> Update desktop nav menu

- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx
- src/Components/Carousel.tsx
Minor updates to pass `contextModule` to carousel, and to use the prop as a `data-test` attr for integrity.
> Add data-test attrs for artist page

- src/Components/Auction/PostRegistrationModal.tsx
re-finishes https://artsyproduct.atlassian.net/browse/AUCT-952
This is just adding whitespace to before/after FAQ. See screenshot.
> Add whitespace to before/after FAQ link

- src/Components/NavBar/Menus/DropDownMenu.tsx
- src/Components/NavBar/NavBar.tsx
- src/__generated__/SearchResultsEntityQuery.graphql.ts
- src/__generated__/routes_SearchResultsEntityQuery.graphql.ts
This PR depends on https://github.com/artsy/palette/pull/671 and addresses some minor style issues with the drop down menu:
- Adds the chevron to drop down menus in the nav bar.
- Ensure menu extends to the fullwidth of the screen.
- Remove top and bottom padding for fullwidth drop down menu.
- Fixes the styling for the "view all" links.
**Before:**
**After:**
> Style updates to new nav drop down menu 

- src/Components/NavBar/NotificationsBadge.tsx
- src/Components/NavBar/menuData.ts
Addresses: [FX-1905](https://artsyproduct.atlassian.net/browse/FX-1905)
This fixes two minor Drop Down QA items:
-  Switch `Under $1,000` bucket for artworks from `https://www.artsy.net/collect?price_range=50-1000` to `https://www.artsy.net/collect?price_range=%2A-1000`
- Fix the notification badge placement
> [FX-1905] Fix notification badge placement

- package.json
Given that cohesion is a direct dependency of force, including it as a direct dependency of reaction can lead to cases where it's duplicated in Force's bundle. I'm moving it to a dev dependency in reaction so that it'll still be installed and available when developing locally, but won't be included in the production output (and therefore duplicated in force). 
I haven't included it in this PR, but if there are other services that depend on reaction which should also use cohesion then we should add cohesion as a peer dep too.
> Move cohesion to be a dev dep of reaction

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Type checking is currently failing because we are using fields removed from cohesion in https://github.com/artsy/cohesion/pull/15
Updates references to use new naming pattern.
> Auction results auth intent conforms to schema

- package.json
- src/Apps/Components/AppContainer.tsx
- src/Artsy/Router/Boot.tsx
- src/Artsy/Router/RenderStatus.tsx
- src/Artsy/Router/__tests__/buildClientApp.test.tsx
- src/Artsy/Router/__tests__/buildServerApp.test.tsx
- src/Artsy/Router/buildAppRoutes.tsx
- src/Artsy/Router/interceptLinks.ts
- src/Artsy/SystemContext.tsx
- src/Artsy/__tests__/SystemContext.test.tsx
- src/Artsy/__tests__/systemContextState.test.tsx
- src/Artsy/systemContextState.tsx
- yarn.lock
This PR does a couple cleanup-y type things: 
- Converts `Boot` to an FC 
- Updates `SystemContext` to to be a bit more modern, and moves state updates to a reducer
- Adds a new action `setAppMaxWidth` which allows us to modify the outside container width to each of our breakpoints, or `100%`
- Moves our mechanism for catching a-tag links in the new app-shell context (similar to gatsby-catch-links) out of route construction and into its own file.
> [Refactor] Modernize SystemContext, make app shell width configurable 

- src/Artsy/Router/Boot.tsx
Realized that `useSystemContext` was being called before we actually set up the context provider. Removed that and switched to `<SystemContextConsumer>` render props pattern in `Boot`.
> Fix useSystemContext invocation

- src/Apps/Conversation/Components/Conversation.tsx
[PURCHASE-1857]
Add a header to the conversation view on mobile. For the scope of this ticket the info icon won't link to anything. The back button should link back to /user/conversations
Copy includes "Inquiry with" + Conversations.to.name from MP
Uses InfoCircleIcon
Figma link: https://www.figma.com/file/vtXzdPefblvRiAapA79fTh/Conversations?node-id=268%3A0
[PURCHASE-1857]: https://artsyproduct.atlassian.net/browse/PURCHASE-1857
> Add a header to the conversation view on mobile

- src/Apps/Artist/ArtistApp.tsx
Noticed that the recently viewed rail was still visible on /consign. We want to hide it on these types of marketing pages.
> Hide recently viewed on marketing page

- src/Apps/Collect/Routes/Collection/Components/Header/__tests__/Header.test.tsx
- src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
Fixes https://sentry.io/organizations/artsynet/issues/1579743055/?project=28316&referrer=slack
Noticed in #incident-83 that when ES went down, we were throwing an error on the collection page. This adds some safety around that, however a more holistic look should be given to this component as a whole.
> [Bugfix] Make /collection/id Header safer

- src/Components/NavBar/Menus/DropDownMenu.tsx
- src/Components/NavBar/Menus/DropDownSection.tsx
- src/Components/NavBar/Menus/TwoColumnDropDownSection.tsx
- src/Components/NavBar/Menus/__tests__/DropDownMenu.test.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
Addresses: [FX-1907](https://artsyproduct.atlassian.net/browse/FX-1907) & [FX-1908](https://artsyproduct.atlassian.net/browse/FX-1908)
This PR addresses the following QA items:
- Add 10px left and right padding to drop down items
- Ensure `destination_path` is populated
- Make sure to track hover event for Artworks & Aritsts.
**Hover Event:**
**Click Event:**
> [FX-1908] Navbar menu qa

- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedCollections.tsx
- src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedFairs.tsx
- src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
#minor but because we have to manually match the data from the JSON spreadsheet to the data coming back from metaphysics, it's possible that things are out-of-alignment.
This morning I noticed that the page was erroring out due to an instance of this ☝️. I fixed the data entry issue but this PR will make the page more resilient to issues of this type.
(Reminder that this entire page is still curated manually/is rather fragile. It's a one-off and we'll need to invest in a more sustainable solution before hosting other campaigns of this sort).
> Make AKG page more resilient towards mismatched data

- src/Components/NavBar/Menus/DropDownMenu.tsx
- src/Components/NavBar/Menus/DropDownSection.tsx
- src/Components/NavBar/Menus/TwoColumnDropDownSection.tsx
⚠️ **Blocked by: https://github.com/artsy/palette/pull/673**
This PR adds a new prop to control the `background-color` for MenuItems.
> [NavBar Drop Down QA] add a new prop to control background color

- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/NotificationsBadge.tsx
Thanks to @xtina-starr for pairing on this 🙏 
For some context, I noticed in staging that the notification bubble was appearing above the new inbox conversation icon (which is behind a feature flag). 
Here it is rendering in the incorrect position: 
@xtina-starr and I paired on potentially just adding the notion of a notification badge to the icon in palette but decided it was best just to fix the issue in reaction and revisit this. 
The notification badge gets shifted to an incorrect position whenever we add a new header icon because it's just set absolutely. This change adds a conditional relative positioning to the `NavItem` (only if it actually has a notification badge, otherwise it'll break large menu dropdowns)
To be clear, we don't necessarily believe this is the best fix, but it …
> Ensure notification badge proprely aligned

- src/Components/NavBar/NavBar.tsx
- src/Components/NavBar/NavItem.tsx
- src/Components/NavBar/__tests__/NavBar.test.tsx
Addresses: [FX-1925](https://artsyproduct.atlassian.net/browse/FX-1925)
- Fixes analytics hover tracking for Artworks & Artists drop downs.
- Removes the feature flag so the Artworks & Artists menus are visible to all users.
- Fixes a NavBar test.
**Analytics Before:**
**Analytics After:**
cc: @abhitip
> [FX-1925] Fix some minor issues and launch nav drop down menus

- src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
- src/Components/NavBar/menuData.ts
Re: [FX-1819](https://artsyproduct.atlassian.net/browse/FX-1819)
Same place as in the desktop hierarchy.
I don't really understand what this comment is specifically asking for — https://artsyproduct.atlassian.net/browse/FX-1819?focusedCommentId=27330 — should just be a separate issue.
> [FX-1819] Links to consign page in mobile nav

- package.json
- src/Apps/Conversation/Components/Conversation.tsx
- src/Apps/Conversation/Components/Conversations.tsx
- src/Apps/Conversation/Components/NoMessages.tsx
- src/Apps/Conversation/ConversationApp.tsx
- src/Apps/Conversation/Routes/Conversation/index.tsx
- src/Apps/Conversation/__tests__/ConversationApp.test.tsx
- src/Apps/Conversation/routes.tsx
- src/Artsy/Router/Utils/findCurrentRoute.tsx
<p align="center">
</p>
The picture says it all, doesn't it?
I did a better job of breaking down each change into its own commit so the commits should tell the story of the changes. 
<details>
<summary>📦 Published PR as canary version: <code>26.27.13-canary.3461.59063.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.27.13-canary.3461.59063.0
yarn add @artsy/reaction@26.27.13-canary.3461.59063.0
```
</details>
> Add Empty conversations view

- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/__stories__/AppSecondFactor.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/__stories__/BackupSecondFactor.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/__tests__/index.test.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/__stories__/SmsSecondFactor.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/__stories__/TwoFactorAuthenticationStory.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/__tests__/TwoFactorAuthentication.test.tsx
The '..' imports cause Storybooks to not load with an exports is not defined error, as well as specs failing.
> Fixes relative paths for OSX

- src/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx
- src/Components/NavBar/Menus/DropDownMenu/DropDownSection.tsx
- src/Components/NavBar/Menus/DropDownMenu/TwoColumnDropDownSection.tsx
- src/Components/NavBar/NavItem.tsx
Addresses: [FX-1926](https://artsyproduct.atlassian.net/browse/FX-1926)
This PR addresses the following:
- Ensures the link items on the far left have the same top/bottom padding as the rest of the link items.
- Ensures the link texts fit on two lines at larger breakpoints.
- Restores the cursor pointer on hover of Artworks (this is difficult to capture in a screenshot).
> [FX-1926] Minor ui dropdown fixes

- src/Components/NavBar/menuData.ts
Addresses: [FX-1894](https://artsyproduct.atlassian.net/browse/FX-1894)
This PR updates the existing Top Artists URL/copy with Artists from the Focused 20 list to aid in improving our microfunnels for those artists.
> [FX-1894] change top artists

- src/Artsy/Router/Utils/__tests__/findCurrentRoute.test.ts
- src/Artsy/Router/Utils/findCurrentRoute.tsx
The acceptance tests started failing for force on a reaction renovate PR. @xtina-starr dug in and found out that the artist page was broken because the header wasn't being rendered. She dug in and noticed that it was because     `route.displayNavigationTabs` wasn't being set. 
When I started investigating, it turns out that when I updated the logic for `findCurrentRoute` I broke things. I updated it to just use `match.route`, but that's always just the top level route it seems. I updated it logic of that function to actually walk through the route indices and return the properly nested route. I also wrote a test. 
<details>
<summary>📦 Published PR as canary version: <code>26.30.2-canary.3469.59299.0</code></summary>
<br />
```sh
npm install …
```
> Correct findCurrentRoute logic to unbreak artist page

- package.json
- src/Apps/Artist/Components/ArtistHeader.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
- src/Apps/Artwork/Components/ArtistInfo.tsx
- src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
- src/Components/ArtistCard.tsx
- src/Components/Artwork/Fillwidth.tsx
- src/Components/Artwork/Save.tsx
- src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
- src/Components/Authentication/__tests__/FormSwitcher.test.tsx
- src/Components/Follow.tsx
- src/Components/FollowButton/FollowArtistButton.tsx
- src/Components/FollowButton/FollowGeneButton.tsx
- src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/Components/NavBar/NavBar.tsx
- src/Components/Publishing/Banner/Banner.tsx
- src/Components/__stories__/Authentication.story.tsx
- src/Utils/__tests__/openAuthModal.test.ts
- src/Utils/openAuthModal.ts
- yarn.lock
Fixes breaking changes from Cohesion v1, renames `AuthIntent` enum to `Intent`.
https://github.com/artsy/cohesion/pull/31
<details>
<summary>📦 Published PR as canary version: <code>26.30.3-canary.3474.59395.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.30.3-canary.3474.59395.0
yarn add @artsy/reaction@26.30.3-canary.3474.59395.0
```
</details>
> Use cohesion v1

- .eslintrc.js
Sets it to `warn` which is recommended.
There's 13 warnings right now, and I do think they could be auto-fixed. But I have seen missing dependencies paper over underlying bugs before so I'm reluctant to change them all at once.
> [Chore] Turns on exhaustive-deps

- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/Authentication/Types.ts
- src/Components/Authentication/Validators.tsx
- src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
- src/Components/Authentication/__tests__/fixtures.ts
- src/Components/Wizard/Wizard.tsx
- src/Components/__stories__/Authentication.story.tsx
Add an OTP prompt to the mWeb login modal.
<details>
<summary>📦 Published PR as canary version: <code>26.30.3-canary.3472.59408.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.30.3-canary.3472.59408.0
yarn add @artsy/reaction@26.30.3-canary.3472.59408.0
```
</details>
> [mWeb] Show OTP prompt during login when 2FA-enabled

- src/Components/Authentication/Mobile/LoginForm.tsx
- src/Components/__stories__/Authentication.story.tsx
The mobile login modal supports external error messages via two paths:
- The `error` prop
- Formik actions via the `handleSubmit` handler
We added support for the former in https://github.com/artsy/reaction/pull/3472. This commit adds support for the latter, used in Force:
https://github.com/artsy/force/blob/51733c03c8e490fa8ff705268f86c472412890c1/src/desktop/apps/authentication/helpers.ts#L90-L96
Follow-up to #3472 
<details>
<summary>📦 Published PR as canary version: <code>26.30.5-canary.3476.59467.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.30.5-canary.3476.59467.0
yarn add @artsy/reaction@26.30.5-canary.3476.59467.0
```
</details>
> [mWeb] Support OTP prompt on mobile login modal via Formik setStatus

- package.json
- src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
- src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
Related PR: https://github.com/artsy/metaphysics/pull/2348
We don't want to show the realized price point if missing. 
#trivial
> [Consignments] Hide recently sold data point if missing

- .circleci/config.yml
The storybook upload isn't behind the queuing mechanism so it blocks deploys
> Move storybook behind queue

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Before
After
I don't know exactly _why_ this broke. I'm assuming some extra spacing squeezed through somewhere that caused the column layout to fail. I ripped all that out and simplified the layout.
> Fix auction results layout on mobile

- .circleci/config.yml
Storybook build wasn't gated and is sometimes causing the master build to fail (because the master build won't continue until other jobs on master have finished)
<details>
<summary>📦 Published PR as canary version: <code>26.31.7-canary.3492.59785.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.31.7-canary.3492.59785.0
yarn add @artsy/reaction@26.31.7-canary.3492.59785.0
```
</details>
> Ensure storybook build is gated behind queue

- src/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
- src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
Based on [the specs](https://www.notion.so/artsy/Improve-filtering-on-mWeb-artist-pages-collections-collect-ef262fef2c484a328b80c78878f7d1e4#58636e780d2a4d53888c7e1bdbb62de7), it looks like we actually want the filter order to be the same across-the-board! Instead of adding in the functionality to customize, I just updated it in this one place.
Artist page:
Collect page:
Collection page:
By default, the first three options will be expanded:
> Change the filter order to prioritize more popular filters

- .circleci/config.yml
As mentioned in https://artsy.slack.com/archives/C02BC3HEJ/p1588855759090600.
Test only what changed in a PR for faster PR cycle times.  
This does _not_ change the tests that are ran on master. That's still a full suite. 
<details>
<summary>📦 Published PR as canary version: <code>26.31.8-canary.3493.59832.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.31.8-canary.3493.59832.0
yarn add @artsy/reaction@26.31.8-canary.3493.59832.0
```
</details>
> Enable faster PR builds

- src/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
- src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.test.tsx
Re: [FX-1938](https://artsyproduct.atlassian.net/browse/FX-1938)
Makes the mobile filters fullscreen and moves the "Apply" button to the bottom. Note that here I've just renamed "Cancel" to "Close" for the time being since we don't have a real notion of cancelling. If we want a proper cancel we'll have to just hold off on this until we can refactor the filters to actually be staged.
-----
Note that I'm punting on the scroll lock, which is a separate issue — refactoring the underlying nature of the Modal is... problematic. Closed PR here: https://github.com/artsy/palette/pull/675 — I'm thinking we just pull off `ModalBase` as it's own thing and use that here (and going forward to build Modals and slowly refactor the old one but I'm not thrilled by this prospect).
> Updates mobile artwork filters layout

- src/Artsy/Router/Utils/findCurrentRoute.tsx
There was an issue on conversations that caused `/user/conversation/:id` to 500. 
The issue is related to `findCurrentRoute` returning `null`. I did some work on this function a while back to make it a bit more robust, but in this case the `routesIndicies` is behaving in a way that I don't expect. It's returning `[ 1 ]` but `routes` is an array of only 1 element... which is the element that we're accessing. 
This might be due to how the routing in conversations is structured. It's a flat array instead of nested like on artist pages.
> Fallback to base route if no route found through index

- src/Components/UserSettings/TwoFactorAuthentication/Components/ApiErrorModal.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/__stories__/AppSecondFactor.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/__stories__/BackupSecondFactor.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/DisableFactorConfirmation.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/__stories__/SmsSecondFactor.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/__stories__/TwoFactorAuthenticationStory.story.tsx
- src/Components/UserSettings/TwoFactorAuthentication/index.tsx
Lots of small tweaks
- Add 2FA method disable confirmation prompt
- Update 2FA enrollment API modal to use Palette dialog
- Remove stray character in app authenticator 2FA enrollment modal
- Add step numbers to app authenticator 2FA enrollment modal
- Center show secret app authenticator 2FA enrollment button
- Set loading/disabled props on 2FA enrollment buttons …
- Wait until 2FA refetch completes before dismissing setup modal
- Update "Enabled" typography to Sans style
> Refine 2FA enrollment design and experience

- src/Apps/Conversation/Components/Conversation.tsx
- src/Apps/Conversation/Components/ConversationSnippet.tsx
- src/Apps/Conversation/Components/Conversations.tsx
- src/Apps/Conversation/Components/Details.tsx
- src/Apps/Conversation/Components/InboxHeaders.tsx
- src/Apps/Conversation/Components/Reply.tsx
- src/Apps/Conversation/Components/TimeSince.tsx
- src/Apps/Conversation/ConversationApp.tsx
- src/Apps/Conversation/Routes/Conversation/index.tsx
- src/Apps/Conversation/__tests__/ConversationApp.test.tsx
- src/Apps/__tests__/Fixtures/Conversation.ts
- src/__generated__/ConversationAppTestQuery.graphql.ts
- src/__generated__/ConversationApp_me.graphql.ts
- src/__generated__/ConversationSnippet_conversation.graphql.ts
- src/__generated__/Conversation_me.graphql.ts
- src/__generated__/ConversationsQuery.graphql.ts
- src/__generated__/Conversations_me.graphql.ts
- src/__generated__/routes_ConversationQuery.graphql.ts
- src/__generated__/routes_DetailQuery.graphql.ts
Changes:
- Redirect to first conversation when `/conversations` opened on desktop
- Added
- Refactored inbox header to be responsive
- Refactored layout to be responsive
- Added details stub
Full view (details panel not yet implemented)
md view
Still quite a bit of work to do so expect a lot of fast follows.
> Responsive conversations layout

- src/Apps/Conversation/Components/Conversations.tsx
- src/Apps/Conversation/Components/InboxHeaders.tsx
- src/Apps/Conversation/ConversationApp.tsx
- src/__generated__/ConversationAppTestQuery.graphql.ts
- src/__generated__/ConversationApp_me.graphql.ts
- src/__generated__/routes_ConversationQuery.graphql.ts
I accidentally omitted the inbox header for `/conversations` on mobile in #3509. This readds that. 
<details>
<summary>📦 Published PR as canary version: <code>26.36.1-canary.3510.60244.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.36.1-canary.3510.60244.0
yarn add @artsy/reaction@26.36.1-canary.3510.60244.0
```
</details>
> Readd mobile inbox header

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCurrentBidInfo.test.tsx
- src/index.ts
The tracking decorator for clicking on the buyers' premium link [did not move with its handler function](https://github.com/artsy/reaction/pull/2966/files#diff-c9ef16c3b323f531057622da216d4a53L24) in a recent change - h/t @sweir27 for quickly tracking it down. This fixes it. Should be fine to merge as-is but I'm working on adding a test as well.
> Move tracking code for buyers premium link click

- src/Apps/Feature/Components/FeatureFeaturedLink.tsx
- src/Apps/Feature/Components/FeatureHeader.tsx
- src/Apps/Feature/Components/FeatureSet.tsx
- src/Apps/Feature/Components/__tests__/fixtures.ts
- src/Apps/Feature/FeatureApp.tsx
- src/__generated__/FeatureApp_feature.graphql.ts
- src/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts
- src/__generated__/FeatureHeader_feature.graphql.ts
- src/__generated__/FeatureSet_set.graphql.ts
- src/__generated__/routes_FeatureQuery.graphql.ts
The duplicated fields are just the placeholder aliases — I'm going to switch to working on Metaphysics next.
> Wires up OrderedSets and FeaturedLinks to real data

- src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
Updates "Buy now" and "Make offer" buttons to open "Sign up" form instead of "Log in" for anonymous users. 
Follow up to conversation: https://artsy.slack.com/archives/C9YNS4X32/p1589303325202200
Integrity PR should be merged once this is in Force: https://github.com/artsy/integrity/pull/127
<details>
<summary>📦 Published PR as canary version: <code>26.36.8-canary.3518.60482.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.36.8-canary.3518.60482.0
yarn add @artsy/reaction@26.36.8-canary.3518.60482.0
```
</details>
> Purchase auth triggers use Sign up rather than Log in form

- src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
Log out of the session and reload the page after initial 2FA enrollment.
<details>
<summary>📦 Published PR as canary version: <code>26.39.1-canary.3538.60875.0</code></summary>
<br />
```sh
npm install @artsy/reaction@26.39.1-canary.3538.60875.0
yarn add @artsy/reaction@26.39.1-canary.3538.60875.0
```
</details>
> Redirect to /log_in vs reloading upon initial 2FA setup

- package.json
- src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
- src/Artsy/Analytics/trackingMiddleware.ts
- src/Artsy/Router/buildClientApp.tsx
- yarn.lock
Data team noticed that we were doing some double firing on page view tracking. This doesn't fix that, but simply makes path exclusion more robust. The same technique has been copied over to the corresponding Force PR, which does fix the problem. Uses [path-to-regex](https://github.com/pillarjs/path-to-regexp) under the hood.
Going to merge this in order to get a deploy out.
> Make tracking exclusion more robust

- src/Apps/Conversation/__tests__/ConversationApp.test.tsx
This caused a test failure in master due to the number of months changing from 12 to 13. 
You can see the failure here: https://app.circleci.com/jobs/github/artsy/reaction/61094
As a follow up we should figure out how to properly mock up this date data so that it's consistent between runs. Given that we're still really in flux on this work currently though, I'm just narrowing down the check.
> Ensure test checks don't validate actual dates

- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
One more -- rather than fixed width, we set to auto and let the height drive the shape.
> [ViewingRoom] Make sure width is auto on carousel

- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
The position of the ::after element shifts if margin is applied to the `Select` element. Seems strange but using Spacer elements instead fixes the alignment for now.
> Fix vertical alignment of CountrySelect ::after element

- src/Components/Authentication/Desktop/LoginForm.tsx
- src/Components/Authentication/Mobile/LoginForm.tsx
These inputs conditionally pop into the UI in response to a specific server error code. Autofocus the 2FA authentication code input field when it becomes visible as the user should enter in a valid authentication code at that time.
jira :lock: : https://artsyproduct.atlassian.net/browse/TRUST-235
> Autofocus 2FA authentication code fields

- src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
Missed this in the last go around.
> 2FA enrollment responsive fix: switch to maxWidth

- src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/Apps/ViewingRoom/Routes/Statement/Components/ViewWorksButton.tsx
- src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
- src/Apps/ViewingRoom/Routes/Statement/Utils/scrollToId.tsx
- src/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
- src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
- src/Apps/ViewingRoom/Routes/Works/ViewingRoomWorksRoute.tsx
- src/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/Apps/__stories__/ViewingRoom.story.tsx
- src/Components/Footer.tsx
(Artworks preview on Statement tab)
 
(Statement tab)
(Carousel)
(Statement Tab) 
 Missing “View Works” button at bottom
Footer
> [Viewing Room] QA

- src/Apps/Conversation/Components/Reply.tsx
[PURCHASE-1904]
https://www.notion.so/artsy/Conversation-not-updated-correctly-when-new-messages-is-entered-by-collector-61d0224fe67e4d44bf8c13fe52565a4b
This PR is the result of our mob pairing session on Tuesday. In addition to the message order bug, we fixed an issue where the text area input wasn't clearing properly.
[PURCHASE-1904]: https://artsyproduct.atlassian.net/browse/PURCHASE-1904
> Conversation not updated correctly when new messages is entered by collector

- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1925
Currently on Artist Auction Results, user must be logged-in to see prices. This change is to relax that restriction but only for the default view which is the view on page 1 when filters are at default. We will show prices in the default view even when no user is logged-in.
Please note, due to filter context being incorrect about the page# of the page being viewed (it always says 1), I cannot track the page# the user is on. I resort to tracking whether pagination has occurred. If pagination has occurred, prices are hidden. So if user clicks page 1 while on page 1, the page hasn't changed, but pagination has occurred, prices will be hidden again.
--
Screenshots showing effects of the change:
Not logged-in. Page 1. Default filters. …
> Show prices on default view of artist auction results.

- src/Apps/Artwork/ArtworkApp.tsx
- src/Artsy/Analytics/trackingMiddleware.ts
- src/Components/Publishing/RelatedArticles/Canvas/RelatedArticleCanvasLink.tsx
- src/Components/Publishing/RelatedArticles/Canvas/RelatedArticlesCanvas.tsx
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/RelatedArticleCanvasLink.test.tsx
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/RelatedArticlesCanvas.test.tsx
- src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
- src/Components/Publishing/RelatedArticles/Panel/RelatedArticlesPanel.tsx
- src/Components/Publishing/RelatedArticles/Panel/RelatedArticlesPanelLink.tsx
- src/Components/Publishing/RelatedArticles/Panel/__tests__/RelatedArticlesPanel.test.tsx
- src/Components/Publishing/RelatedArticles/Panel/__tests__/RelatedArticlesPanelLink.test.tsx
- src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
We're hitting our segment quota! This PR:
- Removes publishing events that fire often and are not used.
- Comments out our "Experiment Viewed" event now that we're confident in the result of the test. I didn't remove that code entirely since I figured it would come as part of the A/B test closeout (at which point I think I bunch of code can be cleaned up).
> Remove tracking calls for now

- renovate.json
We still need this repo to get updates for publishing code, reenabling renovate to keep @artsy packages up to date.
> Reenable renovate

- src/Components/Publishing/Sections/ViewFullscreen.tsx
Deprecates unused analytics event `Clicked article impression`
Related conversation: https://artsy.slack.com/archives/C0KEQD4B0/p1596746446145000
Related ticket: https://artsyproduct.atlassian.net/browse/PLATFORM-2668
Related to https://github.com/artsy/force/pull/6066
> deprecate Clicked article impression event

- src/Components/Publishing/Layouts/ClassicLayout.tsx
- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/Sections/__tests__/ArtworkCaption.test.tsx
- Removes errant typo/debugging text
- In article artwork captions, use the `artists` array over to-be-deprecated `artist` to render a single artist's name
Before:
After:
<details>
<summary>📦 Published PR as canary version: <code>28.1.1-canary.3624.62831.0</code></summary>
<br />
```sh
npm install @artsy/reaction@28.1.1-canary.3624.62831.0
yarn add @artsy/reaction@28.1.1-canary.3624.62831.0
```
</details>
> Bugfixes for classic layouts

- src/Components/Publishing/Constants.ts
- src/Components/Publishing/__tests__/Constants.test.ts
Article tooltips fetch content from artsy.net URLs based on simple text parsing. Since we added a redirect on artist pages for to add `/works-for-sale` to the url, the parsing was not finding the slug where it expected it (at the end of the url). This caused fetches to use "works-for-sale" rather than the actual slug, breaking both the artist links & tooltips where the string is present. 
The editorial team has been manually removing these links from articles, that will no longer be necessary with this change.
> Strip /works-for-sale from urls when attempting to fetch tooltop content

- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
- src/Components/Publishing/Sections/ArtworkCaption.tsx
- src/Components/Publishing/Sections/ArtworkSaleMessage.tsx
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
- src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/ArtworkCaption.test.tsx
- src/Components/Publishing/Sections/__tests__/ArtworkSaleMessage.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/__generated__/ArtworkSaleMessageQuery.graphql.ts
We currently show artworks on Editorial that are for sale on Artsy. However, users do not see any pricing information which makes their for-sale status unclear.
Show an artwork's `saleMessage` in an artwork's image caption on Editorial pages when we show an artwork. 
**Note**: The logic for `bidInfo` and `saleMessageDisplay` was lifted from Force: https://github.com/artsy/force/blob/b607b3b2bd9459981203c879ae3b3a3b04e9e587/src/v2/Components/Artwork/Details.tsx#L156. That code is thoroughly tested in Force and so tests are lighter here in comparison.
> Show artwork sale message on editorial articles

- src/Components/Publishing/Sections/ArtworkSaleMessage.tsx
- src/Components/Publishing/Sections/__tests__/ArtworkSaleMessage.test.tsx
https://artsyproduct.atlassian.net/browse/FX-2283
We're currently displaying `null` when the sale message is `null`.
Render an empty string instead of `null` when the sale message is `null`.
**Before**
**After**
> Do not display sale message when sale message is null

- package.json
Moves Cohesion out of dev dependencies and into regular dependencies. 
Cohesion is a real dependency for reaction, so the dev placement is inaccurate. I believe this was added when Reaction was more actively worked on to cut down on CI builds during office hours.
This change will allow us to remove Cohesion from Positron's dependencies.
> chore: move cohesion out of dev deps

- src/Components/FollowButton/MobileFollowArtistButton.tsx
- src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
- src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
- src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
- src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
- src/Components/Publishing/Sections/Sections.tsx
- src/Components/Publishing/Sections/Text.tsx
- src/Components/Publishing/Sections/__tests__/Text.test.tsx
- src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
- src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
- src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
- src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
- src/__generated__/MobileFollowArtistButtonQuery.graphql.ts
Fixes a bug preventing artist follow buttons from working in mobile context for editorial articles
- Adds a MobileFollowButton wrapped in a QueryRenderer 
- Parses html into react components for all cases and instead just doesn't add tooltips in mobile contexts
https://artsyproduct.atlassian.net/browse/FX-2282
> GRO-1: Render react artist follow buttons in mobile contexts

- src/Components/Publishing/Constants.ts
- src/Components/Publishing/__tests__/Constants.test.ts
https://artsyproduct.atlassian.net/browse/GRO-64
`getArtsySlugsFromHTML` incorrectly parses some links in Editorial articles resulting in (1) users being unable to click on any artist link in the article and (2) tooltips for artist links not showing up. 
For example, links like `/artist-series/slug` were incorrectly interpreted as an artist slug and and links like `/artist/slug/` were incorrectly interpreted to not be an artist link.
Update `getArtsySlugsFromHTML` to use a regex that correctly parses a greater variety of inputs. Links including trailing slashes, artist app subroutes (`/works-for-you`, `/auction-results`) and query params will now be correctly parsed.
~**DoNotMerge** until I've validated (1) I've covered all the known cases of broken links and (2) I've confirmed that …
> fix: Update URL parsing to more precisely extract slug

- src/Components/Publishing/ToolTip/Components/Description.tsx
https://artsyproduct.atlassian.net/browse/GRO-65
cc @artsy/grow-devs 
Descriptions in artist tooltips in articles occasionally overflow out of the container instead of being properly truncated, leading to a visually poor user experience.
Add `white-space: initial` to the artist tooltip description container.
**Before**
**After**
> fix: Add white-space CSS property to fix overflowing descriptions

- src/Components/Publishing/Article.tsx
Addresses [CX-1568] and contributes to https://github.com/artsy/force/pull/7721
With the introduced prop we will be able to hide the signup banner for articles in Eigen.
[CX-1568]: https://artsyproduct.atlassian.net/browse/CX-1568
> feat: Add flag to hide auth modal in article component

- src/Components/Publishing/Layouts/SeriesLayout.tsx
- src/Components/Publishing/Layouts/StandardLayout.tsx
- src/Components/Publishing/Layouts/VideoLayout.tsx
Addresses [CX-1585]
This PR contributes towards not showing ads in articles on the app anymore.
The `shouldAdRender` isn't passed from the `Articles` component to the layout components. With this PR the prop get's passed to the layout components and ads get rendered conditionally. 
To keep things safe `shouldAdRender` defaults to `true`.
[CX-1585]: https://artsyproduct.atlassian.net/browse/CX-1585
> feat: Render article ads conditionally

- src/Components/Publishing/Header/Layouts/Components/FeatureSplitHeader.tsx
Fixes https://artsyproduct.atlassian.net/browse/GRO-370
Fixes an issue where the copy text would overlap the header image on mobile. Now we just run overflow:hidden over it and be done with it. Works well enough. 
⚠️  Note: was not able to get article pages running in force without commenting out [client-side mount code here](https://github.com/artsy/force/blob/1d3a83449f2224b3c190a082f83b1b28e7a3b0e2/src/desktop/apps/article/client/article.tsx#L9-L13). For whatever reason after the SSR pass the screen blanks out on client-side mount. I couldn't figure out how to fix. 
Before:
After:
> bugfix: Fix overflow text

- yarn.lock
https://artsyproduct.atlassian.net/browse/PLATFORM-4080
Thankfully _union-value_ was not locked to a particular version and there is a hotfix available so upgrading that dependency resolves this long standing _set-value (CVE-2019-10747)_ _critical_ [security alert](https://github.com/artsy/reaction/security/dependabot/3).
> security: upgrade union-value transitive dependecy to resolve CVE-2019-10747

- src/Components/Publishing/Typings.ts
This PR supports hackathon work in `positron` (see Draft [PR](https://github.com/artsy/positron/pull/3169/files)) to add a marketing collection rail to our editorial articles. See [hackathon card](https://www.notion.so/artsy/Integrating-Collections-and-Editorial-177cab0764a08047a447e162cd60e2e6?pvs=4). These type additions will allow me to finish the draft PR. 
I also alphabetized the declarations. See commit e439074cb8f64fc5a9bc0567d5b6f380899dbcf3 for easier view of what actually was added.
> feat: add marketing collection types
